!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (feature_llhTests) - 27 May 2021 14:23
!
!  Differentiation of b2mn as a context to call tangent code (with options multiDirectional context noISIZE r8):
!   Plus diff mem management of: b2voloncf:in-out b2data:in-out
!                b2dataoncf:in-out state_avg.na_mean:in-out state_avg.ua_mean:in-out
!                state_avg.te_mean:in-out state_avg.ti_mean:in-out
!                state_avg.po_mean:in-out state_avg.kt_mean:in-out
!                state_avg.zt_mean:in-out state_avg.sna_mean:in-out
!                state_avg.smo_mean:in-out state_avg.she_mean:in-out
!                state_avg.shi_mean:in-out state_avg.shn_mean:in-out
!                state_avg.e_na:in-out state_avg.e_ua:in-out state_avg.e_te:in-out
!                state_avg.e_ti:in-out state_avg.e_po:in-out state_avg.e_kt:in-out
!                state_avg.e_zt:in-out state_avg.e_sna:in-out state_avg.e_smo:in-out
!                state_avg.e_she:in-out state_avg.e_shi:in-out
!                state_avg.e_shn:in-out mpg.bcfcor:in-out mpg.rcfcor:in-out
!                mpg.cffcor:in-out mpg.intcellp:in-out mpg.intcellr:in-out
!                mpg.divfcor:in-out geo.cvbb:in-out geo.cvx:in-out
!                geo.cvy:in-out geo.cvsz:in-out geo.cvhz:in-out
!                geo.cvhx:in-out geo.cvqgam:in-out geo.cvvol:in-out
!                geo.cvonedbsq:in-out geo.cvbzb:in-out geo.cveb:in-out
!                geo.cvfpsi:in-out geo.fcbb:in-out geo.fcs:in-out
!                geo.fchc:in-out geo.fcht:in-out geo.fchz:in-out
!                geo.fcvol:in-out geo.fcqgam:in-out geo.fcqalf:in-out
!                geo.fcqbet:in-out geo.fcpbs:in-out geo.fcpbshz:in-out
!                geo.fcbzb:in-out geo.fceb:in-out geo.fcfpsi:in-out
!                geo.vxbb:in-out geo.vxx:in-out geo.vxy:in-out
!                geo.vxhz:in-out geo.vxvol:in-out geo.vxffbz:in-out
!                geo.vxfpsi:in-out geo.vxonedbsq:in-out geo.vxbzb:in-out
!                geo.vxeb:in-out geo.cvconn:in-out geo.vxconn:in-out
!                geo.ftconn:in-out geo.fsconn:in-out geo.fteps:in-out
!                geo.ftbbav2:in-out geo.fspsi:in-out state_ext.zn:in-out
!                state_ext.am:in-out state_ext.ne:in-out state_ext.ne2:in-out
!                state_ext.ue:in-out state_ext.za:in-out state_ext.za2:in-out
!                state_ext.pt:in-out state_ext.na:in-out state_ext.ni:in-out
!                state_ext.ua:in-out state_ext.ta:in-out state_ext.fhi:in-out
!                state_ext.fa:in-out state_ext.sne:in-out state_ext.she:in-out
!                state_ext.shi:in-out state_ext.sch:in-out state_ext.sna:in-out
!                state_ext.smo:in-out state.pl.na:in-out state.pl.ua:in-out
!                state.pl.po:in-out state.pl.te:in-out state.pl.ti:in-out
!                state.pl.tn:in-out state.pl.kt:in-out state.pl.zt:in-out
!                state.co.csig:in-out state.co.calf:in-out state.co.csig_an:in-out
!                state.co.calf_an:in-out state.co.csig_cl:in-out
!                state.co.calf_cl:in-out state.co.csigin:in-out
!                state.co.chve:in-out state.co.chce:in-out state.co.chce_exb:in-out
!                state.co.chvi:in-out state.co.chci:in-out state.co.chci_exb:in-out
!                state.co.chcn:in-out state.co.cdkt:in-out state.co.cdzt:in-out
!                state.co.chvemx:in-out state.co.chvimx:in-out
!                state.co.cvla:in-out state.co.cdna:in-out state.co.cdna_exb:in-out
!                state.co.cdpa:in-out state.co.cvsa:in-out state.co.cvlahz:in-out
!                state.co.cdnahz:in-out state.co.cdpahz:in-out
!                state.co.cvsahz:in-out state.co.cddi:in-out state.co.cvsahz_cl:in-out
!                state.co.chcb:in-out state.co.cvsa_an:in-out state.co.cvmahz:in-out
!                state.co.cvsahz_eff:in-out state.co.cthe:in-out
!                state.co.cthi:in-out state.co.cvsa_cl:in-out state.co.ceqp:in-out
!                state.co.fllim0fhi:in-out state.co.fllimvisc:in-out
!                state.co.fllim0fna:in-out state.co.vsaf_cl:in-out
!                state.co.sig0:in-out state.co.hce0:in-out state.co.hci0:in-out
!                state.co.hcn0:in-out state.co.alf0:in-out state.co.dkt0:in-out
!                state.co.dzt0:in-out state.co.dna_exb:in-out state.co.hce_exb:in-out
!                state.co.hci_exb:in-out state.co.dpa0:in-out state.co.dna0:in-out
!                state.co.vsa0:in-out state.co.hcib:in-out state.co.vla0:in-out
!                state.co.vma0:in-out state.co.kt_neo:in-out state.co.alfx_c:in-out
!                state.co.sigx_c:in-out state.co.sigx_kt:in-out
!                state.co.hcix_c:in-out state.co.fllim_ki:in-out
!                state.co.fllim_ke:in-out state.co.fllim_al:in-out
!                state.co.fllim_al_c:in-out state.co.fllim_ki_c:in-out
!                state.co.f_luc_ke:in-out state.co.f_luc_ki:in-out
!                state.co.f_luc_et:in-out state.co.f_luc_sg:in-out
!                state.co.f_luc_al:in-out state.co.cssb:in-out
!                state.dv.fch:in-out state.dv.fch_32:in-out state.dv.fch_52:in-out
!                state.dv.fch_p:in-out state.dv.fchdia:in-out state.dv.fchin:in-out
!                state.dv.fchvispar:in-out state.dv.fchvisper:in-out
!                state.dv.fchvisq:in-out state.dv.fchinert:in-out
!                state.dv.fchanml:in-out state.dv.fchviskt:in-out
!                state.dv.fch_pi_c:in-out state.dv.fch_pi_f:in-out
!                state.dv.fni_32:in-out state.dv.fni_52:in-out
!                state.dv.fni:in-out state.dv.fni_he:in-out state.dv.fna:in-out
!                state.dv.fna_mdf:in-out state.dv.fna_52:in-out
!                state.dv.fna_32:in-out state.dv.fna_53:in-out
!                state.dv.fna_52nd:in-out state.dv.fna_32nd:in-out
!                state.dv.fna_nodrift:in-out state.dv.fna_he:in-out
!                state.dv.fnapsch:in-out state.dv.fna_fcor:in-out
!                state.dv.fna_eir:in-out state.dv.fna_exb:in-out
!                state.dv.fmo:in-out state.dv.fne:in-out state.dv.fne_he:in-out
!                state.dv.fne_32:in-out state.dv.fne_52:in-out
!                state.dv.fne_eir:in-out state.dv.fne_53:in-out
!                state.dv.fhe:in-out state.dv.fhe_mdf:in-out state.dv.fhet:in-out
!                state.dv.fhepsch:in-out state.dv.fhe_eir:in-out
!                state.dv.fhe_exb:in-out state.dv.fhi:in-out state.dv.fhi_mdf:in-out
!                state.dv.fhit:in-out state.dv.fhipsch:in-out state.dv.fhi_eir:in-out
!                state.dv.fhi_exb:in-out state.dv.fnn:in-out state.dv.fnn_32:in-out
!                state.dv.fnn_52:in-out state.dv.fhn:in-out state.dv.fnn_inc:in-out
!                state.dv.fhm:in-out state.dv.fhp:in-out state.dv.fhj:in-out
!                state.dv.fht:in-out state.dv.fkt:in-out state.dv.fzt:in-out
!                state.dv.kin_frac_hyb:in-out state.dv.fluid_frac_hyb:in-out
!                state.dv.kinrgy:in-out state.dv.conc:in-out state.dv.flob:in-out
!                state.dv.floe:in-out state.dv.floi:in-out state.dv.floe_noc:in-out
!                state.dv.floi_noc:in-out state.dv.flon:in-out
!                state.dv.flokt:in-out state.dv.flozt:in-out state.dv.conn:in-out
!                state.dv.conkt:in-out state.dv.conzt:in-out state.dv.conb:in-out
!                state.dv.cone:in-out state.dv.coni:in-out state.dv.fllime:in-out
!                state.dv.fllimi:in-out state.dv.resmo:in-out state.dv.resco:in-out
!                state.dv.respo:in-out state.dv.reshe:in-out state.dv.reshi:in-out
!                state.dv.resht:in-out state.dv.resmt:in-out state.dv.reshn:in-out
!                state.dv.reskt:in-out state.dv.reszt:in-out state.dv.corua:in-out
!                state.dv.corpa:in-out state.dv.corut:in-out state.dv.corpo:in-out
!                state.dv.cortt:in-out state.dv.corte:in-out state.dv.corti:in-out
!                state.dv.cortn:in-out state.dv.corkt:in-out state.dv.corzt:in-out
!                state.dv.pcca:in-out state.dv.pccm:in-out state.dv.ne:in-out
!                state.dv.ni:in-out state.dv.nn:in-out state.dv.ue:in-out
!                state.dv.ne2:in-out state.dv.pa:in-out state.dv.pz:in-out
!                state.dv.lnlam:in-out state.dv.uadia:in-out state.dv.vadia:in-out
!                state.dv.wadia:in-out state.dv.vaecrb:in-out state.dv.vedia:in-out
!                state.dv.wedia:in-out state.dv.veecrb:in-out state.dv.facdrift:in-out
!                state.dv.fac_exb:in-out state.dv.fac_vis:in-out
!                state.sr.sch:in-out state.sr.she:in-out state.sr.shi:in-out
!                state.sr.sne:in-out state.sr.shn:in-out state.sr.skt:in-out
!                state.sr.szt:in-out state.sr.smo:in-out state.sr.smq:in-out
!                state.sr.sna:in-out state.sr.shedt:in-out state.sr.sktdt:in-out
!                state.sr.sztdt:in-out state.sr.snedt:in-out state.sr.shidt:in-out
!                state.sr.shndt:in-out state.sr.schdt:in-out state.sr.smodt:in-out
!                state.sr.snadt:in-out state.sr.skt_diss:in-out
!                state.sr.skt_prod:in-out state.sr_eir.sch:in-out
!                state.sr_eir.she:in-out state.sr_eir.shi:in-out
!                state.sr_eir.sne:in-out state.sr_eir.smo:in-out
!                state.sr_eir.smq:in-out state.sr_eir.sna:in-out
!                state.srw.sch0:in-out state.srw.she0:in-out state.srw.shi0:in-out
!                state.srw.sne0:in-out state.srw.shn0:in-out state.srw.skt0:in-out
!                state.srw.szt0:in-out state.srw.smo0:in-out state.srw.smq0:in-out
!                state.srw.sna0:in-out state.srw.smcf:in-out state.srw.smpr:in-out
!                state.srw.smpt:in-out state.srw.smfr:in-out state.srw.b2stbc_sch:in-out
!                state.srw.b2stbc_she:in-out state.srw.b2stbc_shi:in-out
!                state.srw.b2stbc_sne:in-out state.srw.b2stbc_shn:in-out
!                state.srw.b2stbc_skt:in-out state.srw.b2stbc_szt:in-out
!                state.srw.b2stbc_smo:in-out state.srw.b2stbc_sna:in-out
!                state.srw.b2stbm_sch:in-out state.srw.b2stbm_she:in-out
!                state.srw.b2stbm_shi:in-out state.srw.b2stbm_sne:in-out
!                state.srw.b2stbm_smo:in-out state.srw.b2stbm_smq:in-out
!                state.srw.b2stbm_sna:in-out state.srw.b2stbr_sch:in-out
!                state.srw.b2stbr_she:in-out state.srw.b2stbr_shi:in-out
!                state.srw.b2stbr_sne:in-out state.srw.b2stbr_shn:in-out
!                state.srw.b2stbr_skt:in-out state.srw.b2stbr_szt:in-out
!                state.srw.b2stbr_smo:in-out state.srw.b2stbr_sna:in-out
!                state.srw.b2npmo_smaf:in-out state.srw.b2npmo_smag:in-out
!                state.srw.b2npmo_smav:in-out state.srw.rsana:in-out
!                state.srw.rsahi:in-out state.srw.rsamo:in-out
!                state.srw.rrana:in-out state.srw.rrahi:in-out
!                state.srw.rramo:in-out state.srw.rcxna:in-out
!                state.srw.rcxhi:in-out state.srw.rcxmo:in-out
!                state.srw.rqahe:in-out state.srw.rqrad:in-out
!                state.srw.rqbrm:in-out state.srw.b2sihs_joule:in-out
!                state.srw.b2sihs_divue:in-out state.srw.b2sihs_divua:in-out
!                state.srw.b2sihs_exbe:in-out state.srw.b2sihs_exba:in-out
!                state.srw.b2sihs_visa:in-out state.srw.b2sihs_fraa:in-out
!                state.srw.b2sihs_str:in-out state.srw.sna0_eir_tot:in-out
!                state.srw.smo0_eir_tot:in-out state.srw.sne0_eir_tot:in-out
!                state.srw.she0_eir_tot:in-out state.srw.shi0_eir_tot:in-out
!                state.srw.shn0_eir_tot:in-out state.srw.sch0_eir_tot:in-out
!                state.rt.rlcx:in-out state.rt.rlqa:in-out state.rt.rlrd:in-out
!                state.rt.rlbr:in-out state.rt.rlra:in-out state.rt.rlsa:in-out
!                state.rt.rlza:in-out state.rt.rlz2:in-out state.rt.rlpt:in-out
!                state.rt.rlpi:in-out state.rt.rlqr:in-out state.rt.rza:in-out
!                state.rt.rz2:in-out state.rt.rpt:in-out state.rt.rpi:in-out
!                state.rtw.rsa:in-out state.rtw.rra:in-out state.rtw.rqa:in-out
!                state.rtw.rrd:in-out state.rtw.rbr:in-out state.rtw.rcx:in-out
!                state.rtw.rqr:in-out state.psnl.na:in-out state.psnl.ua:in-out
!                state.psnl.po:in-out state.psnl.te:in-out state.psnl.ti:in-out
!                state.psnl.tn:in-out state.psnl.kt:in-out state.psnl.zt:in-out
!                state.psnl.ne:in-out state.psnl.ni:in-out state.psnl.nn:in-out
!                state.psnl.fch:in-out state.psnl.fna:in-out state.psnl.fhi:in-out
!                state.psnl.fhe:in-out state.psnl.fhn:in-out state.psnl.fkt:in-out
!                state.psnl.fzt:in-out state.psnl.kinrgy:in-out
!                state.psnc.na:in-out state.psnc.ua:in-out state.psnc.po:in-out
!                state.psnc.te:in-out state.psnc.ti:in-out state.psnc.tn:in-out
!                state.psnc.kt:in-out state.psnc.zt:in-out state.psnc.ne:in-out
!                state.psnc.ni:in-out state.psnc.nn:in-out state.psnc.fch:in-out
!                state.psnc.fna:in-out state.psnc.fhi:in-out state.psnc.fhe:in-out
!                state.psnc.fhn:in-out state.psnc.fkt:in-out state.psnc.fzt:in-out
!                state.psnc.kinrgy:in-out state.diag.srcna:in-out
!                state.diag.srcmo:in-out state.diag.srcpo:in-out
!                state.diag.srche:in-out state.diag.srchi:in-out
!                state.diag.srcmt:in-out state.diag.aresco:in-out
!                state.diag.aresmo:in-out state.diag.acorpa:in-out
!                state.diag.acorua:in-out state.diag.rescoreg:in-out
!                state.diag.resmoreg:in-out state.diag.reshereg:in-out
!                state.diag.reshireg:in-out state.update.ua:in-out
!                state.update.na:in-out state.update.pa:in-out
!                state.update.po:in-out state.update.te:in-out
!                state.update.ti:in-out state.update.kt:in-out
!                state.update.zt:in-out (global)par_opt_phys:in-out
!
!
!
!
!
!
!
!
!
!
!
!-----------------------------------------------------------------------
!.specification
!
PROGRAM B2MN_DV
  USE B2MOD_TYPES
  USE B2MOD_MAIN_DIFFV, ONLY : b2mn_init, b2mn_init_dv, b2mn_step, &
& b2mn_step_dv, b2mn_fin, b2mn_fin_dv
  USE B2MOD_AD_DIFFV, ONLY : nncf
  USE B2MOD_PAR_OPT_DIFFV, ONLY : npar_opt, nsigma_opt, nmean_opt, &
& nshift_opt, ncorr_opt
  USE B2US_DATA_DIFFV
!  Hint: nbdirsmax should be the maximum number of differentiation directions
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!
!-----------------------------------------------------------------------
!.end b2mn
!
  REAL(kind=r8) :: j(nncf)
  REAL(kind=r8) :: jd(nbdirsmax, nncf)
  INTEGER :: nbdirs
!-----------------------------------------------------------------------
!.documentation
!
!  1. purpose
!
!     B2MN is the main program for the B2 code. The code solves a
!     system of fluid equations that models a multi-species plasma
!     in a two-dimensional geometry. This program calls routines
!     within the main program module b2mod_main for the actual
!     computation.
!
!
!  2. specification
!
!     Main program.
!
!
!  3. description (see also routine b2cdca)
!
!     The B2 code /1,2/ solves a system of fluid equations that models
!     a multi-species plasma in a two-dimensional geometry. Its main
!     application is simulation of the edge plasma in tokamaks.
!
!     B2 is composed of several independent programs that communicate
!     through external files. The main sequence involves the programs
!     b2ag (prepares a geometry and magnetic field), b2ah (prepares
!     a table of default physics parameters), b2ai (prepares an
!     initial plasma state), b2mn (principal calculation), and b2yp
!     (postprocessing).
!     Additional programs may prepare tables of rate coefficients for
!     atomic processes, tables of plasma-wall interaction processes,
!     external source terms, and other physics, or may perform further
!     postprocessing.
!
!     The complete program b2mn is designed to solve the equations.
!     This program unit opens and closes the input/output units, and
!     may perform some other system-dependent operations. It calls
!     routines b2mndr_[0-2] to control the actual computation.
!
!     The input units are:
!     ninp(0): formatted; provides physics and numerics parameters.
!     ninp(1): un*formatted; provides the geometry.
!     ninp(2): un*formatted; provides default physics parameters.
!     ninp(3): un*formatted; provides the initial state.
!     ninp(4): un*formatted; provides atomic rate data.
!     ninp(5): un*formatted; provides source term data.
!     ninp(6): un*formatted; provides the initial differentiated state.
!
!     The output units are:
!     nout(0): formatted; provides summary print output.
!     nout(1): un*formatted; provides actual physics parameters.
!     nout(2): un*formatted; provides the final state.
!     nout(3): un*formatted; may provide data for movie.
!     nout(4): un*formatted; provides data on the numerical evolution.
!     nout(5): un*formatted; may provide detailed convergence data.
!     nout(6): un*formatted; save file for restart
!     nout(7): un*formatted; full plasma description with derived quantities
!     nout(8): un*formatted; ASTRA coupling data file
!     nout(9): un*formatted; provides the final differentiated state.
!     nout(10): un*formatted; provides data on the numerical evolution of differentiated quantities.
!     nout(11): formatted; postprocessor output. [JET]
!
!     (See routine b2cdca for the meaning of 'un*formatted'.)
!
!
!  4. references
!
!     (Refs. /1/ and /2/ are out of date; !! to be replaced.)
!     /1/ B. J. Braams, Computational Studies in Tokamak Equilibrium
!     and Transport, thesis, State University at Utrecht, June 1986.
!     /2/ B. J. Braams, A Multi-Fluid Code for Simulation of the Edge
!     Plasma in Tokamaks, NET Report Nr 68, January 1987.
!
!
!  5. parameters (see also routine b2cdcv)
!
!     None.
!
!
!  6. error indicators
!
!     In case an error condition is detected, a call is made to the
!     routine xerrab. This causes an error message to be printed,
!     after which the program halts.
!
!
!  7. accuracy
!
!     As a measure of convergence we employ the scaled L1-norms of the
!     residuals of the individual equations (continuity for each
!     species, parallel momentum balance for each species, electron heat
!     balance, atom heat balance, and charge balance). The scaling
!     provides numbers that have the dimension of (1/time). A reliable
!     estimate of the accuracy of a calculation can be obtained only
!     by continuing the calculation to better convergence.
!
!
!  8. further comments
!
!-----------------------------------------------------------------------
!.computation
!
!  nbdirs=3
  CALL B2MN_INIT_DV(switch, switchd, geo, geod, mpg, mpgd, state, stated&
&             , state_ext, state_extd, state_avg, state_avgd, npar_opt)
  call xertst(npar_opt.le.nbdirsmax, 'Increase size of nbdirsmax in b2mod_diffsizes.F')
  call xertst(switch%b2optim_namelist.eq.1, 'Sensitivity calculation needs b2optim_namelist=1!')
  call set_tgt_perturbation(switchd)
! default case, valid for any species mix
! the first dimension of these variables refers to the number of directions "nbdirs"
!  parm_hcid(3,1) = 1.0_R8
!  parm_hced(2) = 1.0_R8
!  parm_dnad(1,1) = 1.0_R8

!  nbdirs=7 !example multispecies case D D+ He He+ He++
!  parm_dnad(1,1) = 1.0_R8
!  parm_dnad(2,3) = 1.0_R8
!  parm_hced(3) = 1.0_R8
!  parm_hcid(4,1) = 1.0_R8
!  parm_hcid(5,4) = 1.0_R8
!  conpard(6,1,1,1) = 1.0_R8
!  conpard(7,3,1,1) = 1.0_R8

!  nbdirs=8 !example with radially varying transport coefficients
!  tdatad(1,2,2,1,1) = 1.0_R8 !D_perp
!  tdatad(2,2,4,1,1) = 1.0_R8 !D_perp
!  tdatad(3,2,1,3,1) = 1.0_R8 !Xi_perp
!  tdatad(4,2,6,3,1) = 1.0_R8 !Xi_perp
!  tdatad(5,2,3,4,1) = 1.0_R8 !Xe_perp
!  tdatad(6,2,5,4,1) = 1.0_R8 !Xe_perp
!  switchd%b2tqna_ballooning(7) = 1.0_R8
!  switchd%b2tqna_ballooning_rescale(8) = 1.0_R8

!  nbdirs=9 !example with k-model
!  enkpard(1,1,1) = 1.0_R8
!  switchd%keps_cd(2) = 1.0_R8
!  switchd%keps_heat(3) = 1.0_R8
!  switchd%keps_heat_i(4) = 1.0_R8
!  switchd%b2sikt_fac_sheath(5) = 1.0_R8
!  switchd%b2sikt_fac_sheath_core(6) = 1.0_R8
!  switchd%b2sikt_fac_diss(7) = 1.0_R8
!  switchd%b2sikt_fac_diss_core(8) = 1.0_R8
!  switchd%b2tfhi_fsigkt(9) = 1.0_R8

!  nbdirs = 5 !example with reaction rates
!  rtlsad(1,135,240,0) = 1.0_R8
!  rtlrad(2,135,240,1) = 1.0_R8
!  rtlcxd(3,135,240,1) = 1.0_R8
!  rtlqad(4,135,240,0) = 1.0_R8
!  rtlqad(5,135,240,1) = 1.0_R8

!  example set with transport+recycling coefficient (D0,D+)
!  nbdirs=16
!  parm_dnad(1,1) = 1.0_R8
!  parm_hced(2) = 1.0_R8
!  parm_hcid(3,1) = 1.0_R8
!  parm_vsad(4,1) = 1.0_R8
!  parm_sigd(5) = 1.0_R8
!  parm_alfd(6) = 1.0_R8
!  b2recycd(7,0,1) = 1.0_R8
!  b2recycd(8,0,2) = 1.0_R8
!  b2recycd(9,0,3) = 1.0_R8
!  b2recycd(10,0,4) = 1.0_R8
!  b2recycd(11,0,5) = 1.0_R8
!  b2recycd(12,1,1) = 1.0_R8
!  b2recycd(13,1,2) = 1.0_R8
!  b2recycd(14,1,3) = 1.0_R8
!  b2recycd(15,1,4) = 1.0_R8
!  b2recycd(16,1,5) = 1.0_R8

!  example set with continuity BCs (D0,D+)
!  nbdirs=12
!  conpard(1,0,1,1) = 1.0_R8
!  conpard(2,0,2,1) = 1.0_R8
!  conpard(3,0,3,1) = 1.0_R8
!  conpard(4,0,4,1) = 1.0_R8
!  conpard(5,0,5,1) = 1.0_R8
!  conpard(6,0,6,1) = 1.0_R8
!  conpard(7,1,1,1) = 1.0_R8
!  conpard(8,1,2,1) = 1.0_R8
!  conpard(9,1,3,1) = 1.0_R8
!  conpard(10,1,4,1) = 1.0_R8
!  conpard(11,1,5,1) = 1.0_R8
!  conpard(12,1,6,1) = 1.0_R8

!  example set with momentum BCs (D0,D+)
!  nbdirs=12
!  mompard(1,0,1,1) = 1.0_R8
!  mompard(2,0,2,1) = 1.0_R8
!  mompard(3,0,3,1) = 1.0_R8
!  mompard(4,0,4,1) = 1.0_R8
!  mompard(5,0,5,1) = 1.0_R8
!  mompard(6,0,6,1) = 1.0_R8
!  mompard(7,1,1,1) = 1.0_R8
!  mompard(8,1,2,1) = 1.0_R8
!  mompard(9,1,3,1) = 1.0_R8
!  mompard(10,1,4,1) = 1.0_R8
!  mompard(11,1,5,1) = 1.0_R8
!  mompard(12,1,6,1) = 1.0_R8

!  example set with energy and potential BCs
!  nbdirs=18
!  enepard(1,1,1) = 1.0_R8
!  enepard(2,2,2) = 1.0_R8
!  enepard(3,3,2) = 1.0_R8
!  enepard(4,4,1) = 1.0_R8
!  enepard(5,5,1) = 1.0_R8
!  enepard(6,6,1) = 1.0_R8
!  enipard(7,1,1) = 1.0_R8
!  enipard(8,2,1) = 1.0_R8
!  enipard(9,3,1) = 1.0_R8
!  enipard(10,4,1) = 1.0_R8
!  enipard(11,5,1) = 1.0_R8
!  enipard(12,6,1) = 1.0_R8
!  potpard(13,1,1) = 1.0_R8
!  potpard(14,2,2) = 1.0_R8
!  potpard(15,3,2) = 1.0_R8
!  potpard(16,4,1) = 1.0_R8
!  potpard(17,5,1) = 1.0_R8
!  potpard(18,6,1) = 1.0_R8
  CALL B2MN_STEP_DV(switch, switchd, geo, geod, mpg, mpgd, state, stated&
&             , state_ext, state_extd, state_avg, state_avgd, j, jd, &
&             npar_opt-nsigma_opt-nmean_opt-nshift_opt-ncorr_opt)
  CALL B2MN_FIN_DV(switch, geo, geod, mpg, mpgd, state, stated, &
&            state_ext, state_extd, state_avg, state_avgd, npar_opt)
!
  STOP
END PROGRAM B2MN_DV
!

!
!
!
!
!
!
!
!
!
!
!
!-----------------------------------------------------------------------
!.specification
!
SUBROUTINE B2MN_NODIFF()
  USE B2MOD_TYPES
  USE B2MOD_MAIN_DIFFV, ONLY : b2mn_init, b2mn_step, b2mn_fin
  USE B2MOD_AD_DIFFV, ONLY : nncf
  USE B2MOD_PAR_OPT_DIFFV, ONLY : npar_opt, nsigma_opt, nmean_opt, &
& nshift_opt, ncorr_opt
  USE B2US_DATA_DIFFV
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!
!-----------------------------------------------------------------------
!.end b2mn
!
  REAL(kind=r8) :: j(nncf)
!-----------------------------------------------------------------------
!.documentation
!
!  1. purpose
!
!     B2MN is the main program for the B2 code. The code solves a
!     system of fluid equations that models a multi-species plasma
!     in a two-dimensional geometry. This program calls routines
!     within the main program module b2mod_main for the actual
!     computation.
!
!
!  2. specification
!
!     Main program.
!
!
!  3. description (see also routine b2cdca)
!
!     The B2 code /1,2/ solves a system of fluid equations that models
!     a multi-species plasma in a two-dimensional geometry. Its main
!     application is simulation of the edge plasma in tokamaks.
!
!     B2 is composed of several independent programs that communicate
!     through external files. The main sequence involves the programs
!     b2ag (prepares a geometry and magnetic field), b2ah (prepares
!     a table of default physics parameters), b2ai (prepares an
!     initial plasma state), b2mn (principal calculation), and b2yp
!     (postprocessing).
!     Additional programs may prepare tables of rate coefficients for
!     atomic processes, tables of plasma-wall interaction processes,
!     external source terms, and other physics, or may perform further
!     postprocessing.
!
!     The complete program b2mn is designed to solve the equations.
!     This program unit opens and closes the input/output units, and
!     may perform some other system-dependent operations. It calls
!     routines b2mndr_[0-2] to control the actual computation.
!
!     The input units are:
!     ninp(0): formatted; provides physics and numerics parameters.
!     ninp(1): un*formatted; provides the geometry.
!     ninp(2): un*formatted; provides default physics parameters.
!     ninp(3): un*formatted; provides the initial state.
!     ninp(4): un*formatted; provides atomic rate data.
!     ninp(5): un*formatted; provides source term data.
!     ninp(6): un*formatted; provides the initial differentiated state.
!
!     The output units are:
!     nout(0): formatted; provides summary print output.
!     nout(1): un*formatted; provides actual physics parameters.
!     nout(2): un*formatted; provides the final state.
!     nout(3): un*formatted; may provide data for movie.
!     nout(4): un*formatted; provides data on the numerical evolution.
!     nout(5): un*formatted; may provide detailed convergence data.
!     nout(6): un*formatted; save file for restart
!     nout(7): un*formatted; full plasma description with derived quantities
!     nout(8): un*formatted; ASTRA coupling data file
!     nout(9): un*formatted; provides the final differentiated state.
!     nout(10): un*formatted; provides data on the numerical evolution of differentiated quantities.
!     nout(11): formatted; postprocessor output. [JET]
!
!     (See routine b2cdca for the meaning of 'un*formatted'.)
!
!
!  4. references
!
!     (Refs. /1/ and /2/ are out of date; !! to be replaced.)
!     /1/ B. J. Braams, Computational Studies in Tokamak Equilibrium
!     and Transport, thesis, State University at Utrecht, June 1986.
!     /2/ B. J. Braams, A Multi-Fluid Code for Simulation of the Edge
!     Plasma in Tokamaks, NET Report Nr 68, January 1987.
!
!
!  5. parameters (see also routine b2cdcv)
!
!     None.
!
!
!  6. error indicators
!
!     In case an error condition is detected, a call is made to the
!     routine xerrab. This causes an error message to be printed,
!     after which the program halts.
!
!
!  7. accuracy
!
!     As a measure of convergence we employ the scaled L1-norms of the
!     residuals of the individual equations (continuity for each
!     species, parallel momentum balance for each species, electron heat
!     balance, atom heat balance, and charge balance). The scaling
!     provides numbers that have the dimension of (1/time). A reliable
!     estimate of the accuracy of a calculation can be obtained only
!     by continuing the calculation to better convergence.
!
!
!  8. further comments
!
!-----------------------------------------------------------------------
!.computation
!
  CALL B2MN_INIT(switch, geo, mpg, state, state_ext, state_avg)
  CALL B2MN_STEP(switch, geo, mpg, state, state_ext, state_avg, j)
  CALL B2MN_FIN(switch, geo, mpg, state, state_ext, state_avg)
!
  STOP
END SUBROUTINE B2MN_NODIFF
!

