module b2mod_cdf
  use b2mod_types , only : R8
  use b2mod_subsys
  implicit none
#ifndef NO_CDF
# include <netcdf.inc>
#ifndef SOLPS4_3
  public :: rwcdf, rwcdf_settime, rwcdf_setbatch, b2crtimecdf
#endif
  character*(maxncnam), save :: timsav, batchsav
  integer, save :: ntsav, nasav
  data timsav /'!!!! INVALID NAME !!!!'/
  private

contains

#ifndef SOLPS4_3
  subroutine b2crtimecdf(filename, mpg, ns, ismain, ismain0, nnmoli, &
   write_2d, ncid, batch_only, iret)
    use b2mod_constants
    use b2mod_user_namelist_diffv &
    , only : nimp, nomp
    use b2us_map_diffv
    implicit none
#   include <netcdf.inc>
    type (mapping), intent(in) :: mpg
    integer, intent(in) :: ns, ismain, ismain0, nnmoli
    integer nCv, nFc, nc, iret
    integer nya, nyi
    integer nybl, nytl, nytr, nybr
    integer, intent(in) :: write_2d
    logical, intent(in) :: batch_only
    character*256 :: filename
    ! NetCDF id
    integer  ncid
    ! dimension ids
    integer :: ncvdim, nfcdim, nsdim, timedim, batchdim, ncdim, idirdim
    integer :: nyadim, nyidim
    integer :: nydim, nybldim, nytldim, nytrdim, nybrdim
    ! variable ids
    integer :: ntstepid, timesaid, fnixipid, feexipid, feixipid, &
         fnixapid, feexapid, feixapid, nesepiid, tesepiid, tisepiid, &
         nesepmid, tesepmid, tisepmid, nesepaid, tesepaid, tisepaid, &
         nemxipid, temxipid, timxipid, nemxapid, temxapid, timxapid, &
         fniyipid, feeyipid, feiyipid, fniyapid, feeyapid, feiyapid, &
         pwmxipid, pwmxapid, tmneid, tmteid, tmtiid, &
#ifdef WG_TODO
         tmhacoreid, tmhasolid, tmhadivid, &
#endif
         fnisipid, feesipid, feisipid, fnisapid, &
         feesapid, feisapid, fnisippid, feesippid, feisippid, fnisappid, &
         feesappid, feisappid, ne3dlid, te3dlid, ti3dlid, an3dlid, mn3dlid, &
         ne3diid, te3diid, ti3diid, an3diid, mn3diid, &
         ne3daid, te3daid, ti3daid, an3daid, mn3daid, &
         ne3drid, te3drid, ti3drid, an3drid, mn3drid, &
         fn3dlid, fe3dlid, fi3dlid, fn3drid, fe3drid, fi3drid, &
         fetxipid, fetxapid, fetyipid, fetyapid, &
         fetsipid, fetsapid, fetsippid, fetsappid
    integer :: an3dtlid, mn3dtlid, an3dtrid, mn3dtrid, &
         ne3dtlid, te3dtlid, ti3dtlid, ne3dtrid, te3dtrid, &
         ti3dtrid, fn3dtlid, fe3dtlid, fi3dtlid, fn3dtrid, &
         fe3dtrid, fi3dtrid, fc3dtlid, fc3dtrid, &
         fl3dtlid, fl3dtrid, fo3dtlid, fo3dtrid, &
         ft3dtlid, ft3dtrid, po3dtlid, po3dtrid
#ifdef WG_TODO
    integer :: tp3dtlid, tp3dtrid
#endif
    integer :: ne2did, te2did, ti2did, po2did, kin2did, rsahi2did, &
         rsana2did, rrahi2did, rrana2did, rcxhi2did, rcxna2did, rqrad2did, &
         rqahe2did, fch2did, fhe2did, fhi2did, fna2did
    integer :: fchxipid, fchxapid, posepiid, posepmid, posepaid, &
         pomxipid, pomxapid, fchyipid, fchyapid, &
         fchsipid, fchsapid, fchsippid, fchsappid, po3dlid, &
         po3diid, po3daid, po3drid, fc3dlid, fc3drid, &
         fl3dlid, fl3drid, fo3dlid, fo3drid, &
         ft3dlid, ft3drid, &
         dn3diid, dn3daid, dp3diid, dp3daid, ke3diid, ke3daid, &
         ki3diid, ki3daid, vx3diid, vx3daid, vy3diid, vy3daid, &
         vs3diid, vs3daid, lh3diid, lh3daid, ln3diid, ln3daid, &
         dnsepmid, dpsepmid, kesepmid, kisepmid, &
         vxsepmid, vysepmid, vssepmid, &
#ifdef WG_TODO
         tpmxipid, tpmxapid, tp3drid, tp3dlid, &
         tpsepiid, tpsepaid, &
#endif
         ktsepmid, ktsepaid, ktsepiid, &
         nastepid, ntimbatchid, batchsaid, &
         nesepm_avid, tesepm_avid, tisepm_avid, posepm_avid, &
         nesepi_avid, tesepi_avid, tisepi_avid, posepi_avid, &
         nesepa_avid, tesepa_avid, tisepa_avid, posepa_avid, &
         nemxip_avid, temxip_avid, timxip_avid, pomxip_avid, &
         nemxap_avid, temxap_avid, timxap_avid, pomxap_avid, &
         ktsepm_avid, ktsepi_avid, ktsepa_avid, &
         nesepm_stdid, tesepm_stdid, tisepm_stdid, posepm_stdid, &
         nesepi_stdid, tesepi_stdid, tisepi_stdid, posepi_stdid, &
         nesepa_stdid, tesepa_stdid, tisepa_stdid, posepa_stdid, &
         nemxip_stdid, temxip_stdid, timxip_stdid, pomxip_stdid, &
         nemxap_stdid, temxap_stdid, timxap_stdid, pomxap_stdid, &
         ktsepm_stdid, ktsepi_stdid, ktsepa_stdid
    ! variable shapes
    integer :: dims(2)
    real (kind=R8) :: dvals(1)

    ! Create and enter define mode
    iret = nf_create(trim(filename), ncclob, ncid)
    call check_cdf_status(iret)
    ! define dimensions
    if (.not.batch_only) then
      iret = nf_def_dim(ncid, 'nCv', mpg%nCv, ncvdim)
      call check_cdf_status(iret)
      iret = nf_def_dim(ncid, 'nFc', mpg%nFc, nfcdim)
      call check_cdf_status(iret)
      if (maxval(mpg%strDiv).ge.2) then
        nybl = mpg%divFcP(1,2)
        iret = nf_def_dim(ncid, 'nybl', nybl, nybldim)
        call check_cdf_status(iret)
        nybr = mpg%divFcP(maxval(mpg%strDiv),2)
        iret = nf_def_dim(ncid, 'nybr', nybr, nybrdim)
        call check_cdf_status(iret)
      end if
      if (maxval(mpg%strDiv).ge.4) then
        nytl = mpg%divFcP(2,2)
        iret = nf_def_dim(ncid, 'nytl', nytl, nytldim)
        call check_cdf_status(iret)
        nytr = mpg%divFcP(3,2)
        iret = nf_def_dim(ncid, 'nytr', nytr, nytrdim)
        call check_cdf_status(iret)
      endif
      if (nimp.gt.0) then
        nyi = nimp
        iret = nf_def_dim(ncid, 'nyi', nyi, nyidim)
        call check_cdf_status(iret)
      end if
      if (nomp.gt.0) then
        nya = nomp
        iret = nf_def_dim(ncid, 'nya', nya, nyadim)
        call check_cdf_status(iret)
      end if
      iret = nf_def_dim(ncid, 'ns', ns, nsdim)
      call check_cdf_status(iret)
      iret = nf_def_dim(ncid, 'time', ncunlim, timedim)
      call check_cdf_status(iret)
      iret = nf_def_dim(ncid, 'idir', 2, idirdim)  ! Needed for fluxes
      call check_cdf_status(iret)
    else
      iret = nf_def_dim(ncid, 'batch', ncunlim, batchdim)
      call check_cdf_status(iret)
    end if
    nc = max(1,mpg%nXpt)
    iret = nf_def_dim(ncid, 'nc', nc, ncdim)
    call check_cdf_status(iret)
    ! define variables
    if (.not.batch_only) then
      dims(1) = 0
      iret = nf_def_var(ncid, 'ntstep', NCDOUBLE, 0, dims, ntstepid)
      call check_cdf_status(iret)
      dims(1) = timedim
      iret = nf_def_var(ncid, 'timesa', NCDOUBLE, 1, dims, timesaid)
      call check_cdf_status(iret)
      dvals(1) = 1.0_R8/ev
      if (write_2d .ge. 1) then
        iret = nf_def_var(ncid, 'ne2d', NCDOUBLE, 2, (/ncvdim,timedim/), ne2did)
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, ne2did, 'long_name', 2, 'ne')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, ne2did, 'units', 4, 'm^-3')
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'te2d', NCDOUBLE, 2, (/ncvdim,timedim/), te2did)
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, te2did, 'long_name', 2, 'Te')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, te2did, 'units', 2, 'eV')
        call check_cdf_status(iret)
        iret = nf_put_att_double(ncid, te2did, 'scale', NCDOUBLE, 1, dvals(1))
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'ti2d', NCDOUBLE, 2, (/ncvdim,timedim/), ti2did)
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, ti2did, 'long_name', 2, 'Ti')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, ti2did, 'units', 2, 'eV')
        call check_cdf_status(iret)
        iret = nf_put_att_double(ncid, ti2did, 'scale', NCDOUBLE, 1, dvals(1))
        call check_cdf_status(iret)
        if (write_2d .ge. 2) then
          iret = nf_def_var(ncid, 'po2d', NCDOUBLE, 2, (/ncvdim,timedim/), po2did)
          call check_cdf_status(iret)
          iret = nf_put_att_text(ncid, po2did, 'long_name', 9, 'potential')
          call check_cdf_status(iret)
          iret = nf_put_att_text(ncid, po2did, 'units', 1, 'V')
          call check_cdf_status(iret)
          iret = nf_def_var(ncid, 'kin2d', NCDOUBLE, 3, (/ncvdim,nsdim,timedim/), kin2did)
          call check_cdf_status(iret)
          iret = nf_put_att_text(ncid, kin2did, 'long_name', 23, 'parallel kinetic energy')
          call check_cdf_status(iret)
          iret = nf_put_att_text(ncid, kin2did, 'units', 1, 'J')
          call check_cdf_status(iret)
          iret = nf_def_var(ncid, 'rsahi2d', NCDOUBLE, 3, (/ncvdim,nsdim,timedim/), rsahi2did)
          call check_cdf_status(iret)
          iret = nf_put_att_text(ncid, rsahi2did, 'long_name', 21, 'iz energy source/sink')
          call check_cdf_status(iret)
          iret = nf_put_att_text(ncid, rsahi2did, 'units', 1, 'W')
          call check_cdf_status(iret)
          iret = nf_def_var(ncid, 'rsana2d', NCDOUBLE, 3, (/ncvdim,nsdim,timedim/), rsana2did)
          call check_cdf_status(iret)
          iret = nf_put_att_text(ncid, rsana2did, 'long_name', 7, 'iz rate')
          call check_cdf_status(iret)
          iret = nf_put_att_text(ncid, rsana2did, 'units', 3, '1/s')
          call check_cdf_status(iret)
          iret = nf_def_var(ncid, 'rrahi2d', NCDOUBLE, 3, (/ncvdim,nsdim,timedim/), rrahi2did)
          call check_cdf_status(iret)
          iret = nf_put_att_text(ncid, rrahi2did, 'long_name', 21, 'rc energy source/sink')
          call check_cdf_status(iret)
          iret = nf_put_att_text(ncid, rrahi2did, 'units', 1, 'W')
          call check_cdf_status(iret)
          iret = nf_def_var(ncid, 'rrana2d', NCDOUBLE, 3, (/ncvdim,nsdim,timedim/), rrana2did)
          call check_cdf_status(iret)
          iret = nf_put_att_text(ncid, rrana2did, 'long_name', 7, 'rc rate')
          call check_cdf_status(iret)
          iret = nf_put_att_text(ncid, rrana2did, 'units', 3, '1/s')
          call check_cdf_status(iret)
          iret = nf_def_var(ncid, 'rcxhi2d', NCDOUBLE, 3, (/ncvdim,nsdim,timedim/), rcxhi2did)
          call check_cdf_status(iret)
          iret = nf_put_att_text(ncid, rcxhi2did, 'long_name', 21, 'cx energy source/sink')
          call check_cdf_status(iret)
          iret = nf_put_att_text(ncid, rcxhi2did, 'units', 1, 'W')
          call check_cdf_status(iret)
          iret = nf_def_var(ncid, 'rcxna2d', NCDOUBLE, 3, (/ncvdim,nsdim,timedim/), rcxna2did)
          call check_cdf_status(iret)
          iret = nf_put_att_text(ncid, rcxna2did, 'long_name', 7, 'cx rate')
          call check_cdf_status(iret)
          iret = nf_put_att_text(ncid, rcxna2did, 'units', 3, '1/s')
          call check_cdf_status(iret)
          iret = nf_def_var(ncid, 'rqrad2d', NCDOUBLE, 3, (/ncvdim,nsdim,timedim/), rqrad2did)
          call check_cdf_status(iret)
          iret = nf_put_att_text(ncid, rqrad2did, 'long_name', 19, 'Line radiation rate')
          call check_cdf_status(iret)
          iret = nf_put_att_text(ncid, rqrad2did, 'units', 1, 'W')
          call check_cdf_status(iret)
          iret = nf_def_var(ncid, 'rqahe2d', NCDOUBLE, 3, (/ncvdim,nsdim,timedim/), rqahe2did)
          call check_cdf_status(iret)
          iret = nf_put_att_text(ncid, rqahe2did, 'long_name', 21, 'Electron cooling rate')
          call check_cdf_status(iret)
          iret = nf_put_att_text(ncid, rqahe2did, 'units', 1, 'W')
          call check_cdf_status(iret)
          iret = nf_def_var(ncid, 'fhe2d', NCDOUBLE, 3, (/nfcdim,idirdim,timedim/), fhe2did)
          call check_cdf_status(iret)
          iret = nf_put_att_text(ncid, fhe2did, 'long_name', 18, 'Electron heat flux')
          call check_cdf_status(iret)
          iret = nf_put_att_text(ncid, fhe2did, 'units', 1, 'W')
          call check_cdf_status(iret)
          iret = nf_def_var(ncid, 'fhi2d', NCDOUBLE, 3, (/nfcdim,idirdim,timedim/), fhi2did)
          call check_cdf_status(iret)
          iret = nf_put_att_text(ncid, fhi2did, 'long_name', 13, 'Ion heat flux')
          call check_cdf_status(iret)
          iret = nf_put_att_text(ncid, fhi2did, 'units', 1, 'W')
          call check_cdf_status(iret)
          iret = nf_def_var(ncid, 'fch2d', NCDOUBLE, 3, (/nfcdim,idirdim,timedim/), fch2did)
          call check_cdf_status(iret)
          iret = nf_put_att_text(ncid, fch2did, 'long_name', 7, 'Current')
          call check_cdf_status(iret)
          iret = nf_put_att_text(ncid, fch2did, 'units', 1, 'A')
          call check_cdf_status(iret)
          iret = nf_def_var(ncid, 'fna2d', NCDOUBLE, 4, (/nfcdim,idirdim,nsdim,timedim/), fna2did)
          call check_cdf_status(iret)
          iret = nf_put_att_text(ncid, fna2did, 'long_name', 13, 'Particle flux')
          call check_cdf_status(iret)
          iret = nf_put_att_text(ncid, fna2did, 'units', 3, '1/s')
          call check_cdf_status(iret)
        endif
      endif

      dims(1) = ncdim
      dims(2) = timedim
      iret = nf_def_var(ncid, 'fnixip', NCDOUBLE, 2, dims, fnixipid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'feexip', NCDOUBLE, 2, dims, feexipid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'feixip', NCDOUBLE, 2, dims, feixipid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'fetxip', NCDOUBLE, 2, dims, fetxipid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'fchxip', NCDOUBLE, 2, dims, fchxipid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'fnixap', NCDOUBLE, 2, dims, fnixapid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'feexap', NCDOUBLE, 2, dims, feexapid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'feixap', NCDOUBLE, 2, dims, feixapid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'fetxap', NCDOUBLE, 2, dims, fetxapid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'fchxap', NCDOUBLE, 2, dims, fchxapid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'nesepi', NCDOUBLE, 2, dims, nesepiid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'tesepi', NCDOUBLE, 2, dims, tesepiid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'tisepi', NCDOUBLE, 2, dims, tisepiid)
      call check_cdf_status(iret)
#ifdef WG_TODO
      iret = nf_def_var(ncid, 'tpsepi', NCDOUBLE, 2, dims, tpsepiid)
      call check_cdf_status(iret)
#endif
      iret = nf_def_var(ncid, 'posepi', NCDOUBLE, 2, dims, posepiid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'ktsepi', NCDOUBLE, 2, dims, ktsepiid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'nesepm', NCDOUBLE, 2, dims, nesepmid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'tesepm', NCDOUBLE, 2, dims, tesepmid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'tisepm', NCDOUBLE, 2, dims, tisepmid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'posepm', NCDOUBLE, 2, dims, posepmid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'ktsepm', NCDOUBLE, 2, dims, ktsepmid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'dnsepm', NCDOUBLE, 2, dims, dnsepmid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'dpsepm', NCDOUBLE, 2, dims, dpsepmid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'kesepm', NCDOUBLE, 2, dims, kesepmid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'kisepm', NCDOUBLE, 2, dims, kisepmid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'vxsepm', NCDOUBLE, 2, dims, vxsepmid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'vysepm', NCDOUBLE, 2, dims, vysepmid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'vssepm', NCDOUBLE, 2, dims, vssepmid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'nesepa', NCDOUBLE, 2, dims, nesepaid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'tesepa', NCDOUBLE, 2, dims, tesepaid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'tisepa', NCDOUBLE, 2, dims, tisepaid)
      call check_cdf_status(iret)
#ifdef WG_TODO
      iret = nf_def_var(ncid, 'tpsepa', NCDOUBLE, 2, dims, tpsepaid)
      call check_cdf_status(iret)
#endif
      iret = nf_def_var(ncid, 'posepa', NCDOUBLE, 2, dims, posepaid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'ktsepa', NCDOUBLE, 2, dims, ktsepaid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'nemxip', NCDOUBLE, 2, dims, nemxipid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'temxip', NCDOUBLE, 2, dims, temxipid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'timxip', NCDOUBLE, 2, dims, timxipid)
      call check_cdf_status(iret)
#ifdef WG_TODO
      iret = nf_def_var(ncid, 'tpmxip', NCDOUBLE, 2, dims, tpmxipid)
      call check_cdf_status(iret)
#endif
      iret = nf_def_var(ncid, 'pomxip', NCDOUBLE, 2, dims, pomxipid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'nemxap', NCDOUBLE, 2, dims, nemxapid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'temxap', NCDOUBLE, 2, dims, temxapid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'timxap', NCDOUBLE, 2, dims, timxapid)
      call check_cdf_status(iret)
#ifdef WG_TODO
      iret = nf_def_var(ncid, 'tpmxap', NCDOUBLE, 2, dims, tpmxapid)
      call check_cdf_status(iret)
#endif
      iret = nf_def_var(ncid, 'pomxap', NCDOUBLE, 2, dims, pomxapid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'fniyip', NCDOUBLE, 2, dims, fniyipid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'feeyip', NCDOUBLE, 2, dims, feeyipid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'feiyip', NCDOUBLE, 2, dims, feiyipid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'fetyip', NCDOUBLE, 2, dims, fetyipid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'fchyip', NCDOUBLE, 2, dims, fchyipid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'fniyap', NCDOUBLE, 2, dims, fniyapid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'feeyap', NCDOUBLE, 2, dims, feeyapid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'feiyap', NCDOUBLE, 2, dims, feiyapid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'fetyap', NCDOUBLE, 2, dims, fetyapid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'fchyap', NCDOUBLE, 2, dims, fchyapid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'pwmxip', NCDOUBLE, 2, dims, pwmxipid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'pwmxap', NCDOUBLE, 2, dims, pwmxapid)
      call check_cdf_status(iret)
      dims(1) = timedim
      iret = nf_def_var(ncid, 'tmne', NCDOUBLE, 1, dims, tmneid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'tmte', NCDOUBLE, 1, dims, tmteid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'tmti', NCDOUBLE, 1, dims, tmtiid)
      call check_cdf_status(iret)
#ifdef WG_TODO
      iret = nf_def_var(ncid, 'tmhacore', NCDOUBLE, 1, dims, tmhacoreid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'tmhasol', NCDOUBLE, 1, dims, tmhasolid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'tmhadiv', NCDOUBLE, 1, dims, tmhadivid)
      call check_cdf_status(iret)
#endif
      dims(1) = ncdim
      dims(2) = timedim
      iret = nf_def_var(ncid, 'fnisip', NCDOUBLE, 2, dims, fnisipid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'feesip', NCDOUBLE, 2, dims, feesipid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'feisip', NCDOUBLE, 2, dims, feisipid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'fetsip', NCDOUBLE, 2, dims, fetsipid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'fchsip', NCDOUBLE, 2, dims, fchsipid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'fnisap', NCDOUBLE, 2, dims, fnisapid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'feesap', NCDOUBLE, 2, dims, feesapid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'feisap', NCDOUBLE, 2, dims, feisapid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'fetsap', NCDOUBLE, 2, dims, fetsapid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'fchsap', NCDOUBLE, 2, dims, fchsapid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'fnisipp', NCDOUBLE, 2, dims, fnisippid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'feesipp', NCDOUBLE, 2, dims, feesippid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'feisipp', NCDOUBLE, 2, dims, feisippid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'fetsipp', NCDOUBLE, 2, dims, fetsippid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'fchsipp', NCDOUBLE, 2, dims, fchsippid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'fnisapp', NCDOUBLE, 2, dims, fnisappid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'feesapp', NCDOUBLE, 2, dims, feesappid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'feisapp', NCDOUBLE, 2, dims, feisappid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'fetsapp', NCDOUBLE, 2, dims, fetsappid)
      call check_cdf_status(iret)
      iret = nf_def_var(ncid, 'fchsapp', NCDOUBLE, 2, dims, fchsappid)
      call check_cdf_status(iret)

      if (maxval(mpg%strDiv).ge.2) then
        dims(2) = timedim
        dims(1) = nybldim
        iret = nf_def_var(ncid, 'fn3dl', NCDOUBLE, 2, dims, fn3dlid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'fe3dl', NCDOUBLE, 2, dims, fe3dlid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'fi3dl', NCDOUBLE, 2, dims, fi3dlid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'ft3dl', NCDOUBLE, 2, dims, ft3dlid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'fc3dl', NCDOUBLE, 2, dims, fc3dlid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'fl3dl', NCDOUBLE, 2, dims, fl3dlid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'fo3dl', NCDOUBLE, 2, dims, fo3dlid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'ne3dl', NCDOUBLE, 2, dims, ne3dlid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'te3dl', NCDOUBLE, 2, dims, te3dlid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'ti3dl', NCDOUBLE, 2, dims, ti3dlid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'po3dl', NCDOUBLE, 2, dims, po3dlid)
        call check_cdf_status(iret)
        if (ismain0.ne.ismain) then
          iret = nf_def_var(ncid, 'an3dl', NCDOUBLE, 2, dims, an3dlid)
          call check_cdf_status(iret)
        end if
        if (nnmoli.gt.0) then
          iret = nf_def_var(ncid, 'mn3dl', NCDOUBLE, 2, dims, mn3dlid)
          call check_cdf_status(iret)
        end if
#ifdef WG_TODO
        iret = nf_def_var(ncid, 'tp3dl', NCDOUBLE, 2, dims, tp3dlid)
        call check_cdf_status(iret)
#endif
        dims(2) = timedim
        dims(1) = nybrdim
        iret = nf_def_var(ncid, 'ne3dr', NCDOUBLE, 2, dims, ne3drid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'te3dr', NCDOUBLE, 2, dims, te3drid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'ti3dr', NCDOUBLE, 2, dims, ti3drid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'po3dr', NCDOUBLE, 2, dims, po3drid)
        call check_cdf_status(iret)
        if (ismain0.ne.ismain) then
          iret = nf_def_var(ncid, 'an3dr', NCDOUBLE, 2, dims, an3drid)
          call check_cdf_status(iret)
        end if
        if (nnmoli.gt.0) then
          iret = nf_def_var(ncid, 'mn3dr', NCDOUBLE, 2, dims, mn3drid)
          call check_cdf_status(iret)
        end if
        iret = nf_def_var(ncid, 'fn3dr', NCDOUBLE, 2, dims, fn3drid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'fe3dr', NCDOUBLE, 2, dims, fe3drid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'fi3dr', NCDOUBLE, 2, dims, fi3drid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'ft3dr', NCDOUBLE, 2, dims, ft3drid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'fc3dr', NCDOUBLE, 2, dims, fc3drid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'fl3dr', NCDOUBLE, 2, dims, fl3drid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'fo3dr', NCDOUBLE, 2, dims, fo3drid)
        call check_cdf_status(iret)
#ifdef WG_TODO
        iret = nf_def_var(ncid, 'tp3dr', NCDOUBLE, 2, dims, tp3drid)
        call check_cdf_status(iret)
#endif
      end if
      if(maxval(mpg%strDiv).ge.4) then
        dims(2) = timedim
        dims(1) = nytldim
        iret = nf_def_var(ncid, 'fn3dtl', NCDOUBLE, 2, dims, fn3dtlid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'fe3dtl', NCDOUBLE, 2, dims, fe3dtlid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'fi3dtl', NCDOUBLE, 2, dims, fi3dtlid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'ft3dtl', NCDOUBLE, 2, dims, ft3dtlid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'fc3dtl', NCDOUBLE, 2, dims, fc3dtlid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'fl3dtl', NCDOUBLE, 2, dims, fl3dtlid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'fo3dtl', NCDOUBLE, 2, dims, fo3dtlid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'ne3dtl', NCDOUBLE, 2, dims, ne3dtlid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'te3dtl', NCDOUBLE, 2, dims, te3dtlid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'ti3dtl', NCDOUBLE, 2, dims, ti3dtlid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'po3dtl', NCDOUBLE, 2, dims, po3dtlid)
        call check_cdf_status(iret)
        if (ismain0.ne.ismain) then
          iret = nf_def_var(ncid, 'an3dtl', NCDOUBLE, 2, dims, an3dtlid)
          call check_cdf_status(iret)
        end if
        if (nnmoli.gt.0) then
          iret = nf_def_var(ncid, 'mn3dtl', NCDOUBLE, 2, dims, mn3dtlid)
          call check_cdf_status(iret)
        end if
#ifdef WG_TODO
        iret = nf_def_var(ncid, 'tp3dtl', NCDOUBLE, 2, dims, tp3dtlid)
        call check_cdf_status(iret)
#endif
        dims(2) = timedim
        dims(1) = nytrdim
        iret = nf_def_var(ncid, 'ne3dtr', NCDOUBLE, 2, dims, ne3dtrid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'te3dtr', NCDOUBLE, 2, dims, te3dtrid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'ti3dtr', NCDOUBLE, 2, dims, ti3dtrid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'po3dtr', NCDOUBLE, 2, dims, po3dtrid)
        call check_cdf_status(iret)
        if (ismain0.ne.ismain) then
          iret = nf_def_var(ncid, 'an3dtr', NCDOUBLE, 2, dims, an3dtrid)
          call check_cdf_status(iret)
        end if
        if (nnmoli.gt.0) then
          iret = nf_def_var(ncid, 'mn3dtr', NCDOUBLE, 2, dims, mn3dtrid)
          call check_cdf_status(iret)
        end if
        iret = nf_def_var(ncid, 'fn3dtr', NCDOUBLE, 2, dims, fn3dtrid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'fe3dtr', NCDOUBLE, 2, dims, fe3dtrid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'fi3dtr', NCDOUBLE, 2, dims, fi3dtrid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'ft3dtr', NCDOUBLE, 2, dims, ft3dtrid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'fc3dtr', NCDOUBLE, 2, dims, fc3dtrid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'fl3dtr', NCDOUBLE, 2, dims, fl3dtrid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'fo3dtr', NCDOUBLE, 2, dims, fo3dtrid)
        call check_cdf_status(iret)
#ifdef WG_TODO
        iret = nf_def_var(ncid, 'tp3dtr', NCDOUBLE, 2, dims, tp3dtrid)
        call check_cdf_status(iret)
#endif
      endif
      if (nimp.gt.0) then
        dims(2) = timedim
        dims(1) = nyidim
        iret = nf_def_var(ncid, 'ne3di', NCDOUBLE, 2, dims, ne3diid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'te3di', NCDOUBLE, 2, dims, te3diid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'ti3di', NCDOUBLE, 2, dims, ti3diid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'po3di', NCDOUBLE, 2, dims, po3diid)
        call check_cdf_status(iret)
        if (ismain0.ne.ismain) then
          iret = nf_def_var(ncid, 'an3di', NCDOUBLE, 2, dims, an3diid)
          call check_cdf_status(iret)
        end if
        if (nnmoli.gt.0) then
          iret = nf_def_var(ncid, 'mn3di', NCDOUBLE, 2, dims, mn3diid)
          call check_cdf_status(iret)
        end if
        iret = nf_def_var(ncid, 'dn3di', NCDOUBLE, 2, dims, dn3diid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'dp3di', NCDOUBLE, 2, dims, dp3diid)
        call check_cdf_status(iret)
#ifdef WG_TODO
        iret = nf_def_var(ncid, 'lh3di', NCDOUBLE, 2, dims, lh3diid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'ln3di', NCDOUBLE, 2, dims, ln3diid)
        call check_cdf_status(iret)
#endif
        iret = nf_def_var(ncid, 'ke3di', NCDOUBLE, 2, dims, ke3diid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'ki3di', NCDOUBLE, 2, dims, ki3diid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'vx3di', NCDOUBLE, 2, dims, vx3diid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'vy3di', NCDOUBLE, 2, dims, vy3diid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'vs3di', NCDOUBLE, 2, dims, vs3diid)
        call check_cdf_status(iret)
      end if
      if (nomp.gt.0) then
        dims(2) = timedim
        dims(1) = nyadim
        iret = nf_def_var(ncid, 'ne3da', NCDOUBLE, 2, dims, ne3daid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'te3da', NCDOUBLE, 2, dims, te3daid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'ti3da', NCDOUBLE, 2, dims, ti3daid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'po3da', NCDOUBLE, 2, dims, po3daid)
        call check_cdf_status(iret)
        if (ismain0.ne.ismain) then
          iret = nf_def_var(ncid, 'an3da', NCDOUBLE, 2, dims, an3daid)
          call check_cdf_status(iret)
        end if
        if (nnmoli.gt.0) then
          iret = nf_def_var(ncid, 'mn3da', NCDOUBLE, 2, dims, mn3daid)
          call check_cdf_status(iret)
        end if
        iret = nf_def_var(ncid, 'dn3da', NCDOUBLE, 2, dims, dn3daid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'dp3da', NCDOUBLE, 2, dims, dp3daid)
        call check_cdf_status(iret)
#ifdef WG_TODO
        iret = nf_def_var(ncid, 'lh3da', NCDOUBLE, 2, dims, lh3daid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'ln3da', NCDOUBLE, 2, dims, ln3daid)
        call check_cdf_status(iret)
#endif
        iret = nf_def_var(ncid, 'ke3da', NCDOUBLE, 2, dims, ke3daid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'ki3da', NCDOUBLE, 2, dims, ki3daid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'vx3da', NCDOUBLE, 2, dims, vx3daid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'vy3da', NCDOUBLE, 2, dims, vy3daid)
        call check_cdf_status(iret)
        iret = nf_def_var(ncid, 'vs3da', NCDOUBLE, 2, dims, vs3daid)
        call check_cdf_status(iret)
      end if
    endif !not.batch_only

    !wdk averages
    if (batch_only) then
      dims(1) = 0
      iret  = nf_def_var(ncid, 'nastep', NCDOUBLE, 0, dims, nastepid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'ntim_batch', NCDOUBLE, 0, dims, ntimbatchid)
      call check_cdf_status(iret)
      dims(1) = batchdim
      iret  = nf_def_var(ncid, 'batchsa', NCDOUBLE, 1, dims, batchsaid)
      call check_cdf_status(iret)
      dims(1) = ncdim
      dims(2) = batchdim
      iret  = nf_def_var(ncid, 'nesepm_av', NCDOUBLE, 2, dims, nesepm_avid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'tesepm_av', NCDOUBLE, 2, dims, tesepm_avid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'tisepm_av', NCDOUBLE, 2, dims, tisepm_avid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'posepm_av', NCDOUBLE, 2, dims, posepm_avid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'ktsepm_av', NCDOUBLE, 2, dims, ktsepm_avid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'nesepi_av', NCDOUBLE, 2, dims, nesepi_avid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'tesepi_av', NCDOUBLE, 2, dims, tesepi_avid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'tisepi_av', NCDOUBLE, 2, dims, tisepi_avid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'posepi_av', NCDOUBLE, 2, dims, posepi_avid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'ktsepi_av', NCDOUBLE, 2, dims, ktsepi_avid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'nesepa_av', NCDOUBLE, 2, dims, nesepa_avid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'tesepa_av', NCDOUBLE, 2, dims, tesepa_avid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'tisepa_av', NCDOUBLE, 2, dims, tisepa_avid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'posepa_av', NCDOUBLE, 2, dims, posepa_avid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'ktsepa_av', NCDOUBLE, 2, dims, ktsepa_avid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'nemxip_av', NCDOUBLE, 2, dims, nemxip_avid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'temxip_av', NCDOUBLE, 2, dims, temxip_avid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'timxip_av', NCDOUBLE, 2, dims, timxip_avid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'pomxip_av', NCDOUBLE, 2, dims, pomxip_avid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'nemxap_av', NCDOUBLE, 2, dims, nemxap_avid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'temxap_av', NCDOUBLE, 2, dims, temxap_avid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'timxap_av', NCDOUBLE, 2, dims, timxap_avid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'pomxap_av', NCDOUBLE, 2, dims, pomxap_avid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'nesepm_std', NCDOUBLE, 2, dims, nesepm_stdid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'tesepm_std', NCDOUBLE, 2, dims, tesepm_stdid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'tisepm_std', NCDOUBLE, 2, dims, tisepm_stdid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'posepm_std', NCDOUBLE, 2, dims, posepm_stdid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'ktsepm_std', NCDOUBLE, 2, dims, ktsepm_stdid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'nesepi_std', NCDOUBLE, 2, dims, nesepi_stdid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'tesepi_std', NCDOUBLE, 2, dims, tesepi_stdid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'tisepi_std', NCDOUBLE, 2, dims, tisepi_stdid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'posepi_std', NCDOUBLE, 2, dims, posepi_stdid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'ktsepi_std', NCDOUBLE, 2, dims, ktsepi_stdid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'nesepa_std', NCDOUBLE, 2, dims, nesepa_stdid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'tesepa_std', NCDOUBLE, 2, dims, tesepa_stdid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'tisepa_std', NCDOUBLE, 2, dims, tisepa_stdid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'posepa_std', NCDOUBLE, 2, dims, posepa_stdid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'ktsepa_std', NCDOUBLE, 2, dims, ktsepa_stdid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'nemxip_std', NCDOUBLE, 2, dims, nemxip_stdid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'temxip_std', NCDOUBLE, 2, dims, temxip_stdid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'timxip_std', NCDOUBLE, 2, dims, timxip_stdid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'pomxip_std', NCDOUBLE, 2, dims, pomxip_stdid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'nemxap_std', NCDOUBLE, 2, dims, nemxap_stdid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'temxap_std', NCDOUBLE, 2, dims, temxap_stdid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'timxap_std', NCDOUBLE, 2, dims, timxap_stdid)
      call check_cdf_status(iret)
      iret  = nf_def_var(ncid, 'pomxap_std', NCDOUBLE, 2, dims, pomxap_stdid)
      call check_cdf_status(iret)
    endif

    ! assign attributes
    if (.not.batch_only) then
      iret = nf_put_att_text(ncid, timesaid, 'long_name', 4, 'time')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, timesaid, 'units', 2, 's ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fnixipid, 'long_name', 47, 'integrated poloidal particle flux, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fnixipid, 'units', 4, 's^-1')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, feexipid, 'long_name', 54, 'integrated poloidal electron energy flux, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, feexipid, 'units', 2, 'W ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, feixipid, 'long_name', 49, 'integrated poloidal ion energy flux, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, feixipid, 'units', 2, 'W ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fetxipid, 'long_name', 60, 'integrated poloidal total internal energy flux, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fetxipid, 'units', 2, 'W ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fchxipid, 'long_name', 41, 'integrated poloidal current, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fchxipid, 'units', 2, 'A ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fnixapid, 'long_name', 47, 'integrated poloidal particle flux, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fnixapid, 'units', 4, 's^-1')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, feexapid, 'long_name', 54, 'integrated poloidal electron energy flux, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, feexapid, 'units', 2, 'W ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, feixapid, 'long_name', 49, 'integrated poloidal ion energy flux, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, feixapid, 'units', 2, 'W ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fetxapid, 'long_name', 60, 'integrated poloidal total internal energy flux, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fetxapid, 'units', 2, 'W ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fchxapid, 'long_name', 41, 'integrated poloidal current, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fchxapid, 'units', 2, 'A ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, nesepiid, 'long_name', 41, 'separatrix electron density, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, nesepiid, 'units', 4, 'm^-3')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tesepiid, 'long_name', 45, 'separatrix electron temperature, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tesepiid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tisepiid, 'long_name', 40, 'separatrix ion temperature, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tisepiid, 'units', 2, 'eV')
      call check_cdf_status(iret)
#ifdef WG_TODO
      iret = nf_put_att_text(ncid, tpsepiid, 'long_name', 42, 'separatrix plate temperature, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tpsepiid, 'units', 2, 'K ')
      call check_cdf_status(iret)
#endif
      iret = nf_put_att_text(ncid, posepiid, 'long_name', 34, 'separatrix potential, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, posepiid, 'units', 2, 'V ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ktsepiid, 'long_name', 49, 'separatrix turbulent kinetic energy, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ktsepiid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, nesepmid, 'long_name', 43, 'separatrix electron density, outer midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, nesepmid, 'units', 4, 'm^-3')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tesepmid, 'long_name', 47, 'separatrix electron temperature, outer midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tesepmid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tisepmid, 'long_name', 42, 'separatrix ion temperature, outer midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tisepmid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, posepmid, 'long_name', 36, 'separatrix potential, outer midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, posepmid, 'units', 2, 'V ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ktsepmid, 'long_name', 51, 'separatrix turbulent kinetic energy, outer midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ktsepmid, 'units', 2, 'eV')
      call check_cdf_status(iret)

      iret = nf_put_att_text(ncid, dnsepmid, 'long_name', 37, 'diffusion coefficient, outer midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, dnsepmid, 'units', 8, 'm^2.s^-1')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, dpsepmid, 'long_name', 46, 'pressure diffusion coefficient, outer midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, dpsepmid, 'units', 8, 'm^2.s^-1')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, kesepmid, 'long_name', 44, 'electron thermal diffusivity, outer midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, kesepmid, 'units', 8, 'm^2.s^-1')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, kisepmid, 'long_name', 39, 'ion thermal diffusivity, outer midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, kisepmid, 'units', 8, 'm^2.s^-1')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, vxsepmid, 'long_name', 39, 'poloidal pinch velocity, outer midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, vxsepmid, 'units', 6, 'm.s^-1')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, vysepmid, 'long_name', 37, 'radial pinch velocity, outer midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, vysepmid, 'units', 6, 'm.s^-1')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, vssepmid, 'long_name', 37, 'viscosity coefficient, outer midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, vssepmid, 'units', 12, 'm.kg^-1.s^-1')
      call check_cdf_status(iret)

      iret = nf_put_att_text(ncid, nesepaid, 'long_name', 41, 'separatrix electron density, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, nesepaid, 'units', 4, 'm^-3')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tesepaid, 'long_name', 45, 'separatrix electron temperature, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tesepaid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tisepaid, 'long_name', 40, 'separatrix ion temperature, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tisepaid, 'units', 2, 'eV')
      call check_cdf_status(iret)
#ifdef WG_TODO
      iret = nf_put_att_text(ncid, tpsepaid, 'long_name', 42, 'separatrix plate temperature, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tpsepaid, 'units', 2, 'K ')
      call check_cdf_status(iret)
#endif
      iret = nf_put_att_text(ncid, posepaid, 'long_name', 34, 'separatrix potential, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, posepaid, 'units', 2, 'V ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ktsepaid, 'long_name', 50, 'separatrix turbulent kinetic energy, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ktsepaid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, nemxipid, 'long_name', 38, 'maximum electron density, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, nemxipid, 'units', 4, 'm^-3')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, temxipid, 'long_name', 42, 'maximum electron temperature, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, temxipid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, timxipid, 'long_name', 37, 'maximum ion temperature, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, timxipid, 'units', 2, 'eV')
      call check_cdf_status(iret)
#ifdef WG_TODO
      iret = nf_put_att_text(ncid, tpmxipid, 'long_name', 39, 'maximum plate temperature, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tpmxipid, 'units', 2, 'K ')
      call check_cdf_status(iret)
#endif
      iret = nf_put_att_text(ncid, pomxipid, 'long_name', 31, 'maximum potential, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, pomxipid, 'units', 2, 'V ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, nemxapid, 'long_name', 38, 'maximum electron density, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, nemxapid, 'units', 4, 'm^-3')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, temxapid, 'long_name', 42, 'maximum electron temperature, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, temxapid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, timxapid, 'long_name', 38, 'maximum ion temperature, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, timxapid, 'units', 2, 'eV')
      call check_cdf_status(iret)
#ifdef WG_TODO
      iret = nf_put_att_text(ncid, tpmxapid, 'long_name', 40, 'maximum plate temperature, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tpmxapid, 'units', 2, 'K ')
      call check_cdf_status(iret)
#endif
      iret = nf_put_att_text(ncid, pomxapid, 'long_name', 32, 'maximum potential, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, pomxapid, 'units', 2, 'V ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fniyipid, 'long_name', 45, 'integrated radial particle flux, main chamber')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fniyipid, 'units', 4, 's^-1')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, feeyipid, 'long_name', 52, 'integrated radial electron energy flux, main chamber')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, feeyipid, 'units', 2, 'W ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, feiyipid, 'long_name', 47, 'integrated radial ion energy flux, main chamber')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, feiyipid, 'units', 2, 'W ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fetyipid, 'long_name', 58, 'integrated radial total internal energy flux, main chamber')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fetyipid, 'units', 2, 'W ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fchyipid, 'long_name', 39, 'integrated radial current, main chamber')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fchyipid, 'units', 2, 'A ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fniyapid, 'long_name', 48, 'integrated radial particle flux, divertor region')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fniyapid, 'units', 4, 's^-1')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, feeyapid, 'long_name', 55, 'integrated radial electron energy flux, divertor region')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, feeyapid, 'units', 2, 'W ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, feiyapid, 'long_name', 50, 'integrated radial ion energy flux, divertor region')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, feiyapid, 'units', 2, 'W ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fetyapid, 'long_name', 61, 'integrated radial total internal energy flux, divertor region')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fetyapid, 'units', 2, 'W ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fchyapid, 'long_name', 42, 'integrated radial current, divertor region')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fchyapid, 'units', 2, 'A ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, pwmxipid, 'long_name', 38, 'maximum total power flux, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, pwmxipid, 'units', 6, 'W.m^-2')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, pwmxapid, 'long_name', 38, 'maximum total power flux, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, pwmxapid, 'units', 6, 'W.m^-2')
      call check_cdf_status(iret)

      ! global quantities
      iret = nf_put_att_text(ncid, tmneid, 'long_name', 25, 'total number of particles')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tmneid, 'units', 2, '  ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tmteid, 'long_name', 21, 'total electron energy')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tmteid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tmtiid, 'long_name', 16, 'total ion energy')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tmtiid, 'units', 2, 'eV')
      call check_cdf_status(iret)
#ifdef WG_TODO
      iret = nf_put_att_text(ncid, tmhacoreid, 'long_name', 24, 'H-alpha emissivity, core')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tmhacoreid, 'units', 19, 'photons.m^-2.sr^-1?')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tmhasolid, 'long_name', 41, 'H-alpha emissivity, SOL above the x-point')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tmhasolid, 'units', 19, 'photons.m^-2.sr^-1?')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tmhadivid, 'long_name', 35, 'H-alpha emissivity, divertor region')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tmhadivid, 'units', 19, 'photons.m^-2.sr^-1?')
      call check_cdf_status(iret)
#endif

      ! internal flux quantities
      iret = nf_put_att_text(ncid, fnisipid, 'long_name', 54, 'poloidal particle flux, into Western separatrix throat')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fnisipid, 'units', 4, 's^-1')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, feesipid, 'long_name', 61, 'poloidal electron energy flux, into Western separatrix throat')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, feesipid, 'units', 2, 'W ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, feisipid, 'long_name', 56, 'poloidal ion energy flux, into Western separatrix throat')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, feisipid, 'units', 2, 'W ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fetsipid, 'long_name', 67, 'poloidal total internal energy flux, into Western separatrix throat')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fetsipid, 'units', 2, 'W ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fchsipid, 'long_name', 48, 'poloidal current, into Western separatrix throat')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fchsipid, 'units', 2, 'A ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fnisapid, 'long_name', 54, 'poloidal particle flux, into Eastern separatrix throat')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fnisapid, 'units', 4, 's^-1')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, feesapid, 'long_name', 61, 'poloidal electron energy flux, into Eastern separatrix throat')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, feesapid, 'units', 2, 'W ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, feisapid, 'long_name', 56, 'poloidal ion energy flux, into Eastern separatrix throat')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, feisapid, 'units', 2, 'W ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fetsapid, 'long_name', 67, 'poloidal total internal energy flux, into Eastern separatrix throat')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fetsapid, 'units', 2, 'W ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fchsapid, 'long_name', 48, 'poloidal current, into Eastern separatrix throat')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fchsapid, 'units', 2, 'A ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fnisippid, 'long_name', 40, 'poloidal particle flux, core x-pt region')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fnisippid, 'units', 4, 's^-1')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, feesippid, 'long_name', 52, 'poloidal electron energy flux, core x-pt flux region')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, feesippid, 'units', 2, 'W ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, feisippid, 'long_name', 47, 'poloidal ion energy flux, core x-pt flux region')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, feisippid, 'units', 2, 'W ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fetsippid, 'long_name', 58, 'poloidal total internal energy flux, core x-pt flux region')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fetsippid, 'units', 2, 'W ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fchsippid, 'long_name', 39, 'poloidal current, core x-pt flux region')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fchsippid, 'units', 2, 'A ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fnisappid, 'long_name', 48, 'poloidal particle flux, x-pt private flux region')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fnisappid, 'units', 4, 's^-1')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, feesappid, 'long_name', 55, 'poloidal electron energy flux, x-pt private flux region')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, feesappid, 'units', 2, 'W ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, feisappid, 'long_name', 50, 'poloidal ion energy flux, x-pt private flux region')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, feisappid, 'units', 2, 'W ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fetsappid, 'long_name', 61, 'poloidal total internal energy flux, x-pt private flux region')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fetsappid, 'units', 2, 'W ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fchsappid, 'long_name', 42, 'poloidal current, x-pt private flux region')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fchsappid, 'units', 2, 'A ')
      call check_cdf_status(iret)

      ! Western edge (inboard divertor for LSN, outboard divertor for USN) quantities
      iret = nf_put_att_text(ncid, ne3dlid, 'long_name', 30, 'electron density, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ne3dlid, 'units', 4, 'm^-3')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, te3dlid, 'long_name', 34, 'electron temperature, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, te3dlid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_double(ncid, te3dlid, 'scale', NCDOUBLE, 1, dvals(1))
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ti3dlid, 'long_name', 29, 'ion temperature, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ti3dlid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_double(ncid, ti3dlid, 'scale', NCDOUBLE, 1, dvals(1))
      call check_cdf_status(iret)
#ifdef WG_TODO
      iret = nf_put_att_text(ncid, tp3dlid, 'long_name', 31, 'plate temperature, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tp3dlid, 'units', 2, 'K ')
      call check_cdf_status(iret)
#endif
      iret = nf_put_att_text(ncid, po3dlid, 'long_name', 23, 'potential, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, po3dlid, 'units', 2, 'V ')
      call check_cdf_status(iret)
      if (ismain0.ne.ismain) then
        iret = nf_put_att_text(ncid, an3dlid, 'long_name', 26, 'atom density, Western edge')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, an3dlid, 'units', 4, 'm^-3')
        call check_cdf_status(iret)
      end if
      if (nnmoli.gt.0) then
        iret = nf_put_att_text(ncid, mn3dlid, 'long_name', 30, 'molecule density, Western edge')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, mn3dlid, 'units', 4, 'm^-3')
        call check_cdf_status(iret)
      end if
      dvals(1) = -1.0_R8
      iret = nf_put_att_text(ncid, fn3dlid, 'long_name', 40, 'poloidal main species flux, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fn3dlid, 'units', 4, 's^-1')
      call check_cdf_status(iret)
      iret = nf_put_att_double(ncid, fn3dlid, 'scale', NCDOUBLE, 1, dvals(1))
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fl3dlid, 'long_name', 36, 'poloidal electron flux, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fl3dlid, 'units', 4, 's^-1')
      call check_cdf_status(iret)
      iret = nf_put_att_double(ncid, fl3dlid, 'scale', NCDOUBLE, 1, dvals(1))
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fo3dlid, 'long_name', 31, 'poloidal ion flux, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fo3dlid, 'units', 4, 's^-1')
      call check_cdf_status(iret)
      iret = nf_put_att_double(ncid, fo3dlid, 'scale', NCDOUBLE, 1, dvals(1))
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fe3dlid, 'long_name', 43, 'poloidal electron energy flux, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fe3dlid, 'units', 2, 'W ')
      call check_cdf_status(iret)
      iret = nf_put_att_double(ncid, fe3dlid, 'scale', NCDOUBLE, 1, dvals(1))
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fi3dlid, 'long_name', 38, 'poloidal ion energy flux, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fi3dlid, 'units', 2, 'W ')
      call check_cdf_status(iret)
      iret = nf_put_att_double(ncid, fi3dlid, 'scale', NCDOUBLE, 1, dvals(1))
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ft3dlid, 'long_name', 40, 'poloidal total energy flux, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ft3dlid, 'units', 2, 'W ')
      call check_cdf_status(iret)
      iret = nf_put_att_double(ncid, ft3dlid, 'scale', NCDOUBLE, 1, dvals(1))
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fc3dlid, 'long_name', 31, 'poloidal current, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fc3dlid, 'units', 2, 'A ')
      call check_cdf_status(iret)
      iret = nf_put_att_double(ncid, fc3dlid, 'scale', NCDOUBLE, 1, dvals(1))
      call check_cdf_status(iret)

      ! inboard midplane quantities
      iret = nf_put_att_text(ncid, ne3diid, 'long_name', 34, 'electron density, inboard midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ne3diid, 'units', 4, 'm^-3')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, te3diid, 'long_name', 38, 'electron temperature, inboard midplane')
      call check_cdf_status(iret)
      dvals(1) = 1.0_R8/ev
      iret = nf_put_att_text(ncid, te3diid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_double(ncid, te3diid, 'scale', NCDOUBLE, 1, dvals(1))
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ti3diid, 'long_name', 33, 'ion temperature, inboard midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ti3diid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_double(ncid, ti3diid, 'scale', NCDOUBLE, 1, dvals(1))
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, po3diid, 'long_name', 27, 'potential, inboard midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, po3diid, 'units', 2, 'V ')
      call check_cdf_status(iret)
      if (ismain0.ne.ismain) then
        iret = nf_put_att_text(ncid, an3diid, 'long_name', 30, 'atom density, inboard midplane')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, an3diid, 'units', 4, 'm^-3')
        call check_cdf_status(iret)
      end if
      if (nnmoli.gt.0) then
        iret = nf_put_att_text(ncid, mn3diid, 'long_name', 34, 'molecule density, inboard midplane')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, mn3diid, 'units', 4, 'm^-3')
        call check_cdf_status(iret)
      end if
      iret = nf_put_att_text(ncid, dn3diid, 'long_name', 39, 'diffusion coefficient, inboard midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, dn3diid, 'units', 8, 'm^2.s^-1')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, dp3diid, 'long_name', 48, 'pressure diffusion coefficient, inboard midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, dp3diid, 'units', 8, 'm^2.s^-1')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, lh3diid, 'long_name', 50, 'radial neutral heat flux limiter, inboard midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, lh3diid, 'units', 1, ' ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ln3diid, 'long_name', 50, 'radial neutral part flux limiter, inboard midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ln3diid, 'units', 1, ' ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ke3diid, 'long_name', 46, 'electron thermal diffusivity, inboard midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ke3diid, 'units', 8, 'm^2.s^-1')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ki3diid, 'long_name', 41, 'ion thermal diffusivity, inboard midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ki3diid, 'units', 8, 'm^2.s^-1')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, vx3diid, 'long_name', 41, 'poloidal pinch velocity, inboard midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, vx3diid, 'units', 6, 'm.s^-1')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, vy3diid, 'long_name', 39, 'radial pinch velocity, inboard midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, vy3diid, 'units', 6, 'm.s^-1')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, vs3diid, 'long_name', 39, 'viscosity coefficient, inboard midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, vs3diid, 'units', 12, 'm.kg^-1.s^-1')
      call check_cdf_status(iret)
      ! upper inboard divertor quantities
      if(maxval(mpg%strDiv).ge.4) then
        iret = nf_put_att_text(ncid, ne3dtlid, 'long_name', 40, 'electron density, upper inboard divertor')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, ne3dtlid, 'units', 4, 'm^-3')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, te3dtlid, 'long_name', 44, 'electron temperature, upper inboard divertor')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, te3dtlid, 'units', 2, 'eV')
        call check_cdf_status(iret)
        iret = nf_put_att_double(ncid, te3dtlid, 'scale', NCDOUBLE, 1, dvals(1))
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, ti3dtlid, 'long_name', 39, 'ion temperature, upper inboard divertor')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, ti3dtlid, 'units', 2, 'eV')
        call check_cdf_status(iret)
        iret = nf_put_att_double(ncid, ti3dtlid, 'scale', NCDOUBLE, 1, dvals(1))
        call check_cdf_status(iret)
#ifdef WG_TODO
        iret = nf_put_att_text(ncid, tp3dtlid, 'long_name', 41, 'plate temperature, upper inboard divertor')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, tp3dtlid, 'units', 2, 'K ')
        call check_cdf_status(iret)
#endif
        iret = nf_put_att_text(ncid, po3dtlid, 'long_name', 32, 'potential, upper inboard divertor')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, po3dtlid, 'units', 2, 'V ')
        call check_cdf_status(iret)
        if (ismain0.ne.ismain) then
          iret = nf_put_att_text(ncid, an3dtlid, 'long_name', 36, 'atom density, upper inboard divertor')
          call check_cdf_status(iret)
          iret = nf_put_att_text(ncid, an3dtlid, 'units', 4, 'm^-3')
          call check_cdf_status(iret)
        end if
        if (nnmoli.gt.0) then
          iret = nf_put_att_text(ncid, mn3dtlid, 'long_name', 40, 'molecule density, upper inboard divertor')
          call check_cdf_status(iret)
          iret = nf_put_att_text(ncid, mn3dtlid, 'units', 4, 'm^-3')
          call check_cdf_status(iret)
        end if
        iret = nf_put_att_text(ncid, fn3dtlid, 'long_name', 50, 'poloidal main species flux, upper inboard divertor')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, fn3dtlid, 'units', 4, 's^-1')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, fl3dtlid, 'long_name', 46, 'poloidal electron flux, upper inboard divertor')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, fl3dtlid, 'units', 4, 's^-1')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, fo3dtlid, 'long_name', 41, 'poloidal ion flux, upper inboard divertor')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, fo3dtlid, 'units', 4, 's^-1')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, fe3dtlid, 'long_name', 53, 'poloidal electron energy flux, upper inboard divertor')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, fe3dtlid, 'units', 2, 'W ')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, fi3dtlid, 'long_name', 48, 'poloidal ion energy flux, upper inboard divertor')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, fi3dtlid, 'units', 2, 'W ')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, ft3dtlid, 'long_name', 50, 'poloidal total energy flux, upper inboard divertor')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, ft3dtlid, 'units', 2, 'W ')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, fc3dtlid, 'long_name', 41, 'poloidal current, upper inboard divertor')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, fc3dtlid, 'units', 2, 'A ')
        call check_cdf_status(iret)
      endif
      ! outboard midplane quantities
      iret = nf_put_att_text(ncid, ne3daid, 'long_name', 35, 'electron density, outboard midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ne3daid, 'units', 4, 'm^-3')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, te3daid, 'long_name', 39, 'electron temperature, outboard midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, te3daid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_double(ncid, te3daid, 'scale', NCDOUBLE, 1, dvals(1))
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ti3daid, 'long_name', 34, 'ion temperature, outboard midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ti3daid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_double(ncid, ti3daid, 'scale', NCDOUBLE, 1, dvals(1))
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, po3daid, 'long_name', 28, 'potential, outboard midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, po3daid, 'units', 2, 'V ')
      call check_cdf_status(iret)
      if (ismain0.ne.ismain) then
        iret = nf_put_att_text(ncid, an3daid, 'long_name', 31, 'atom density, outboard midplane')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, an3daid, 'units', 4, 'm^-3')
        call check_cdf_status(iret)
      end if
      if (nnmoli.gt.0) then
        iret = nf_put_att_text(ncid, mn3daid, 'long_name', 35, 'molecule density, outboard midplane')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, mn3daid, 'units', 4, 'm^-3')
        call check_cdf_status(iret)
      end if
      iret = nf_put_att_text(ncid, dn3daid, 'long_name', 40, 'diffusion coefficient, outboard midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, dn3daid, 'units', 8, 'm^2.s^-1')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, dp3daid, 'long_name', 49, 'pressure diffusion coefficient, outboard midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, dp3daid, 'units', 8, 'm^2.s^-1')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, lh3daid, 'long_name', 51, 'radial neutral heat flux limiter, outboard midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, lh3daid, 'units', 8, 'm^2.s^-1')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ln3daid, 'long_name', 51, 'radial neutral part flux limiter, outboard midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ln3daid, 'units', 8, 'm^2.s^-1')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ke3daid, 'long_name', 47, 'electron thermal diffusivity, outboard midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ke3daid, 'units', 8, 'm^2.s^-1')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ki3daid, 'long_name', 42, 'ion thermal diffusivity, outboard midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ki3daid, 'units', 8, 'm^2.s^-1')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, vx3daid, 'long_name', 42, 'poloidal pinch velocity, outboard midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, vx3daid, 'units', 6, 'm.s^-1')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, vy3daid, 'long_name', 40, 'radial pinch velocity, outboard midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, vy3daid, 'units', 6, 'm.s^-1')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, vs3daid, 'long_name', 40, 'viscosity coefficient, outboard midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, vs3daid, 'units', 12, 'm.kg^-1.s^-1')
      call check_cdf_status(iret)

      ! Eastern edge (outboard divertor for LSN, inboard divertor for USN) quantities
      iret = nf_put_att_text(ncid, ne3drid, 'long_name', 30, 'electron density, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ne3drid, 'units', 4, 'm^-3')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, te3drid, 'long_name', 34, 'electron temperature, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, te3drid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_double(ncid, te3drid, 'scale', NCDOUBLE, 1, dvals(1))
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ti3drid, 'long_name', 29, 'ion temperature, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ti3drid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_double(ncid, ti3drid, 'scale', NCDOUBLE, 1, dvals(1))
      call check_cdf_status(iret)
#ifdef WG_TODO
      iret = nf_put_att_text(ncid, tp3drid, 'long_name', 31, 'plate temperature, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tp3drid, 'units', 2, 'K ')
      call check_cdf_status(iret)
#endif
      iret = nf_put_att_text(ncid, po3drid, 'long_name', 23, 'potential, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, po3drid, 'units', 2, 'V ')
      call check_cdf_status(iret)
      if (ismain0.ne.ismain) then
        iret = nf_put_att_text(ncid, an3drid, 'long_name', 26, 'atom density, Eastern edge')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, an3drid, 'units', 4, 'm^-3')
        call check_cdf_status(iret)
      end if
      if (nnmoli.gt.0) then
        iret = nf_put_att_text(ncid, mn3drid, 'long_name', 30, 'molecule density, Eastern edge')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, mn3drid, 'units', 4, 'm^-3')
        call check_cdf_status(iret)
      end if
      iret = nf_put_att_text(ncid, fn3drid, 'long_name', 40, 'poloidal main species flux, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fn3drid, 'units', 4, 's^-1')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fl3drid, 'long_name', 36, 'poloidal electron flux, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fl3drid, 'units', 4, 's^-1')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fo3drid, 'long_name', 31, 'poloidal ion flux, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fo3drid, 'units', 2, 'W ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fe3drid, 'long_name', 43, 'poloidal electron energy flux, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fe3drid, 'units', 2, 'W ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fi3drid, 'long_name', 38, 'poloidal ion energy flux, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fi3drid, 'units', 2, 'W ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ft3drid, 'long_name', 40, 'poloidal total energy flux, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ft3drid, 'units', 2, 'W ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fc3drid, 'long_name', 30, 'poloidal current, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, fc3drid, 'units', 2, 'A ')
      call check_cdf_status(iret)
      ! upper outboard divertor quantities
      if(maxval(mpg%strDiv).ge.4) then
        iret = nf_put_att_text(ncid, ne3dtrid, 'long_name', 41, 'electron density, upper outboard divertor')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, ne3dtrid, 'units', 4, 'm^-3')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, te3dtrid, 'long_name', 45, 'electron temperature, upper outboard divertor')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, te3dtrid, 'units', 2, 'eV')
        call check_cdf_status(iret)
        iret = nf_put_att_double(ncid, te3dtrid, 'scale', NCDOUBLE, 1, dvals(1))
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, ti3dtrid, 'long_name', 40, 'ion temperature, upper outboard divertor')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, ti3dtrid, 'units', 2, 'eV')
        call check_cdf_status(iret)
        iret = nf_put_att_double(ncid, ti3dtrid, 'scale', NCDOUBLE, 1, dvals(1))
        call check_cdf_status(iret)
#ifdef WG_TODO
        iret = nf_put_att_text(ncid, tp3dtrid, 'long_name', 42, 'plate temperature, upper outboard divertor')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, tp3dtrid, 'units', 2, 'K ')
        call check_cdf_status(iret)
#endif
        iret = nf_put_att_text(ncid, po3dtrid, 'long_name', 34, 'potential, upper outboard divertor')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, po3dtrid, 'units', 2, 'V ')
        call check_cdf_status(iret)
        if (ismain0.ne.ismain) then
          iret = nf_put_att_text(ncid, an3dtrid, 'long_name', 37, 'atom density, upper outboard divertor')
          call check_cdf_status(iret)
          iret = nf_put_att_text(ncid, an3dtrid, 'units', 4, 'm^-3')
          call check_cdf_status(iret)
        end if
        if (nnmoli.gt.0) then
          iret = nf_put_att_text(ncid, mn3dtrid, 'long_name', 41, 'molecule density, upper outboard divertor')
          call check_cdf_status(iret)
          iret = nf_put_att_text(ncid, mn3dtrid, 'units', 4, 'm^-3')
          call check_cdf_status(iret)
        end if
        dvals(1) = -1.0_R8
        iret = nf_put_att_text(ncid, fn3dtrid, 'long_name', 51, 'poloidal main species flux, upper outboard divertor')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, fn3dtrid, 'units', 4, 's^-1')
        call check_cdf_status(iret)
        iret = nf_put_att_double(ncid, fn3dtrid, 'scale', NCDOUBLE, 1, dvals(1))
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, fl3dtrid, 'long_name', 47, 'poloidal electron flux, upper outboard divertor')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, fl3dtrid, 'units', 4, 's^-1')
        call check_cdf_status(iret)
        iret = nf_put_att_double(ncid, fl3dtrid, 'scale', NCDOUBLE, 1, dvals(1))
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, fo3dtrid, 'long_name', 42, 'poloidal ion flux, upper outboard divertor')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, fo3dtrid, 'units', 2, 'W ')
        call check_cdf_status(iret)
        iret = nf_put_att_double(ncid, fo3dtrid, 'scale', NCDOUBLE, 1, dvals(1))
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, fe3dtrid, 'long_name', 54, 'poloidal electron energy flux, upper outboard divertor')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, fe3dtrid, 'units', 2, 'W ')
        call check_cdf_status(iret)
        iret = nf_put_att_double(ncid, fe3dtrid, 'scale', NCDOUBLE, 1, dvals(1))
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, fi3dtrid, 'long_name', 49, 'poloidal ion energy flux, upper outboard divertor')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, fi3dtrid, 'units', 2, 'W ')
        call check_cdf_status(iret)
        iret = nf_put_att_double(ncid, fi3dtrid, 'scale', NCDOUBLE, 1, dvals(1))
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, ft3dtrid, 'long_name', 51, 'poloidal total energy flux, upper outboard divertor')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, ft3dtrid, 'units', 2, 'W ')
        call check_cdf_status(iret)
        iret = nf_put_att_double(ncid, ft3dtrid, 'scale', NCDOUBLE, 1, dvals(1))
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, fc3dtrid, 'long_name', 42, 'poloidal current, upper outboard divertor')
        call check_cdf_status(iret)
        iret = nf_put_att_text(ncid, fc3dtrid, 'units', 2, 'A ')
        call check_cdf_status(iret)
        iret = nf_put_att_double(ncid, fc3dtrid, 'scale', NCDOUBLE, 1, dvals(1))
        call check_cdf_status(iret)
      endif
    else
    !wdk averaged quantities
      iret = nf_put_att_text(ncid, nesepm_avid, 'long_name', 52, 'averaged separatrix electron density, outer midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, nesepm_avid, 'units', 4, 'm^-3')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tesepm_avid, 'long_name', 56, 'averaged separatrix electron temperature, outer midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tesepm_avid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tisepm_avid, 'long_name', 51, 'averaged separatrix ion temperature, outer midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tisepm_avid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, posepm_avid, 'long_name', 45, 'averaged separatrix potential, outer midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, posepm_avid, 'units', 2, 'V ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ktsepm_avid, 'long_name', 60, 'averaged separatrix turbulent kinetic energy, outer midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ktsepm_avid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, nesepi_avid, 'long_name', 50, 'averaged separatrix electron density, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, nesepi_avid, 'units', 4, 'm^-3')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tesepi_avid, 'long_name', 54, 'averaged separatrix electron temperature, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tesepi_avid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tisepi_avid, 'long_name', 49, 'averaged separatrix ion temperature, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tisepi_avid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, posepi_avid, 'long_name', 43, 'averaged separatrix potential, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, posepi_avid, 'units', 2, 'V ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ktsepi_avid, 'long_name', 58, 'averaged separatrix turbulent kinetic energy, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ktsepi_avid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, nesepa_avid, 'long_name', 50, 'averaged separatrix electron density, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, nesepa_avid, 'units', 4, 'm^-3')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tesepa_avid, 'long_name', 54, 'averaged separatrix electron temperature, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tesepa_avid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tisepa_avid, 'long_name', 49, 'averaged separatrix ion temperature, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tisepa_avid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, posepa_avid, 'long_name', 43, 'averaged separatrix potential, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, posepa_avid, 'units', 2, 'V ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ktsepa_avid, 'long_name', 58, 'averaged separatrix turbulent kinetic energy, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ktsepa_avid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, nemxip_avid, 'long_name', 47, 'averaged maximum electron density, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, nemxip_avid, 'units', 4, 'm^-3')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, temxip_avid, 'long_name', 51, 'averaged maximum electron temperature, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, temxip_avid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, timxip_avid, 'long_name', 46, 'averaged maximum ion temperature, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, timxip_avid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, pomxip_avid, 'long_name', 40, 'averaged maximum potential, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, pomxip_avid, 'units', 2, 'V ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, nemxap_avid, 'long_name', 47, 'averaged maximum electron density, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, nemxap_avid, 'units', 4, 'm^-3')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, temxap_avid, 'long_name', 51, 'averaged maximum electron temperature, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, temxap_avid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, timxap_avid, 'long_name', 46, 'averaged maximum ion temperature, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, timxap_avid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, pomxap_avid, 'long_name', 40, 'averaged maximum potential, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, pomxap_avid, 'units', 2, 'V ')
      call check_cdf_status(iret)

    !wdk standard deviation of averaged quantities
      iret = nf_put_att_text(ncid, nesepm_stdid, 'long_name', 55, 'variance of separatrix electron density, outer midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, nesepm_stdid, 'units', 4, 'm^-3')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tesepm_stdid, 'long_name', 59, 'variance of separatrix electron temperature, outer midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tesepm_stdid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tisepm_stdid, 'long_name', 54, 'variance of separatrix ion temperature, outer midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tisepm_stdid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, posepm_stdid, 'long_name', 48, 'variance of separatrix potential, outer midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, posepm_stdid, 'units', 2, 'V ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ktsepm_stdid, 'long_name', 63, &
           'variance of separatrix turbulent kinetic energy, outer midplane')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ktsepm_stdid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, nesepi_stdid, 'long_name', 53, 'variance of separatrix electron density, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, nesepi_stdid, 'units', 4, 'm^-3')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tesepi_stdid, 'long_name', 57, 'variance of separatrix electron temperature, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tesepi_stdid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tisepi_stdid, 'long_name', 52, 'variance of separatrix ion temperature, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tisepi_stdid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, posepi_stdid, 'long_name', 46, 'variance of separatrix potential, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, posepi_stdid, 'units', 2, 'V ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ktsepi_stdid, 'long_name', 65, &
           'variance of separatrix turbulent kinetic energy, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ktsepi_stdid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, nesepa_stdid, 'long_name', 53, 'variance of separatrix electron density, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, nesepa_stdid, 'units', 4, 'm^-3')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tesepa_stdid, 'long_name', 57, 'variance of separatrix electron temperature, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tesepa_stdid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tisepa_stdid, 'long_name', 52, 'variance of separatrix ion temperature, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, tisepa_stdid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, posepa_stdid, 'long_name', 46, 'variance of separatrix potential, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, posepa_stdid, 'units', 2, 'V ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ktsepa_stdid, 'long_name', 61, &
           'variance of separatrix turbulent kinetic energy, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, ktsepa_stdid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, nemxip_stdid, 'long_name', 50, 'variance of maximum electron density, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, nemxip_stdid, 'units', 4, 'm^-3')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, temxip_stdid, 'long_name', 54, 'variance of maximum electron temperature, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, temxip_stdid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, timxip_stdid, 'long_name', 49, 'variance of maximum ion temperature, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, timxip_stdid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, pomxip_stdid, 'long_name', 43, 'variance of maximum potential, Western edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, pomxip_stdid, 'units', 2, 'V ')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, nemxap_stdid, 'long_name', 50, 'variance of maximum electron density, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, nemxap_stdid, 'units', 4, 'm^-3')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, temxap_stdid, 'long_name', 54, 'variance of maximum electron temperature, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, temxap_stdid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, timxap_stdid, 'long_name', 50, 'variance of maximum ion temperature, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, timxap_stdid, 'units', 2, 'eV')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, pomxap_stdid, 'long_name', 43, 'variance of maximum potential, Eastern edge')
      call check_cdf_status(iret)
      iret = nf_put_att_text(ncid, pomxap_stdid, 'units', 2, 'V ')
      call check_cdf_status(iret)
    endif

    ! leave define mode
    iret = nf_enddef(ncid)
    call check_cdf_status(iret)
    iret = nf_close(ncid)
    call check_cdf_status(iret)
    return
  end subroutine b2crtimecdf

  subroutine rwcdf(rw,ncid,data_name,imap,data_set,iret)
#   include <netcdf.inc>

    character*(*) rw,data_name
    integer ncid,imap(*),iret,i,varid,dimlen
    real(kind=R8), Intent(InOut) :: data_set(*)
    character*(maxncnam) dimnam
    integer vartyp,nvdims,start(maxvdims),mycount(maxvdims),dimids(maxvdims)
    integer :: istride, imax
#ifdef DBG
    logical, parameter :: debug = .true.
#else
    logical, parameter :: debug = .false.
#endif
    external check_cdf_status, xerrab
    !
    call subini ('rwcdf')
    iret = nf_inq_varid(ncid,data_name,varid)
    call check_cdf_status(iret)
    if(iret.ne.0) then
      write(*,*) 'Error: Could not inquire data_name: ',trim(data_name)
      call xerrab('Data name '//trim(data_name)//' not declared')
    endif
    if (debug) write(*,*) "Subroutine rwcdf in mode: ", rw
    if (debug) write(*,*) "Working on variable: ", data_name
    iret = nf_inq_varndims(ncid,varid,nvdims)
    if (debug) write(*,*) "Variable has nvdims=", nvdims
    if (debug.and.nvdims.gt.0) write(*,*) "Input imap(:)=", imap(1:nvdims)
    iret = nf_inq_vardimid(ncid,varid,dimids)
    call check_cdf_status(iret)
    mycount(1) = 1 ! for scalars
    start(1) = 1
    do i=1,nvdims
      iret = nf_inq_dim(ncid,dimids(i),dimnam,dimlen)
      call check_cdf_status(iret)
      mycount(i) = dimlen
      if(dimnam.eq.timsav) then
        start(i)=ntsav
        mycount(i)=1
      elseif(dimnam.eq.batchsav) then
        start(i)=nasav
        mycount(i)=1
      else
        start(i)=1
      endif
    enddo
    if (debug.and.nvdims.gt.0) write(*,*) "start(:)=", start(1:nvdims)
    if (debug.and.nvdims.gt.0) write(*,*) "mycount(:)=", mycount(1:nvdims)
    istride = 1
    imax = 1
    do i=1,nvdims-1
      istride = istride*imap(i)
      imax = imax*imap(i)*mycount(i)
    enddo
    if (debug) write(*,*) "istride=", istride
    if (debug) write(*,*) "imax=", imax
    iret = nf_inq_vartype(ncid,varid,vartyp)
    call check_cdf_status(iret)
    if(rw.eq.'read') then
      select case (vartyp)
      case (NCDOUBLE)
        iret = nf_get_vara_double(ncid,varid,start,mycount,data_set(1:imax:istride))
        call check_cdf_status(iret)
      case default
        call xerrab ('Unknown data type in rwcdf read')
      end select
    elseif(rw.eq.'write') then
      select case (vartyp)
      case (NCDOUBLE)
        iret = nf_put_vara_double(ncid,varid,start,mycount,data_set(1:imax:istride))
        call check_cdf_status(iret)
      case default
        call xerrab ('Unknown data type in rwcdf write')
      end select
    else
      write(*,*) 'Either "read" or "write" must be chosen, not ', rw
    endif

    call subend ()
    return
  end subroutine rwcdf
    !
  subroutine rwcdf_settime(timnam,ntstep)
    implicit none
    character*(*) timnam
    integer ntstep
    write(*,*) 'Saving ',trim(timnam),' as the time dimension'
    write(*,*) 'ntstep = ',ntstep
    timsav=timnam
    ntsav=ntstep
    return
  end subroutine rwcdf_settime
    !
  subroutine rwcdf_setbatch(batchnam,nastep)
    implicit none
    character*(*) batchnam
    integer nastep
    write(*,*) 'Saving ',trim(batchnam),' as the batch dimension'
    write(*,*) 'nastep = ',nastep
    batchsav=batchnam
    nasav=nastep
    return
  end subroutine rwcdf_setbatch
#endif
#endif

end module b2mod_cdf

!!!Local Variables:
!!! mode: f90
!!! End:
