!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (feature_llhTests) - 27 May 2021 14:23
!
!
!
!
!
!
!
!
!
!
!
!
!-----------------------------------------------------------------------
!.specification
!
SUBROUTINE B2MWQT_NODIFF(nput, ncv, ns, itim, itcnt, switch, geo, pl, dv&
& , diag)
  USE B2MOD_TYPES
  USE B2MOD_CONSTANTS
  USE B2MOD_B2CMPA_DIFFV
  USE B2MOD_SWITCHES_DIFFV
  USE B2US_GEO_DIFFV
  USE B2US_PLASMA_DIFFV
  USE B2MOD_SUBSYS
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!
!-----------------------------------------------------------------------
!.end b2mwqt
!
!   ..input arguments (unchanged on exit)
  INTEGER :: nput, ncv, ns, itim, itcnt
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(B2PLASMA), INTENT(IN) :: pl
  TYPE(B2DERIVATIVES), INTENT(IN) :: dv
  TYPE(B2DIAGNOSTIC), INTENT(IN) :: diag
!   ..common blocks
!-----------------------------------------------------------------------
!.documentation
!
!  1. purpose
!
!     B2MWQT writes brief data concerning the numerical evolution.
!
!
!  3. description (see also routine b2cdca)
!
!     This routine writes to unit (nput) the 'quick trace' evolution
!     data. Unit (nput) must be connected to an un*formatted file.
!
!
!  5. parameters (see also routine b2cdcv)
!
!     nput - integer, input.
!     nput specifies a unit number for un*formatted output.
!
!     ns - integer, input.
!     ns specifies the number of atomic species in the calculation.
!     The species are indexed by (0:ns-1).
!     It will hold that 1.le.ns.
!
!     itim - integer, input.
!     itim specifies the timestep counter. It is initialised to 0 and
!     incremented by 1 following each successful call to b2mndt.
!
!     itcnt - integer, input.
!     itcnt counts the number of inner iterations. It is initialised to
!     0 and incremented by 1 following each call to b2news.
!
!     na, ua, te, ti, po, ne, ni - real*8 array, input.
!     See the calling routine for description.
!
!     fna, fhe, fhi, fch - real*8 array, input.
!     See the calling routine for description.
!
!     aresco - (0:ns-1) real*8 array, input.
!     For (is) in (0:ns-1), aresco(is) specifies the scaled norm of the
!     residual of the continuity equation for species (is).
!
!     aresmo - (0:ns-1) real*8 array, input.
!     For (is) in (0:ns-1), aresmo(is) specifies the scaled norm of the
!     residual of the parallel momentum equation for species (is).
!
!     aresmt - real, input.
!     aresmt specifies the scaled norm of the residual of the total
!     parallel momentum equation.
!
!     areshe - real, input.
!     areshe specifies the scaled norm of the residual of the electron
!     heat balance equation.
!
!     areshi - real, input.
!     areshi specifies the scaled norm of the residual of the all atom
!     heat balance equation.
!
!     areshn - real, input.
!     areshn specifies the scaled norm of the residual of the fluid neutral
!     heat balance equation. Only non-zero if a separate neutral energy 
!     equation is solved. In this case areshi contains only the ions.
!
!     arespo - real, input.
!     arespo specifies the scaled norm of the residual of the electric
!     potential equation.
!
!     areskt - real, input.
!     areskt specifies the scaled norm of the residual of the turbulent
!     kinetic energy equation.
!
!     areszt - real, input.
!     areszt specifies the scaled norm of the residual of the turbulent
!     enstrophy equation.
!
!     acorpa - (0:ns-1) real*8 array, input.
!     For (is) in (0:ns-1), acorpa(is) specifies the norm of the last
!     computed correction for the continuity equation for species (is).
!
!     acorua - (0:ns-1) real*8 array, input.
!     For (is) in (0:ns-1), acorua(is) specifies the norm of the last
!     computed correction for the parallel momentum balance equation for
!     species (is).
!
!     acorut - real, input.
!     acorut specifies the norm of the last computed correction for the
!     parallel momentum balance equation for all species simultaneously.
!
!     acorte - real, input.
!     acorte specifies the norm of the last computed correction for the
!     electron heat balance equation.
!
!     acorti - real, input.
!     acorti specifies the norm of the last computed correction for the
!     all atom heat balance equation.
!
!     acortn - real, input.
!     acortn specifies the norm of the last computed correction for the
!     fluid neutral heat balance equation.
!
!     acorpo - real, input.
!     acorpo specifies the norm of the last computed correction for the
!     electric potential equation.
!
!     acorkt - real, input.
!     acorkt specifies the norm of the last computed correction for the
!     turbulent kinetic energy equation.
!
!     acorzt - real, input.
!     acorzt specifies the norm of the last computed correction for the
!     turbulent enstrophy equation.
!
!     (parameters in common:)
!
!     /b2cmpa/ - input.
!     /b2cmpa/ specifies basic physics parameters.
!     See the calling routine for description.
!
!-----------------------------------------------------------------------
!.declarations
!
!   ..local variables
  INTEGER :: nfldmx, nfld
  PARAMETER (nfldmx=1000)
  INTEGER :: k, is
  REAL(kind=r8) :: z(0:nfldmx-1)
  EXTERNAL XERTST, IPGETI, smin, CFWURE
!   ..procedures
  REAL(kind=r8) :: smin
  EXTERNAL XERRAB
  REAL(kind=r8) :: result1
!-----------------------------------------------------------------------
!.documentation-internal
!
!     Description of some local variables:
!
!     style - integer.
!     style specifies the amount of output produced on each call.
!     Legitimate values are in the range 0..4. style.eq.0 implies
!     no output, and the amount of output is an ascending function
!     of the value of style. See the code for precise information.
!
!-----------------------------------------------------------------------
!.computation
!
! ..preliminaries
!   ..subprogram start-up calls
  CALL SUBINI('b2mwqt')
!   ..test nput
  CALL XERTST(1 .LE. nput, 'faulty argument nput')
!   ..test ns
  CALL XERTST(1 .LE. ns, 'faulty argument ns')
!   ..test itim, itcnt
  CALL XERTST(0 .LE. itim .AND. 0 .LE. itcnt, &
&       'faulty argument itim, itcnt')
!   ..test residuals
  result1 = smin(ns, diag%aresco, 1)
  CALL XERTST(0.0_R8 .LE. result1 .AND. 0.0_R8 .LE. diag%areshe .AND. &
&       0.0_R8 .LE. diag%areshi .AND. 0.0_R8 .LE. diag%arespo .AND. &
&       0.0_R8 .LE. diag%areskt .AND. 0.0_R8 .LE. diag%areszt, &
&       'faulty argument aresco/ee/ei/po/kt/zt')
!   ..test corrections
  result1 = smin(ns, diag%acorpa, 1)
  CALL XERTST(0.0_R8 .LE. result1 .AND. 0.0_R8 .LE. diag%acorte .AND. &
&       0.0_R8 .LE. diag%acorti .AND. 0.0_R8 .LE. diag%acorpo .AND. &
&       0.0_R8 .LE. diag%acorkt .AND. 0.0_R8 .LE. diag%acorzt .AND. &
&       0.0_R8 .LE. diag%acortn, &
&       'faulty argument acorpa/te/ti/po/kt/zt/tn')
!   ..set and test nfld
  nfld = 0
  IF (1 .LE. switch%b2mwqt_style) nfld = nfld + 2 + 2*(2*ns+7)
  IF (2 .LE. switch%b2mwqt_style) nfld = nfld + 36*(ns+3)
  IF (3 .LE. switch%b2mwqt_style) nfld = nfld + 40*(ns+3)
  IF (4 .LE. switch%b2mwqt_style) nfld = nfld + 72*(ns+3)
  CALL XERTST(nfld .LE. nfldmx, 'faulty parameter nfldmx')
!   ..define region boundaries
! ..get data for output
  k = 0
  IF (1 .LE. switch%b2mwqt_style) THEN
!    ..iteration counters
    z(k) = itim
    k = k + 1
    z(k) = itcnt
    k = k + 1
!    ..norms of residuals
    DO is=0,ns-1
      z(k) = diag%aresco(is)
      k = k + 1
    END DO
    DO is=0,ns-1
      z(k) = diag%aresmo(is)
      k = k + 1
    END DO
    z(k) = diag%aresmt
    k = k + 1
    z(k) = diag%areshe
    k = k + 1
    z(k) = diag%areshi
    k = k + 1
    z(k) = diag%areshn
    k = k + 1
    z(k) = diag%arespo
    k = k + 1
    z(k) = diag%areskt
    k = k + 1
    z(k) = diag%areszt
    k = k + 1
!    ..norms of corrections
    DO is=0,ns-1
      z(k) = diag%acorpa(is)
      k = k + 1
    END DO
    DO is=0,ns-1
      z(k) = diag%acorua(is)
      k = k + 1
    END DO
    z(k) = diag%acorut
    k = k + 1
    z(k) = diag%acorte/ev
    k = k + 1
    z(k) = diag%acorti/ev
    k = k + 1
    z(k) = diag%acortn/ev
    k = k + 1
    z(k) = diag%acorpo
    k = k + 1
    z(k) = diag%acorkt/ev
    k = k + 1
    z(k) = diag%acorzt/ev
    k = k + 1
  END IF
  IF (2 .LE. switch%b2mwqt_style) THEN
!    ..total content on regions
    CALL XERRAB('WG - to be done!')
  END IF
  IF (3 .LE. switch%b2mwqt_style) THEN
!    ..integrated fluxes
    CALL XERRAB('WG - to be done!')
  END IF
  IF (4 .LE. switch%b2mwqt_style) THEN
!    ..min and max on regions
    CALL XERRAB('WG - to be done!')
  END IF
!   ..test k
  CALL XERTST(k .EQ. nfld, 'faulty parameter nfld')
!
! ..produce output
  CALL CFWURE(nput, nfld, z, 'data')
!
! ..return
  CALL SUBEND()
  RETURN
END SUBROUTINE B2MWQT_NODIFF

