!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 23 Jul 2024 17:41
!
!  Differentiation of b2nppo in forward (tangent) mode (with options multiDirectional context noISIZE r8):
!   variations   of useful results: *(dv.respo) *(dv.corpo) *(pl.po)
!   with respect to varying inputs: *(dv.fch) *(dv.conc) *(dv.respo)
!                *(dv.corpo) *(dv.ne) *(sr.sch) *(pl.po) *(pl.te)
!   Plus diff mem management of: dv.fch:in dv.conc:in dv.respo:in
!                dv.corpo:in dv.ne:in geo.vxvol:in sr.sch:in pl.po:in
!                pl.te:in
!
!
!
!
!
!
!
!
!
!
!
!-----------------------------------------------------------------------
!.specification
!
!srv 22.05.18
SUBROUTINE B2NPPO_DV(ncv, nfc, nvx, nregionv, solving, solvereg, itcnt, &
& rxf, switch, switchd, geo, geod, mpg, mpgd, pl, pld, dv, dvd, sr, srd&
& , nbdirs)
  USE B2MOD_TYPES
  USE B2MOD_CONSTANTS
  USE B2MOD_B2CMPA_DIFFV
  USE B2MOD_SWITCHES_DIFFV
  USE B2US_GEO_DIFFV
  USE B2US_MAP_DIFFV
  USE B2US_PLASMA_DIFFV
  USE B2MOD_AD_DIFFV, ONLY : ncall_b2nppo
! csc The following are not necessary for computation but are needed
!     for adjoint AD to avoid side-effect variables
  USE B2MOD_AD_DIFFV, ONLY : ncall_b2uspo, my_out_folder, ncall_b2ursd
  USE B2MOD_SUBSYS
!  Hint: nbdirsmax should be the maximum number of differentiation directions
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!   ..read switches
!   ..input arguments (unchanged on exit)
  INTEGER :: ncv, nfc, nvx, nregionv, itcnt
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(SWITCHES_DIFFV), INTENT(IN) :: switchd
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(GEOMETRY_DIFFV), INTENT(IN) :: geod
  TYPE(MAPPING), INTENT(IN) :: mpg
  TYPE(MAPPING_DIFFV), INTENT(IN) :: mpgd
  REAL(kind=r8) :: rxf
!srv 22.05.18
  LOGICAL :: solving, solvereg(0:nregionv)
!   ..input/output arguments
  TYPE(B2PLASMA), INTENT(INOUT) :: pl
  TYPE(B2PLASMA_DIFFV), INTENT(INOUT) :: pld
  TYPE(B2DERIVATIVES), INTENT(INOUT) :: dv
  TYPE(B2DERIVATIVES_DIFFV), INTENT(INOUT) :: dvd
  TYPE(B2SOURCE), INTENT(INOUT) :: sr
  TYPE(B2SOURCE_DIFFV), INTENT(INOUT) :: srd
!   ..common blocks
!-----------------------------------------------------------------------
!.documentation
!
!  1. purpose
!
!     B2NPPO performs one iteration of a relaxation process for the
!     solution of the charge conservation equation, which governs the
!     electric potential.
!
!
!  3. description (see also routine b2cdca)
!
!     For a detailed description of the equations and the method of
!     solution, see the references cited in the main program unit.
!
!     This routine performs one inner iteration for the equation that
!     governs the electric potential po.
!     An outline of the procedure follows.
!     ..compute residual
!     ..compute correction
!     ..apply correction
!
!-----------------------------------------------------------------------
!.declarations
!
!   ..local variables
  INTEGER :: icv
  REAL(kind=r8) :: aa(mpg%ncmxnv), wrk0(ncv), wrk
  REAL(kind=r8) :: aad(nbdirsmax, mpg%ncmxnv)
!   ..procedures
  EXTERNAL XERTST
  EXTERNAL B2XVSG, B2URSD_NODIFF, B2USPO_NODIFF, B2UPPO
  EXTERNAL B2URSD_DV, B2USPO_DV, B2UPPO_DV
  INTRINSIC ANY
  INTRINSIC ABS
  INTRINSIC SIGN
  REAL(kind=r8) :: abs0
  REAL(kind=r8) :: abs1
  REAL(kind=r8) :: abs2
  REAL(kind=r8) :: arg1
  REAL(kind=r8), DIMENSION(nbdirsmax) :: arg1d
  REAL(r8), DIMENSION(nbdirsmax, SIZE(pl%te, 1)) :: dummyzerodiffd
  INTEGER :: nd
  INTEGER :: nbdirs
!   ..initialisation
!
!-----------------------------------------------------------------------
!.computation
!
! ..preliminaries
!   ..subprogram start-up calls
  CALL SUBINI('b2nppo')
!   ..test nCv, nFc
  CALL XERTST(0 .LT. ncv .AND. 0 .LT. nfc, 'faulty argument nCv, nFc')
!   ..test rxf
  CALL XERTST(0.0_R8 .LE. rxf .AND. rxf .LE. 1.0_R8, &
&       'faulty argument rxf')
!   ..extensive tests on first few calls
  IF (ncall_b2nppo .LT. 3) THEN
!    ..test sign of ne, te
    CALL B2XVSG(ncv, dv%ne, 1, 'ne', '.gt.')
    CALL B2XVSG(ncv, pl%te, 1, 'te', '.gt.')
!    ..test sign of sch
    CALL B2XVSG(ncv, sr%sch(1, 1), 1, 'sch1', '.le.')
    CALL B2XVSG(ncv, sr%sch(1, 3), 1, 'sch3', '.le.')
  END IF
!srv 22.05.18
!
! ..main computation
!   ..compute residual
  IF ((solving .AND. ANY(solvereg(0:nregionv))) .OR. switch%&
&     get_residuals .EQ. 1) THEN
!srv 22.05.18
    CALL B2URSD_DV(ncv, nfc, mpg, dv%ne, dvd%ne, pl%po, pld%po, sr%sch, &
&            srd%sch, dv%fch, dvd%fch, dv%respo, dvd%respo, nbdirs)
  END IF
!srv 22.05.18
!-rfs      write(6,*) 'ix=20, iy=-1, po ',po(20,-1), po(21,-1)
!-rfs      write(6,*) 'ix=20, iy=-1, sch ',
!-rfs     .  sch(20,-1,0), sch(20,-1,1),
!-rfs     .  sch(20,-1,2), sch(20,-1,3)
!-rfs      write(6,*) 'ix=20, iy=-1, fch, respo',
!-rfs     .  fch(20,-1,0), fch(20,-1,1),
!-rfs     .  fch(20,0,1), respo(20,-1)
!-rfs      write(6,*) 'ix=21, iy=-1, fch, respo',
!-rfs     .  fch(21,-1,0), fch(21,-1,1),
!-rfs     .  fch(21,0,1), respo(21,-1)
!   ..compute correction
  IF (solving .AND. ANY(solvereg(0:nregionv))) THEN
!srv 22.05.18
    dummyzerodiffd = 0.D0
    CALL B2USPO_DV(ncv, nfc, nvx, nregionv, solvereg, itcnt, switch, geo&
&            , mpg, mpgd, dv%ne, dvd%ne, pl%te, dummyzerodiffd, dv%conc&
&            , dvd%conc, sr%sch, srd%sch, dv%respo, dvd%respo, dv%corpo&
&            , dvd%corpo, aa, aad, 'b2nppo', nbdirs)
!   ..apply correction
    CALL B2UPPO_DV(ncv, rxf, dv%corpo, dvd%corpo, pl%po, pld%po, nbdirs)
    IF (switch%b2nppo_restr_po .NE. 0.0_R8) THEN
      DO icv=1,mpg%ncv
        IF (.NOT.mpg%cvonclosedsurface(icv)) THEN
          IF (switch%b2nppo_restr_po .GT. 0.0_R8) THEN
            IF (qe*pl%po(icv) .GE. 0.) THEN
              abs0 = qe*pl%po(icv)
            ELSE
              abs0 = -(qe*pl%po(icv))
            END IF
            IF (abs0/pl%te(icv) .GT. switch%b2nppo_restr_po) THEN
              wrk = pl%po(icv)
              arg1 = switch%b2nppo_restr_po*pl%te(icv)/qe
              DO nd=1,nbdirs
                arg1d(nd) = switch%b2nppo_restr_po*pld%te(nd, icv)/qe
                pld%po(nd, icv) = SIGN(1.d0, arg1*pl%po(icv))*arg1d(nd)
              END DO
              pl%po(icv) = SIGN(arg1, pl%po(icv))
              WRITE(*, *) 'Applied po/Te ratio limit', icv, wrk, pl%po(&
&             icv)
            END IF
          ELSE
            IF (qe*pl%po(icv) .GE. 0.) THEN
              abs1 = qe*pl%po(icv)
            ELSE
              abs1 = -(qe*pl%po(icv))
            END IF
            IF (switch%b2nppo_restr_po .GE. 0.) THEN
              abs2 = switch%b2nppo_restr_po
            ELSE
              abs2 = -switch%b2nppo_restr_po
            END IF
            IF (abs1/pl%te(icv) .GT. abs2 .AND. pl%po(icv) .LT. 0.0_R8) &
&           THEN
              wrk = pl%po(icv)
              arg1 = switch%b2nppo_restr_po*pl%te(icv)/qe
              DO nd=1,nbdirs
                arg1d(nd) = switch%b2nppo_restr_po*pld%te(nd, icv)/qe
                pld%po(nd, icv) = SIGN(1.d0, arg1*pl%po(icv))*arg1d(nd)
              END DO
              pl%po(icv) = SIGN(arg1, pl%po(icv))
              WRITE(*, *) 'Applied po/Te ratio limit', icv, wrk, pl%po(&
&             icv)
            END IF
          END IF
        END IF
      END DO
    END IF
  END IF
!srv 11.09.09 }
!
  IF (switch%b2nppo_iout .EQ. 1 .OR. switch%iout_b2wdat .EQ. 4) THEN
!srv 11.09.09 {
!       call my_out_us(70,nCv,0,pl%te,'b2nppo_te')
!       call my_out_us(70,nCv,0,dv%ne,'b2nppo_ne')
    CALL MY_OUT_US(70, ncv, 0, pl%po, 'b2nppo_po')
    CALL MY_OUT_US(70, ncv, 0, dv%respo, 'b2nppo_respo')
    CALL MY_OUT_US(70, nfc, 1, dv%fch(1, 0), 'b2nppo_fch_th')
    CALL MY_OUT_US(70, nfc, 1, dv%fch(1, 1), 'b2nppo_fch_r')
!       call my_out_us(70,nCv,0,sr%sch(1,0),'b2nppo_sch0')
!       call my_out_us(70,nCv,0,sr%sch(1,1),'b2nppo_sch1')
!       call my_out_us(70,nCv,0,sr%sch(1,2),'b2nppo_sch2')
!       call my_out_us(70,nCv,0,sr%sch(1,3),'b2nppo_sch3')
    wrk0 = sr%sch(:, 0) + sr%sch(:, 1)*pl%po + sr%sch(:, 2)*dv%ne + sr%&
&     sch(:, 3)*dv%ne*pl%po
    CALL MY_OUT_US(70, ncv, 0, wrk0, 'b2nppo_sch')
  END IF
!
! ..return
  ncall_b2nppo = ncall_b2nppo + 1
  CALL SUBEND()
  RETURN
!
!-----------------------------------------------------------------------
!.end b2nppo
!
END SUBROUTINE B2NPPO_DV

!
!
!
!
!
!
!
!
!
!
!
!-----------------------------------------------------------------------
!.specification
!
!srv 22.05.18
SUBROUTINE B2NPPO_NODIFF(ncv, nfc, nvx, nregionv, solving, solvereg, &
& itcnt, rxf, switch, geo, mpg, pl, dv, sr)
  USE B2MOD_TYPES
  USE B2MOD_CONSTANTS
  USE B2MOD_B2CMPA_DIFFV
  USE B2MOD_SWITCHES_DIFFV
  USE B2US_GEO_DIFFV
  USE B2US_MAP_DIFFV
  USE B2US_PLASMA_DIFFV
  USE B2MOD_AD_DIFFV, ONLY : ncall_b2nppo
! csc The following are not necessary for computation but are needed
!     for adjoint AD to avoid side-effect variables
  USE B2MOD_AD_DIFFV, ONLY : ncall_b2uspo, my_out_folder, ncall_b2ursd
  USE B2MOD_SUBSYS
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!   ..read switches
!   ..input arguments (unchanged on exit)
  INTEGER :: ncv, nfc, nvx, nregionv, itcnt
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(MAPPING), INTENT(IN) :: mpg
  REAL(kind=r8) :: rxf
!srv 22.05.18
  LOGICAL :: solving, solvereg(0:nregionv)
!   ..input/output arguments
  TYPE(B2PLASMA), INTENT(INOUT) :: pl
  TYPE(B2DERIVATIVES), INTENT(INOUT) :: dv
  TYPE(B2SOURCE), INTENT(INOUT) :: sr
!   ..common blocks
!-----------------------------------------------------------------------
!.documentation
!
!  1. purpose
!
!     B2NPPO performs one iteration of a relaxation process for the
!     solution of the charge conservation equation, which governs the
!     electric potential.
!
!
!  3. description (see also routine b2cdca)
!
!     For a detailed description of the equations and the method of
!     solution, see the references cited in the main program unit.
!
!     This routine performs one inner iteration for the equation that
!     governs the electric potential po.
!     An outline of the procedure follows.
!     ..compute residual
!     ..compute correction
!     ..apply correction
!
!-----------------------------------------------------------------------
!.declarations
!
!   ..local variables
  INTEGER :: icv
  REAL(kind=r8) :: aa(mpg%ncmxnv), wrk0(ncv), wrk
!   ..procedures
  EXTERNAL XERTST
  EXTERNAL B2XVSG, B2URSD_NODIFF, B2USPO_NODIFF, B2UPPO
  INTRINSIC ANY
  INTRINSIC ABS
  INTRINSIC SIGN
  REAL(kind=r8) :: abs0
  REAL(kind=r8) :: abs1
  REAL(kind=r8) :: abs2
  REAL(kind=r8) :: arg1
!   ..initialisation
!
!-----------------------------------------------------------------------
!.computation
!
! ..preliminaries
!   ..subprogram start-up calls
  CALL SUBINI('b2nppo')
!   ..test nCv, nFc
  CALL XERTST(0 .LT. ncv .AND. 0 .LT. nfc, 'faulty argument nCv, nFc')
!   ..test rxf
  CALL XERTST(0.0_R8 .LE. rxf .AND. rxf .LE. 1.0_R8, &
&       'faulty argument rxf')
!   ..extensive tests on first few calls
  IF (ncall_b2nppo .LT. 3) THEN
!    ..test sign of ne, te
    CALL B2XVSG(ncv, dv%ne, 1, 'ne', '.gt.')
    CALL B2XVSG(ncv, pl%te, 1, 'te', '.gt.')
!    ..test sign of sch
    CALL B2XVSG(ncv, sr%sch(1, 1), 1, 'sch1', '.le.')
    CALL B2XVSG(ncv, sr%sch(1, 3), 1, 'sch3', '.le.')
  END IF
!srv 22.05.18
!
! ..main computation
!   ..compute residual
  IF ((solving .AND. ANY(solvereg(0:nregionv))) .OR. switch%&
&     get_residuals .EQ. 1) THEN
!srv 22.05.18
    CALL B2URSD_NODIFF(ncv, nfc, mpg, dv%ne, pl%po, sr%sch, dv%fch, dv%&
&                respo)
  END IF
!srv 22.05.18
!-rfs      write(6,*) 'ix=20, iy=-1, po ',po(20,-1), po(21,-1)
!-rfs      write(6,*) 'ix=20, iy=-1, sch ',
!-rfs     .  sch(20,-1,0), sch(20,-1,1),
!-rfs     .  sch(20,-1,2), sch(20,-1,3)
!-rfs      write(6,*) 'ix=20, iy=-1, fch, respo',
!-rfs     .  fch(20,-1,0), fch(20,-1,1),
!-rfs     .  fch(20,0,1), respo(20,-1)
!-rfs      write(6,*) 'ix=21, iy=-1, fch, respo',
!-rfs     .  fch(21,-1,0), fch(21,-1,1),
!-rfs     .  fch(21,0,1), respo(21,-1)
!   ..compute correction
  IF (solving .AND. ANY(solvereg(0:nregionv))) THEN
!srv 22.05.18
    CALL B2USPO_NODIFF(ncv, nfc, nvx, nregionv, solvereg, itcnt, switch&
&                , geo, mpg, dv%ne, pl%te, dv%conc, sr%sch, dv%respo, dv&
&                %corpo, aa, 'b2nppo')
!   ..apply correction
    CALL B2UPPO(ncv, rxf, dv%corpo, pl%po)
    IF (switch%b2nppo_restr_po .NE. 0.0_R8) THEN
      DO icv=1,mpg%ncv
        IF (.NOT.mpg%cvonclosedsurface(icv)) THEN
          IF (switch%b2nppo_restr_po .GT. 0.0_R8) THEN
            IF (qe*pl%po(icv) .GE. 0.) THEN
              abs0 = qe*pl%po(icv)
            ELSE
              abs0 = -(qe*pl%po(icv))
            END IF
            IF (abs0/pl%te(icv) .GT. switch%b2nppo_restr_po) THEN
              wrk = pl%po(icv)
              arg1 = switch%b2nppo_restr_po*pl%te(icv)/qe
              pl%po(icv) = SIGN(arg1, pl%po(icv))
              WRITE(*, *) 'Applied po/Te ratio limit', icv, wrk, pl%po(&
&             icv)
            END IF
          ELSE
            IF (qe*pl%po(icv) .GE. 0.) THEN
              abs1 = qe*pl%po(icv)
            ELSE
              abs1 = -(qe*pl%po(icv))
            END IF
            IF (switch%b2nppo_restr_po .GE. 0.) THEN
              abs2 = switch%b2nppo_restr_po
            ELSE
              abs2 = -switch%b2nppo_restr_po
            END IF
            IF (abs1/pl%te(icv) .GT. abs2 .AND. pl%po(icv) .LT. 0.0_R8) &
&           THEN
              wrk = pl%po(icv)
              arg1 = switch%b2nppo_restr_po*pl%te(icv)/qe
              pl%po(icv) = SIGN(arg1, pl%po(icv))
              WRITE(*, *) 'Applied po/Te ratio limit', icv, wrk, pl%po(&
&             icv)
            END IF
          END IF
        END IF
      END DO
    END IF
  END IF
!srv 11.09.09 }
!
  IF (switch%b2nppo_iout .EQ. 1 .OR. switch%iout_b2wdat .EQ. 4) THEN
!srv 11.09.09 {
!       call my_out_us(70,nCv,0,pl%te,'b2nppo_te')
!       call my_out_us(70,nCv,0,dv%ne,'b2nppo_ne')
    CALL MY_OUT_US(70, ncv, 0, pl%po, 'b2nppo_po')
    CALL MY_OUT_US(70, ncv, 0, dv%respo, 'b2nppo_respo')
    CALL MY_OUT_US(70, nfc, 1, dv%fch(1, 0), 'b2nppo_fch_th')
    CALL MY_OUT_US(70, nfc, 1, dv%fch(1, 1), 'b2nppo_fch_r')
!       call my_out_us(70,nCv,0,sr%sch(1,0),'b2nppo_sch0')
!       call my_out_us(70,nCv,0,sr%sch(1,1),'b2nppo_sch1')
!       call my_out_us(70,nCv,0,sr%sch(1,2),'b2nppo_sch2')
!       call my_out_us(70,nCv,0,sr%sch(1,3),'b2nppo_sch3')
    wrk0 = sr%sch(:, 0) + sr%sch(:, 1)*pl%po + sr%sch(:, 2)*dv%ne + sr%&
&     sch(:, 3)*dv%ne*pl%po
    CALL MY_OUT_US(70, ncv, 0, wrk0, 'b2nppo_sch')
  END IF
!
! ..return
  ncall_b2nppo = ncall_b2nppo + 1
  CALL SUBEND()
  RETURN
!
!-----------------------------------------------------------------------
!.end b2nppo
!
END SUBROUTINE B2NPPO_NODIFF

