!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (feature_llhTests) - 27 May 2021 14:23
!
!  Differentiation of b2tiner in forward (tangent) mode (with options multiDirectional context noISIZE r8):
!   variations   of useful results: fchinert
!   with respect to varying inputs: na ua fchinert
!   Plus diff mem management of: geo.cvonedbsq:in geo.fcbb:in geo.fcs:in
!                geo.fchc:in geo.fcht:in geo.fcqgam:in geo.fcqalf:in
!                geo.fcqbet:in geo.vxvol:in geo.vxonedbsq:in
!
!
!
!
!
!
!
!
!
!
!
!-----------------------------------------------------------------------
!.specification
!
SUBROUTINE B2TINER_DV(ncv, nfc, nvx, ns, switch, geo, geod, mpg, mpgd, &
& na, nad, ua, uad, facdrift, fchinert, fchinertd, nbdirs)
  USE B2MOD_TYPES
  USE B2MOD_CONSTANTS
  USE B2MOD_B2CMFS
  USE B2MOD_B2CMPA_DIFFV
  USE B2MOD_SWITCHES_DIFFV
  USE B2US_GEO_DIFFV
  USE B2US_MAP_DIFFV
  USE B2MOD_SUBSYS
!  Hint: nbdirsmax should be the maximum number of differentiation directions
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!
!-----------------------------------------------------------------------
!.end b2tiner
!
!   ..input arguments (unchanged on exit)
  INTEGER, INTENT(IN) :: ncv, nfc, nvx, ns
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(GEOMETRY_DIFFV), INTENT(IN) :: geod
  TYPE(MAPPING), INTENT(IN) :: mpg
  TYPE(MAPPING_DIFFV), INTENT(IN) :: mpgd
  REAL(kind=r8) :: na(ncv, 0:ns-1), ua(ncv, 0:ns-1), facdrift(nfc)
  REAL(kind=r8) :: nad(nbdirsmax, ncv, 0:ns-1), uad(nbdirsmax, ncv, 0:ns&
& -1)
!   ..output arguments (unspecified on entry)
  REAL(kind=r8) :: fchinert(nfc, 0:1)
  REAL(kind=r8) :: fchinertd(nbdirsmax, nfc, 0:1)
!   ..common blocks
!-----------------------------------------------------------------------
!.documentation
!
!  1. purpose
!
!     B2TINER computes the X and Y components of the inertial current.
!
!  8. further comments
!
!-----------------------------------------------------------------------
!.declarations
!
!   ..global named constants
!
!   ..local variables
  INTEGER :: is
  REAL(kind=r8) :: wght(nfc, 2), gonedbsq(nfc, 0:1), wrk(ncv), wrk0(nfc)&
& , wrk1(nfc)
  REAL(kind=r8) :: wrkd(nbdirsmax, ncv), wrk0d(nbdirsmax, nfc), wrk1d(&
& nbdirsmax, nfc)
!   ..procedures
  EXTERNAL XERTST
  EXTERNAL B2XVSG
  INTRINSIC MAXVAL
  REAL(kind=r8) :: result1
  INTEGER :: nd
  REAL(kind=r8), DIMENSION(nfc) :: temp
  INTEGER :: nbdirs
!   ..initialization
!-----------------------------------------------------------------------
!.computation
!
! ..preliminaries
!   ..subprogram start-up calls
  CALL SUBINI('b2tiner')
!   ..test nCv, nFc
  CALL XERTST(0 .LT. ncv .AND. 0 .LT. nfc, 'faulty argument nCv, nFc')
! Drift terms
  result1 = MAXVAL(facdrift)
  IF (switch%fch_inert .NE. 0.0_R8 .AND. result1 .NE. 0.0_R8 .AND. &
&     switch%no_current .EQ. 0) THEN
!srv 07.07.99
!
!     ..compute gradients of OnedBsq on cell faces
    CALL GRAD_NODIFF(ncv, nfc, nvx, 1, geo, mpg, geo%cvonedbsq, geo%&
&              vxonedbsq, gonedbsq)
!
!     ..sum of inertia terms
    wght = 1.0_R8
    wrk0 = 0.0_R8
    DO nd=1,nbdirsmax
      wrk0d(nd, :) = 0.D0
    END DO
    DO nd=1,nbdirsmax
      wrk1d(nd, :) = 0.D0
    END DO
    DO is=0,ns-1
      IF (.NOT.is_neutral(is)) THEN
        DO nd=1,nbdirs
          wrkd(nd, :) = ua(:, is)**2*nad(nd, :, is) + na(:, is)*2*ua(:, &
&           is)*uad(nd, :, is)
        END DO
        wrk = na(:, is)*ua(:, is)**2
        CALL INTFACE_DV(ncv, nfc, mpg%fccv, wght, wrk, wrkd, wrk1, wrk1d&
&                 , nbdirs)
        DO nd=1,nbdirs
          wrk0d(nd, :) = wrk0d(nd, :) + am(is)*wrk1d(nd, :)
        END DO
        wrk0 = wrk0 + am(is)*wrk1
      END IF
    END DO
!
!     ..COMPONENTS OF INERTIA CURRENT
    temp = switch%fch_inert*facdrift*geo%fcqalf(:, 0)
    DO nd=1,nbdirs
      wrk0d(nd, :) = mp*0.5_R8*wrk0d(nd, :)
      fchinertd(nd, :, 0) = temp*gonedbsq(:, 1)*geo%fcbb(:, 2)*geo%fcs*&
&       wrk0d(nd, :)
    END DO
    wrk0 = 0.5_R8*mp*wrk0
    fchinert(:, 0) = temp*(gonedbsq(:, 1)*geo%fcbb(:, 2)*(geo%fcs*wrk0))
    temp = switch%fch_inert*facdrift*geo%fcqalf(:, 1)
    DO nd=1,nbdirs
      fchinertd(nd, :, 1) = -(temp*gonedbsq(:, 0)*geo%fcbb(:, 2)*geo%fcs&
&       *wrk0d(nd, :))
    END DO
    fchinert(:, 1) = -(temp*(gonedbsq(:, 0)*geo%fcbb(:, 2)*(geo%fcs*wrk0&
&     )))
!
  ELSE
    fchinert = 0.0_R8
    DO nd=1,nbdirsmax
      fchinertd(nd, :, :) = 0.D0
    END DO
  END IF
!
! ..return
  CALL SUBEND()
  RETURN
END SUBROUTINE B2TINER_DV
!srv 20.09.06 }

!
!
!
!
!
!
!
!
!
!
!
!-----------------------------------------------------------------------
!.specification
!
SUBROUTINE B2TINER_NODIFF(ncv, nfc, nvx, ns, switch, geo, mpg, na, ua, &
& facdrift, fchinert)
  USE B2MOD_TYPES
  USE B2MOD_CONSTANTS
  USE B2MOD_B2CMFS
  USE B2MOD_B2CMPA_DIFFV
  USE B2MOD_SWITCHES_DIFFV
  USE B2US_GEO_DIFFV
  USE B2US_MAP_DIFFV
  USE B2MOD_SUBSYS
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!
!-----------------------------------------------------------------------
!.end b2tiner
!
!   ..input arguments (unchanged on exit)
  INTEGER, INTENT(IN) :: ncv, nfc, nvx, ns
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(MAPPING), INTENT(IN) :: mpg
  REAL(kind=r8) :: na(ncv, 0:ns-1), ua(ncv, 0:ns-1), facdrift(nfc)
!   ..output arguments (unspecified on entry)
  REAL(kind=r8) :: fchinert(nfc, 0:1)
!   ..common blocks
!-----------------------------------------------------------------------
!.documentation
!
!  1. purpose
!
!     B2TINER computes the X and Y components of the inertial current.
!
!  8. further comments
!
!-----------------------------------------------------------------------
!.declarations
!
!   ..global named constants
!
!   ..local variables
  INTEGER :: is
  REAL(kind=r8) :: wght(nfc, 2), gonedbsq(nfc, 0:1), wrk(ncv), wrk0(nfc)&
& , wrk1(nfc)
!   ..procedures
  EXTERNAL XERTST
  EXTERNAL B2XVSG
  INTRINSIC MAXVAL
  REAL(kind=r8) :: result1
!   ..initialization
!-----------------------------------------------------------------------
!.computation
!
! ..preliminaries
!   ..subprogram start-up calls
  CALL SUBINI('b2tiner')
!   ..test nCv, nFc
  CALL XERTST(0 .LT. ncv .AND. 0 .LT. nfc, 'faulty argument nCv, nFc')
! Drift terms
  result1 = MAXVAL(facdrift)
  IF (switch%fch_inert .NE. 0.0_R8 .AND. result1 .NE. 0.0_R8 .AND. &
&     switch%no_current .EQ. 0) THEN
!srv 07.07.99
!
!     ..compute gradients of OnedBsq on cell faces
    CALL GRAD_NODIFF(ncv, nfc, nvx, 1, geo, mpg, geo%cvonedbsq, geo%&
&              vxonedbsq, gonedbsq)
!
!     ..sum of inertia terms
    wght = 1.0_R8
    wrk0 = 0.0_R8
    DO is=0,ns-1
      IF (.NOT.is_neutral(is)) THEN
        wrk = na(:, is)*ua(:, is)**2
        CALL INTFACE(ncv, nfc, mpg%fccv, wght, wrk, wrk1)
        wrk0 = wrk0 + am(is)*wrk1
      END IF
    END DO
    wrk0 = 0.5_R8*mp*wrk0
!
!     ..COMPONENTS OF INERTIA CURRENT
    fchinert(:, 0) = switch%fch_inert*facdrift*wrk0*gonedbsq(:, 1)*geo%&
&     fcbb(:, 2)*geo%fcs*geo%fcqalf(:, 0)
    fchinert(:, 1) = -(switch%fch_inert*facdrift*wrk0*gonedbsq(:, 0)*geo&
&     %fcbb(:, 2)*geo%fcs*geo%fcqalf(:, 1))
!
  ELSE
    fchinert = 0.0_R8
  END IF
!
! ..return
  CALL SUBEND()
  RETURN
END SUBROUTINE B2TINER_NODIFF
!srv 20.09.06 }

