!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (feature_llhTests) - 27 May 2021 14:23
!
!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE B2TLHE_NODIFF(ncv, nfc, me, cflme, switch, geo, mpg, ne, te, &
& chvemx)
  USE B2MOD_TYPES
  USE B2MOD_SWITCHES_DIFFV
  USE B2US_GEO_DIFFV
  USE B2US_MAP_DIFFV
! csc The following are not necessary for computation but are needed
!     for adjoint AD to avoid side-effect variables
  USE B2MOD_AD_DIFFV, ONLY : ncall_b2tlhe
  USE B2MOD_SUBSYS
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!
  INTEGER :: ncv, nfc
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(MAPPING), INTENT(IN) :: mpg
  REAL(kind=r8) :: me, cflme, ne(ncv), te(ncv), chvemx(nfc)
!     ------------------------------------------------------------------
!     B2TLHE computes the electron heat transport flux limit velocity.
!     ------------------------------------------------------------------
!   ..local variables
  INTEGER :: ifc
  REAL(kind=r8) :: t0, t1, cflme_loc(nfc), nef(nfc)
!   ..procedures
  INTRINSIC MAX, SQRT
  EXTERNAL XERTST, B2XVSG
  INTRINSIC ABS
  REAL(kind=r8) :: abs0
  REAL(kind=r8) :: abs1
  REAL(kind=r8) :: max1
  REAL(kind=r8) :: arg1
  REAL(kind=r8) :: result1
  REAL(kind=r8) :: result2
  REAL(kind=r8) :: result3
  REAL(kind=r8) :: arg2
  REAL(kind=r8) :: result4
!
!   ..initialisation
!     ------------------------------------------------------------------
!   ..subprogram start-up calls
  CALL SUBINI('b2tlhe')
!   ..test nCv, nFc
  CALL XERTST(0 .LT. ncv .AND. 0 .LT. nfc, 'faulty argument nCv, nFc')
!   ..test me, cflme
  CALL XERTST(0.0_R8 .LT. me, 'faulty argument me')
  CALL XERTST(0.0_R8 .LE. cflme, 'faulty argument cflme')
! Init local flux limit to constant value
!   ..extensive tests on first few calls
  IF (ncall_b2tlhe .LT. 3) THEN
!    ..test sign of ne, te
    CALL B2XVSG(ncv, ne, 1, 'ne', '.gt.')
    CALL B2XVSG(ncv, te, 1, 'te', '.gt.')
  END IF
!
! Enhanced flux limit for low-density regions
  cflme_loc = cflme
!
  IF (switch%b2tlhe_far_sol .EQ. 1) THEN
! Attempt enhanced flux limit for low-density regions
    CALL INTFACE(ncv, nfc, mpg%fccv, geo%fcvol, ne, nef)
    DO ifc=1,nfc
      IF (nef(ifc) .LE. switch%b2tlhe_ne_min) THEN
! Set at min value
        cflme_loc(ifc) = switch%b2tlhe_cflme_min
      ELSE IF (nef(ifc) .LT. switch%b2tlhe_ne_max) THEN
! Interpolate for smooth transition
        cflme_loc(ifc) = (cflme*(nef(ifc)-switch%b2tlhe_ne_min)+switch%&
&         b2tlhe_cflme_min*(switch%b2tlhe_ne_max-nef(ifc)))/(switch%&
&         b2tlhe_ne_max-switch%b2tlhe_ne_min)
      END IF
    END DO
  END IF
!
!   ..compute flux limit velocity
  IF (switch%b2tqce_model .EQ. 1 .OR. switch%b2tqce_model .EQ. 3) THEN
! SOLPS5.0 treatments
!wdk perhaps the if-test should be based on a 'mode' switch, instead of b2tqce_model,
!    because now both options are interchangeable
    DO ifc=1,nfc
      IF (te(mpg%fccv(ifc, 1)) .LT. te(mpg%fccv(ifc, 2))) THEN
        t0 = te(mpg%fccv(ifc, 2))
      ELSE
        t0 = te(mpg%fccv(ifc, 1))
      END IF
      IF (geo%fcpbs(ifc) .GE. 0.) THEN
        abs0 = geo%fcpbs(ifc)
      ELSE
        abs0 = -geo%fcpbs(ifc)
      END IF
!srv 11.01.13
      arg1 = t0/me
      result1 = SQRT(arg1)
      chvemx(ifc) = cflme_loc(ifc)*result1*abs0
    END DO
  ELSE IF (switch%b2tqce_model .EQ. 2) THEN
! SOLPS4.0 treatment
    DO ifc=1,nfc
      t0 = te(mpg%fccv(ifc, 2))
      t1 = te(mpg%fccv(ifc, 1))
      IF (geo%fcqalf(ifc, 0) .GE. 0.) THEN
        abs1 = geo%fcqalf(ifc, 0)
      ELSE
        abs1 = -geo%fcqalf(ifc, 0)
      END IF
      IF (t0 .LT. t1) THEN
        max1 = t1
      ELSE
        max1 = t0
      END IF
!wdk 10.03.16 Divide by ne*te at cell faces, so chvemx contains the same information
!           as case b2tqce_model.eq.1
!           Removes need for different treatment later on in the code (b2tfhe), and
!           ensures consistency with b2trcl_conductive_limit .ne. 0
      result1 = PIT(mpg%fccv(ifc, 2))
      arg1 = t0/me
      result2 = SQRT(arg1)
      result3 = PIT(mpg%fccv(ifc, 1))
      arg2 = t1/me
      result4 = SQRT(arg2)
      chvemx(ifc) = cflme_loc(ifc)*geo%fcs(ifc)*abs1*(ne(mpg%fccv(ifc, 2&
&       ))*result1*result2*t0+ne(mpg%fccv(ifc, 1))*result3*result4*t1)/(&
&       (ne(mpg%fccv(ifc, 1))+ne(mpg%fccv(ifc, 2)))*max1)
    END DO
  END IF
  ncall_b2tlhe = ncall_b2tlhe + 1
  CALL SUBEND()
  RETURN

CONTAINS
!     ------------------------------------------------------------------
!
  FUNCTION PIT(icv)
  USE B2MOD_DIFFSIZES
    IMPLICIT NONE
    REAL(kind=r8) :: pit
    INTEGER, INTENT(IN) :: icv
    INTRINSIC ABS
    REAL(kind=r8) :: abs2
    IF (geo%cvbb(icv, 0) .GE. 0.) THEN
      abs2 = geo%cvbb(icv, 0)
    ELSE
      abs2 = -geo%cvbb(icv, 0)
    END IF
!
    pit = abs2/geo%cvbb(icv, 3)
!
    RETURN
  END FUNCTION PIT

END SUBROUTINE B2TLHE_NODIFF

!  Differentiation of b2tlhe in forward (tangent) mode (with options multiDirectional context noISIZE r8):
!   variations   of useful results: chvemx
!   with respect to varying inputs: ne chvemx te
!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE B2TLHE_DV(ncv, nfc, me, cflme, switch, switchd, geo, geod, &
& mpg, ne, ned, te, ted, chvemx, chvemxd, nbdirs)
  USE B2MOD_TYPES
  USE B2MOD_SWITCHES_DIFFV
  USE B2US_GEO_DIFFV
  USE B2US_MAP_DIFFV
! csc The following are not necessary for computation but are needed
!     for adjoint AD to avoid side-effect variables
  USE B2MOD_AD_DIFFV, ONLY : ncall_b2tlhe
  USE B2MOD_SUBSYS
!  Hint: nbdirsmax should be the maximum number of differentiation directions
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!
  INTEGER :: ncv, nfc
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(SWITCHES_DIFFV), INTENT(IN) :: switchd
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(GEOMETRY_DIFFV), INTENT(IN) :: geod
  TYPE(MAPPING), INTENT(IN) :: mpg
  REAL(kind=r8) :: me, cflme, ne(ncv), te(ncv), chvemx(nfc)
  REAL(kind=r8) :: ned(nbdirsmax, ncv), ted(nbdirsmax, ncv), chvemxd(&
& nbdirsmax, nfc)
!     ------------------------------------------------------------------
!     B2TLHE computes the electron heat transport flux limit velocity.
!     ------------------------------------------------------------------
!   ..local variables
  INTEGER :: ifc
  REAL(kind=r8) :: t0, t1, cflme_loc(nfc), nef(nfc)
  REAL(kind=r8) :: t0d(nbdirsmax), t1d(nbdirsmax), cflme_locd(nbdirsmax&
& , nfc), nefd(nbdirsmax, nfc)
!   ..procedures
  INTRINSIC MAX, SQRT
  EXTERNAL XERTST, B2XVSG
  INTRINSIC ABS
  REAL(kind=r8) :: abs0
  REAL(kind=r8) :: abs1
  REAL(kind=r8) :: max1
  REAL(kind=r8), DIMENSION(nbdirsmax) :: max1d
  REAL(kind=r8) :: arg1
  REAL(kind=r8), DIMENSION(nbdirsmax) :: arg1d
  REAL(kind=r8) :: result1
  REAL(kind=r8), DIMENSION(nbdirsmax) :: result1d
  REAL(kind=r8) :: result2
  REAL(kind=r8), DIMENSION(nbdirsmax) :: result2d
  REAL(kind=r8) :: result3
  REAL(kind=r8) :: arg2
  REAL(kind=r8), DIMENSION(nbdirsmax) :: arg2d
  REAL(kind=r8) :: result4
  REAL(kind=r8), DIMENSION(nbdirsmax) :: result4d
  INTEGER :: nd
  REAL(kind=r8) :: temp
  REAL(kind=r8) :: temp0
  REAL(kind=r8) :: temp1
  REAL(kind=r8) :: temp2
  REAL(kind=r8) :: temp3
  INTEGER :: nbdirs
!
!   ..initialisation
!     ------------------------------------------------------------------
!   ..subprogram start-up calls
  CALL SUBINI('b2tlhe')
!   ..test nCv, nFc
  CALL XERTST(0 .LT. ncv .AND. 0 .LT. nfc, 'faulty argument nCv, nFc')
!   ..test me, cflme
  CALL XERTST(0.0_R8 .LT. me, 'faulty argument me')
  CALL XERTST(0.0_R8 .LE. cflme, 'faulty argument cflme')
! Init local flux limit to constant value
!   ..extensive tests on first few calls
  IF (ncall_b2tlhe .LT. 3) THEN
!    ..test sign of ne, te
    CALL B2XVSG(ncv, ne, 1, 'ne', '.gt.')
    CALL B2XVSG(ncv, te, 1, 'te', '.gt.')
  END IF
!
! Enhanced flux limit for low-density regions
  cflme_loc = cflme
!
  IF (switch%b2tlhe_far_sol .EQ. 1) THEN
! Attempt enhanced flux limit for low-density regions
    DO nd=1,nbdirsmax
      nefd(nd, :) = 0.D0
    END DO
    CALL INTFACE_DV(ncv, nfc, mpg%fccv, geo%fcvol, ne, ned, nef, nefd, &
&             nbdirs)
    DO nd=1,nbdirsmax
      cflme_locd(nd, :) = 0.D0
    END DO
    DO ifc=1,nfc
      IF (nef(ifc) .LE. switch%b2tlhe_ne_min) THEN
! Set at min value
        DO nd=1,nbdirs
          cflme_locd(nd, ifc) = 0.D0
        END DO
        cflme_loc(ifc) = switch%b2tlhe_cflme_min
      ELSE IF (nef(ifc) .LT. switch%b2tlhe_ne_max) THEN
! Interpolate for smooth transition
        DO nd=1,nbdirs
          cflme_locd(nd, ifc) = (cflme-switch%b2tlhe_cflme_min)*nefd(nd&
&           , ifc)/(switch%b2tlhe_ne_max-switch%b2tlhe_ne_min)
        END DO
        cflme_loc(ifc) = (cflme*(nef(ifc)-switch%b2tlhe_ne_min)+switch%&
&         b2tlhe_cflme_min*(switch%b2tlhe_ne_max-nef(ifc)))/(switch%&
&         b2tlhe_ne_max-switch%b2tlhe_ne_min)
      END IF
    END DO
  ELSE
    DO nd=1,nbdirsmax
      cflme_locd(nd, :) = 0.D0
    END DO
  END IF
!
!   ..compute flux limit velocity
  IF (switch%b2tqce_model .EQ. 1 .OR. switch%b2tqce_model .EQ. 3) THEN
! SOLPS5.0 treatments
!wdk perhaps the if-test should be based on a 'mode' switch, instead of b2tqce_model,
!    because now both options are interchangeable
    DO ifc=1,nfc
      IF (te(mpg%fccv(ifc, 1)) .LT. te(mpg%fccv(ifc, 2))) THEN
        DO nd=1,nbdirs
          t0d(nd) = ted(nd, mpg%fccv(ifc, 2))
        END DO
        t0 = te(mpg%fccv(ifc, 2))
      ELSE
        DO nd=1,nbdirs
          t0d(nd) = ted(nd, mpg%fccv(ifc, 1))
        END DO
        t0 = te(mpg%fccv(ifc, 1))
      END IF
      IF (geo%fcpbs(ifc) .GE. 0.) THEN
        abs0 = geo%fcpbs(ifc)
      ELSE
        abs0 = -geo%fcpbs(ifc)
      END IF
      arg1 = t0/me
      temp = SQRT(arg1)
      result1 = temp
      DO nd=1,nbdirs
!srv 11.01.13
        arg1d(nd) = t0d(nd)/me
        IF (arg1 .EQ. 0.D0) THEN
          result1d(nd) = 0.D0
        ELSE
          result1d(nd) = arg1d(nd)/(2.0*temp)
        END IF
        chvemxd(nd, ifc) = abs0*(result1*cflme_locd(nd, ifc)+cflme_loc(&
&         ifc)*result1d(nd))
      END DO
      chvemx(ifc) = cflme_loc(ifc)*result1*abs0
    END DO
  ELSE IF (switch%b2tqce_model .EQ. 2) THEN
! SOLPS4.0 treatment
    DO ifc=1,nfc
      DO nd=1,nbdirs
        t0d(nd) = ted(nd, mpg%fccv(ifc, 2))
        t1d(nd) = ted(nd, mpg%fccv(ifc, 1))
      END DO
      t0 = te(mpg%fccv(ifc, 2))
      t1 = te(mpg%fccv(ifc, 1))
      IF (geo%fcqalf(ifc, 0) .GE. 0.) THEN
        abs1 = geo%fcqalf(ifc, 0)
      ELSE
        abs1 = -geo%fcqalf(ifc, 0)
      END IF
      IF (t0 .LT. t1) THEN
        DO nd=1,nbdirs
          max1d(nd) = t1d(nd)
        END DO
        max1 = t1
      ELSE
        DO nd=1,nbdirs
          max1d(nd) = t0d(nd)
        END DO
        max1 = t0
      END IF
!wdk 10.03.16 Divide by ne*te at cell faces, so chvemx contains the same information
!           as case b2tqce_model.eq.1
!           Removes need for different treatment later on in the code (b2tfhe), and
!           ensures consistency with b2trcl_conductive_limit .ne. 0
      result1 = PIT(mpg%fccv(ifc, 2))
      arg1 = t0/me
      temp = SQRT(arg1)
      DO nd=1,nbdirs
        arg1d(nd) = t0d(nd)/me
        IF (arg1 .EQ. 0.D0) THEN
          result2d(nd) = 0.D0
        ELSE
          result2d(nd) = arg1d(nd)/(2.0*temp)
        END IF
        arg2d(nd) = t1d(nd)/me
      END DO
      result2 = temp
      result3 = PIT(mpg%fccv(ifc, 1))
      arg2 = t1/me
      temp = SQRT(arg2)
      DO nd=1,nbdirs
        IF (arg2 .EQ. 0.D0) THEN
          result4d(nd) = 0.D0
        ELSE
          result4d(nd) = arg2d(nd)/(2.0*temp)
        END IF
      END DO
      result4 = temp
      temp = geo%fcs(ifc)*abs1
      temp0 = ne(mpg%fccv(ifc, 1)) + ne(mpg%fccv(ifc, 2))
      temp1 = temp0*max1
      temp2 = cflme_loc(ifc)/temp1
      temp3 = result1*ne(mpg%fccv(ifc, 2))*result2*t0 + result3*ne(mpg%&
&       fccv(ifc, 1))*result4*t1
      DO nd=1,nbdirs
        chvemxd(nd, ifc) = temp*(temp2*(result1*(result2*t0*ned(nd, mpg%&
&         fccv(ifc, 2))+ne(mpg%fccv(ifc, 2))*(t0*result2d(nd)+result2*&
&         t0d(nd)))+result3*(result4*t1*ned(nd, mpg%fccv(ifc, 1))+ne(mpg&
&         %fccv(ifc, 1))*(t1*result4d(nd)+result4*t1d(nd))))+temp3*(&
&         cflme_locd(nd, ifc)-temp2*(max1*(ned(nd, mpg%fccv(ifc, 1))+ned&
&         (nd, mpg%fccv(ifc, 2)))+temp0*max1d(nd)))/temp1)
      END DO
      chvemx(ifc) = temp*(temp3*temp2)
    END DO
  END IF
  ncall_b2tlhe = ncall_b2tlhe + 1
  CALL SUBEND()
  RETURN

CONTAINS
!     ------------------------------------------------------------------
!
  FUNCTION PIT(icv)
  USE B2MOD_DIFFSIZES
    IMPLICIT NONE
    REAL(kind=r8) :: pit
    INTEGER, INTENT(IN) :: icv
    INTRINSIC ABS
    REAL(kind=r8) :: abs2
    IF (geo%cvbb(icv, 0) .GE. 0.) THEN
      abs2 = geo%cvbb(icv, 0)
    ELSE
      abs2 = -geo%cvbb(icv, 0)
    END IF
!
    pit = abs2/geo%cvbb(icv, 3)
!
    RETURN
  END FUNCTION PIT

END SUBROUTINE B2TLHE_DV

