!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (feature_llhTests) - 27 May 2021 14:23
!
!  Differentiation of b2tlh0 in forward (tangent) mode (with options multiDirectional context noISIZE r8):
!   variations   of useful results: chcb
!   with respect to varying inputs: tn na chcb chcib
!   Plus diff mem management of: geo.fcs:in geo.fchc:in geo.fcht:in
!                geo.fcqalf:in geo.fcqbet:in geo.vxvol:in
!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE B2TLH0_DV(ncv, nfc, nvx, ns, switch, switchd, geo, geod, mpg&
& , mpgd, na, nad, ti, tn, tnd, chcib, chcibd, chcb, chcbd, fllim0fhi, &
& fllim0fhid, nbdirs)
  USE B2MOD_TYPES
  USE B2MOD_CONSTANTS
  USE B2MOD_B2CMPA_DIFFV
  USE B2MOD_SWITCHES_DIFFV
  USE B2US_GEO_DIFFV
  USE B2US_MAP_DIFFV
! csc The following are not necessary for computation but are needed
!     for adjoint AD to avoid side-effect variables
  USE B2MOD_AD_DIFFV, ONLY : ncall_b2tlh0, b2tlh0_cutlo
  USE B2MOD_AD_DIFFV, ONLY : my_out_folder
  USE B2MOD_SUBSYS
!  Hint: nbdirsmax should be the maximum number of differentiation directions
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!     ------------------------------------------------------------------
!   ..input arguments (unchanged on exit)
  INTEGER :: ncv, nfc, nvx, ns
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(SWITCHES_DIFFV), INTENT(IN) :: switchd
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(GEOMETRY_DIFFV), INTENT(IN) :: geod
  TYPE(MAPPING), INTENT(IN) :: mpg
  TYPE(MAPPING_DIFFV), INTENT(IN) :: mpgd
  REAL(kind=r8) :: na(ncv, 0:ns-1), ti(ncv), tn(ncv), chcib(nfc, 0:ns-1)&
& , chcb(nfc, 0:1, 0:ns-1)
  REAL(kind=r8) :: nad(nbdirsmax, ncv, 0:ns-1), tnd(nbdirsmax, ncv), &
& chcibd(nbdirsmax, nfc, 0:ns-1), chcbd(nbdirsmax, nfc, 0:1, 0:ns-1)
!   ..output arguments (unspecified on entry)
  REAL(kind=r8) :: fllim0fhi(nfc, 0:1, 0:ns-1)
  REAL(kind=r8) :: fllim0fhid(nbdirsmax, nfc, 0:1, 0:ns-1)
!   ..common blocks
!     ------------------------------------------------------------------
!     B2TLH0 computes the conductive neutral heat transport flux limit.
!     ------------------------------------------------------------------
!   ..local variables
  INTEGER :: ifc, is
!srv 13.01.04 {
  REAL(kind=r8), ALLOCATABLE :: w1(:)
!srv 13.01.04 }
  CHARACTER :: charns*3
  REAL(kind=r8) :: alpha, gamma, t0, t1, t2, dtn, vthi, maxfluxlimit(0:1&
& ), tnv(nvx), dtnf(nfc, 0:1)
  REAL(kind=r8) :: t0d(nbdirsmax), t1d(nbdirsmax), t2d(nbdirsmax), dtnd(&
& nbdirsmax), vthid(nbdirsmax), tnvd(nbdirsmax, nvx), dtnfd(nbdirsmax, &
& nfc, 0:1)
!   ..initialisation
!   ..procedures
  INTRINSIC MAX, ABS, SQRT
  EXTERNAL XERTST, IPGETR, IPGETI
  REAL(kind=r8) :: abs0
  REAL(kind=r8) :: abs1
  INTEGER :: arg1
  REAL(r8) :: arg10
  REAL(r8), DIMENSION(nbdirsmax) :: arg10d
  REAL(kind=r8) :: result1
  REAL(kind=r8), DIMENSION(nbdirsmax) :: result1d
  REAL(kind=r8) :: pwx1
  REAL(kind=r8), DIMENSION(nbdirsmax) :: pwx1d
  REAL(kind=r8) :: pwr1
  REAL(kind=r8), DIMENSION(nbdirsmax) :: pwr1d
  REAL(r8) :: pwx2
  REAL(r8), DIMENSION(nbdirsmax) :: pwx2d
  REAL(r8) :: pwy2
  REAL(r8) :: pwr2
  REAL(r8), DIMENSION(nbdirsmax) :: pwr2d
  REAL(kind=r8) :: arg11
  REAL(kind=r8), DIMENSION(nbdirsmax) :: arg11d
  CHARACTER(len=12) :: arg12
  CHARACTER(len=11) :: arg13
  CHARACTER(len=7) :: arg14
  CHARACTER(len=6) :: arg15
  INTEGER :: nd
  REAL(kind=r8) :: temp
  INTEGER :: nbdirs
!     ------------------------------------------------------------------
!   ..subprogram start-up calls
  CALL SUBINI('b2tlh0')
!   ..test nCv, nFc, ns
  CALL XERTST(0 .LT. ncv .AND. 0 .LT. nfc, 'faulty argument nCv, nFc')
  CALL XERTST(1 .LE. ns, 'faulty argument ns')
!   ..read input on first call
! The following switches are only used in 'WG-TODO' blocks, i.e. not yet converted to wide grid functionality
!        call ipgetr ('b2tlh0_flux_limit_min_ti', flux_limit_min_tn) !! do not change name of switch for compatibility with exist
!ing input files?
!        flux_limit_min_tn=flux_limit_min_tn*ev
!
  alpha = switch%b2tlh0_alpha
  gamma = switch%b2tlh0_gamma
  arg1 = nfc*2*ns
  CALL SFILL_NODIFF(arg1, 1.0_R8, fllim0fhi, 1)
  maxfluxlimit = 0.0_R8
!
  IF (alpha .NE. 0.0_R8) THEN
!   .. compute differences of temperature
    DO nd=1,nbdirsmax
      dtnfd(nd, :, :) = 0.D0
    END DO
    DO nd=1,nbdirsmax
      tnvd(nd, :) = 0.D0
    END DO
    CALL DIFF_DV(ncv, nfc, nvx, 0, geo, geod, mpg, mpgd, tn, tnd, tnv, &
&          tnvd, dtnf, dtnfd, nbdirs)
    IF (switch%b2tlh0_style .EQ. 0) THEN
      DO is=0,ns-1
        IF (is_neutral(is)) THEN
          DO ifc=1,nfc
            DO nd=1,nbdirs
              t0d(nd) = (tnd(nd, mpg%fccv(ifc, 1))+tnd(nd, mpg%fccv(ifc&
&               , 2)))/2.0_R8
              t1d(nd) = (nad(nd, mpg%fccv(ifc, 1), is)+nad(nd, mpg%fccv(&
&               ifc, 2), is))/2.0_R8
            END DO
            t0 = (tn(mpg%fccv(ifc, 1))+tn(mpg%fccv(ifc, 2)))/2.0_R8
            t1 = (na(mpg%fccv(ifc, 1), is)+na(mpg%fccv(ifc, 2), is))/&
&             2.0_R8
            IF (chcb(ifc, 0, is)*dtnf(ifc, 0) .GE. 0.) THEN
              DO nd=1,nbdirs
                dtnd(nd) = dtnf(ifc, 0)*chcbd(nd, ifc, 0, is) + chcb(ifc&
&                 , 0, is)*dtnfd(nd, ifc, 0)
              END DO
              dtn = chcb(ifc, 0, is)*dtnf(ifc, 0)
            ELSE
              DO nd=1,nbdirs
                dtnd(nd) = -(dtnf(ifc, 0)*chcbd(nd, ifc, 0, is)+chcb(ifc&
&                 , 0, is)*dtnfd(nd, ifc, 0))
              END DO
              dtn = -(chcb(ifc, 0, is)*dtnf(ifc, 0))
            END IF
            IF (geo%fcqalf(ifc, 0) .GE. 0.) THEN
              abs0 = geo%fcqalf(ifc, 0)
            ELSE
              abs0 = -geo%fcqalf(ifc, 0)
            END IF
            arg10 = 2.0_R8*t0/(am(is)*mp)
            temp = SQRT(arg10)
            DO nd=1,nbdirs
              arg10d(nd) = 2.0_R8*t0d(nd)/(am(is)*mp)
              IF (arg10 .EQ. 0.D0) THEN
                result1d(nd) = 0.D0
              ELSE
                result1d(nd) = arg10d(nd)/(2.0*temp)
              END IF
              vthid(nd) = geo%fcs(ifc)*abs0*result1d(nd)
            END DO
            result1 = temp
            vthi = result1*geo%fcs(ifc)*abs0
            temp = b2tlh0_cutlo + alpha*vthi*t1*t0
            pwx1 = dtn/temp
            pwr1 = pwx1**gamma
            pwx2 = 1.0_R8 + pwr1
            pwy2 = 1.0_R8/gamma
            pwr2 = pwx2**pwy2
            t2 = 1.0_R8/pwr2
            DO nd=1,nbdirs
              pwx1d(nd) = (dtnd(nd)-dtn*alpha*(t0*(t1*vthid(nd)+vthi*t1d&
&               (nd))+vthi*t1*t0d(nd))/temp)/temp
              IF (pwx1 .LE. 0.D0 .AND. (gamma .EQ. 0.D0 .OR. gamma .NE. &
&                 INT(gamma))) THEN
                pwr1d(nd) = 0.D0
              ELSE
                pwr1d(nd) = gamma*pwx1**(gamma-1)*pwx1d(nd)
              END IF
              pwx2d(nd) = pwr1d(nd)
              IF (pwx2 .LE. 0.D0 .AND. (pwy2 .EQ. 0.D0 .OR. pwy2 .NE. &
&                 INT(pwy2))) THEN
                pwr2d(nd) = 0.D0
              ELSE
                pwr2d(nd) = pwy2*pwx2**(pwy2-1)*pwx2d(nd)
              END IF
              t2d(nd) = -(pwr2d(nd)/pwr2**2)
              chcbd(nd, ifc, 0, is) = t2*chcbd(nd, ifc, 0, is) + chcb(&
&               ifc, 0, is)*t2d(nd)
            END DO
            chcb(ifc, 0, is) = chcb(ifc, 0, is)*t2
            fllim0fhi(ifc, 0, is) = t2
            IF (maxfluxlimit(0) .LT. t2) THEN
              maxfluxlimit(0) = t2
            ELSE
              maxfluxlimit(0) = maxfluxlimit(0)
            END IF
            IF (chcb(ifc, 1, is)*dtnf(ifc, 1) .GE. 0.) THEN
              DO nd=1,nbdirs
                dtnd(nd) = dtnf(ifc, 1)*chcbd(nd, ifc, 1, is) + chcb(ifc&
&                 , 1, is)*dtnfd(nd, ifc, 1)
              END DO
              dtn = chcb(ifc, 1, is)*dtnf(ifc, 1)
            ELSE
              DO nd=1,nbdirs
                dtnd(nd) = -(dtnf(ifc, 1)*chcbd(nd, ifc, 1, is)+chcb(ifc&
&                 , 1, is)*dtnfd(nd, ifc, 1))
              END DO
              dtn = -(chcb(ifc, 1, is)*dtnf(ifc, 1))
            END IF
            IF (geo%fcqalf(ifc, 1) .GE. 0.) THEN
              abs1 = geo%fcqalf(ifc, 1)
            ELSE
              abs1 = -geo%fcqalf(ifc, 1)
            END IF
            arg10 = 2.0_R8*t0/(am(is)*mp)
            temp = SQRT(arg10)
            DO nd=1,nbdirs
              arg10d(nd) = 2.0_R8*t0d(nd)/(am(is)*mp)
              IF (arg10 .EQ. 0.D0) THEN
                result1d(nd) = 0.D0
              ELSE
                result1d(nd) = arg10d(nd)/(2.0*temp)
              END IF
              vthid(nd) = geo%fcs(ifc)*abs1*result1d(nd)
            END DO
            result1 = temp
            vthi = result1*geo%fcs(ifc)*abs1
            temp = b2tlh0_cutlo + alpha*vthi*t1*t0
            pwx1 = dtn/temp
            pwr1 = pwx1**gamma
            pwx2 = 1.0_R8 + pwr1
            pwy2 = 1.0_R8/gamma
            pwr2 = pwx2**pwy2
            t2 = 1.0_R8/pwr2
            DO nd=1,nbdirs
              pwx1d(nd) = (dtnd(nd)-dtn*alpha*(t0*(t1*vthid(nd)+vthi*t1d&
&               (nd))+vthi*t1*t0d(nd))/temp)/temp
              IF (pwx1 .LE. 0.D0 .AND. (gamma .EQ. 0.D0 .OR. gamma .NE. &
&                 INT(gamma))) THEN
                pwr1d(nd) = 0.D0
              ELSE
                pwr1d(nd) = gamma*pwx1**(gamma-1)*pwx1d(nd)
              END IF
              pwx2d(nd) = pwr1d(nd)
              IF (pwx2 .LE. 0.D0 .AND. (pwy2 .EQ. 0.D0 .OR. pwy2 .NE. &
&                 INT(pwy2))) THEN
                pwr2d(nd) = 0.D0
              ELSE
                pwr2d(nd) = pwy2*pwx2**(pwy2-1)*pwx2d(nd)
              END IF
              t2d(nd) = -(pwr2d(nd)/pwr2**2)
              chcbd(nd, ifc, 1, is) = t2*chcbd(nd, ifc, 1, is) + chcb(&
&               ifc, 1, is)*t2d(nd)
            END DO
            chcb(ifc, 1, is) = chcb(ifc, 1, is)*t2
            fllim0fhi(ifc, 1, is) = t2
            IF (maxfluxlimit(1) .LT. t2) THEN
              maxfluxlimit(1) = t2
            ELSE
              maxfluxlimit(1) = maxfluxlimit(1)
            END IF
          END DO
        END IF
      END DO
    ELSE
!wdk    flux limit total gradient-driven flow, not individual poloidal
!wdk    or radial contributions, since neutral transport is isotropic
      DO is=0,ns-1
        IF (is_neutral(is)) THEN
          DO ifc=1,nfc
            arg11 = dtnf(ifc, 0)**2 + dtnf(ifc, 1)**2
            temp = SQRT(arg11)
            result1 = temp
            DO nd=1,nbdirs
              t0d(nd) = (tnd(nd, mpg%fccv(ifc, 1))+tnd(nd, mpg%fccv(ifc&
&               , 2)))/2.0_R8
              t1d(nd) = (nad(nd, mpg%fccv(ifc, 1), is)+nad(nd, mpg%fccv(&
&               ifc, 2), is))/2.0_R8
!   .. compute neutral heat conductivity flux limit
              arg11d(nd) = 2*dtnf(ifc, 0)*dtnfd(nd, ifc, 0) + 2*dtnf(ifc&
&               , 1)*dtnfd(nd, ifc, 1)
              IF (arg11 .EQ. 0.D0) THEN
                result1d(nd) = 0.D0
              ELSE
                result1d(nd) = arg11d(nd)/(2.0*temp)
              END IF
              dtnd(nd) = result1*chcibd(nd, ifc, is) + chcib(ifc, is)*&
&               result1d(nd)
              arg10d(nd) = 2.0_R8*t0d(nd)/(am(is)*mp)
            END DO
            t0 = (tn(mpg%fccv(ifc, 1))+tn(mpg%fccv(ifc, 2)))/2.0_R8
            t1 = (na(mpg%fccv(ifc, 1), is)+na(mpg%fccv(ifc, 2), is))/&
&             2.0_R8
            dtn = chcib(ifc, is)*result1
            arg10 = 2.0_R8*t0/(am(is)*mp)
            temp = SQRT(arg10)
            DO nd=1,nbdirs
              IF (arg10 .EQ. 0.D0) THEN
                result1d(nd) = 0.D0
              ELSE
                result1d(nd) = arg10d(nd)/(2.0*temp)
              END IF
              vthid(nd) = geo%fcs(ifc)*result1d(nd)
            END DO
            result1 = temp
            vthi = result1*geo%fcs(ifc)
            temp = b2tlh0_cutlo + alpha*vthi*t1*t0
            pwx1 = dtn/temp
            pwr1 = pwx1**gamma
            pwx2 = 1.0_R8 + pwr1
            pwy2 = 1.0_R8/gamma
            pwr2 = pwx2**pwy2
            t2 = 1.0_R8/pwr2
            DO nd=1,nbdirs
              pwx1d(nd) = (dtnd(nd)-dtn*alpha*(t0*(t1*vthid(nd)+vthi*t1d&
&               (nd))+vthi*t1*t0d(nd))/temp)/temp
              IF (pwx1 .LE. 0.D0 .AND. (gamma .EQ. 0.D0 .OR. gamma .NE. &
&                 INT(gamma))) THEN
                pwr1d(nd) = 0.D0
              ELSE
                pwr1d(nd) = gamma*pwx1**(gamma-1)*pwx1d(nd)
              END IF
              pwx2d(nd) = pwr1d(nd)
              IF (pwx2 .LE. 0.D0 .AND. (pwy2 .EQ. 0.D0 .OR. pwy2 .NE. &
&                 INT(pwy2))) THEN
                pwr2d(nd) = 0.D0
              ELSE
                pwr2d(nd) = pwy2*pwx2**(pwy2-1)*pwx2d(nd)
              END IF
              t2d(nd) = -(pwr2d(nd)/pwr2**2)
!   .. limit in poloidal direction
              chcbd(nd, ifc, 0, is) = t2*chcbd(nd, ifc, 0, is) + chcb(&
&               ifc, 0, is)*t2d(nd)
            END DO
            chcb(ifc, 0, is) = chcb(ifc, 0, is)*t2
            fllim0fhi(ifc, 0, is) = t2
            IF (maxfluxlimit(0) .LT. t2) THEN
              maxfluxlimit(0) = t2
            ELSE
              maxfluxlimit(0) = maxfluxlimit(0)
            END IF
!   .. limit in radial diretion
            DO nd=1,nbdirs
              chcbd(nd, ifc, 1, is) = t2*chcbd(nd, ifc, 1, is) + chcb(&
&               ifc, 1, is)*t2d(nd)
            END DO
            chcb(ifc, 1, is) = chcb(ifc, 1, is)*t2
            fllim0fhi(ifc, 1, is) = t2
            IF (maxfluxlimit(1) .LT. t2) THEN
              maxfluxlimit(1) = t2
            ELSE
              maxfluxlimit(1) = maxfluxlimit(1)
            END IF
          END DO
        END IF
      END DO
    END IF
  END IF
!
  IF (ncall_b2tlh0 .LT. 100) WRITE(*, '(1x,a,1p,2e10.2)') &
&                            'b2tlh0: maxfluxlimit = ', maxfluxlimit
!
  IF (switch%b2tlh0_iout .NE. 0) THEN
    ALLOCATE(w1(ncv))
!srv 13.01.04 {
    DO is=0,ns-1
      WRITE(charns, '(i3.3)') is
      arg12(:) = 'fllim0fhi_th'//charns
      CALL MY_OUT_US(70, nfc, 1, fllim0fhi(1, 0, is), arg12(:))
      arg13(:) = 'fllim0fhi_r'//charns
      CALL MY_OUT_US(70, nfc, 1, fllim0fhi(1, 1, is), arg13(:))
      arg14(:) = 'chci_th'//charns
      CALL MY_OUT_US(70, nfc, 1, chcb(1, 0, is), arg14(:))
      arg15(:) = 'chci_r'//charns
      CALL MY_OUT_US(70, nfc, 1, chcb(1, 1, is), arg15(:))
    END DO
!srv 13.01.04 }
    DEALLOCATE(w1)
  END IF
!
!   ..return
  ncall_b2tlh0 = ncall_b2tlh0 + 1
  CALL SUBEND()
  RETURN
END SUBROUTINE B2TLH0_DV

!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE B2TLH0_NODIFF(ncv, nfc, nvx, ns, switch, geo, mpg, na, ti, tn&
& , chcib, chcb, fllim0fhi)
  USE B2MOD_TYPES
  USE B2MOD_CONSTANTS
  USE B2MOD_B2CMPA_DIFFV
  USE B2MOD_SWITCHES_DIFFV
  USE B2US_GEO_DIFFV
  USE B2US_MAP_DIFFV
! csc The following are not necessary for computation but are needed
!     for adjoint AD to avoid side-effect variables
  USE B2MOD_AD_DIFFV, ONLY : ncall_b2tlh0, b2tlh0_cutlo
  USE B2MOD_AD_DIFFV, ONLY : my_out_folder
  USE B2MOD_SUBSYS
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!     ------------------------------------------------------------------
!   ..input arguments (unchanged on exit)
  INTEGER :: ncv, nfc, nvx, ns
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(MAPPING), INTENT(IN) :: mpg
  REAL(kind=r8) :: na(ncv, 0:ns-1), ti(ncv), tn(ncv), chcib(nfc, 0:ns-1)&
& , chcb(nfc, 0:1, 0:ns-1)
!   ..output arguments (unspecified on entry)
  REAL(kind=r8) :: fllim0fhi(nfc, 0:1, 0:ns-1)
!   ..common blocks
!     ------------------------------------------------------------------
!     B2TLH0 computes the conductive neutral heat transport flux limit.
!     ------------------------------------------------------------------
!   ..local variables
  INTEGER :: ifc, is
!srv 13.01.04 {
  REAL(kind=r8), ALLOCATABLE :: w1(:)
!srv 13.01.04 }
  CHARACTER :: charns*3
  REAL(kind=r8) :: alpha, gamma, t0, t1, t2, dtn, vthi, maxfluxlimit(0:1&
& ), tnv(nvx), dtnf(nfc, 0:1)
!   ..initialisation
!   ..procedures
  INTRINSIC MAX, ABS, SQRT
  EXTERNAL XERTST, IPGETR, IPGETI
  REAL(kind=r8) :: abs0
  REAL(kind=r8) :: abs1
  INTEGER :: arg1
  REAL(r8) :: arg10
  REAL(kind=r8) :: result1
  REAL(kind=r8) :: pwx1
  REAL(kind=r8) :: pwr1
  REAL(r8) :: pwx2
  REAL(r8) :: pwy2
  REAL(r8) :: pwr2
  REAL(kind=r8) :: arg11
  CHARACTER(len=12) :: arg12
  CHARACTER(len=11) :: arg13
  CHARACTER(len=7) :: arg14
  CHARACTER(len=6) :: arg15
!     ------------------------------------------------------------------
!   ..subprogram start-up calls
  CALL SUBINI('b2tlh0')
!   ..test nCv, nFc, ns
  CALL XERTST(0 .LT. ncv .AND. 0 .LT. nfc, 'faulty argument nCv, nFc')
  CALL XERTST(1 .LE. ns, 'faulty argument ns')
!   ..read input on first call
! The following switches are only used in 'WG-TODO' blocks, i.e. not yet converted to wide grid functionality
!        call ipgetr ('b2tlh0_flux_limit_min_ti', flux_limit_min_tn) !! do not change name of switch for compatibility with exist
!ing input files?
!        flux_limit_min_tn=flux_limit_min_tn*ev
!
  alpha = switch%b2tlh0_alpha
  gamma = switch%b2tlh0_gamma
  arg1 = nfc*2*ns
  CALL SFILL_NODIFF(arg1, 1.0_R8, fllim0fhi, 1)
  maxfluxlimit = 0.0_R8
!
  IF (alpha .NE. 0.0_R8) THEN
!   .. compute differences of temperature
    CALL DIFF_NODIFF(ncv, nfc, nvx, 0, geo, mpg, tn, tnv, dtnf)
    IF (switch%b2tlh0_style .EQ. 0) THEN
      DO is=0,ns-1
        IF (is_neutral(is)) THEN
          DO ifc=1,nfc
            t0 = (tn(mpg%fccv(ifc, 1))+tn(mpg%fccv(ifc, 2)))/2.0_R8
            t1 = (na(mpg%fccv(ifc, 1), is)+na(mpg%fccv(ifc, 2), is))/&
&             2.0_R8
            IF (chcb(ifc, 0, is)*dtnf(ifc, 0) .GE. 0.) THEN
              dtn = chcb(ifc, 0, is)*dtnf(ifc, 0)
            ELSE
              dtn = -(chcb(ifc, 0, is)*dtnf(ifc, 0))
            END IF
            IF (geo%fcqalf(ifc, 0) .GE. 0.) THEN
              abs0 = geo%fcqalf(ifc, 0)
            ELSE
              abs0 = -geo%fcqalf(ifc, 0)
            END IF
            arg10 = 2.0_R8*t0/(am(is)*mp)
            result1 = SQRT(arg10)
            vthi = result1*geo%fcs(ifc)*abs0
            pwx1 = dtn/(alpha*vthi*t1*t0+b2tlh0_cutlo)
            pwr1 = pwx1**gamma
            pwx2 = 1.0_R8 + pwr1
            pwy2 = 1.0_R8/gamma
            pwr2 = pwx2**pwy2
            t2 = 1.0_R8/pwr2
            chcb(ifc, 0, is) = chcb(ifc, 0, is)*t2
            fllim0fhi(ifc, 0, is) = t2
            IF (maxfluxlimit(0) .LT. t2) THEN
              maxfluxlimit(0) = t2
            ELSE
              maxfluxlimit(0) = maxfluxlimit(0)
            END IF
            IF (chcb(ifc, 1, is)*dtnf(ifc, 1) .GE. 0.) THEN
              dtn = chcb(ifc, 1, is)*dtnf(ifc, 1)
            ELSE
              dtn = -(chcb(ifc, 1, is)*dtnf(ifc, 1))
            END IF
            IF (geo%fcqalf(ifc, 1) .GE. 0.) THEN
              abs1 = geo%fcqalf(ifc, 1)
            ELSE
              abs1 = -geo%fcqalf(ifc, 1)
            END IF
            arg10 = 2.0_R8*t0/(am(is)*mp)
            result1 = SQRT(arg10)
            vthi = result1*geo%fcs(ifc)*abs1
            pwx1 = dtn/(alpha*vthi*t1*t0+b2tlh0_cutlo)
            pwr1 = pwx1**gamma
            pwx2 = 1.0_R8 + pwr1
            pwy2 = 1.0_R8/gamma
            pwr2 = pwx2**pwy2
            t2 = 1.0_R8/pwr2
            chcb(ifc, 1, is) = chcb(ifc, 1, is)*t2
            fllim0fhi(ifc, 1, is) = t2
            IF (maxfluxlimit(1) .LT. t2) THEN
              maxfluxlimit(1) = t2
            ELSE
              maxfluxlimit(1) = maxfluxlimit(1)
            END IF
          END DO
        END IF
      END DO
    ELSE
!wdk    flux limit total gradient-driven flow, not individual poloidal
!wdk    or radial contributions, since neutral transport is isotropic
      DO is=0,ns-1
        IF (is_neutral(is)) THEN
          DO ifc=1,nfc
            t0 = (tn(mpg%fccv(ifc, 1))+tn(mpg%fccv(ifc, 2)))/2.0_R8
            t1 = (na(mpg%fccv(ifc, 1), is)+na(mpg%fccv(ifc, 2), is))/&
&             2.0_R8
!   .. compute neutral heat conductivity flux limit
            arg11 = dtnf(ifc, 0)**2 + dtnf(ifc, 1)**2
            result1 = SQRT(arg11)
            dtn = chcib(ifc, is)*result1
            arg10 = 2.0_R8*t0/(am(is)*mp)
            result1 = SQRT(arg10)
            vthi = result1*geo%fcs(ifc)
            pwx1 = dtn/(alpha*vthi*t1*t0+b2tlh0_cutlo)
            pwr1 = pwx1**gamma
            pwx2 = 1.0_R8 + pwr1
            pwy2 = 1.0_R8/gamma
            pwr2 = pwx2**pwy2
            t2 = 1.0_R8/pwr2
!   .. limit in poloidal direction
            chcb(ifc, 0, is) = chcb(ifc, 0, is)*t2
            fllim0fhi(ifc, 0, is) = t2
            IF (maxfluxlimit(0) .LT. t2) THEN
              maxfluxlimit(0) = t2
            ELSE
              maxfluxlimit(0) = maxfluxlimit(0)
            END IF
!   .. limit in radial diretion
            chcb(ifc, 1, is) = chcb(ifc, 1, is)*t2
            fllim0fhi(ifc, 1, is) = t2
            IF (maxfluxlimit(1) .LT. t2) THEN
              maxfluxlimit(1) = t2
            ELSE
              maxfluxlimit(1) = maxfluxlimit(1)
            END IF
          END DO
        END IF
      END DO
    END IF
  END IF
!
  IF (ncall_b2tlh0 .LT. 100) WRITE(*, '(1x,a,1p,2e10.2)') &
&                            'b2tlh0: maxfluxlimit = ', maxfluxlimit
!
  IF (switch%b2tlh0_iout .NE. 0) THEN
    ALLOCATE(w1(ncv))
!srv 13.01.04 {
    DO is=0,ns-1
      WRITE(charns, '(i3.3)') is
      arg12(:) = 'fllim0fhi_th'//charns
      CALL MY_OUT_US(70, nfc, 1, fllim0fhi(1, 0, is), arg12(:))
      arg13(:) = 'fllim0fhi_r'//charns
      CALL MY_OUT_US(70, nfc, 1, fllim0fhi(1, 1, is), arg13(:))
      arg14(:) = 'chci_th'//charns
      CALL MY_OUT_US(70, nfc, 1, chcb(1, 0, is), arg14(:))
      arg15(:) = 'chci_r'//charns
      CALL MY_OUT_US(70, nfc, 1, chcb(1, 1, is), arg15(:))
    END DO
!srv 13.01.04 }
    DEALLOCATE(w1)
  END IF
!
!   ..return
  ncall_b2tlh0 = ncall_b2tlh0 + 1
  CALL SUBEND()
  RETURN
END SUBROUTINE B2TLH0_NODIFF

