!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (feature_llhTests) - 27 May 2021 14:23
!
!  Differentiation of b2trcl in forward (tangent) mode (with options multiDirectional context noISIZE r8):
!   variations   of useful results: vsaf_cl *(dv.lnlam) chce chci
!                cvsa_cl cvsahz_cl cdkt csigin calf *(co.alfx_c)
!                *(co.sigx_c) *(co.sigx_kt) *(co.hcix_c) *(co.fllim_ki)
!                *(co.fllim_ke) *(co.fllim_al) *(co.fllim_al_c)
!                *(co.fllim_ki_c) *(co.f_luc_ke) *(co.f_luc_ki)
!                *(co.f_luc_et) *(co.f_luc_sg) *(co.f_luc_al) csig
!   with respect to varying inputs: vsaf_cl *(dv.ne) *(dv.ni) *(dv.ne2)
!                *(dv.lnlam) *(rt.rlcx) *(rt.rza) *(rt.rz2) csigin
!                switch.b2tfhi_fsigkt *(co.chvemx) *(co.chvimx)
!                *(co.alfx_c) *(co.sigx_c) *(co.sigx_kt) *(co.hcix_c)
!                *(co.fllim_ki) *(co.fllim_ke) *(co.fllim_al) *(co.fllim_al_c)
!                *(co.fllim_ki_c) *(co.f_luc_ke) *(co.f_luc_ki)
!                *(co.f_luc_et) *(co.f_luc_sg) *(co.f_luc_al) *(pl.na)
!                *(pl.ua) *(pl.te) *(pl.ti) *(pl.tn)
!   Plus diff mem management of: dv.ne:in dv.ni:in dv.ne2:in dv.lnlam:in
!                mpg.intcellp:in geo.cvbb:in geo.cvhz:in geo.cvqgam:in
!                geo.cvvol:in geo.fcs:in geo.fchc:in geo.fcht:in
!                geo.fchz:in geo.fcvol:in geo.fcqgam:in geo.fcqalf:in
!                geo.fcqbet:in geo.fcpbs:in geo.vxvol:in geo.ftconn:in
!                geo.fsconn:in geo.fteps:in st_ext.am:in st_ext.za2:in
!                st_ext.na:in rt.rlcx:in rt.rza:in rt.rz2:in co.chvemx:in
!                co.chvimx:in co.alfx_c:in co.sigx_c:in co.sigx_kt:in
!                co.hcix_c:in co.fllim_ki:in co.fllim_ke:in co.fllim_al:in
!                co.fllim_al_c:in co.fllim_ki_c:in co.f_luc_ke:in
!                co.f_luc_ki:in co.f_luc_et:in co.f_luc_sg:in co.f_luc_al:in
!                pl.na:in pl.ua:in pl.te:in pl.ti:in pl.tn:in
!
!
!
!
!
!
!
!
!
!
!
!-----------------------------------------------------------------------
!.specification
!
!srv 23.11.10
!srv 09.01.01 03.06.03
!xpb
!srv 09.01.01
!xpb
SUBROUTINE B2TRCL_DV(ncv, nfc, nvx, ns, nscx, iscx, ismain, switch, &
& switchd, geo, geod, mpg, mpgd, pl, pld, dv, dvd, rt, rtd, co, cod, &
& st_ext, st_extd, cvsahz, cvsahzd, cvsa, cvsad, chce, chced, chve, &
& chved, chci, chcid, chvi, chvid, csig, csigd, calf, calfd, cdkt, cdktd&
& , csigin, csigind, cthe, cthed, cthi, cthid, vsaf_cl, vsaf_cld, &
& cvsa_cl, cvsa_cld, cvsahz_cl, cvsahz_cld, fllimvisc, csig_cl, calf_cl&
& , nbdirs)
  USE B2MOD_TYPES
  USE B2MOD_CONSTANTS
  USE B2MOD_B2CMPA_DIFFV
  USE B2MOD_B2CMPT_DIFFV
  USE B2MOD_SWITCHES_DIFFV
  USE B2US_GEO_DIFFV
  USE B2US_MAP_DIFFV
  USE B2US_PLASMA_DIFFV
  USE B2MOD_AD_DIFFV, ONLY : ncall_b2trcl, b2trcl_cutlo
! csc The following are not necessary for computation but are needed
!     for adjoint AD to avoid side-effect variables
  USE B2MOD_MATH_DIFFV, ONLY : b2mod_math_initialised, cutlo, cutlod, &
& cutll, small_r4_constant
  USE B2MOD_AD_DIFFV, ONLY : my_out_folder, ncall_b2tlnl, ncall_b2tlmv, &
& ncall_b2tqin, ncall_b2tqce, ncall_b2tqca, ncall_b2ttia
  USE B2MOD_SUBSYS
!  Hint: nCv should be the size of dimension 1 of array arg1
!  Hint: nCv should be the size of dimension 1 of array result1
!  Hint: nCv should be the size of dimension 1 of array cvbb
!  Hint: nCv should be the size of dimension 1 of array temp
!  Hint: nCv should be the size of dimension 1 of array lnlam
!  Hint: nbdirsmax should be the maximum number of differentiation directions
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!
!-----------------------------------------------------------------------
!.end b2trcl
!
!   ..input arguments (unchanged on exit)
  INTEGER, INTENT(IN) :: ncv, nfc, nvx, ns, nscx, ismain
  INTEGER, INTENT(IN) :: iscx(0:nscx-1)
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(SWITCHES_DIFFV), INTENT(IN) :: switchd
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(GEOMETRY_DIFFV), INTENT(IN) :: geod
  TYPE(MAPPING), INTENT(IN) :: mpg
  TYPE(MAPPING_DIFFV), INTENT(IN) :: mpgd
  TYPE(B2PLASMA), INTENT(IN) :: pl
  TYPE(B2PLASMA_DIFFV), INTENT(IN) :: pld
  TYPE(B2DERIVATIVES), INTENT(INOUT) :: dv
  TYPE(B2DERIVATIVES_DIFFV), INTENT(INOUT) :: dvd
  TYPE(B2RATES), INTENT(IN) :: rt
  TYPE(B2RATES_DIFFV), INTENT(IN) :: rtd
  TYPE(B2STATEEXT), INTENT(IN) :: st_ext
  TYPE(B2STATEEXT_DIFFV), INTENT(IN) :: st_extd
!   ..output arguments (unspecified on entry)
  TYPE(B2COEFF), INTENT(INOUT) :: co
  TYPE(B2COEFF_DIFFV), INTENT(INOUT) :: cod
!wdk to consider: create an output struct co0 of type (B2Coeff) for this?
!xpb
!srv 09.01.01
!srv 09.01.01
  REAL(kind=r8) :: cvsa(nfc, 0:1, 0:ns-1), chce(nfc, 0:1), chve(nfc, 0:1&
& ), chci(nfc, 0:1), chvi(nfc, 0:1), csig(nfc, 0:1), calf(nfc, 0:1), &
& cdkt(nfc, 0:1), csigin(nfc, 0:1, 0:ns-1, 0:ns-1), cthe(ncv, 0:ns-1), &
& cthi(ncv, 0:ns-1), vsaf_cl(nfc, 0:1, 0:ns-1), cvsa_cl(nfc, 0:1, 0:ns-1&
& ), cvsahz_cl(nfc, 0:1, 0:ns-1), fllimvisc(nfc, 0:ns-1), cvsahz(nfc, 0:&
& 1, 0:ns-1), csig_cl(nfc, 0:1), calf_cl(nfc, 0:1)
  REAL(kind=r8) :: cvsad(nbdirsmax, nfc, 0:1, 0:ns-1), chced(nbdirsmax, &
& nfc, 0:1), chved(nbdirsmax, nfc, 0:1), chcid(nbdirsmax, nfc, 0:1), &
& chvid(nbdirsmax, nfc, 0:1), csigd(nbdirsmax, nfc, 0:1), calfd(&
& nbdirsmax, nfc, 0:1), cdktd(nbdirsmax, nfc, 0:1), csigind(nbdirsmax, &
& nfc, 0:1, 0:ns-1, 0:ns-1), cthed(nbdirsmax, ncv, 0:ns-1), cthid(&
& nbdirsmax, ncv, 0:ns-1), vsaf_cld(nbdirsmax, nfc, 0:1, 0:ns-1), &
& cvsa_cld(nbdirsmax, nfc, 0:1, 0:ns-1), cvsahz_cld(nbdirsmax, nfc, 0:1&
& , 0:ns-1), cvsahzd(nbdirsmax, nfc, 0:1, 0:ns-1)
!   ..common blocks
!-----------------------------------------------------------------------
!.documentation
!
!  1. purpose
!
!     B2TRCL computes the classical transport coefficients, including
!     geometric factors such as vol/hx**2 and vol/hy**2.
!
!
!  3. description (see also routine b2cdca)
!
!     This routine computes the following discrete classical transport
!     coefficients.
!     - cvsa: viscosity.
!     - chce: electron thermal conductivity.
!     - chve: electron thermal strange velocity.
!     - chci: atom thermal conductivity.
!     - chvi: atom thermal strange velocity.
!     - csig: electrical conductivity.
!     - csigin: ion-neutral conductivity.
!     - calf: thermo-electric coefficient.
!
!     The local differential transport coefficients, defined on cells,
!     are obtained by calls to b2tqca and b2tqce. To compute from these
!     the discrete transport coefficients involves multiplication by
!     geometric factors (vol, vol/hx**2, vol/hy**2), and, usually,
!     interpolation to cell faces.
!
!-----------------------------------------------------------------------
!.declarations
!
!   ..local variables
  INTEGER :: k, is, is0, icv, ifc, ift, mode
!srv 17.06.08
  CHARACTER(len=3) :: chns, chns0
!srv 13.01.17
  REAL(kind=r8) :: cflmv, jemax
  REAL(kind=r8), DIMENSION(nbdirsmax) :: jemaxd
!srv 03.06.03
  REAL(kind=r8) :: t0, dte(nfc), dti(nfc), flomx, connf, epsf
  REAL(kind=r8) :: t0d(nbdirsmax), dted(nbdirsmax, nfc), dtid(nbdirsmax&
& , nfc), flomxd(nbdirsmax)
!lk 19.09.07
  REAL(kind=r8) :: tauia(ncv, 0:ns-1), nu2(ncv), k2(ncv)
  REAL(kind=r8) :: tauiad(nbdirsmax, ncv, 0:ns-1), nu2d(nbdirsmax, ncv)&
& , k2d(nbdirsmax, ncv)
!lk 12.05.11
!lk 12.05.11
  REAL(kind=r8) :: tau(ncv), nu1(ncv), k1(ncv), t1, t2
  REAL(kind=r8) :: taud(nbdirsmax, ncv), nu1d(nbdirsmax, ncv), k1d(&
& nbdirsmax, ncv)
!srv 01.07.99 09.01.01
  REAL(kind=r8) :: hce(ncv, 0:1), sig(ncv, 0:1), alf(ncv, 0:1), vsa(ncv&
& , 0:1, 0:ns-1), hci(ncv, 0:1), sigin(ncv, 0:1, 0:ns-1, 0:nscx-1), wrk(&
& nfc), wrk1(nfc, 2), wrkv(nvx), wrkc(ncv), tef(nfc), tif(nfc), ne2f(nfc&
& ), k1f, k2f, gtec(ncv), nu1f, nu2f, tauf(nfc), tauiaf(nfc)
  REAL(kind=r8) :: hced(nbdirsmax, ncv, 0:1), sigd(nbdirsmax, ncv, 0:1)&
& , alfd(nbdirsmax, ncv, 0:1), vsad(nbdirsmax, ncv, 0:1, 0:ns-1), hcid(&
& nbdirsmax, ncv, 0:1), sigind(nbdirsmax, ncv, 0:1, 0:ns-1, 0:nscx-1), &
& wrkd(nbdirsmax, nfc), wrkvd(nbdirsmax, nvx), wrkcd(nbdirsmax, ncv), &
& tefd(nbdirsmax, nfc), tifd(nbdirsmax, nfc), ne2fd(nbdirsmax, nfc), &
& k1fd(nbdirsmax), k2fd(nbdirsmax), gtecd(nbdirsmax, ncv), nu1fd(&
& nbdirsmax), nu2fd(nbdirsmax), taufd(nbdirsmax, nfc), tauiafd(nbdirsmax&
& , nfc)
  EXTERNAL XERTST, XERRAB, SFILL_NODIFF, smin, smax
  EXTERNAL SFILL_DV
!   ..procedures
!srv 22.04.16
  REAL(kind=r8) :: smin, smax
!xpb
!lk 19.09.07
  EXTERNAL B2TQCA_NODIFF, B2TQCE_NODIFF, B2TQIN_NODIFF, B2TXCX_NODIFF, &
&     B2TXCY_NODIFF, B2TLMV_NODIFF, IPGETI, IPGETR, B2TTIA_NODIFF
  EXTERNAL B2TQCA_DV, B2TQCE_DV, B2TQIN_DV, B2TXCX_DV, B2TXCY_DV, &
&     B2TLMV_DV, B2TTIA_DV
  EXTERNAL B2XVSG
  INTRINSIC NINT
  INTRINSIC SQRT
  INTRINSIC ABS
  INTRINSIC MAX
  REAL(r8) :: x1
  REAL(r8), DIMENSION(nbdirsmax) :: x1d
  REAL(kind=r8) :: abs0
  REAL(kind=r8), DIMENSION(nbdirsmax) :: abs0d
  REAL(kind=r8) :: abs1
  REAL(kind=r8), DIMENSION(nbdirsmax) :: abs1d
  REAL(kind=r8) :: abs2
  REAL(kind=r8), DIMENSION(nbdirsmax) :: abs2d
  REAL(kind=r8) :: abs3
  REAL(kind=r8) :: abs4
  REAL(kind=r8), DIMENSION(nbdirsmax) :: abs4d
  REAL(kind=r8), DIMENSION(nCv) :: dabs0
  REAL(kind=r8), DIMENSION(nbdirsmax, nCv) :: dabs0d
  REAL(r8) :: max1
  REAL(r8), DIMENSION(nbdirsmax) :: max1d
  REAL(r8) :: max2
  REAL(r8), DIMENSION(nbdirsmax) :: max2d
  REAL(r8) :: max3
  REAL(r8), DIMENSION(nbdirsmax) :: max3d
  REAL(kind=r8) :: result1
  REAL(kind=r8), DIMENSION(nbdirsmax) :: result1d
  REAL(kind=r8) :: result2
  REAL(kind=r8), DIMENSION(nbdirsmax) :: result2d
  INTEGER :: arg1
  CHARACTER(len=14) :: arg10
  REAL(r8) :: arg11
  REAL(r8), DIMENSION(nbdirsmax) :: arg11d
  REAL(kind=r8) :: result10
  REAL(kind=r8) :: result3
  REAL(r8), DIMENSION(nCv) :: arg12
  REAL(r8), DIMENSION(nbdirsmax, nCv) :: arg12d
  REAL(r8), DIMENSION(nCv) :: result11
  REAL(r8), DIMENSION(nbdirsmax, nCv) :: result11d
  REAL(r8) :: result12
  REAL(r8), DIMENSION(nbdirsmax) :: result12d
  REAL(kind=r8) :: arg13
  REAL(kind=r8), DIMENSION(nbdirsmax) :: arg13d
  REAL(kind=r8) :: arg2
  CHARACTER(len=22) :: arg14
  REAL(r8), DIMENSION(nCv) :: arg15
  REAL(r8), DIMENSION(nbdirsmax, nCv) :: arg15d
  REAL(kind=r8), DIMENSION(nCv) :: result13
  REAL(kind=r8), DIMENSION(nbdirsmax, nCv) :: result13d
  CHARACTER(len=30) :: arg16
  CHARACTER(len=10) :: arg17
  CHARACTER(len=9) :: arg18
  CHARACTER(len=12) :: arg19
  CHARACTER(len=11) :: arg110
  CHARACTER(len=13) :: arg111
  CHARACTER(len=7) :: arg112
  REAL(r8), DIMENSION(nbdirsmax) :: dummyzerodiffd
  INTEGER :: nd
  REAL(r8), DIMENSION(nbdirsmax) :: dummyzerodiffd0
  REAL(r8), DIMENSION(nbdirsmax) :: dummyzerodiffd1
  REAL(r8), DIMENSION(nbdirsmax) :: dummyzerodiffd2
  REAL(kind=r8) :: temp
  REAL(r8), DIMENSION(nbdirsmax) :: dummyzerodiffd3
  REAL(kind=r8) :: temp0
  REAL(r8) :: temp1
  REAL(r8) :: temp2
  REAL(r8), DIMENSION(nCv) :: temp3
  REAL(kind=r8), DIMENSION(nCv) :: temp4
  REAL(r8), DIMENSION(nCv) :: temp5
  REAL(kind=r8) :: temp6
  REAL(kind=r8) :: temp7
  REAL(kind=r8) :: temp8
  REAL(kind=r8) :: temp9
  REAL(kind=r8) :: temp10
  REAL(kind=r8) :: temp11
  REAL(kind=r8), DIMENSION(nCv) :: temp12
  INTEGER :: nbdirs
!   ..initialisation
!
!-----------------------------------------------------------------------
!.computation
!
! ..preliminaries
!   ..subprogram start-up calls
  CALL SUBINI('b2trcl')
!   ..test nCv, nFc, ns
  CALL XERTST(0 .LT. ncv .AND. 0 .LT. nfc, 'faulty argument nCv, nFc')
  CALL XERTST(1 .LE. ns, 'faulty argument ns')
!   ..set internal parameters on first call
! The following switches are only used in 'WG-TODO' blocks, i.e. not yet converted to wide grid functionality
!        call ipgetr ('b2tfhe_vis_par',vis_par)
!        call ipgeti ('b2trcl_integral_modeling', integral_modeling)  !srv 01.11.11
!        call ipgeti ('b2trcl_lthf21',lthf21)
!       call ipgeti ('b2trcl_lvis21',lvis21)
!#ifdef NO_21
!        call xertst (lthf21.eq.0.and.lvis21.eq.0,
!     &   'Recompile without NO_21 option for 21-moment approach!')
!#endif
!        call xertst (.not.(lvis21.ne.0.and.vis_par.ne.0.0_R8),
!     &   '21-moment viscosity already includes parallel viscosity!')
!   ..extensive tests on first few calls
  IF (ncall_b2trcl .LT. 3) THEN
!    ..test bb
    CALL B2XVSG(ncv, geo%cvbb(1, 3), 1, 'bb3', '.gt.')
!    ..test sign of vol
    CALL B2XVSG(ncv, geo%cvvol, 1, 'vol', '.gt.')
!    ..test range of cvQgam, fcQgam
    result1 = smin(ncv, geo%cvqgam(1, 1), 1)
    result2 = smax(ncv, geo%cvqgam(1, 1), 1)
    CALL XERTST(-1.0_R8 .LT. result1 .AND. result2 .LT. 1.0_R8, &
&         'faulty argument range cvQgam(,1)')
    result1 = smin(ncv, geo%cvqgam(1, 0), 1)
    result2 = smax(ncv, geo%cvqgam(1, 0), 1)
    CALL XERTST(0.0_R8 .LT. result1 .AND. result2 .LE. 1.0_R8, &
&         'faulty argument range cvQgam(,0)')
    result1 = smin(nfc, geo%fcqgam(1, 1), 1)
    result2 = smax(nfc, geo%fcqgam(1, 1), 1)
    CALL XERTST(-1.0_R8 .LT. result1 .AND. result2 .LT. 1.0_R8, &
&         'faulty argument range fcQgam(,1)')
    result1 = smin(nfc, geo%fcqgam(1, 0), 1)
    result2 = smax(nfc, geo%fcqgam(1, 0), 1)
    CALL XERTST(0.0_R8 .LT. result1 .AND. result2 .LE. 1.0_R8, &
&         'faulty argument range fcQgam(,0)')
!    ..test sign of na, te, ti
    arg1 = ncv*ns
    CALL B2XVSG(arg1, pl%na, 1, 'na', '.gt.')
    CALL B2XVSG(ncv, pl%te, 1, 'te', '.gt.')
    CALL B2XVSG(ncv, pl%ti, 1, 'ti', '.gt.')
  END IF
!
  mode = switch%b2tral_mode
!
! ..compute transport coefficients
!   ..compute differential classical transport coefficients
  CALL B2TQCA_DV(ncv, ns, switch, switchd, geo, geod, pl, pld, dv, dvd, &
&          rt, rtd, st_ext, vsa, vsad, hci, hcid, nbdirs)
!srv 01.07.09 20.09.11
  CALL B2TQCE_DV(ncv, switch, switchd, geo, geod, mpg, pl, pld, dv, dvd&
&          , hce, hced, sig, sigd, alf, alfd, nbdirs)
!srv 01.07.09 20.09.11
  CALL B2TQIN_DV(ncv, ns, nscx, iscx, switch, geo, geod, pl, pld, rt, &
&          rtd, sigin, sigind, nbdirs)
!xpb
  arg1 = ncv*ns
  CALL SFILL_NODIFF(arg1, switch%cthev, cthe, 1)
  arg1 = ncv*ns
  CALL SFILL_NODIFF(arg1, switch%cthiv, cthi, 1)
  DO nd=1,nbdirsmax
    dummyzerodiffd(nd) = 0.D0
  END DO
  CALL SFILL_DV(nfc, 1.0_R8, dummyzerodiffd, co%fllim_ki, cod%fllim_ki, &
&         1, nbdirs)
!srv 13.01.17 {
  DO nd=1,nbdirsmax
    dummyzerodiffd0(nd) = 0.D0
  END DO
  CALL SFILL_DV(nfc, 1.0_R8, dummyzerodiffd0, co%fllim_ke, cod%fllim_ke&
&         , 1, nbdirs)
  DO nd=1,nbdirsmax
    dummyzerodiffd1(nd) = 0.D0
  END DO
  CALL SFILL_DV(nfc, 1.0_R8, dummyzerodiffd1, co%fllim_al, cod%fllim_al&
&         , 1, nbdirs)
  DO nd=1,nbdirsmax
    dummyzerodiffd2(nd) = 0.D0
  END DO
  CALL SFILL_DV(ncv, 1.0_R8, dummyzerodiffd2, co%fllim_al_c, cod%&
&         fllim_al_c, 1, nbdirs)
  DO nd=1,nbdirs
!/abs((bb(:,:,0))/bb(:,:,3))          !iys 19.11.13 !srv 08.10.14 { !srv 13.01.17
    cod%alfx_c(nd, :) = alfd(nd, :, 0)
!/abs((bb(:,:,0))/bb(:,:,3))          !             }               !srv 13.01.17
    cod%sigx_c(nd, :) = sigd(nd, :, 0)
!wdk need to write general routine for volume interpolation like this...
!wdk intface_v? intface with mode switch?
    cod%hcix_c(nd, :) = hcid(nd, :, 0)
  END DO
  co%alfx_c(:) = alf(:, 0)
  co%sigx_c(:) = sig(:, 0)
  co%hcix_c(:) = hci(:, 0)
!   ..interpolate vsa to faces
  DO is=0,ns-1
    DO ifc=1,nfc
      temp = geo%fcvol(ifc, 1) + geo%fcvol(ifc, 2)
      DO nd=1,nbdirs
        vsaf_cld(nd, ifc, 0, is) = (geo%fcvol(ifc, 1)*vsad(nd, mpg%fccv(&
&         ifc, 1), 0, is)+geo%fcvol(ifc, 2)*vsad(nd, mpg%fccv(ifc, 2), 0&
&         , is))/temp
      END DO
      vsaf_cl(ifc, 0, is) = (geo%fcvol(ifc, 1)*vsa(mpg%fccv(ifc, 1), 0, &
&       is)+geo%fcvol(ifc, 2)*vsa(mpg%fccv(ifc, 2), 0, is))/temp
      temp = geo%fcvol(ifc, 1) + geo%fcvol(ifc, 2)
      DO nd=1,nbdirs
        vsaf_cld(nd, ifc, 1, is) = (geo%fcvol(ifc, 1)*vsad(nd, mpg%fccv(&
&         ifc, 1), 1, is)+geo%fcvol(ifc, 2)*vsad(nd, mpg%fccv(ifc, 2), 1&
&         , is))/temp
      END DO
      vsaf_cl(ifc, 1, is) = (geo%fcvol(ifc, 1)*vsa(mpg%fccv(ifc, 1), 1, &
&       is)+geo%fcvol(ifc, 2)*vsa(mpg%fccv(ifc, 2), 1, is))/temp
    END DO
  END DO
!   ..incorporate geometry with hz                                    !srv 09.01.01
  wrk = geo%fcs*geo%fchz
  DO ifc=1,nfc
    wrk1(ifc, 1) = geo%fcvol(ifc, 1)*geo%cvhz(mpg%fccv(ifc, 1))
    wrk1(ifc, 2) = geo%fcvol(ifc, 2)*geo%cvhz(mpg%fccv(ifc, 2))
  END DO
  DO nd=1,nbdirsmax
    cvsahzd(nd, :, :, :) = 0.D0
  END DO
  DO is=0,ns-1
!srv 01.07.05 {
    CALL B2TXCX_DV(ncv, nfc, mode, geo, mpg, wrk1, wrk, vsa(:, 0, is), &
&            vsad(:, :, 0, is), cvsahz(:, 0, is), cvsahzd(:, :, 0, is), &
&            nbdirs)
    CALL B2TXCY_DV(ncv, nfc, mode, geo, mpg, wrk1, wrk, vsa(:, 1, is), &
&            vsad(:, :, 1, is), cvsahz(:, 1, is), cvsahzd(:, :, 1, is), &
&            nbdirs)
  END DO
!srv 01.07.05 }
!srv 09.01.01
!   ..incorporate geometry
  arg1 = nfc*2*ns*ns
  DO nd=1,nbdirsmax
    dummyzerodiffd3(nd) = 0.D0
  END DO
  CALL SFILL_DV(arg1, 0.0_R8, dummyzerodiffd3, csigin, csigind, 1, &
&         nbdirs)
  DO nd=1,nbdirsmax
    cvsad(nd, :, :, :) = 0.D0
  END DO
  DO is=0,ns-1
    CALL B2TXCX_DV(ncv, nfc, mode, geo, mpg, geo%fcvol, geo%fcs, vsa(:, &
&            0, is), vsad(:, :, 0, is), cvsa(:, 0, is), cvsad(:, :, 0, &
&            is), nbdirs)
    CALL B2TXCY_DV(ncv, nfc, mode, geo, mpg, geo%fcvol, geo%fcs, vsa(:, &
&            1, is), vsad(:, :, 1, is), cvsa(:, 1, is), cvsad(:, :, 1, &
&            is), nbdirs)
    DO k=0,nscx-1
      is0 = iscx(k)
      IF (.NOT.is_neutral(is) .AND. NINT(zn(is)) .EQ. 1) THEN
!sv
        CALL B2TXCX_DV(ncv, nfc, mode, geo, mpg, geo%fcvol, geo%fcs, &
&                sigin(:, 0, is, k), sigind(:, :, 0, is, k), csigin(:, 0&
&                , is, is0), csigind(:, :, 0, is, is0), nbdirs)
!sv 01.07.99
!sv
        CALL B2TXCY_DV(ncv, nfc, mode, geo, mpg, geo%fcvol, geo%fcs, &
&                sigin(:, 1, is, k), sigind(:, :, 1, is, k), csigin(:, 1&
&                , is, is0), csigind(:, :, 1, is, is0), nbdirs)
!sv
      END IF
    END DO
  END DO
!
  DO nd=1,nbdirsmax
    chced(nd, :, :) = 0.D0
  END DO
  CALL B2TXCX_DV(ncv, nfc, mode, geo, mpg, geo%fcvol, geo%fcs, hce(:, 0)&
&          , hced(:, :, 0), chce(:, 0), chced(:, :, 0), nbdirs)
  CALL B2TXCY_DV(ncv, nfc, mode, geo, mpg, geo%fcvol, geo%fcs, hce(:, 1)&
&          , hced(:, :, 1), chce(:, 1), chced(:, :, 1), nbdirs)
  DO nd=1,nbdirsmax
    chcid(nd, :, :) = 0.D0
  END DO
  CALL B2TXCX_DV(ncv, nfc, mode, geo, mpg, geo%fcvol, geo%fcs, hci(:, 0)&
&          , hcid(:, :, 0), chci(:, 0), chcid(:, :, 0), nbdirs)
  CALL B2TXCY_DV(ncv, nfc, mode, geo, mpg, geo%fcvol, geo%fcs, hci(:, 1)&
&          , hcid(:, :, 1), chci(:, 1), chcid(:, :, 1), nbdirs)
  DO nd=1,nbdirsmax
    csigd(nd, :, :) = 0.D0
  END DO
  CALL B2TXCX_DV(ncv, nfc, mode, geo, mpg, geo%fcvol, geo%fcs, sig(:, 0)&
&          , sigd(:, :, 0), csig(:, 0), csigd(:, :, 0), nbdirs)
  CALL B2TXCY_DV(ncv, nfc, mode, geo, mpg, geo%fcvol, geo%fcs, sig(:, 1)&
&          , sigd(:, :, 1), csig(:, 1), csigd(:, :, 1), nbdirs)
  DO nd=1,nbdirsmax
    calfd(nd, :, :) = 0.D0
  END DO
  CALL B2TXCX_DV(ncv, nfc, -1, geo, mpg, geo%fcvol, geo%fcs, alf(:, 0), &
&          alfd(:, :, 0), calf(:, 0), calfd(:, :, 0), nbdirs)
  CALL B2TXCY_DV(ncv, nfc, -1, geo, mpg, geo%fcvol, geo%fcs, alf(:, 1), &
&          alfd(:, :, 1), calf(:, 1), calfd(:, :, 1), nbdirs)
!
  IF (switch%b2npmo_iout .NE. 0 .OR. switch%iout_b2wdat .EQ. 4) THEN
    DO is=0,ns-1
      WRITE(chns, '(i3.3)') is
      IF (.NOT.is_neutral(is)) THEN
        arg10(:) = 'b2trcl_cvsahzx'//chns
        CALL MY_OUT_US(70, nfc, 1, cvsahz(1, 0, is), arg10(:))
      END IF
    END DO
  END IF
  IF (switch%b2npht_iout .NE. 0 .OR. switch%iout_b2wdat .EQ. 4) THEN
    CALL MY_OUT_US(70, nfc, 1, chce(1, 0), 'b2trcl_chcex')
!        call my_out_us(70,nFc,1,chce(1,1),'b2trcl_chcey')
    CALL MY_OUT_US(70, nfc, 1, calf(1, 0), 'b2trcl_calfx')
!        call my_out_us(70,nFc,1,calf(1,1),'b2trcl_calfy')
    CALL MY_OUT_US(70, ncv, 0, co%alfx_c, 'b2trcl_alfx_c')
!srv 05.07.17
    CALL MY_OUT_US(70, nfc, 1, chci(1, 0), 'b2trcl_chcix')
!        call my_out_us(70,nFc,1,chci(1,1),'b2trcl_chciy')
  END IF
  IF ((switch%b2npp7_iout .NE. 0 .OR. switch%b2nppo_iout .NE. 0) .OR. &
&     switch%iout_b2wdat .EQ. 4) THEN
    CALL MY_OUT_US(70, nfc, 1, csig(1, 0), 'b2trcl_csigx')
!        call my_out_us(70,nFc,1,csig(1,1),'b2trcl_csigy')
    CALL MY_OUT_US(70, ncv, 0, co%sigx_c, 'b2trcl_sigx_c')
!srv 05.07.17
  END IF
  DO nd=1,nbdirs
!
!   ..call 21 moment routines
!   ..luciani
!srv 13.01.17 {
    cod%f_luc_ke(nd, :) = 0.D0
    cod%f_luc_ki(nd, :) = 0.D0
    cod%f_luc_et(nd, :) = 0.D0
    cod%f_luc_sg(nd, :) = 0.D0
!srv 13.01.17 }
    cod%f_luc_al(nd, :) = 0.D0
  END DO
  co%f_luc_ke = 1.0_R8
  co%f_luc_ki = 1.0_R8
  co%f_luc_et = 1.0_R8
  co%f_luc_sg = 1.0_R8
  co%f_luc_al = 1.0_R8
  IF (switch%lluciani .EQ. 1) THEN
! connection length formulation
!wdk There is implicit assumption here that flux tubes exist in the grid.
!wdk Need to generalize to truly unstructured grids; using fcConn at each
!wdk face?
!    ..interpolate te, ti and ne2 to cell faces
    wrk1 = 1.0_R8
    DO nd=1,nbdirsmax
      tefd(nd, :) = 0.D0
    END DO
    CALL INTFACE_DV(ncv, nfc, mpg%fccv, wrk1, pl%te, pld%te, tef, tefd, &
&             nbdirs)
    DO nd=1,nbdirsmax
      tifd(nd, :) = 0.D0
    END DO
    CALL INTFACE_DV(ncv, nfc, mpg%fccv, wrk1, pl%ti, pld%ti, tif, tifd, &
&             nbdirs)
    DO nd=1,nbdirsmax
      ne2fd(nd, :) = 0.D0
    END DO
    CALL INTFACE_DV(ncv, nfc, mpg%fccv, wrk1, dv%ne2, dvd%ne2, ne2f, &
&             ne2fd, nbdirs)
!lkw 12.10.22 {
    DO ifc=1,nfc
      IF (mpg%cvonclosedsurface(mpg%fccv(ifc, 1)) .OR. mpg%&
&         cvonclosedsurface(mpg%fccv(ifc, 2))) THEN
! compute flux limits
        IF (mpg%fcfs(ifc) .GT. 0) THEN
          connf = geo%fsconn(mpg%fcfs(ifc))
        ELSE
          ift = mpg%cvft(mpg%fccv(ifc, 1))
          IF (ift .GT. 0 .AND. ift .LE. mpg%nft) connf = geo%ftconn(ift)
        END IF
        IF (connf .GT. 0.0_R8) THEN
          temp = ev*ev*connf
          temp0 = tef(ifc)*tef(ifc)/(temp*ne2f(ifc))
          temp1 = 1.0/(7.5e16_R8*temp0+1.0_R8)
          DO nd=1,nbdirs
            cod%f_luc_ke(nd, ifc) = -(temp1*7.5e16_R8*(2*tef(ifc)*tefd(&
&             nd, ifc)-temp0*temp*ne2fd(nd, ifc))/((7.5e16_R8*temp0+&
&             1.0_R8)*temp*ne2f(ifc)))
          END DO
          co%f_luc_ke(ifc) = temp1
          temp0 = ev*ev*connf
          temp = tif(ifc)*tif(ifc)/(temp0*ne2f(ifc))
          temp1 = 1.0/(7.5e16_R8*temp+1.0_R8)
          DO nd=1,nbdirs
            cod%f_luc_ki(nd, ifc) = -(temp1*7.5e16_R8*(2*tif(ifc)*tifd(&
&             nd, ifc)-temp*temp0*ne2fd(nd, ifc))/((7.5e16_R8*temp+&
&             1.0_R8)*temp0*ne2f(ifc)))
          END DO
          co%f_luc_ki(ifc) = temp1
        END IF
        DO nd=1,nbdirs
          cod%f_luc_sg(nd, ifc) = cod%f_luc_ke(nd, ifc)
          cod%f_luc_al(nd, ifc) = cod%f_luc_ke(nd, ifc)
          cod%f_luc_et(nd, ifc) = cod%f_luc_ki(nd, ifc)
        END DO
        co%f_luc_sg(ifc) = co%f_luc_ke(ifc)
        co%f_luc_al(ifc) = co%f_luc_ke(ifc)
        co%f_luc_et(ifc) = co%f_luc_ki(ifc)
        DO is=0,ns-1
          IF (.NOT.is_neutral(is)) THEN
            DO nd=1,nbdirs
              cvsad(nd, ifc, 0, is) = co%f_luc_et(ifc)*cvsad(nd, ifc, 0&
&               , is) + cvsa(ifc, 0, is)*cod%f_luc_et(nd, ifc)
              cvsahzd(nd, ifc, 0, is) = co%f_luc_et(ifc)*cvsahzd(nd, ifc&
&               , 0, is) + cvsahz(ifc, 0, is)*cod%f_luc_et(nd, ifc)
              vsaf_cld(nd, ifc, 0, is) = co%f_luc_et(ifc)*vsaf_cld(nd, &
&               ifc, 0, is) + vsaf_cl(ifc, 0, is)*cod%f_luc_et(nd, ifc)
            END DO
            cvsa(ifc, 0, is) = cvsa(ifc, 0, is)*co%f_luc_et(ifc)
            cvsahz(ifc, 0, is) = cvsahz(ifc, 0, is)*co%f_luc_et(ifc)
            vsaf_cl(ifc, 0, is) = vsaf_cl(ifc, 0, is)*co%f_luc_et(ifc)
          END IF
        END DO
        DO nd=1,nbdirs
          chced(nd, ifc, 0) = co%f_luc_ke(ifc)*chced(nd, ifc, 0) + chce(&
&           ifc, 0)*cod%f_luc_ke(nd, ifc)
          csigd(nd, ifc, 0) = co%f_luc_sg(ifc)*csigd(nd, ifc, 0) + csig(&
&           ifc, 0)*cod%f_luc_sg(nd, ifc)
          calfd(nd, ifc, 0) = co%f_luc_al(ifc)*calfd(nd, ifc, 0) + calf(&
&           ifc, 0)*cod%f_luc_al(nd, ifc)
          chcid(nd, ifc, 0) = co%f_luc_ki(ifc)*chcid(nd, ifc, 0) + chci(&
&           ifc, 0)*cod%f_luc_ki(nd, ifc)
        END DO
        chce(ifc, 0) = chce(ifc, 0)*co%f_luc_ke(ifc)
        csig(ifc, 0) = csig(ifc, 0)*co%f_luc_sg(ifc)
        calf(ifc, 0) = calf(ifc, 0)*co%f_luc_al(ifc)
        chci(ifc, 0) = chci(ifc, 0)*co%f_luc_ki(ifc)
      END IF
    END DO
    DO icv=1,ncv
      IF (mpg%cvonclosedsurface(icv)) THEN
        ift = mpg%cvft(icv)
        IF (ift .GT. 0 .AND. ift .LE. mpg%nft) THEN
          temp0 = ev*ev*geo%ftconn(ift)
          temp = temp0*dv%ne2(icv)
          temp1 = pl%te(icv)*pl%te(icv)/temp
          temp2 = 1.0/(7.5e16_R8*temp1+1.0_R8)
          t0 = temp2
          DO nd=1,nbdirs
            t0d(nd) = -(temp2*7.5e16_R8*(2*pl%te(icv)*pld%te(nd, icv)-&
&             temp1*temp0*dvd%ne2(nd, icv))/((7.5e16_R8*temp1+1.0_R8)*&
&             temp))
            cod%sigx_c(nd, icv) = t0*cod%sigx_c(nd, icv) + co%sigx_c(icv&
&             )*t0d(nd)
            cod%alfx_c(nd, icv) = t0*cod%alfx_c(nd, icv) + co%alfx_c(icv&
&             )*t0d(nd)
          END DO
          co%sigx_c(icv) = co%sigx_c(icv)*t0
          co%alfx_c(icv) = co%alfx_c(icv)*t0
          temp0 = ev*ev*geo%ftconn(ift)
          temp = temp0*dv%ne2(icv)
          temp2 = pl%ti(icv)*pl%ti(icv)/temp
          temp1 = 1.0/(7.5e16_R8*temp2+1.0_R8)
          t0 = temp1
          DO nd=1,nbdirs
            t0d(nd) = -(temp1*7.5e16_R8*(2*pl%ti(icv)*pld%ti(nd, icv)-&
&             temp2*temp0*dvd%ne2(nd, icv))/((7.5e16_R8*temp2+1.0_R8)*&
&             temp))
            cod%hcix_c(nd, icv) = t0*cod%hcix_c(nd, icv) + co%hcix_c(icv&
&             )*t0d(nd)
          END DO
          co%hcix_c(icv) = co%hcix_c(icv)*t0
        END IF
      END IF
    END DO
  ELSE IF (switch%lluciani .EQ. 2) THEN
! SOLPS4.0 formulation
!    ..interpolate te, ti and ne2 to cell faces
    wrk1 = 1.0_R8
    DO nd=1,nbdirsmax
      tefd(nd, :) = 0.D0
    END DO
    CALL INTFACE_DV(ncv, nfc, mpg%fccv, wrk1, pl%te, pld%te, tef, tefd, &
&             nbdirs)
    DO nd=1,nbdirsmax
      tifd(nd, :) = 0.D0
    END DO
    CALL INTFACE_DV(ncv, nfc, mpg%fccv, wrk1, pl%ti, pld%ti, tif, tifd, &
&             nbdirs)
    DO nd=1,nbdirsmax
      ne2fd(nd, :) = 0.D0
    END DO
    CALL INTFACE_DV(ncv, nfc, mpg%fccv, wrk1, dv%ne2, dvd%ne2, ne2f, &
&             ne2fd, nbdirs)
!lkw 12.10.22 {
    DO ifc=1,nfc
      IF (mpg%cvonclosedsurface(mpg%fccv(ifc, 1)) .OR. mpg%&
&         cvonclosedsurface(mpg%fccv(ifc, 2))) THEN
        temp0 = ev*ev*ne2f(ifc)
        temp = tef(ifc)*tef(ifc)/temp0
        temp2 = 1.0/(0.3e16_R8*temp+1.0_R8)
        DO nd=1,nbdirs
          cod%f_luc_ke(nd, ifc) = -(temp2*0.3e16_R8*(2*tef(ifc)*tefd(nd&
&           , ifc)-temp*ev**2*ne2fd(nd, ifc))/((0.3e16_R8*temp+1.0_R8)*&
&           temp0))
          cod%f_luc_sg(nd, ifc) = cod%f_luc_ke(nd, ifc)
          cod%f_luc_al(nd, ifc) = cod%f_luc_ke(nd, ifc)
        END DO
        co%f_luc_ke(ifc) = temp2
        temp0 = ev*ev*ne2f(ifc)
        temp = tif(ifc)*tif(ifc)/temp0
        temp2 = 1.0/(0.3e16_R8*temp+1.0_R8)
        DO nd=1,nbdirs
          cod%f_luc_ki(nd, ifc) = -(temp2*0.3e16_R8*(2*tif(ifc)*tifd(nd&
&           , ifc)-temp*ev**2*ne2fd(nd, ifc))/((0.3e16_R8*temp+1.0_R8)*&
&           temp0))
          cod%f_luc_et(nd, ifc) = cod%f_luc_ki(nd, ifc)
        END DO
        co%f_luc_ki(ifc) = temp2
        co%f_luc_sg(ifc) = co%f_luc_ke(ifc)
        co%f_luc_al(ifc) = co%f_luc_ke(ifc)
        co%f_luc_et(ifc) = co%f_luc_ki(ifc)
        DO is=0,ns-1
          IF (.NOT.is_neutral(is)) THEN
            DO nd=1,nbdirs
              cvsad(nd, ifc, 0, is) = co%f_luc_et(ifc)*cvsad(nd, ifc, 0&
&               , is) + cvsa(ifc, 0, is)*cod%f_luc_et(nd, ifc)
              cvsahzd(nd, ifc, 0, is) = co%f_luc_et(ifc)*cvsahzd(nd, ifc&
&               , 0, is) + cvsahz(ifc, 0, is)*cod%f_luc_et(nd, ifc)
              vsaf_cld(nd, ifc, 0, is) = co%f_luc_et(ifc)*vsaf_cld(nd, &
&               ifc, 0, is) + vsaf_cl(ifc, 0, is)*cod%f_luc_et(nd, ifc)
            END DO
            cvsa(ifc, 0, is) = cvsa(ifc, 0, is)*co%f_luc_et(ifc)
            cvsahz(ifc, 0, is) = cvsahz(ifc, 0, is)*co%f_luc_et(ifc)
            vsaf_cl(ifc, 0, is) = vsaf_cl(ifc, 0, is)*co%f_luc_et(ifc)
          END IF
        END DO
        DO nd=1,nbdirs
          chced(nd, ifc, 0) = co%f_luc_ke(ifc)*chced(nd, ifc, 0) + chce(&
&           ifc, 0)*cod%f_luc_ke(nd, ifc)
          csigd(nd, ifc, 0) = co%f_luc_sg(ifc)*csigd(nd, ifc, 0) + csig(&
&           ifc, 0)*cod%f_luc_sg(nd, ifc)
          calfd(nd, ifc, 0) = co%f_luc_al(ifc)*calfd(nd, ifc, 0) + calf(&
&           ifc, 0)*cod%f_luc_al(nd, ifc)
          chcid(nd, ifc, 0) = co%f_luc_ki(ifc)*chcid(nd, ifc, 0) + chci(&
&           ifc, 0)*cod%f_luc_ki(nd, ifc)
        END DO
        chce(ifc, 0) = chce(ifc, 0)*co%f_luc_ke(ifc)
        csig(ifc, 0) = csig(ifc, 0)*co%f_luc_sg(ifc)
        calf(ifc, 0) = calf(ifc, 0)*co%f_luc_al(ifc)
        chci(ifc, 0) = chci(ifc, 0)*co%f_luc_ki(ifc)
      END IF
    END DO
    DO icv=1,ncv
      IF (mpg%cvonclosedsurface(icv)) THEN
        ift = mpg%cvft(icv)
        IF (ift .GT. 0 .AND. ift .LE. mpg%nft) THEN
          temp0 = ev*ev*dv%ne2(icv)
          temp2 = pl%te(icv)*pl%te(icv)/temp0
          temp1 = 1.0/(0.3e16_R8*temp2+1.0_R8)
          t0 = temp1
          DO nd=1,nbdirs
            t0d(nd) = -(temp1*0.3e16_R8*(2*pl%te(icv)*pld%te(nd, icv)-&
&             temp2*ev**2*dvd%ne2(nd, icv))/((0.3e16_R8*temp2+1.0_R8)*&
&             temp0))
            cod%sigx_c(nd, icv) = t0*cod%sigx_c(nd, icv) + co%sigx_c(icv&
&             )*t0d(nd)
            cod%alfx_c(nd, icv) = t0*cod%alfx_c(nd, icv) + co%alfx_c(icv&
&             )*t0d(nd)
          END DO
          co%sigx_c(icv) = co%sigx_c(icv)*t0
          co%alfx_c(icv) = co%alfx_c(icv)*t0
          temp0 = ev*ev*dv%ne2(icv)
          temp2 = pl%ti(icv)*pl%ti(icv)/temp0
          temp1 = 1.0/(0.3e16_R8*temp2+1.0_R8)
          t0 = temp1
          DO nd=1,nbdirs
            t0d(nd) = -(temp1*0.3e16_R8*(2*pl%ti(icv)*pld%ti(nd, icv)-&
&             temp2*ev**2*dvd%ne2(nd, icv))/((0.3e16_R8*temp2+1.0_R8)*&
&             temp0))
            cod%hcix_c(nd, icv) = t0*cod%hcix_c(nd, icv) + co%hcix_c(icv&
&             )*t0d(nd)
          END DO
          co%hcix_c(icv) = co%hcix_c(icv)*t0
        END IF
      END IF
    END DO
  ELSE IF (switch%lluciani .EQ. 3) THEN
! new formulation
!   .. plateau and banana correction for ion heat conduction          !lk 19.09.07 {
    DO nd=1,nbdirsmax
      tauiad(nd, :, :) = 0.D0
    END DO
    CALL B2TTIA_DV(ncv, ns, pl%ti, pld%ti, rt%rz2, rtd%rz2, dv%ne2, dvd%&
&            ne2, dv%lnlam, dvd%lnlam, tauia, tauiad, nbdirs)
!   .. calculate collisionality parameter nu_star
!lk 12.05.11{
    nu1 = 0.0_R8
    k1 = 0.58_R8
    nu2 = 0.0_R8
    k2 = 1.6_R8
    t1 = 4.0_R8*pi*eps0/qe/qe
    arg11 = 2.0_R8*pi
    result10 = SQRT(arg11)
    result2 = SQRT(ev)
    result3 = SQRT(me)
    t2 = 3.0_R8/(4.0_R8*result10)*t1*t1*ev*result2*result3
    arg12(:) = pl%te/ev
    temp3 = SQRT(arg12(:))
    result11 = temp3
    temp4 = ev*dv%lnlam*dv%ne2
    temp5 = pl%te*result11/temp4
    DO nd=1,nbdirs
      arg12d(nd, :) = pld%te(nd, :)/ev
      WHERE (arg12(:) .EQ. 0.D0) 
        result11d(nd, :) = 0.D0
      ELSEWHERE
        result11d(nd, :) = arg12d(nd, :)/(2.0*temp3)
      END WHERE
      taud(nd, :) = t2*(result11*pld%te(nd, :)+pl%te*result11d(nd, :)-&
&       temp5*(dv%ne2*ev*dvd%lnlam(nd, :)+ev*dv%lnlam*dvd%ne2(nd, :)))/&
&       temp4
    END DO
    tau = t2*temp5
    DO nd=1,nbdirsmax
      k1d(nd, :) = 0.D0
    END DO
    DO nd=1,nbdirsmax
      k2d(nd, :) = 0.D0
    END DO
    DO nd=1,nbdirsmax
      nu1d(nd, :) = 0.D0
    END DO
    DO nd=1,nbdirsmax
      nu2d(nd, :) = 0.D0
    END DO
    DO icv=1,ncv
      IF (mpg%cvonclosedsurface(icv)) THEN
        ift = mpg%cvft(icv)
        IF (ift .GT. 0 .AND. ift .LE. mpg%nft) THEN
          arg11 = pl%te(icv)/me
          temp2 = SQRT(arg11)
          DO nd=1,nbdirs
            arg11d(nd) = pld%te(nd, icv)/me
            IF (arg11 .EQ. 0.D0) THEN
              result12d(nd) = 0.D0
            ELSE
              result12d(nd) = arg11d(nd)/(2.0*temp2)
            END IF
            arg11d(nd) = pld%ti(nd, icv)/(mp*am(ismain))
          END DO
          result12 = temp2
          temp2 = 2.0_R8*pi*geo%fteps(ift)**1.5_R8
          temp0 = geo%ftconn(ift)/(temp2*tau(icv)*result12)
          DO nd=1,nbdirs
            nu1d(nd, icv) = -(temp0*(result12*taud(nd, icv)+tau(icv)*&
&             result12d(nd))/(tau(icv)*result12))
          END DO
          nu1(icv) = temp0
          temp0 = SQRT(nu1(icv))
          DO nd=1,nbdirs
            IF (nu1(icv) .EQ. 0.D0) THEN
              result1d(nd) = 0.D0
            ELSE
              result1d(nd) = nu1d(nd, icv)/(2.0*temp0)
            END IF
          END DO
          result1 = temp0
          arg13 = geo%fteps(ift)**3
          result2 = SQRT(arg13)
          temp2 = 1.0/(2.01_R8*result1+1.53_R8*nu1(icv)+1.0_R8)
          temp0 = 0.52_R8*(geo%fteps(ift)*geo%fteps(ift)*geo%fteps(ift))
          temp = 0.89_R8*result2*nu1(icv) + 1.0_R8
          temp6 = nu1(icv)/temp
          DO nd=1,nbdirs
            k1d(nd, icv) = temp0*(1.0-temp6*result2*0.89_R8)*nu1d(nd, &
&             icv)/temp - temp2*(2.01_R8*result1d(nd)+1.53_R8*nu1d(nd, &
&             icv))/(2.01_R8*result1+1.53_R8*nu1(icv)+1.0_R8)
          END DO
          k1(icv) = temp2 + temp0*temp6
          arg11 = pl%ti(icv)/(mp*am(ismain))
          temp2 = SQRT(arg11)
          DO nd=1,nbdirs
            IF (arg11 .EQ. 0.D0) THEN
              result12d(nd) = 0.D0
            ELSE
              result12d(nd) = arg11d(nd)/(2.0*temp2)
            END IF
          END DO
          result12 = temp2
          temp2 = 2.0_R8*pi*geo%fteps(ift)**1.5_R8
          temp6 = geo%ftconn(ift)/(temp2*tauia(icv, ismain)*result12)
          DO nd=1,nbdirs
            nu2d(nd, icv) = -(temp6*(result12*tauiad(nd, icv, ismain)+&
&             tauia(icv, ismain)*result12d(nd))/(tauia(icv, ismain)*&
&             result12))
          END DO
          nu2(icv) = temp6
          arg13 = geo%fteps(ift)
          result1 = SQRT(arg13)
          temp6 = SQRT(nu2(icv))
          DO nd=1,nbdirs
            IF (nu2(icv) .EQ. 0.D0) THEN
              result2d(nd) = 0.D0
            ELSE
              result2d(nd) = nu2d(nd, icv)/(2.0*temp6)
            END IF
          END DO
          result2 = temp6
          arg2 = geo%fteps(ift)**3
          result3 = SQRT(arg2)
          temp6 = (1.88_R8*result1-1.54_R8*geo%fteps(ift)+0.66_R8)/(&
&           1.03_R8*result2+0.31_R8*nu2(icv)+1.0_R8)
          temp0 = 1.17_R8*(geo%fteps(ift)*geo%fteps(ift)*geo%fteps(ift))
          temp = 0.74_R8*result3*nu2(icv) + 1.0_R8
          temp7 = nu2(icv)/temp
          DO nd=1,nbdirs
            k2d(nd, icv) = temp0*(1.0-temp7*result3*0.74_R8)*nu2d(nd, &
&             icv)/temp - temp6*(1.03_R8*result2d(nd)+0.31_R8*nu2d(nd, &
&             icv))/(1.03_R8*result2+0.31_R8*nu2(icv)+1.0_R8)
          END DO
          k2(icv) = temp6 + temp0*temp7
        END IF
      END IF
    END DO
!lk 19.09.07 }
!    ..interpolate te, ti and ne2 to cell faces
    wrk1 = 1.0_R8
    DO nd=1,nbdirsmax
      tefd(nd, :) = 0.D0
    END DO
    CALL INTFACE_DV(ncv, nfc, mpg%fccv, wrk1, pl%te, pld%te, tef, tefd, &
&             nbdirs)
    DO nd=1,nbdirsmax
      tifd(nd, :) = 0.D0
    END DO
    CALL INTFACE_DV(ncv, nfc, mpg%fccv, wrk1, pl%ti, pld%ti, tif, tifd, &
&             nbdirs)
    DO nd=1,nbdirsmax
      ne2fd(nd, :) = 0.D0
    END DO
    CALL INTFACE_DV(ncv, nfc, mpg%fccv, wrk1, dv%ne2, dvd%ne2, ne2f, &
&             ne2fd, nbdirs)
    DO nd=1,nbdirsmax
      taufd(nd, :) = 0.D0
    END DO
    CALL INTFACE_DV(ncv, nfc, mpg%fccv, wrk1, tau, taud, tauf, taufd, &
&             nbdirs)
    DO nd=1,nbdirsmax
      tauiafd(nd, :) = 0.D0
    END DO
    CALL INTFACE_DV(ncv, nfc, mpg%fccv, wrk1, tauia(:, ismain), tauiad(:&
&             , :, ismain), tauiaf, tauiafd, nbdirs)
!    ..compute flux limits at faces
!lkw 12.10.22 {
    DO ifc=1,nfc
!lkw 12.10.22 {
      IF (mpg%cvonclosedsurface(mpg%fccv(ifc, 1)) .OR. mpg%&
&         cvonclosedsurface(mpg%fccv(ifc, 2))) THEN
! parameters at faces
! compute conn and eps on the face
        IF (mpg%fcfs(ifc) .GT. 0) THEN
          connf = geo%fsconn(mpg%fcfs(ifc))
          epsf = 0.0_R8
          IF (mpg%cvonclosedsurface(mpg%fccv(ifc, 1))) THEN
            ift = mpg%cvft(mpg%fccv(ifc, 1))
            IF (ift .GT. 0 .AND. ift .LE. mpg%nft) epsf = epsf + geo%&
&               fteps(ift)
          END IF
          IF (mpg%cvonclosedsurface(mpg%fccv(ifc, 2))) THEN
            ift = mpg%cvft(mpg%fccv(ifc, 2))
            IF (ift .GT. 0 .AND. ift .LE. mpg%nft) epsf = epsf + geo%&
&               fteps(ift)
          END IF
          IF (mpg%cvonclosedsurface(mpg%fccv(ifc, 1)) .AND. mpg%&
&             cvonclosedsurface(mpg%fccv(ifc, 2))) epsf = 0.5_R8
        ELSE
          ift = mpg%cvft(mpg%fccv(ifc, 1))
          IF (ift .GT. 0 .AND. ift .LE. mpg%nft) THEN
            connf = geo%ftconn(ift)
            epsf = geo%fteps(ift)
          END IF
        END IF
        arg13 = tef(ifc)/me
        temp7 = SQRT(arg13)
        DO nd=1,nbdirs
          arg13d(nd) = tefd(nd, ifc)/me
          IF (arg13 .EQ. 0.D0) THEN
            result1d(nd) = 0.D0
          ELSE
            result1d(nd) = arg13d(nd)/(2.0*temp7)
          END IF
          arg13d(nd) = tifd(nd, ifc)/(mp*am(ismain))
        END DO
        result1 = temp7
        temp2 = 2.0_R8*pi*epsf**1.5_R8
        temp7 = connf/(temp2*tauf(ifc)*result1)
        DO nd=1,nbdirs
          nu1fd(nd) = -(temp7*(result1*taufd(nd, ifc)+tauf(ifc)*result1d&
&           (nd))/(tauf(ifc)*result1))
        END DO
        nu1f = temp7
        temp7 = SQRT(nu1f)
        DO nd=1,nbdirs
          IF (nu1f .EQ. 0.D0) THEN
            result1d(nd) = 0.D0
          ELSE
            result1d(nd) = nu1fd(nd)/(2.0*temp7)
          END IF
        END DO
        result1 = temp7
        arg13 = epsf**3
        result2 = SQRT(arg13)
        temp2 = 1.0/(2.01_R8*result1+1.53_R8*nu1f+1.0_R8)
        temp7 = 0.52_R8*(epsf*epsf*epsf)
        temp6 = 0.89_R8*result2*nu1f + 1.0_R8
        DO nd=1,nbdirs
          k1fd(nd) = temp7*(1.0-nu1f*result2*0.89_R8/temp6)*nu1fd(nd)/&
&           temp6 - temp2*(2.01_R8*result1d(nd)+1.53_R8*nu1fd(nd))/(&
&           2.01_R8*result1+1.53_R8*nu1f+1.0_R8)
        END DO
        k1f = temp2 + temp7*(nu1f/temp6)
        arg13 = tif(ifc)/(mp*am(ismain))
        temp7 = SQRT(arg13)
        DO nd=1,nbdirs
          IF (arg13 .EQ. 0.D0) THEN
            result1d(nd) = 0.D0
          ELSE
            result1d(nd) = arg13d(nd)/(2.0*temp7)
          END IF
        END DO
        result1 = temp7
        temp2 = 2.0_R8*pi*epsf**1.5_R8
        temp7 = connf/(temp2*tauiaf(ifc)*result1)
        DO nd=1,nbdirs
          nu2fd(nd) = -(temp7*(result1*tauiafd(nd, ifc)+tauiaf(ifc)*&
&           result1d(nd))/(tauiaf(ifc)*result1))
        END DO
        nu2f = temp7
! compute flux limits
        result1 = SQRT(epsf)
        temp7 = SQRT(nu2f)
        DO nd=1,nbdirs
          IF (nu2f .EQ. 0.D0) THEN
            result2d(nd) = 0.D0
          ELSE
            result2d(nd) = nu2fd(nd)/(2.0*temp7)
          END IF
        END DO
        result2 = temp7
        arg13 = epsf**3
        result3 = SQRT(arg13)
        temp7 = (1.88_R8*result1-1.54_R8*epsf+0.66_R8)/(1.03_R8*result2+&
&         0.31_R8*nu2f+1.0_R8)
        temp6 = 1.17_R8*(epsf*epsf*epsf)
        temp0 = 0.74_R8*result3*nu2f + 1.0_R8
        DO nd=1,nbdirs
          k2fd(nd) = temp6*(1.0-nu2f*result3*0.74_R8/temp0)*nu2fd(nd)/&
&           temp0 - temp7*(1.03_R8*result2d(nd)+0.31_R8*nu2fd(nd))/(&
&           1.03_R8*result2+0.31_R8*nu2f+1.0_R8)
        END DO
        k2f = temp7 + temp6*(nu2f/temp0)
        arg13 = epsf**3
        result1 = SQRT(arg13)
        temp7 = 0.58_R8*result1/k1f
        DO nd=1,nbdirs
          cod%f_luc_ke(nd, ifc) = -(temp7*k1fd(nd)/k1f)
        END DO
        co%f_luc_ke(ifc) = temp7
        arg13 = epsf**3
        result1 = SQRT(arg13)
        temp7 = 1.60_R8*result1/k2f
        DO nd=1,nbdirs
          cod%f_luc_ki(nd, ifc) = -(temp7*k2fd(nd)/k2f)
        END DO
        co%f_luc_ki(ifc) = temp7
        IF (connf .GT. 0.0_R8) THEN
          temp7 = connf*(ev*ev)
          temp6 = temp7*ne2f(ifc)
          temp0 = tif(ifc)*tif(ifc)/temp6
          temp = 15.12e16_R8*epsf**1.5_R8
          temp8 = temp*temp0 + 1.0_R8
          temp9 = connf*(ev*ev)
          temp10 = tif(ifc)*tif(ifc)/(temp9*ne2f(ifc))
          temp11 = switch%cvsa_mltpl/((15.12e16_R8*temp10+1.0_R8)*temp8)
          DO nd=1,nbdirs
            cod%f_luc_et(nd, ifc) = -(temp11*(temp8*15.12e16_R8*(2*tif(&
&             ifc)*tifd(nd, ifc)-temp10*temp9*ne2fd(nd, ifc))/(temp9*&
&             ne2f(ifc))+(15.12e16_R8*temp10+1.0_R8)*temp*(2*tif(ifc)*&
&             tifd(nd, ifc)-temp0*temp7*ne2fd(nd, ifc))/temp6)/((&
&             15.12e16_R8*temp10+1.0_R8)*temp8))
          END DO
          co%f_luc_et(ifc) = temp11
        ELSE
          DO nd=1,nbdirs
            cod%f_luc_et(nd, ifc) = 0.D0
          END DO
          co%f_luc_et(ifc) = switch%cvsa_mltpl
        END IF
        DO nd=1,nbdirs
          cod%f_luc_sg(nd, ifc) = cod%f_luc_ke(nd, ifc)
          cod%f_luc_al(nd, ifc) = cod%f_luc_ke(nd, ifc)
        END DO
        co%f_luc_sg(ifc) = co%f_luc_ke(ifc)
        co%f_luc_al(ifc) = co%f_luc_ke(ifc)
        DO is=0,ns-1
          IF (.NOT.is_neutral(is)) THEN
            DO nd=1,nbdirs
              cvsad(nd, ifc, 0, is) = co%f_luc_et(ifc)*cvsad(nd, ifc, 0&
&               , is) + cvsa(ifc, 0, is)*cod%f_luc_et(nd, ifc)
              cvsahzd(nd, ifc, 0, is) = co%f_luc_et(ifc)*cvsahzd(nd, ifc&
&               , 0, is) + cvsahz(ifc, 0, is)*cod%f_luc_et(nd, ifc)
              vsaf_cld(nd, ifc, 0, is) = co%f_luc_et(ifc)*vsaf_cld(nd, &
&               ifc, 0, is) + vsaf_cl(ifc, 0, is)*cod%f_luc_et(nd, ifc)
            END DO
            cvsa(ifc, 0, is) = cvsa(ifc, 0, is)*co%f_luc_et(ifc)
            cvsahz(ifc, 0, is) = cvsahz(ifc, 0, is)*co%f_luc_et(ifc)
            vsaf_cl(ifc, 0, is) = vsaf_cl(ifc, 0, is)*co%f_luc_et(ifc)
          END IF
        END DO
        DO nd=1,nbdirs
          chced(nd, ifc, 0) = co%f_luc_ke(ifc)*chced(nd, ifc, 0) + chce(&
&           ifc, 0)*cod%f_luc_ke(nd, ifc)
          csigd(nd, ifc, 0) = co%f_luc_sg(ifc)*csigd(nd, ifc, 0) + csig(&
&           ifc, 0)*cod%f_luc_sg(nd, ifc)
          calfd(nd, ifc, 0) = co%f_luc_al(ifc)*calfd(nd, ifc, 0) + calf(&
&           ifc, 0)*cod%f_luc_al(nd, ifc)
          chcid(nd, ifc, 0) = co%f_luc_ki(ifc)*chcid(nd, ifc, 0) + chci(&
&           ifc, 0)*cod%f_luc_ki(nd, ifc)
        END DO
        chce(ifc, 0) = chce(ifc, 0)*co%f_luc_ke(ifc)
        csig(ifc, 0) = csig(ifc, 0)*co%f_luc_sg(ifc)
        calf(ifc, 0) = calf(ifc, 0)*co%f_luc_al(ifc)
        chci(ifc, 0) = chci(ifc, 0)*co%f_luc_ki(ifc)
      END IF
    END DO
    DO icv=1,ncv
      IF (mpg%cvonclosedsurface(icv)) THEN
        ift = mpg%cvft(icv)
        IF (ift .GT. 0 .AND. ift .LE. mpg%nft) THEN
          arg13 = geo%fteps(ift)**3
          result1 = SQRT(arg13)
          temp11 = 0.58_R8*result1/k1(icv)
          t0 = temp11
          DO nd=1,nbdirs
            t0d(nd) = -(temp11*k1d(nd, icv)/k1(icv))
            cod%sigx_c(nd, icv) = t0*cod%sigx_c(nd, icv) + co%sigx_c(icv&
&             )*t0d(nd)
            cod%alfx_c(nd, icv) = t0*cod%alfx_c(nd, icv) + co%alfx_c(icv&
&             )*t0d(nd)
          END DO
          co%sigx_c(icv) = co%sigx_c(icv)*t0
          co%alfx_c(icv) = co%alfx_c(icv)*t0
          arg13 = geo%fteps(ift)**3
          result1 = SQRT(arg13)
          temp11 = 1.60_R8*result1/k2(icv)
          t0 = temp11
          DO nd=1,nbdirs
            t0d(nd) = -(temp11*k2d(nd, icv)/k2(icv))
            cod%hcix_c(nd, icv) = t0*cod%hcix_c(nd, icv) + co%hcix_c(icv&
&             )*t0d(nd)
          END DO
          co%hcix_c(icv) = co%hcix_c(icv)*t0
        END IF
      END IF
    END DO
  END IF
!   ..set strange velocities chve, chvi
  arg1 = nfc*2
  CALL SFILL_NODIFF(arg1, 0.0_R8, chve, 1)
  arg1 = nfc*2
  CALL SFILL_NODIFF(arg1, 0.0_R8, chvi, 1)
!
  IF (switch%b2npmo_iout .NE. 0 .OR. switch%iout_b2wdat .EQ. 4) THEN
    DO is=0,ns-1
      WRITE(chns, '(i3.3)') is
      IF (.NOT.is_neutral(is)) THEN
        arg14(:) = 'b2trcl_luciani_cvsahzx'//chns
        CALL MY_OUT_US(70, nfc, 1, cvsahz(1, 0, is), arg14(:))
      END IF
    END DO
  END IF
!        call my_out_us(70,nFc,1,cvsahz(1,1,is),
!     &              'b2trcl_luciani_cvsahzy'//chns)
  IF (switch%b2npht_iout .NE. 0 .OR. switch%iout_b2wdat .EQ. 4) THEN
    CALL MY_OUT_US(70, nfc, 1, chce(1, 0), &
&                   'b2trcl_luciani_chce_th')
!        call my_out_us(70,nFc,1,chce(1,1),'b2trcl_luciani_chcey')
    CALL MY_OUT_US(70, nfc, 1, calf(1, 0), &
&                   'b2trcl_luciani_calf_th')
    CALL MY_OUT_US(70, ncv, 0, co%alfx_c, 'b2trcl_luciani_alfx_c'&
&                  )
!srv 05.07.17
!        call my_out_us(70,nFc,1,calf(1,1),'b2trcl_luciani_calfy')
    CALL MY_OUT_US(70, nfc, 1, chci(1, 0), &
&                   'b2trcl_luciani_chci_th')
!        call my_out_us(70,nFc,1,chci(1,1),'b2trcl_luciani_chciy')
  END IF
  IF ((switch%b2npp7_iout .NE. 0 .OR. switch%b2nppo_iout .NE. 0) .OR. &
&     switch%iout_b2wdat .EQ. 4) THEN
    CALL MY_OUT_US(70, nfc, 1, csig(1, 0), &
&                   'b2trcl_luciani_csig_th')
!        call my_out_us(70,nFc,1,csig(1,1),'b2trcl_luciani_csigy')
    CALL MY_OUT_US(70, ncv, 0, co%sigx_c, &
&                   'b2trcl_luciani_sig_th_c')
!srv 05.07.17
  END IF
!
!   .. save chce(:,0) after applying Luciani
!srv 13.01.17
  DO nd=1,nbdirs
    wrkd(nd, :) = chced(nd, :, 0)
  END DO
  wrk = chce(:, 0)
!srv 16.06.08 }
!
  IF (switch%conductive_limit .NE. 0) THEN
!srv 16.06.08 {
!   .. pre-compute poloidal differences of te, ti
    DO nd=1,nbdirsmax
      dted(nd, :) = 0.D0
    END DO
    DO nd=1,nbdirsmax
      wrkvd(nd, :) = 0.D0
    END DO
    CALL DIFF_P_DV(ncv, nfc, nvx, 0, geo, mpg, mpgd, pl%te, pld%te, wrkv&
&            , wrkvd, dte, dted, nbdirs)
    DO nd=1,nbdirsmax
      dtid(nd, :) = 0.D0
    END DO
    CALL DIFF_P_DV(ncv, nfc, nvx, 0, geo, mpg, mpgd, pl%ti, pld%ti, wrkv&
&            , wrkvd, dti, dtid, nbdirs)
!   .. apply the conductive limit of parallel electron heat flux         !srv 03.06.03 {
    IF (cflim(0) .NE. 0.0_R8) THEN
      DO ifc=1,nfc
!sw 19oct2011, also in core for SOLPS4.3 comparison!!!
!            if(.not.on_closed_surface(ix,iy)) then                      !lk 06.05.07
        IF (switch%core_cond_limit .NE. 0 .OR. (.NOT.(mpg%&
&           cvonclosedsurface(mpg%fccv(ifc, 1)) .AND. mpg%&
&           cvonclosedsurface(mpg%fccv(ifc, 2))))) THEN
          temp2 = dv%ne(mpg%fccv(ifc, 1)) + dv%ne(mpg%fccv(ifc, 2))
          temp1 = co%chvemx(ifc)/2.0_R8
          DO nd=1,nbdirs
            flomxd(nd) = temp2*cod%chvemx(nd, ifc)/2.0_R8 + temp1*(dvd%&
&             ne(nd, mpg%fccv(ifc, 1))+dvd%ne(nd, mpg%fccv(ifc, 2)))
          END DO
          flomx = temp1*temp2
          IF (chce(ifc, 0)*dte(ifc) .GE. 0.) THEN
            DO nd=1,nbdirs
              abs0d(nd) = dte(ifc)*chced(nd, ifc, 0) + chce(ifc, 0)*dted&
&               (nd, ifc)
            END DO
            abs0 = chce(ifc, 0)*dte(ifc)
          ELSE
            DO nd=1,nbdirs
              abs0d(nd) = -(dte(ifc)*chced(nd, ifc, 0)+chce(ifc, 0)*dted&
&               (nd, ifc))
            END DO
            abs0 = -(chce(ifc, 0)*dte(ifc))
          END IF
          IF (pl%te(mpg%fccv(ifc, 1)) .LT. pl%te(mpg%fccv(ifc, 2))) THEN
            DO nd=1,nbdirs
              max1d(nd) = pld%te(nd, mpg%fccv(ifc, 2))
            END DO
            max1 = pl%te(mpg%fccv(ifc, 2))
          ELSE
            DO nd=1,nbdirs
              max1d(nd) = pld%te(nd, mpg%fccv(ifc, 1))
            END DO
            max1 = pl%te(mpg%fccv(ifc, 1))
          END IF
          temp11 = abs0/(b2trcl_cutlo+flomx*max1)
          t0 = temp11
          co%fllim_ke(ifc) = 1.0_R8/(1.0_R8+t0)
          DO nd=1,nbdirs
            t0d(nd) = (abs0d(nd)-temp11*(max1*flomxd(nd)+flomx*max1d(nd)&
&             ))/(b2trcl_cutlo+flomx*max1)
            cod%fllim_ke(nd, ifc) = -(t0d(nd)/(t0+1.0_R8)**2)
            chced(nd, ifc, 0) = co%fllim_ke(ifc)*chced(nd, ifc, 0) + &
&             chce(ifc, 0)*cod%fllim_ke(nd, ifc)
          END DO
          chce(ifc, 0) = chce(ifc, 0)*co%fllim_ke(ifc)
        END IF
      END DO
    END IF
!   .. apply the conductive limit of parallel ion heat flux
    IF (cflim(1) .NE. 0.0_R8) THEN
      DO ifc=1,nfc
!sw 19oct2011, also in core for SOLPS4.3 comparison!!!
!          if(.not.on_closed_surface(ix,iy)) then                           !lk 06.05.07
        IF (switch%core_cond_limit .NE. 0 .OR. (.NOT.(mpg%&
&           cvonclosedsurface(mpg%fccv(ifc, 1)) .AND. mpg%&
&           cvonclosedsurface(mpg%fccv(ifc, 2))))) THEN
          temp2 = dv%ni(mpg%fccv(ifc, 1), 0) + dv%ni(mpg%fccv(ifc, 2), 0&
&           )
          temp1 = co%chvimx(ifc)/2.0_R8
          DO nd=1,nbdirs
            flomxd(nd) = temp2*cod%chvimx(nd, ifc)/2.0_R8 + temp1*(dvd%&
&             ni(nd, mpg%fccv(ifc, 1), 0)+dvd%ni(nd, mpg%fccv(ifc, 2), 0&
&             ))
          END DO
          flomx = temp1*temp2
          IF (chci(ifc, 0)*dti(ifc) .GE. 0.) THEN
            DO nd=1,nbdirs
              abs1d(nd) = dti(ifc)*chcid(nd, ifc, 0) + chci(ifc, 0)*dtid&
&               (nd, ifc)
            END DO
            abs1 = chci(ifc, 0)*dti(ifc)
          ELSE
            DO nd=1,nbdirs
              abs1d(nd) = -(dti(ifc)*chcid(nd, ifc, 0)+chci(ifc, 0)*dtid&
&               (nd, ifc))
            END DO
            abs1 = -(chci(ifc, 0)*dti(ifc))
          END IF
          IF (pl%ti(mpg%fccv(ifc, 1)) .LT. pl%ti(mpg%fccv(ifc, 2))) THEN
            DO nd=1,nbdirs
              max2d(nd) = pld%ti(nd, mpg%fccv(ifc, 2))
            END DO
            max2 = pl%ti(mpg%fccv(ifc, 2))
          ELSE
            DO nd=1,nbdirs
              max2d(nd) = pld%ti(nd, mpg%fccv(ifc, 1))
            END DO
            max2 = pl%ti(mpg%fccv(ifc, 1))
          END IF
          temp11 = abs1/(b2trcl_cutlo+flomx*max2)
          t0 = temp11
          co%fllim_ki(ifc) = 1.0_R8/(1.0_R8+t0)
          DO nd=1,nbdirs
            t0d(nd) = (abs1d(nd)-temp11*(max2*flomxd(nd)+flomx*max2d(nd)&
&             ))/(b2trcl_cutlo+flomx*max2)
            cod%fllim_ki(nd, ifc) = -(t0d(nd)/(t0+1.0_R8)**2)
            chcid(nd, ifc, 0) = co%fllim_ki(ifc)*chcid(nd, ifc, 0) + &
&             chci(ifc, 0)*cod%fllim_ki(nd, ifc)
          END DO
          chci(ifc, 0) = chci(ifc, 0)*co%fllim_ki(ifc)
        END IF
      END DO
!wdk pragmatic approximation for cell center flux limits: based on interpolation
!wdk of face flux limit
      CALL INTCELL_DV(nfc, ncv, mpg, mpg%intcellp, co%fllim_ki, cod%&
&               fllim_ki, co%fllim_ki_c, cod%fllim_ki_c, nbdirs)
      DO icv=1,ncv
        IF (switch%core_cond_limit .NE. 0 .OR. (.NOT.mpg%&
&           cvonclosedsurface(icv))) THEN
          DO nd=1,nbdirs
            cod%hcix_c(nd, icv) = co%fllim_ki_c(icv)*cod%hcix_c(nd, icv)&
&             + co%hcix_c(icv)*cod%fllim_ki_c(nd, icv)
          END DO
          co%hcix_c(icv) = co%hcix_c(icv)*co%fllim_ki_c(icv)
        END IF
      END DO
    END IF
  ELSE
    DO nd=1,nbdirsmax
      wrkvd(nd, :) = 0.D0
    END DO
    DO nd=1,nbdirsmax
      dted(nd, :) = 0.D0
    END DO
  END IF
!   ..apply flux limit to calf                                           !srv 13.01.17 {
  IF (switch%b2sigp_style .NE. 2) THEN
    IF (cflim(0) .NE. 0.0_R8) THEN
      DO ifc=1,nfc
        IF (.NOT.(mpg%cvonclosedsurface(mpg%fccv(ifc, 1)) .AND. mpg%&
&           cvonclosedsurface(mpg%fccv(ifc, 2)))) THEN
          temp2 = dv%ne(mpg%fccv(ifc, 1)) + dv%ne(mpg%fccv(ifc, 2))
          temp1 = co%chvemx(ifc)/2.0_R8
          DO nd=1,nbdirs
            flomxd(nd) = temp2*cod%chvemx(nd, ifc)/2.0_R8 + temp1*(dvd%&
&             ne(nd, mpg%fccv(ifc, 1))+dvd%ne(nd, mpg%fccv(ifc, 2)))
          END DO
          flomx = temp1*temp2
          IF (wrk(ifc)*dte(ifc) .GE. 0.) THEN
            DO nd=1,nbdirs
              abs2d(nd) = dte(ifc)*wrkd(nd, ifc) + wrk(ifc)*dted(nd, ifc&
&               )
            END DO
            abs2 = wrk(ifc)*dte(ifc)
          ELSE
            DO nd=1,nbdirs
              abs2d(nd) = -(dte(ifc)*wrkd(nd, ifc)+wrk(ifc)*dted(nd, ifc&
&               ))
            END DO
            abs2 = -(wrk(ifc)*dte(ifc))
          END IF
          IF (pl%te(mpg%fccv(ifc, 1)) .LT. pl%te(mpg%fccv(ifc, 2))) THEN
            DO nd=1,nbdirs
              max3d(nd) = pld%te(nd, mpg%fccv(ifc, 2))
            END DO
            max3 = pl%te(mpg%fccv(ifc, 2))
          ELSE
            DO nd=1,nbdirs
              max3d(nd) = pld%te(nd, mpg%fccv(ifc, 1))
            END DO
            max3 = pl%te(mpg%fccv(ifc, 1))
          END IF
          temp11 = abs2/(b2trcl_cutlo+flomx*max3)
          t0 = temp11
          co%fllim_al(ifc) = 1.0_R8/(1.0_R8+t0)
          DO nd=1,nbdirs
            t0d(nd) = (abs2d(nd)-temp11*(max3*flomxd(nd)+flomx*max3d(nd)&
&             ))/(b2trcl_cutlo+flomx*max3)
            cod%fllim_al(nd, ifc) = -(t0d(nd)/(t0+1.0_R8)**2)
!srv 13.01.17
            calfd(nd, ifc, 0) = co%fllim_al(ifc)*calfd(nd, ifc, 0) + &
&             calf(ifc, 0)*cod%fllim_al(nd, ifc)
          END DO
          calf(ifc, 0) = calf(ifc, 0)*co%fllim_al(ifc)
        END IF
      END DO
!wdk pragmatic approximation for cell center flux limits: based on interpolation
!wdk of face flux limit
      CALL INTCELL_DV(nfc, ncv, mpg, mpg%intcellp, co%fllim_al, cod%&
&               fllim_al, co%fllim_al_c, cod%fllim_al_c, nbdirs)
      DO icv=1,ncv
        IF (.NOT.mpg%cvonclosedsurface(icv)) THEN
          DO nd=1,nbdirs
            cod%alfx_c(nd, icv) = co%fllim_al_c(icv)*cod%alfx_c(nd, icv)&
&             + co%alfx_c(icv)*cod%fllim_al_c(nd, icv)
          END DO
          co%alfx_c(icv) = co%alfx_c(icv)*co%fllim_al_c(icv)
        END IF
      END DO
    END IF
  ELSE IF (cflim(3) .NE. 0.0_R8) THEN
!   ..apply flux limit to calf at cell faces
    DO ifc=1,nfc
      IF (.NOT.(mpg%cvonclosedsurface(mpg%fccv(ifc, 1)) .AND. mpg%&
&         cvonclosedsurface(mpg%fccv(ifc, 2)))) THEN
        IF (geo%fcpbs(ifc) .GE. 0.) THEN
          abs3 = geo%fcpbs(ifc)
        ELSE
          abs3 = -geo%fcpbs(ifc)
        END IF
        arg11 = (pl%te(mpg%fccv(ifc, 1))+pl%te(mpg%fccv(ifc, 2)))/2.0_R8&
&         /me
        temp2 = SQRT(arg11)
        DO nd=1,nbdirs
          arg11d(nd) = (pld%te(nd, mpg%fccv(ifc, 1))+pld%te(nd, mpg%fccv&
&           (ifc, 2)))/(2.0_R8*me)
          IF (arg11 .EQ. 0.D0) THEN
            result12d(nd) = 0.D0
          ELSE
            result12d(nd) = arg11d(nd)/(2.0*temp2)
          END IF
        END DO
        result12 = temp2
        temp2 = dv%ne(mpg%fccv(ifc, 1)) + dv%ne(mpg%fccv(ifc, 2))
        DO nd=1,nbdirs
          jemaxd(nd) = qe*abs3*(temp2*result12d(nd)/2.0_R8+result12*(dvd&
&           %ne(nd, mpg%fccv(ifc, 1))+dvd%ne(nd, mpg%fccv(ifc, 2)))/&
&           2.0_R8)
        END DO
        jemax = qe*abs3*(result12/2.0_R8*temp2)
        IF (calf(ifc, 0)*dte(ifc) .GE. 0.) THEN
          DO nd=1,nbdirs
            abs4d(nd) = dte(ifc)*calfd(nd, ifc, 0) + calf(ifc, 0)*dted(&
&             nd, ifc)
          END DO
          abs4 = calf(ifc, 0)*dte(ifc)
        ELSE
          DO nd=1,nbdirs
            abs4d(nd) = -(dte(ifc)*calfd(nd, ifc, 0)+calf(ifc, 0)*dted(&
&             nd, ifc))
          END DO
          abs4 = -(calf(ifc, 0)*dte(ifc))
        END IF
        temp11 = b2trcl_cutlo + cflim(3)*jemax
        t0 = abs4/temp11
        co%fllim_al(ifc) = 1.0_R8/(1.0_R8+t0)
        DO nd=1,nbdirs
          t0d(nd) = (abs4d(nd)-abs4*cflim(3)*jemaxd(nd)/temp11)/temp11
          cod%fllim_al(nd, ifc) = -(t0d(nd)/(t0+1.0_R8)**2)
!srv 13.01.17
          calfd(nd, ifc, 0) = co%fllim_al(ifc)*calfd(nd, ifc, 0) + calf(&
&           ifc, 0)*cod%fllim_al(nd, ifc)
        END DO
        calf(ifc, 0) = calf(ifc, 0)*co%fllim_al(ifc)
      END IF
    END DO
!   ..apply flux limit to alfx_c at cell centers
    CALL GRADC_P_DV(ncv, nfc, nvx, 0, geo, geod, mpg, mpgd, pl%te, pld%&
&             te, wrkv, wrkvd, gtec, gtecd, nbdirs)
    DO icv=1,ncv
      IF (.NOT.mpg%cvonclosedsurface(icv)) THEN
        arg11 = pl%te(icv)/me
        temp2 = SQRT(arg11)
        result12 = temp2
        temp11 = qe*geo%cvbb(icv, 0)
        DO nd=1,nbdirs
          arg11d(nd) = pld%te(nd, icv)/me
          IF (arg11 .EQ. 0.D0) THEN
            result12d(nd) = 0.D0
          ELSE
            result12d(nd) = arg11d(nd)/(2.0*temp2)
          END IF
          jemaxd(nd) = temp11*(dv%ne(icv)*result12d(nd)+result12*dvd%ne(&
&           nd, icv))/geo%cvbb(icv, 3)
        END DO
        jemax = temp11*(result12*dv%ne(icv)/geo%cvbb(icv, 3))
        temp11 = b2trcl_cutlo + cflim(3)*jemax
        temp2 = co%alfx_c(icv)*gtec(icv)/temp11
        DO nd=1,nbdirs
          x1d(nd) = (gtec(icv)*cod%alfx_c(nd, icv)+co%alfx_c(icv)*gtecd(&
&           nd, icv)-temp2*cflim(3)*jemaxd(nd))/temp11
        END DO
        x1 = temp2
        IF (x1 .GE. 0.) THEN
          DO nd=1,nbdirs
            t0d(nd) = x1d(nd)
          END DO
          t0 = x1
        ELSE
          DO nd=1,nbdirs
            t0d(nd) = -x1d(nd)
          END DO
          t0 = -x1
        END IF
        co%fllim_al_c(icv) = 1.0_R8/(1.0_R8+t0)
        DO nd=1,nbdirs
          cod%fllim_al_c(nd, icv) = -(t0d(nd)/(t0+1.0_R8)**2)
!iyv 19.11.13 !srv 08.10.14
          cod%alfx_c(nd, icv) = co%fllim_al_c(icv)*cod%alfx_c(nd, icv) +&
&           co%alfx_c(icv)*cod%fllim_al_c(nd, icv)
        END DO
        co%alfx_c(icv) = co%alfx_c(icv)*co%fllim_al_c(icv)
      END IF
    END DO
  END IF
!   ..apply flux limit to cvsa
  cflmv = cflim(2)
  DO is=0,ns-1
    CALL B2TLMV_DV(ncv, nfc, nvx, is, cflmv, switch, switchd, geo, geod&
&            , mpg, mpgd, pl%na(:, is), pld%na(:, :, is), pl%ti, pld%ti&
&            , pl%ua(:, is), pld%ua(:, :, is), vsaf_cl(:, 0, is), &
&            vsaf_cld(:, :, 0, is), cvsa(:, 0, is), cvsad(:, :, 0, is), &
&            cvsahz(:, 0, is), cvsahzd(:, :, 0, is), fllimvisc(:, is), &
&            nbdirs)
  END DO
  DO nd=1,nbdirsmax
    dabs0d(nd, :) = 0.D0
  END DO
  DO nd=1,nbdirs
    WHERE (rt%rza(:, ismain)*qe*geo%cvbb(:, 3) .GE. 0.) dabs0d(nd, :) = &
&       qe*geo%cvbb(:, 3)*rtd%rza(nd, :, ismain)
  END DO
  WHERE (rt%rza(:, ismain)*qe*geo%cvbb(:, 3) .GE. 0.) dabs0 = rt%rza(:, &
&     ismain)*qe*geo%cvbb(:, 3)
  DO nd=1,nbdirs
    WHERE (.NOT.rt%rza(:, ismain)*qe*geo%cvbb(:, 3) .GE. 0.) dabs0d(nd, &
&     :) = -(qe*geo%cvbb(:, 3)*rtd%rza(nd, :, ismain))
  END DO
  WHERE (.NOT.rt%rza(:, ismain)*qe*geo%cvbb(:, 3) .GE. 0.) dabs0 = -(rt%&
&     rza(:, ismain)*qe*geo%cvbb(:, 3))
  arg15(:) = 2.0_R8*pl%ti*(am(ismain)*mp)
  temp12 = SQRT(arg15(:))
  result13 = temp12
  wrkc = result13/dabs0
  DO nd=1,nbdirsmax
    cdktd(nd, :, :) = 0.D0
  END DO
  DO nd=1,nbdirs
!   ..computation conductivity of kt due to classical parallel current
!wdk  current model: conductivity ~ sigx*rhol**2/(am(ismain)*mp)
    arg15d(nd, :) = mp*2.0_R8*am(ismain)*pld%ti(nd, :)
    WHERE (arg15(:) .EQ. 0.D0) 
      result13d(nd, :) = 0.D0
    ELSEWHERE
      result13d(nd, :) = arg15d(nd, :)/(2.0*temp12)
    END WHERE
    wrkcd(nd, :) = (result13d(nd, :)-result13*dabs0d(nd, :)/dabs0)/dabs0
    wrkcd(nd, :) = geo%cvbb(:, 3)**2*(wrkc**2*cod%sigx_c(nd, :)+co%&
&     sigx_c*2*wrkc*wrkcd(nd, :))/(am(ismain)*mp)
    cdktd(nd, :, 1) = 0.D0
    cod%sigx_kt(nd, :) = wrkcd(nd, :)
    cvsa_cld(nd, :, :, :) = cvsad(nd, :, :, :)
!srv 09.01.01
    cvsahz_cld(nd, :, :, :) = cvsahzd(nd, :, :, :)
  END DO
  wrkc = co%sigx_c*wrkc**2*geo%cvbb(:, 3)**2/(am(ismain)*mp)
  CALL B2TXCX_DV(ncv, nfc, mode, geo, mpg, geo%fcvol, geo%fcs, wrkc, &
&          wrkcd, cdkt(:, 0), cdktd(:, :, 0), nbdirs)
  DO nd=1,nbdirs
    cdktd(nd, :, 0) = switch%b2tfhi_fsigkt*cdktd(nd, :, 0) + cdkt(:, 0)*&
&     switchd%b2tfhi_fsigkt(nd)
  END DO
  cdkt(:, 0) = cdkt(:, 0)*switch%b2tfhi_fsigkt
  cdkt(:, 1) = 0.0_R8
  co%sigx_kt = wrkc
!   ..save the classical transport coefficients
  csig_cl = csig
  calf_cl = calf
  cvsa_cl = cvsa
  cvsahz_cl = cvsahz
!
  IF (switch%b2npmo_iout .NE. 0 .OR. switch%iout_b2wdat .EQ. 4) THEN
    DO is=0,ns-1
      WRITE(chns, '(i3.3)') is
      arg16(:) = 'b2trcl_luciani_fllim_cvsahz_th'//chns
      CALL MY_OUT_US(70, nfc, 1, cvsahz(1, 0, is), arg16(:))
    END DO
  END IF
!        call my_out_us(70,nFc,1,cvsahz(1,1,is),
!     &              'b2trcl_luciani_fllim_cvsahzy'//chns)
  IF (switch%b2npht_iout .NE. 0 .OR. switch%iout_b2wdat .EQ. 4) THEN
    CALL MY_OUT_US(70, nfc, 1, chce(1, 0), &
&                   'b2trcl_luciani_fllim_chce_th')
!        call my_out_us(70,nFc,1,chce(1,1),'b2trcl_luciani_fllim_chcey')
    CALL MY_OUT_US(70, nfc, 1, calf(1, 0), &
&                   'b2trcl_luciani_fllim_calf_th')
!        call my_out_us(70,nFc,1,calf(1,1),'b2trcl_luciani_fllim_calfy')
    CALL MY_OUT_US(70, ncv, 0, co%alfx_c, &
&                   'b2trcl_luciani_fllim_alf_th_c')
!srv 05.07.17
    CALL MY_OUT_US(70, nfc, 1, chci(1, 0), &
&                   'b2trcl_luciani_fllim_chci_th')
!        call my_out_us(70,nFc,1,chci(1,1),'b2trcl_luciani_fllim_chciy')
  END IF
!srv 17.06.08 }
!
  IF (switch%b2trcl_iout .NE. 0) THEN
!srv 17.06.08 {
    DO is=0,ns-1
      WRITE(chns, '(i3.3)') is
      arg17(:) = 'cl_cvsa_th'//chns
      CALL MY_OUT_US(70, nfc, 1, cvsa(1, 0, is), arg17(:))
      arg18(:) = 'cl_cvsa_r'//chns
      CALL MY_OUT_US(70, nfc, 1, cvsa(1, 1, is), arg18(:))
      arg19(:) = 'cl_cvsahz_th'//chns
      CALL MY_OUT_US(70, nfc, 1, cvsahz(1, 0, is), arg19(:))
      arg110(:) = 'cl_cvsahz_r'//chns
      CALL MY_OUT_US(70, nfc, 1, cvsahz(1, 1, is), arg110(:))
      arg111(:) = 'cl_cvsa_cl_th'//chns
      CALL MY_OUT_US(70, nfc, 1, cvsa_cl(1, 0, is), arg111(:))
      arg19(:) = 'cl_cvsa_cl_r'//chns
      CALL MY_OUT_US(70, nfc, 1, cvsa_cl(1, 1, is), arg19(:))
      arg111(:) = 'cl_cvsahz_clx'//chns
      CALL MY_OUT_US(70, nfc, 1, cvsahz_cl(1, 0, is), arg111(:))
      arg111(:) = 'cl_cvsahz_cly'//chns
      CALL MY_OUT_US(70, nfc, 1, cvsahz_cl(1, 1, is), arg111(:))
      arg112(:) = 'cl_cthe'//chns
      CALL MY_OUT_US(70, ncv, 0, cthe(1, is), arg112(:))
      arg112(:) = 'cl_cthi'//chns
      CALL MY_OUT_US(70, ncv, 0, cthi(1, is), arg112(:))
      DO is0=0,ns-1
        WRITE(chns0, '(i3.3)') is0
        arg19(:) = 'cl_csigin_th'//chns//'_'//chns0
        CALL MY_OUT_US(70, nfc, 1, csigin(1, 0, is, is0), arg19(:&
&                       ))
        arg110(:) = 'cl_csigin_r'//chns//'_'//chns0
        CALL MY_OUT_US(70, nfc, 1, csigin(1, 1, is, is0), arg110(&
&                       :))
      END DO
    END DO
    CALL MY_OUT_US(70, nfc, 1, chce(1, 0), 'cl_chce_th')
    CALL MY_OUT_US(70, nfc, 1, chce(1, 1), 'cl_chce_r')
    CALL MY_OUT_US(70, nfc, 1, chci(1, 0), 'cl_chci_th')
    CALL MY_OUT_US(70, nfc, 1, chci(1, 1), 'cl_chci_r')
    CALL MY_OUT_US(70, nfc, 1, chve(1, 0), 'cl_chve_th')
    CALL MY_OUT_US(70, nfc, 1, chve(1, 1), 'cl_chve_r')
    CALL MY_OUT_US(70, nfc, 1, chvi(1, 0), 'cl_chvi_th')
    CALL MY_OUT_US(70, nfc, 1, chvi(1, 1), 'cl_chvi_r')
    CALL MY_OUT_US(70, nfc, 1, csig(1, 0), 'cl_csig_th')
    CALL MY_OUT_US(70, nfc, 1, csig(1, 1), 'cl_csig_r')
    CALL MY_OUT_US(70, nfc, 1, calf(1, 0), 'cl_calf_th')
    CALL MY_OUT_US(70, nfc, 1, calf(1, 1), 'cl_calf_r')
    CALL MY_OUT_US(70, ncv, 0, co%sigx_c, 'cl_sig_th_c')
!srv 05.07.17
    CALL MY_OUT_US(70, ncv, 0, co%alfx_c, 'cl_alf_th_c')
!srv 05.07.17
  END IF
!
! ..return
  ncall_b2trcl = ncall_b2trcl + 1
  CALL SUBEND()
  RETURN
END SUBROUTINE B2TRCL_DV

!
!
!
!
!
!
!
!
!
!
!
!-----------------------------------------------------------------------
!.specification
!
!srv 23.11.10
!srv 09.01.01 03.06.03
!xpb
!srv 09.01.01
!xpb
SUBROUTINE B2TRCL_NODIFF(ncv, nfc, nvx, ns, nscx, iscx, ismain, switch, &
& geo, mpg, pl, dv, rt, co, st_ext, cvsahz, cvsa, chce, chve, chci, chvi&
& , csig, calf, cdkt, csigin, cthe, cthi, vsaf_cl, cvsa_cl, cvsahz_cl, &
& fllimvisc, csig_cl, calf_cl)
  USE B2MOD_TYPES
  USE B2MOD_CONSTANTS
  USE B2MOD_B2CMPA_DIFFV
  USE B2MOD_B2CMPT_DIFFV
  USE B2MOD_SWITCHES_DIFFV
  USE B2US_GEO_DIFFV
  USE B2US_MAP_DIFFV
  USE B2US_PLASMA_DIFFV
  USE B2MOD_AD_DIFFV, ONLY : ncall_b2trcl, b2trcl_cutlo
! csc The following are not necessary for computation but are needed
!     for adjoint AD to avoid side-effect variables
  USE B2MOD_MATH_DIFFV, ONLY : b2mod_math_initialised, cutlo, cutll, &
& small_r4_constant
  USE B2MOD_AD_DIFFV, ONLY : my_out_folder, ncall_b2tlnl, ncall_b2tlmv, &
& ncall_b2tqin, ncall_b2tqce, ncall_b2tqca, ncall_b2ttia
  USE B2MOD_SUBSYS
!  Hint: nCv should be the size of dimension 1 of array arg1
!  Hint: nCv should be the size of dimension 1 of array result1
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!
!-----------------------------------------------------------------------
!.end b2trcl
!
!   ..input arguments (unchanged on exit)
  INTEGER, INTENT(IN) :: ncv, nfc, nvx, ns, nscx, ismain
  INTEGER, INTENT(IN) :: iscx(0:nscx-1)
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(MAPPING), INTENT(IN) :: mpg
  TYPE(B2PLASMA), INTENT(IN) :: pl
  TYPE(B2DERIVATIVES), INTENT(INOUT) :: dv
  TYPE(B2RATES), INTENT(IN) :: rt
  TYPE(B2STATEEXT), INTENT(IN) :: st_ext
!   ..output arguments (unspecified on entry)
  TYPE(B2COEFF), INTENT(INOUT) :: co
!wdk to consider: create an output struct co0 of type (B2Coeff) for this?
!xpb
!srv 09.01.01
!srv 09.01.01
  REAL(kind=r8) :: cvsa(nfc, 0:1, 0:ns-1), chce(nfc, 0:1), chve(nfc, 0:1&
& ), chci(nfc, 0:1), chvi(nfc, 0:1), csig(nfc, 0:1), calf(nfc, 0:1), &
& cdkt(nfc, 0:1), csigin(nfc, 0:1, 0:ns-1, 0:ns-1), cthe(ncv, 0:ns-1), &
& cthi(ncv, 0:ns-1), vsaf_cl(nfc, 0:1, 0:ns-1), cvsa_cl(nfc, 0:1, 0:ns-1&
& ), cvsahz_cl(nfc, 0:1, 0:ns-1), fllimvisc(nfc, 0:ns-1), cvsahz(nfc, 0:&
& 1, 0:ns-1), csig_cl(nfc, 0:1), calf_cl(nfc, 0:1)
!   ..common blocks
!-----------------------------------------------------------------------
!.documentation
!
!  1. purpose
!
!     B2TRCL computes the classical transport coefficients, including
!     geometric factors such as vol/hx**2 and vol/hy**2.
!
!
!  3. description (see also routine b2cdca)
!
!     This routine computes the following discrete classical transport
!     coefficients.
!     - cvsa: viscosity.
!     - chce: electron thermal conductivity.
!     - chve: electron thermal strange velocity.
!     - chci: atom thermal conductivity.
!     - chvi: atom thermal strange velocity.
!     - csig: electrical conductivity.
!     - csigin: ion-neutral conductivity.
!     - calf: thermo-electric coefficient.
!
!     The local differential transport coefficients, defined on cells,
!     are obtained by calls to b2tqca and b2tqce. To compute from these
!     the discrete transport coefficients involves multiplication by
!     geometric factors (vol, vol/hx**2, vol/hy**2), and, usually,
!     interpolation to cell faces.
!
!-----------------------------------------------------------------------
!.declarations
!
!   ..local variables
  INTEGER :: k, is, is0, icv, ifc, ift, mode
!srv 17.06.08
  CHARACTER(len=3) :: chns, chns0
!srv 13.01.17
  REAL(kind=r8) :: cflmv, jemax
!srv 03.06.03
  REAL(kind=r8) :: t0, dte(nfc), dti(nfc), flomx, connf, epsf
!lk 19.09.07
  REAL(kind=r8) :: tauia(ncv, 0:ns-1), nu2(ncv), k2(ncv)
!lk 12.05.11
!lk 12.05.11
  REAL(kind=r8) :: tau(ncv), nu1(ncv), k1(ncv), t1, t2
!srv 01.07.99 09.01.01
  REAL(kind=r8) :: hce(ncv, 0:1), sig(ncv, 0:1), alf(ncv, 0:1), vsa(ncv&
& , 0:1, 0:ns-1), hci(ncv, 0:1), sigin(ncv, 0:1, 0:ns-1, 0:nscx-1), wrk(&
& nfc), wrk1(nfc, 2), wrkv(nvx), wrkc(ncv), tef(nfc), tif(nfc), ne2f(nfc&
& ), k1f, k2f, gtec(ncv), nu1f, nu2f, tauf(nfc), tauiaf(nfc)
  EXTERNAL XERTST, XERRAB, SFILL_NODIFF, smin, smax
!   ..procedures
!srv 22.04.16
  REAL(kind=r8) :: smin, smax
!xpb
!lk 19.09.07
  EXTERNAL B2TQCA_NODIFF, B2TQCE_NODIFF, B2TQIN_NODIFF, B2TXCX_NODIFF, &
&     B2TXCY_NODIFF, B2TLMV_NODIFF, IPGETI, IPGETR, B2TTIA_NODIFF
  EXTERNAL B2XVSG
  INTRINSIC NINT
  INTRINSIC SQRT
  INTRINSIC ABS
  INTRINSIC MAX
  REAL(r8) :: x1
  REAL(kind=r8) :: abs0
  REAL(kind=r8) :: abs1
  REAL(kind=r8) :: abs2
  REAL(kind=r8) :: abs3
  REAL(kind=r8) :: abs4
  REAL(kind=r8), DIMENSION(nCv) :: dabs0
  REAL(r8) :: max1
  REAL(r8) :: max2
  REAL(r8) :: max3
  REAL(kind=r8) :: result1
  REAL(kind=r8) :: result2
  INTEGER :: arg1
  CHARACTER(len=14) :: arg10
  REAL(r8) :: arg11
  REAL(kind=r8) :: result10
  REAL(kind=r8) :: result3
  REAL(r8), DIMENSION(nCv) :: arg12
  REAL(r8), DIMENSION(nCv) :: result11
  REAL(r8) :: result12
  REAL(kind=r8) :: arg13
  REAL(kind=r8) :: arg2
  CHARACTER(len=22) :: arg14
  REAL(r8), DIMENSION(nCv) :: arg15
  REAL(kind=r8), DIMENSION(nCv) :: result13
  CHARACTER(len=30) :: arg16
  CHARACTER(len=10) :: arg17
  CHARACTER(len=9) :: arg18
  CHARACTER(len=12) :: arg19
  CHARACTER(len=11) :: arg110
  CHARACTER(len=13) :: arg111
  CHARACTER(len=7) :: arg112
!   ..initialisation
!
!-----------------------------------------------------------------------
!.computation
!
! ..preliminaries
!   ..subprogram start-up calls
  CALL SUBINI('b2trcl')
!   ..test nCv, nFc, ns
  CALL XERTST(0 .LT. ncv .AND. 0 .LT. nfc, 'faulty argument nCv, nFc')
  CALL XERTST(1 .LE. ns, 'faulty argument ns')
!   ..set internal parameters on first call
! The following switches are only used in 'WG-TODO' blocks, i.e. not yet converted to wide grid functionality
!        call ipgetr ('b2tfhe_vis_par',vis_par)
!        call ipgeti ('b2trcl_integral_modeling', integral_modeling)  !srv 01.11.11
!        call ipgeti ('b2trcl_lthf21',lthf21)
!       call ipgeti ('b2trcl_lvis21',lvis21)
!#ifdef NO_21
!        call xertst (lthf21.eq.0.and.lvis21.eq.0,
!     &   'Recompile without NO_21 option for 21-moment approach!')
!#endif
!        call xertst (.not.(lvis21.ne.0.and.vis_par.ne.0.0_R8),
!     &   '21-moment viscosity already includes parallel viscosity!')
!   ..extensive tests on first few calls
  IF (ncall_b2trcl .LT. 3) THEN
!    ..test bb
    CALL B2XVSG(ncv, geo%cvbb(1, 3), 1, 'bb3', '.gt.')
!    ..test sign of vol
    CALL B2XVSG(ncv, geo%cvvol, 1, 'vol', '.gt.')
!    ..test range of cvQgam, fcQgam
    result1 = smin(ncv, geo%cvqgam(1, 1), 1)
    result2 = smax(ncv, geo%cvqgam(1, 1), 1)
    CALL XERTST(-1.0_R8 .LT. result1 .AND. result2 .LT. 1.0_R8, &
&         'faulty argument range cvQgam(,1)')
    result1 = smin(ncv, geo%cvqgam(1, 0), 1)
    result2 = smax(ncv, geo%cvqgam(1, 0), 1)
    CALL XERTST(0.0_R8 .LT. result1 .AND. result2 .LE. 1.0_R8, &
&         'faulty argument range cvQgam(,0)')
    result1 = smin(nfc, geo%fcqgam(1, 1), 1)
    result2 = smax(nfc, geo%fcqgam(1, 1), 1)
    CALL XERTST(-1.0_R8 .LT. result1 .AND. result2 .LT. 1.0_R8, &
&         'faulty argument range fcQgam(,1)')
    result1 = smin(nfc, geo%fcqgam(1, 0), 1)
    result2 = smax(nfc, geo%fcqgam(1, 0), 1)
    CALL XERTST(0.0_R8 .LT. result1 .AND. result2 .LE. 1.0_R8, &
&         'faulty argument range fcQgam(,0)')
!    ..test sign of na, te, ti
    arg1 = ncv*ns
    CALL B2XVSG(arg1, pl%na, 1, 'na', '.gt.')
    CALL B2XVSG(ncv, pl%te, 1, 'te', '.gt.')
    CALL B2XVSG(ncv, pl%ti, 1, 'ti', '.gt.')
  END IF
!
  mode = switch%b2tral_mode
!
! ..compute transport coefficients
!   ..compute differential classical transport coefficients
  CALL B2TQCA_NODIFF(ncv, ns, switch, geo, pl, dv, rt, st_ext, vsa, hci)
!srv 01.07.09 20.09.11
  CALL B2TQCE_NODIFF(ncv, switch, geo, mpg, pl, dv, hce, sig, alf)
!srv 01.07.09 20.09.11
  CALL B2TQIN_NODIFF(ncv, ns, nscx, iscx, switch, geo, pl, rt, sigin)
!xpb
  arg1 = ncv*ns
  CALL SFILL_NODIFF(arg1, switch%cthev, cthe, 1)
  arg1 = ncv*ns
  CALL SFILL_NODIFF(arg1, switch%cthiv, cthi, 1)
  CALL SFILL_NODIFF(nfc, 1.0_R8, co%fllim_ki, 1)
!srv 13.01.17 {
  CALL SFILL_NODIFF(nfc, 1.0_R8, co%fllim_ke, 1)
  CALL SFILL_NODIFF(nfc, 1.0_R8, co%fllim_al, 1)
  CALL SFILL_NODIFF(ncv, 1.0_R8, co%fllim_al_c, 1)
!/abs((bb(:,:,0))/bb(:,:,3))          !iys 19.11.13 !srv 08.10.14 { !srv 13.01.17
  co%alfx_c(:) = alf(:, 0)
!/abs((bb(:,:,0))/bb(:,:,3))          !             }               !srv 13.01.17
  co%sigx_c(:) = sig(:, 0)
!wdk need to write general routine for volume interpolation like this...
!wdk intface_v? intface with mode switch?
  co%hcix_c(:) = hci(:, 0)
!   ..interpolate vsa to faces
  DO is=0,ns-1
    DO ifc=1,nfc
      vsaf_cl(ifc, 0, is) = (geo%fcvol(ifc, 1)*vsa(mpg%fccv(ifc, 1), 0, &
&       is)+geo%fcvol(ifc, 2)*vsa(mpg%fccv(ifc, 2), 0, is))/(geo%fcvol(&
&       ifc, 1)+geo%fcvol(ifc, 2))
      vsaf_cl(ifc, 1, is) = (geo%fcvol(ifc, 1)*vsa(mpg%fccv(ifc, 1), 1, &
&       is)+geo%fcvol(ifc, 2)*vsa(mpg%fccv(ifc, 2), 1, is))/(geo%fcvol(&
&       ifc, 1)+geo%fcvol(ifc, 2))
    END DO
  END DO
!   ..incorporate geometry with hz                                    !srv 09.01.01
  wrk = geo%fcs*geo%fchz
  DO ifc=1,nfc
    wrk1(ifc, 1) = geo%fcvol(ifc, 1)*geo%cvhz(mpg%fccv(ifc, 1))
    wrk1(ifc, 2) = geo%fcvol(ifc, 2)*geo%cvhz(mpg%fccv(ifc, 2))
  END DO
  DO is=0,ns-1
!srv 01.07.05 {
    CALL B2TXCX_NODIFF(ncv, nfc, mode, geo, mpg, wrk1, wrk, vsa(:, 0, is&
&                ), cvsahz(:, 0, is))
    CALL B2TXCY_NODIFF(ncv, nfc, mode, geo, mpg, wrk1, wrk, vsa(:, 1, is&
&                ), cvsahz(:, 1, is))
  END DO
!srv 01.07.05 }
!srv 09.01.01
!   ..incorporate geometry
  arg1 = nfc*2*ns*ns
  CALL SFILL_NODIFF(arg1, 0.0_R8, csigin, 1)
  DO is=0,ns-1
    CALL B2TXCX_NODIFF(ncv, nfc, mode, geo, mpg, geo%fcvol, geo%fcs, vsa&
&                (:, 0, is), cvsa(:, 0, is))
    CALL B2TXCY_NODIFF(ncv, nfc, mode, geo, mpg, geo%fcvol, geo%fcs, vsa&
&                (:, 1, is), cvsa(:, 1, is))
    DO k=0,nscx-1
      is0 = iscx(k)
      IF (.NOT.is_neutral(is) .AND. NINT(zn(is)) .EQ. 1) THEN
!sv
        CALL B2TXCX_NODIFF(ncv, nfc, mode, geo, mpg, geo%fcvol, geo%fcs&
&                    , sigin(:, 0, is, k), csigin(:, 0, is, is0))
!sv 01.07.99
!sv
        CALL B2TXCY_NODIFF(ncv, nfc, mode, geo, mpg, geo%fcvol, geo%fcs&
&                    , sigin(:, 1, is, k), csigin(:, 1, is, is0))
!sv
      END IF
    END DO
  END DO
!
  CALL B2TXCX_NODIFF(ncv, nfc, mode, geo, mpg, geo%fcvol, geo%fcs, hce(:&
&              , 0), chce(:, 0))
  CALL B2TXCY_NODIFF(ncv, nfc, mode, geo, mpg, geo%fcvol, geo%fcs, hce(:&
&              , 1), chce(:, 1))
  CALL B2TXCX_NODIFF(ncv, nfc, mode, geo, mpg, geo%fcvol, geo%fcs, hci(:&
&              , 0), chci(:, 0))
  CALL B2TXCY_NODIFF(ncv, nfc, mode, geo, mpg, geo%fcvol, geo%fcs, hci(:&
&              , 1), chci(:, 1))
  CALL B2TXCX_NODIFF(ncv, nfc, mode, geo, mpg, geo%fcvol, geo%fcs, sig(:&
&              , 0), csig(:, 0))
  CALL B2TXCY_NODIFF(ncv, nfc, mode, geo, mpg, geo%fcvol, geo%fcs, sig(:&
&              , 1), csig(:, 1))
  CALL B2TXCX_NODIFF(ncv, nfc, -1, geo, mpg, geo%fcvol, geo%fcs, alf(:, &
&              0), calf(:, 0))
  CALL B2TXCY_NODIFF(ncv, nfc, -1, geo, mpg, geo%fcvol, geo%fcs, alf(:, &
&              1), calf(:, 1))
!
  IF (switch%b2npmo_iout .NE. 0 .OR. switch%iout_b2wdat .EQ. 4) THEN
    DO is=0,ns-1
      WRITE(chns, '(i3.3)') is
      IF (.NOT.is_neutral(is)) THEN
        arg10(:) = 'b2trcl_cvsahzx'//chns
        CALL MY_OUT_US(70, nfc, 1, cvsahz(1, 0, is), arg10(:))
      END IF
    END DO
  END IF
  IF (switch%b2npht_iout .NE. 0 .OR. switch%iout_b2wdat .EQ. 4) THEN
    CALL MY_OUT_US(70, nfc, 1, chce(1, 0), 'b2trcl_chcex')
!        call my_out_us(70,nFc,1,chce(1,1),'b2trcl_chcey')
    CALL MY_OUT_US(70, nfc, 1, calf(1, 0), 'b2trcl_calfx')
!        call my_out_us(70,nFc,1,calf(1,1),'b2trcl_calfy')
    CALL MY_OUT_US(70, ncv, 0, co%alfx_c, 'b2trcl_alfx_c')
!srv 05.07.17
    CALL MY_OUT_US(70, nfc, 1, chci(1, 0), 'b2trcl_chcix')
!        call my_out_us(70,nFc,1,chci(1,1),'b2trcl_chciy')
  END IF
  IF ((switch%b2npp7_iout .NE. 0 .OR. switch%b2nppo_iout .NE. 0) .OR. &
&     switch%iout_b2wdat .EQ. 4) THEN
    CALL MY_OUT_US(70, nfc, 1, csig(1, 0), 'b2trcl_csigx')
!        call my_out_us(70,nFc,1,csig(1,1),'b2trcl_csigy')
    CALL MY_OUT_US(70, ncv, 0, co%sigx_c, 'b2trcl_sigx_c')
!srv 05.07.17
  END IF
!
!   ..call 21 moment routines
!   ..luciani
!srv 13.01.17 {
  co%f_luc_ke = 1.0_R8
  co%f_luc_ki = 1.0_R8
  co%f_luc_et = 1.0_R8
  co%f_luc_sg = 1.0_R8
!srv 13.01.17 }
  co%f_luc_al = 1.0_R8
  IF (switch%lluciani .EQ. 1) THEN
! connection length formulation
!wdk There is implicit assumption here that flux tubes exist in the grid.
!wdk Need to generalize to truly unstructured grids; using fcConn at each
!wdk face?
!    ..interpolate te, ti and ne2 to cell faces
    wrk1 = 1.0_R8
    CALL INTFACE(ncv, nfc, mpg%fccv, wrk1, pl%te, tef)
    CALL INTFACE(ncv, nfc, mpg%fccv, wrk1, pl%ti, tif)
    CALL INTFACE(ncv, nfc, mpg%fccv, wrk1, dv%ne2, ne2f)
!lkw 12.10.22 {
    DO ifc=1,nfc
      IF (mpg%cvonclosedsurface(mpg%fccv(ifc, 1)) .OR. mpg%&
&         cvonclosedsurface(mpg%fccv(ifc, 2))) THEN
! compute flux limits
        IF (mpg%fcfs(ifc) .GT. 0) THEN
          connf = geo%fsconn(mpg%fcfs(ifc))
        ELSE
          ift = mpg%cvft(mpg%fccv(ifc, 1))
          IF (ift .GT. 0 .AND. ift .LE. mpg%nft) connf = geo%ftconn(ift)
        END IF
        IF (connf .GT. 0.0_R8) THEN
          co%f_luc_ke(ifc) = 1.0_R8/(1.0_R8+7.5e16_R8*(tef(ifc)/ev)**2/(&
&           connf*ne2f(ifc)))
          co%f_luc_ki(ifc) = 1.0_R8/(1.0_R8+7.5e16_R8*(tif(ifc)/ev)**2/(&
&           connf*ne2f(ifc)))
        END IF
        co%f_luc_sg(ifc) = co%f_luc_ke(ifc)
        co%f_luc_al(ifc) = co%f_luc_ke(ifc)
        co%f_luc_et(ifc) = co%f_luc_ki(ifc)
        DO is=0,ns-1
          IF (.NOT.is_neutral(is)) THEN
            cvsa(ifc, 0, is) = cvsa(ifc, 0, is)*co%f_luc_et(ifc)
            cvsahz(ifc, 0, is) = cvsahz(ifc, 0, is)*co%f_luc_et(ifc)
            vsaf_cl(ifc, 0, is) = vsaf_cl(ifc, 0, is)*co%f_luc_et(ifc)
          END IF
        END DO
        chce(ifc, 0) = chce(ifc, 0)*co%f_luc_ke(ifc)
        csig(ifc, 0) = csig(ifc, 0)*co%f_luc_sg(ifc)
        calf(ifc, 0) = calf(ifc, 0)*co%f_luc_al(ifc)
        chci(ifc, 0) = chci(ifc, 0)*co%f_luc_ki(ifc)
      END IF
    END DO
    DO icv=1,ncv
      IF (mpg%cvonclosedsurface(icv)) THEN
        ift = mpg%cvft(icv)
        IF (ift .GT. 0 .AND. ift .LE. mpg%nft) THEN
          t0 = 1.0_R8/(1.0_R8+7.5e16_R8*(pl%te(icv)/ev)**2/(geo%ftconn(&
&           ift)*dv%ne2(icv)))
          co%sigx_c(icv) = co%sigx_c(icv)*t0
          co%alfx_c(icv) = co%alfx_c(icv)*t0
          t0 = 1.0_R8/(1.0_R8+7.5e16_R8*(pl%ti(icv)/ev)**2/(geo%ftconn(&
&           ift)*dv%ne2(icv)))
          co%hcix_c(icv) = co%hcix_c(icv)*t0
        END IF
      END IF
    END DO
  ELSE IF (switch%lluciani .EQ. 2) THEN
! SOLPS4.0 formulation
!    ..interpolate te, ti and ne2 to cell faces
    wrk1 = 1.0_R8
    CALL INTFACE(ncv, nfc, mpg%fccv, wrk1, pl%te, tef)
    CALL INTFACE(ncv, nfc, mpg%fccv, wrk1, pl%ti, tif)
    CALL INTFACE(ncv, nfc, mpg%fccv, wrk1, dv%ne2, ne2f)
!lkw 12.10.22 {
    DO ifc=1,nfc
      IF (mpg%cvonclosedsurface(mpg%fccv(ifc, 1)) .OR. mpg%&
&         cvonclosedsurface(mpg%fccv(ifc, 2))) THEN
        co%f_luc_ke(ifc) = 1.0_R8/(1.0_R8+0.3e16_R8*(tef(ifc)/ev)**2/&
&         ne2f(ifc))
        co%f_luc_ki(ifc) = 1.0_R8/(1.0_R8+0.3e16_R8*(tif(ifc)/ev)**2/&
&         ne2f(ifc))
        co%f_luc_sg(ifc) = co%f_luc_ke(ifc)
        co%f_luc_al(ifc) = co%f_luc_ke(ifc)
        co%f_luc_et(ifc) = co%f_luc_ki(ifc)
        DO is=0,ns-1
          IF (.NOT.is_neutral(is)) THEN
            cvsa(ifc, 0, is) = cvsa(ifc, 0, is)*co%f_luc_et(ifc)
            cvsahz(ifc, 0, is) = cvsahz(ifc, 0, is)*co%f_luc_et(ifc)
            vsaf_cl(ifc, 0, is) = vsaf_cl(ifc, 0, is)*co%f_luc_et(ifc)
          END IF
        END DO
        chce(ifc, 0) = chce(ifc, 0)*co%f_luc_ke(ifc)
        csig(ifc, 0) = csig(ifc, 0)*co%f_luc_sg(ifc)
        calf(ifc, 0) = calf(ifc, 0)*co%f_luc_al(ifc)
        chci(ifc, 0) = chci(ifc, 0)*co%f_luc_ki(ifc)
      END IF
    END DO
    DO icv=1,ncv
      IF (mpg%cvonclosedsurface(icv)) THEN
        ift = mpg%cvft(icv)
        IF (ift .GT. 0 .AND. ift .LE. mpg%nft) THEN
          t0 = 1.0_R8/(1.0_R8+0.3e16_R8*(pl%te(icv)/ev)**2/dv%ne2(icv))
          co%sigx_c(icv) = co%sigx_c(icv)*t0
          co%alfx_c(icv) = co%alfx_c(icv)*t0
          t0 = 1.0_R8/(1.0_R8+0.3e16_R8*(pl%ti(icv)/ev)**2/dv%ne2(icv))
          co%hcix_c(icv) = co%hcix_c(icv)*t0
        END IF
      END IF
    END DO
  ELSE IF (switch%lluciani .EQ. 3) THEN
! new formulation
!   .. plateau and banana correction for ion heat conduction          !lk 19.09.07 {
    CALL B2TTIA_NODIFF(ncv, ns, pl%ti, rt%rz2, dv%ne2, dv%lnlam, tauia)
!   .. calculate collisionality parameter nu_star
!lk 12.05.11{
    nu1 = 0.0_R8
    k1 = 0.58_R8
    nu2 = 0.0_R8
    k2 = 1.6_R8
    t1 = 4.0_R8*pi*eps0/qe/qe
    arg11 = 2.0_R8*pi
    result10 = SQRT(arg11)
    result2 = SQRT(ev)
    result3 = SQRT(me)
    t2 = 3.0_R8/(4.0_R8*result10)*t1*t1*ev*result2*result3
    arg12(:) = pl%te/ev
    result11 = SQRT(arg12(:))
    tau = t2/dv%lnlam*pl%te/ev*result11/dv%ne2
    DO icv=1,ncv
      IF (mpg%cvonclosedsurface(icv)) THEN
        ift = mpg%cvft(icv)
        IF (ift .GT. 0 .AND. ift .LE. mpg%nft) THEN
          arg11 = pl%te(icv)/me
          result12 = SQRT(arg11)
          nu1(icv) = geo%ftconn(ift)/(tau(icv)*result12*2.0_R8*pi*geo%&
&           fteps(ift)**1.5_R8)
          result1 = SQRT(nu1(icv))
          arg13 = geo%fteps(ift)**3
          result2 = SQRT(arg13)
          k1(icv) = 1.0_R8/(1.0_R8+2.01_R8*result1+1.53_R8*nu1(icv)) + &
&           0.52_R8*geo%fteps(ift)**3*nu1(icv)/(1.0_R8+0.89_R8*result2*&
&           nu1(icv))
          arg11 = pl%ti(icv)/(mp*am(ismain))
          result12 = SQRT(arg11)
          nu2(icv) = geo%ftconn(ift)/(tauia(icv, ismain)*result12*2.0_R8&
&           *pi*geo%fteps(ift)**1.5_R8)
          arg13 = geo%fteps(ift)
          result1 = SQRT(arg13)
          result2 = SQRT(nu2(icv))
          arg2 = geo%fteps(ift)**3
          result3 = SQRT(arg2)
          k2(icv) = (0.66_R8+1.88_R8*result1-1.54_R8*geo%fteps(ift))/(&
&           1.0_R8+1.03_R8*result2+0.31_R8*nu2(icv)) + 1.17_R8*geo%fteps&
&           (ift)**3*nu2(icv)/(1.0_R8+0.74_R8*result3*nu2(icv))
        END IF
      END IF
    END DO
!lk 19.09.07 }
!    ..interpolate te, ti and ne2 to cell faces
    wrk1 = 1.0_R8
    CALL INTFACE(ncv, nfc, mpg%fccv, wrk1, pl%te, tef)
    CALL INTFACE(ncv, nfc, mpg%fccv, wrk1, pl%ti, tif)
    CALL INTFACE(ncv, nfc, mpg%fccv, wrk1, dv%ne2, ne2f)
    CALL INTFACE(ncv, nfc, mpg%fccv, wrk1, tau, tauf)
    CALL INTFACE(ncv, nfc, mpg%fccv, wrk1, tauia(:, ismain), tauiaf)
!    ..compute flux limits at faces
!lkw 12.10.22 {
    DO ifc=1,nfc
!lkw 12.10.22 {
      IF (mpg%cvonclosedsurface(mpg%fccv(ifc, 1)) .OR. mpg%&
&         cvonclosedsurface(mpg%fccv(ifc, 2))) THEN
! parameters at faces
! compute conn and eps on the face
        IF (mpg%fcfs(ifc) .GT. 0) THEN
          connf = geo%fsconn(mpg%fcfs(ifc))
          epsf = 0.0_R8
          IF (mpg%cvonclosedsurface(mpg%fccv(ifc, 1))) THEN
            ift = mpg%cvft(mpg%fccv(ifc, 1))
            IF (ift .GT. 0 .AND. ift .LE. mpg%nft) epsf = epsf + geo%&
&               fteps(ift)
          END IF
          IF (mpg%cvonclosedsurface(mpg%fccv(ifc, 2))) THEN
            ift = mpg%cvft(mpg%fccv(ifc, 2))
            IF (ift .GT. 0 .AND. ift .LE. mpg%nft) epsf = epsf + geo%&
&               fteps(ift)
          END IF
          IF (mpg%cvonclosedsurface(mpg%fccv(ifc, 1)) .AND. mpg%&
&             cvonclosedsurface(mpg%fccv(ifc, 2))) epsf = 0.5_R8
        ELSE
          ift = mpg%cvft(mpg%fccv(ifc, 1))
          IF (ift .GT. 0 .AND. ift .LE. mpg%nft) THEN
            connf = geo%ftconn(ift)
            epsf = geo%fteps(ift)
          END IF
        END IF
        arg13 = tef(ifc)/me
        result1 = SQRT(arg13)
        nu1f = connf/(tauf(ifc)*result1*2.0_R8*pi*epsf**1.5_R8)
        result1 = SQRT(nu1f)
        arg13 = epsf**3
        result2 = SQRT(arg13)
        k1f = 1.0_R8/(1.0_R8+2.01_R8*result1+1.53_R8*nu1f) + 0.52_R8*&
&         epsf**3*nu1f/(1.0_R8+0.89_R8*result2*nu1f)
        arg13 = tif(ifc)/(mp*am(ismain))
        result1 = SQRT(arg13)
        nu2f = connf/(tauiaf(ifc)*result1*2.0_R8*pi*epsf**1.5_R8)
! compute flux limits
        result1 = SQRT(epsf)
        result2 = SQRT(nu2f)
        arg13 = epsf**3
        result3 = SQRT(arg13)
        k2f = (0.66_R8+1.88_R8*result1-1.54_R8*epsf)/(1.0_R8+1.03_R8*&
&         result2+0.31_R8*nu2f) + 1.17_R8*epsf**3*nu2f/(1.0_R8+0.74_R8*&
&         result3*nu2f)
        arg13 = epsf**3
        result1 = SQRT(arg13)
        co%f_luc_ke(ifc) = 1.0_R8/k1f*0.58_R8*result1
        arg13 = epsf**3
        result1 = SQRT(arg13)
        co%f_luc_ki(ifc) = 1.0_R8/k2f*1.60_R8*result1
        IF (connf .GT. 0.0_R8) THEN
          co%f_luc_et(ifc) = switch%cvsa_mltpl/(1.0_R8+15.12e16_R8/connf&
&           *(tif(ifc)/ev)**2/ne2f(ifc))/(1.0_R8+15.12e16_R8*epsf**&
&           1.5_R8/connf*(tif(ifc)/ev)**2/ne2f(ifc))
        ELSE
          co%f_luc_et(ifc) = switch%cvsa_mltpl
        END IF
        co%f_luc_sg(ifc) = co%f_luc_ke(ifc)
        co%f_luc_al(ifc) = co%f_luc_ke(ifc)
        DO is=0,ns-1
          IF (.NOT.is_neutral(is)) THEN
            cvsa(ifc, 0, is) = cvsa(ifc, 0, is)*co%f_luc_et(ifc)
            cvsahz(ifc, 0, is) = cvsahz(ifc, 0, is)*co%f_luc_et(ifc)
            vsaf_cl(ifc, 0, is) = vsaf_cl(ifc, 0, is)*co%f_luc_et(ifc)
          END IF
        END DO
        chce(ifc, 0) = chce(ifc, 0)*co%f_luc_ke(ifc)
        csig(ifc, 0) = csig(ifc, 0)*co%f_luc_sg(ifc)
        calf(ifc, 0) = calf(ifc, 0)*co%f_luc_al(ifc)
        chci(ifc, 0) = chci(ifc, 0)*co%f_luc_ki(ifc)
      END IF
    END DO
    DO icv=1,ncv
      IF (mpg%cvonclosedsurface(icv)) THEN
        ift = mpg%cvft(icv)
        IF (ift .GT. 0 .AND. ift .LE. mpg%nft) THEN
          arg13 = geo%fteps(ift)**3
          result1 = SQRT(arg13)
          t0 = 1.0_R8/k1(icv)*0.58_R8*result1
          co%sigx_c(icv) = co%sigx_c(icv)*t0
          co%alfx_c(icv) = co%alfx_c(icv)*t0
          arg13 = geo%fteps(ift)**3
          result1 = SQRT(arg13)
          t0 = 1.0_R8/k2(icv)*1.60_R8*result1
          co%hcix_c(icv) = co%hcix_c(icv)*t0
        END IF
      END IF
    END DO
  END IF
!   ..set strange velocities chve, chvi
  arg1 = nfc*2
  CALL SFILL_NODIFF(arg1, 0.0_R8, chve, 1)
  arg1 = nfc*2
  CALL SFILL_NODIFF(arg1, 0.0_R8, chvi, 1)
!
  IF (switch%b2npmo_iout .NE. 0 .OR. switch%iout_b2wdat .EQ. 4) THEN
    DO is=0,ns-1
      WRITE(chns, '(i3.3)') is
      IF (.NOT.is_neutral(is)) THEN
        arg14(:) = 'b2trcl_luciani_cvsahzx'//chns
        CALL MY_OUT_US(70, nfc, 1, cvsahz(1, 0, is), arg14(:))
      END IF
    END DO
  END IF
!        call my_out_us(70,nFc,1,cvsahz(1,1,is),
!     &              'b2trcl_luciani_cvsahzy'//chns)
  IF (switch%b2npht_iout .NE. 0 .OR. switch%iout_b2wdat .EQ. 4) THEN
    CALL MY_OUT_US(70, nfc, 1, chce(1, 0), &
&                   'b2trcl_luciani_chce_th')
!        call my_out_us(70,nFc,1,chce(1,1),'b2trcl_luciani_chcey')
    CALL MY_OUT_US(70, nfc, 1, calf(1, 0), &
&                   'b2trcl_luciani_calf_th')
    CALL MY_OUT_US(70, ncv, 0, co%alfx_c, 'b2trcl_luciani_alfx_c'&
&                  )
!srv 05.07.17
!        call my_out_us(70,nFc,1,calf(1,1),'b2trcl_luciani_calfy')
    CALL MY_OUT_US(70, nfc, 1, chci(1, 0), &
&                   'b2trcl_luciani_chci_th')
!        call my_out_us(70,nFc,1,chci(1,1),'b2trcl_luciani_chciy')
  END IF
  IF ((switch%b2npp7_iout .NE. 0 .OR. switch%b2nppo_iout .NE. 0) .OR. &
&     switch%iout_b2wdat .EQ. 4) THEN
    CALL MY_OUT_US(70, nfc, 1, csig(1, 0), &
&                   'b2trcl_luciani_csig_th')
!        call my_out_us(70,nFc,1,csig(1,1),'b2trcl_luciani_csigy')
    CALL MY_OUT_US(70, ncv, 0, co%sigx_c, &
&                   'b2trcl_luciani_sig_th_c')
!srv 05.07.17
  END IF
!
!   .. save chce(:,0) after applying Luciani
!srv 13.01.17
  wrk = chce(:, 0)
!srv 16.06.08 }
!
  IF (switch%conductive_limit .NE. 0) THEN
!srv 16.06.08 {
!   .. pre-compute poloidal differences of te, ti
    CALL DIFF_P_NODIFF(ncv, nfc, nvx, 0, geo, mpg, pl%te, wrkv, dte)
    CALL DIFF_P_NODIFF(ncv, nfc, nvx, 0, geo, mpg, pl%ti, wrkv, dti)
!   .. apply the conductive limit of parallel electron heat flux         !srv 03.06.03 {
    IF (cflim(0) .NE. 0.0_R8) THEN
      DO ifc=1,nfc
!sw 19oct2011, also in core for SOLPS4.3 comparison!!!
!            if(.not.on_closed_surface(ix,iy)) then                      !lk 06.05.07
        IF (switch%core_cond_limit .NE. 0 .OR. (.NOT.(mpg%&
&           cvonclosedsurface(mpg%fccv(ifc, 1)) .AND. mpg%&
&           cvonclosedsurface(mpg%fccv(ifc, 2))))) THEN
          flomx = co%chvemx(ifc)*(dv%ne(mpg%fccv(ifc, 1))+dv%ne(mpg%fccv&
&           (ifc, 2)))/2.0_R8
          IF (chce(ifc, 0)*dte(ifc) .GE. 0.) THEN
            abs0 = chce(ifc, 0)*dte(ifc)
          ELSE
            abs0 = -(chce(ifc, 0)*dte(ifc))
          END IF
          IF (pl%te(mpg%fccv(ifc, 1)) .LT. pl%te(mpg%fccv(ifc, 2))) THEN
            max1 = pl%te(mpg%fccv(ifc, 2))
          ELSE
            max1 = pl%te(mpg%fccv(ifc, 1))
          END IF
          t0 = abs0/(flomx*max1+b2trcl_cutlo)
          co%fllim_ke(ifc) = 1.0_R8/(1.0_R8+t0)
          chce(ifc, 0) = chce(ifc, 0)*co%fllim_ke(ifc)
        END IF
      END DO
    END IF
!   .. apply the conductive limit of parallel ion heat flux
    IF (cflim(1) .NE. 0.0_R8) THEN
      DO ifc=1,nfc
!sw 19oct2011, also in core for SOLPS4.3 comparison!!!
!          if(.not.on_closed_surface(ix,iy)) then                           !lk 06.05.07
        IF (switch%core_cond_limit .NE. 0 .OR. (.NOT.(mpg%&
&           cvonclosedsurface(mpg%fccv(ifc, 1)) .AND. mpg%&
&           cvonclosedsurface(mpg%fccv(ifc, 2))))) THEN
          flomx = co%chvimx(ifc)*(dv%ni(mpg%fccv(ifc, 1), 0)+dv%ni(mpg%&
&           fccv(ifc, 2), 0))/2.0_R8
          IF (chci(ifc, 0)*dti(ifc) .GE. 0.) THEN
            abs1 = chci(ifc, 0)*dti(ifc)
          ELSE
            abs1 = -(chci(ifc, 0)*dti(ifc))
          END IF
          IF (pl%ti(mpg%fccv(ifc, 1)) .LT. pl%ti(mpg%fccv(ifc, 2))) THEN
            max2 = pl%ti(mpg%fccv(ifc, 2))
          ELSE
            max2 = pl%ti(mpg%fccv(ifc, 1))
          END IF
          t0 = abs1/(flomx*max2+b2trcl_cutlo)
          co%fllim_ki(ifc) = 1.0_R8/(1.0_R8+t0)
          chci(ifc, 0) = chci(ifc, 0)*co%fllim_ki(ifc)
        END IF
      END DO
!wdk pragmatic approximation for cell center flux limits: based on interpolation
!wdk of face flux limit
      CALL INTCELL_NODIFF(nfc, ncv, mpg, mpg%intcellp, co%fllim_ki, co%&
&                   fllim_ki_c)
      DO icv=1,ncv
        IF (switch%core_cond_limit .NE. 0 .OR. (.NOT.mpg%&
&           cvonclosedsurface(icv))) co%hcix_c(icv) = co%hcix_c(icv)*co%&
&           fllim_ki_c(icv)
      END DO
    END IF
  END IF
!   ..apply flux limit to calf                                           !srv 13.01.17 {
  IF (switch%b2sigp_style .NE. 2) THEN
    IF (cflim(0) .NE. 0.0_R8) THEN
      DO ifc=1,nfc
        IF (.NOT.(mpg%cvonclosedsurface(mpg%fccv(ifc, 1)) .AND. mpg%&
&           cvonclosedsurface(mpg%fccv(ifc, 2)))) THEN
          flomx = co%chvemx(ifc)*(dv%ne(mpg%fccv(ifc, 1))+dv%ne(mpg%fccv&
&           (ifc, 2)))/2.0_R8
          IF (wrk(ifc)*dte(ifc) .GE. 0.) THEN
            abs2 = wrk(ifc)*dte(ifc)
          ELSE
            abs2 = -(wrk(ifc)*dte(ifc))
          END IF
          IF (pl%te(mpg%fccv(ifc, 1)) .LT. pl%te(mpg%fccv(ifc, 2))) THEN
            max3 = pl%te(mpg%fccv(ifc, 2))
          ELSE
            max3 = pl%te(mpg%fccv(ifc, 1))
          END IF
          t0 = abs2/(flomx*max3+b2trcl_cutlo)
          co%fllim_al(ifc) = 1.0_R8/(1.0_R8+t0)
!srv 13.01.17
          calf(ifc, 0) = calf(ifc, 0)*co%fllim_al(ifc)
        END IF
      END DO
!wdk pragmatic approximation for cell center flux limits: based on interpolation
!wdk of face flux limit
      CALL INTCELL_NODIFF(nfc, ncv, mpg, mpg%intcellp, co%fllim_al, co%&
&                   fllim_al_c)
      DO icv=1,ncv
        IF (.NOT.mpg%cvonclosedsurface(icv)) co%alfx_c(icv) = co%alfx_c(&
&           icv)*co%fllim_al_c(icv)
      END DO
    END IF
  ELSE IF (cflim(3) .NE. 0.0_R8) THEN
!   ..apply flux limit to calf at cell faces
    DO ifc=1,nfc
      IF (.NOT.(mpg%cvonclosedsurface(mpg%fccv(ifc, 1)) .AND. mpg%&
&         cvonclosedsurface(mpg%fccv(ifc, 2)))) THEN
        IF (geo%fcpbs(ifc) .GE. 0.) THEN
          abs3 = geo%fcpbs(ifc)
        ELSE
          abs3 = -geo%fcpbs(ifc)
        END IF
        arg11 = (pl%te(mpg%fccv(ifc, 1))+pl%te(mpg%fccv(ifc, 2)))/2.0_R8&
&         /me
        result12 = SQRT(arg11)
        jemax = result12*qe*(dv%ne(mpg%fccv(ifc, 1))+dv%ne(mpg%fccv(ifc&
&         , 2)))/2.0_R8*abs3
        IF (calf(ifc, 0)*dte(ifc) .GE. 0.) THEN
          abs4 = calf(ifc, 0)*dte(ifc)
        ELSE
          abs4 = -(calf(ifc, 0)*dte(ifc))
        END IF
        t0 = abs4/(cflim(3)*jemax+b2trcl_cutlo)
        co%fllim_al(ifc) = 1.0_R8/(1.0_R8+t0)
!srv 13.01.17
        calf(ifc, 0) = calf(ifc, 0)*co%fllim_al(ifc)
      END IF
    END DO
!   ..apply flux limit to alfx_c at cell centers
    CALL GRADC_P_NODIFF(ncv, nfc, nvx, 0, geo, mpg, pl%te, wrkv, gtec)
    DO icv=1,ncv
      IF (.NOT.mpg%cvonclosedsurface(icv)) THEN
        arg11 = pl%te(icv)/me
        result12 = SQRT(arg11)
        jemax = result12*qe*dv%ne(icv)*geo%cvbb(icv, 0)/geo%cvbb(icv, 3)
        x1 = co%alfx_c(icv)*gtec(icv)/(cflim(3)*jemax+b2trcl_cutlo)
        IF (x1 .GE. 0.) THEN
          t0 = x1
        ELSE
          t0 = -x1
        END IF
        co%fllim_al_c(icv) = 1.0_R8/(1.0_R8+t0)
!iyv 19.11.13 !srv 08.10.14
        co%alfx_c(icv) = co%alfx_c(icv)*co%fllim_al_c(icv)
      END IF
    END DO
  END IF
!   ..apply flux limit to cvsa
  cflmv = cflim(2)
  DO is=0,ns-1
    CALL B2TLMV_NODIFF(ncv, nfc, nvx, is, cflmv, switch, geo, mpg, pl%na&
&                (:, is), pl%ti, pl%ua(:, is), vsaf_cl(:, 0, is), cvsa(:&
&                , 0, is), cvsahz(:, 0, is), fllimvisc(:, is))
  END DO
  WHERE (rt%rza(:, ismain)*qe*geo%cvbb(:, 3) .GE. 0.) 
    dabs0 = rt%rza(:, ismain)*qe*geo%cvbb(:, 3)
  ELSEWHERE
    dabs0 = -(rt%rza(:, ismain)*qe*geo%cvbb(:, 3))
  END WHERE
!   ..computation conductivity of kt due to classical parallel current
!wdk  current model: conductivity ~ sigx*rhol**2/(am(ismain)*mp)
  arg15(:) = 2.0_R8*pl%ti*(am(ismain)*mp)
  result13 = SQRT(arg15(:))
  wrkc = result13/dabs0
  wrkc = co%sigx_c*wrkc**2*geo%cvbb(:, 3)**2/(am(ismain)*mp)
  CALL B2TXCX_NODIFF(ncv, nfc, mode, geo, mpg, geo%fcvol, geo%fcs, wrkc&
&              , cdkt(:, 0))
  cdkt(:, 0) = cdkt(:, 0)*switch%b2tfhi_fsigkt
  cdkt(:, 1) = 0.0_R8
  co%sigx_kt = wrkc
!   ..save the classical transport coefficients
  csig_cl = csig
  calf_cl = calf
  cvsa_cl = cvsa
!srv 09.01.01
  cvsahz_cl = cvsahz
!
  IF (switch%b2npmo_iout .NE. 0 .OR. switch%iout_b2wdat .EQ. 4) THEN
    DO is=0,ns-1
      WRITE(chns, '(i3.3)') is
      arg16(:) = 'b2trcl_luciani_fllim_cvsahz_th'//chns
      CALL MY_OUT_US(70, nfc, 1, cvsahz(1, 0, is), arg16(:))
    END DO
  END IF
!        call my_out_us(70,nFc,1,cvsahz(1,1,is),
!     &              'b2trcl_luciani_fllim_cvsahzy'//chns)
  IF (switch%b2npht_iout .NE. 0 .OR. switch%iout_b2wdat .EQ. 4) THEN
    CALL MY_OUT_US(70, nfc, 1, chce(1, 0), &
&                   'b2trcl_luciani_fllim_chce_th')
!        call my_out_us(70,nFc,1,chce(1,1),'b2trcl_luciani_fllim_chcey')
    CALL MY_OUT_US(70, nfc, 1, calf(1, 0), &
&                   'b2trcl_luciani_fllim_calf_th')
!        call my_out_us(70,nFc,1,calf(1,1),'b2trcl_luciani_fllim_calfy')
    CALL MY_OUT_US(70, ncv, 0, co%alfx_c, &
&                   'b2trcl_luciani_fllim_alf_th_c')
!srv 05.07.17
    CALL MY_OUT_US(70, nfc, 1, chci(1, 0), &
&                   'b2trcl_luciani_fllim_chci_th')
!        call my_out_us(70,nFc,1,chci(1,1),'b2trcl_luciani_fllim_chciy')
  END IF
!srv 17.06.08 }
!
  IF (switch%b2trcl_iout .NE. 0) THEN
!srv 17.06.08 {
    DO is=0,ns-1
      WRITE(chns, '(i3.3)') is
      arg17(:) = 'cl_cvsa_th'//chns
      CALL MY_OUT_US(70, nfc, 1, cvsa(1, 0, is), arg17(:))
      arg18(:) = 'cl_cvsa_r'//chns
      CALL MY_OUT_US(70, nfc, 1, cvsa(1, 1, is), arg18(:))
      arg19(:) = 'cl_cvsahz_th'//chns
      CALL MY_OUT_US(70, nfc, 1, cvsahz(1, 0, is), arg19(:))
      arg110(:) = 'cl_cvsahz_r'//chns
      CALL MY_OUT_US(70, nfc, 1, cvsahz(1, 1, is), arg110(:))
      arg111(:) = 'cl_cvsa_cl_th'//chns
      CALL MY_OUT_US(70, nfc, 1, cvsa_cl(1, 0, is), arg111(:))
      arg19(:) = 'cl_cvsa_cl_r'//chns
      CALL MY_OUT_US(70, nfc, 1, cvsa_cl(1, 1, is), arg19(:))
      arg111(:) = 'cl_cvsahz_clx'//chns
      CALL MY_OUT_US(70, nfc, 1, cvsahz_cl(1, 0, is), arg111(:))
      arg111(:) = 'cl_cvsahz_cly'//chns
      CALL MY_OUT_US(70, nfc, 1, cvsahz_cl(1, 1, is), arg111(:))
      arg112(:) = 'cl_cthe'//chns
      CALL MY_OUT_US(70, ncv, 0, cthe(1, is), arg112(:))
      arg112(:) = 'cl_cthi'//chns
      CALL MY_OUT_US(70, ncv, 0, cthi(1, is), arg112(:))
      DO is0=0,ns-1
        WRITE(chns0, '(i3.3)') is0
        arg19(:) = 'cl_csigin_th'//chns//'_'//chns0
        CALL MY_OUT_US(70, nfc, 1, csigin(1, 0, is, is0), arg19(:&
&                       ))
        arg110(:) = 'cl_csigin_r'//chns//'_'//chns0
        CALL MY_OUT_US(70, nfc, 1, csigin(1, 1, is, is0), arg110(&
&                       :))
      END DO
    END DO
    CALL MY_OUT_US(70, nfc, 1, chce(1, 0), 'cl_chce_th')
    CALL MY_OUT_US(70, nfc, 1, chce(1, 1), 'cl_chce_r')
    CALL MY_OUT_US(70, nfc, 1, chci(1, 0), 'cl_chci_th')
    CALL MY_OUT_US(70, nfc, 1, chci(1, 1), 'cl_chci_r')
    CALL MY_OUT_US(70, nfc, 1, chve(1, 0), 'cl_chve_th')
    CALL MY_OUT_US(70, nfc, 1, chve(1, 1), 'cl_chve_r')
    CALL MY_OUT_US(70, nfc, 1, chvi(1, 0), 'cl_chvi_th')
    CALL MY_OUT_US(70, nfc, 1, chvi(1, 1), 'cl_chvi_r')
    CALL MY_OUT_US(70, nfc, 1, csig(1, 0), 'cl_csig_th')
    CALL MY_OUT_US(70, nfc, 1, csig(1, 1), 'cl_csig_r')
    CALL MY_OUT_US(70, nfc, 1, calf(1, 0), 'cl_calf_th')
    CALL MY_OUT_US(70, nfc, 1, calf(1, 1), 'cl_calf_r')
    CALL MY_OUT_US(70, ncv, 0, co%sigx_c, 'cl_sig_th_c')
!srv 05.07.17
    CALL MY_OUT_US(70, ncv, 0, co%alfx_c, 'cl_alf_th_c')
!srv 05.07.17
  END IF
!
! ..return
  ncall_b2trcl = ncall_b2trcl + 1
  CALL SUBEND()
  RETURN
END SUBROUTINE B2TRCL_NODIFF

