!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 23 Jul 2024 17:41
!
!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE B2TXFY_NODIFF(nx, ny, ns, mode, vol, gs, hy, qz, kapy, cony)
  USE B2MOD_TYPES
  USE B2MOD_MATH_DIFFV
  USE B2MOD_INDIRECT_DIFFV
  USE B2MOD_SUBSYS
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
  INTEGER :: nx, ny, ns, mode
  REAL(kind=r8) :: vol(-1:nx, -1:ny), gs(-1:nx, -1:ny, 0:2), hy(-1:nx, -&
& 1:ny), qz(-1:nx, -1:ny, 0:1), kapy(-1:nx, -1:ny, 0:1, 0:ns-1), cony(-1&
& :nx, -1:ny)
!     ------------------------------------------------------------------
!     B2TXFY computes conductances between neighbouring cells in the
!     y-direction, given the flux-limited conductivities.
!     ------------------------------------------------------------------
  INTEGER :: ix, iy, is
  REAL(kind=r8) :: t0, t1, kaps, kapsn
  INTRINSIC MAX, SQRT
  REAL(kind=r8) :: hy1(-1:nx, -1:ny)
  EXTERNAL B2XXGS, HARM
  REAL(kind=r8) :: HARM
  EXTERNAL XERTST
  REAL(r8) :: y1
  REAL(r8) :: max1
  REAL(r8) :: result1
!     ------------------------------------------------------------------
!   ..subprogram start-up calls
  CALL SUBINI('b2txfy')
!   ..test mode
  CALL XERTST(-1 .LE. mode .AND. mode .LE. 2, &
&       'b2txfy--faulty argument mode')
!
!   ..precompute hy1
  hy1 = hy*qz(:, :, 1)
!
!   ..compute cony
  DO iy=-1,ny
    DO ix=-1,nx
      IF (bottomiy(ix, iy) .EQ. -2) THEN
        cony(ix, iy) = 0.0_R8
      ELSE
        kaps = 0.0_R8
        kapsn = 0.0_R8
        DO is=0,ns-1
          kaps = kaps + kapy(ix, iy, 1, is)
          kapsn = kapsn + kapy(bottomix(ix, iy), bottomiy(ix, iy), 1, is&
&           )
        END DO
        IF (mode .EQ. -1) THEN
!    ..use harmonic averaging
          t0 = vol(bottomix(ix, iy), bottomiy(ix, iy))*kapsn/hy1(&
&           bottomix(ix, iy), bottomiy(ix, iy))**2
          t1 = vol(ix, iy)*kaps/hy1(ix, iy)**2
          IF (t0*t1 .LE. 0.0_R8) THEN
            cony(ix, iy) = 0.0_R8
          ELSE
            cony(ix, iy) = HARM(t0, t1)
          END IF
        ELSE IF (mode .EQ. 0) THEN
          y1 = vol(bottomix(ix, iy), bottomiy(ix, iy))*kapsn/hy1(&
&           bottomix(ix, iy), bottomiy(ix, iy))*(vol(ix, iy)*kaps/hy1(ix&
&           , iy))
          IF (0.0_R8 .LT. y1) THEN
            max1 = y1
          ELSE
            max1 = 0.0_R8
          END IF
!    ..use geometric averaging
          result1 = SQRT(max1)
          cony(ix, iy) = 2.0_R8*result1/(hy1(bottomix(ix, iy), bottomiy(&
&           ix, iy))+hy1(ix, iy))
        ELSE IF (mode .EQ. 1) THEN
!    ..use arithmetic averaging (SOLPS5.0 formulation)
          cony(ix, iy) = 2.0_R8*(vol(bottomix(ix, iy), bottomiy(ix, iy))&
&           *kapsn+vol(ix, iy)*kaps)/(hy1(bottomix(ix, iy), bottomiy(ix&
&           , iy))+hy1(ix, iy))**2
        ELSE IF (mode .EQ. 2) THEN
!    ..use arithmetic averaging (SOLPS4.0 formulation)
          cony(ix, iy) = gs(ix, iy, 1)*2.0_R8*(hy1(bottomix(ix, iy), &
&           bottomiy(ix, iy))*kapsn+hy1(ix, iy)*kaps)/(hy1(bottomix(ix, &
&           iy), bottomiy(ix, iy))+hy1(ix, iy))**2
        END IF
      END IF
    END DO
  END DO
!     (Note: We used to have the loop over ix outside the one over iy
!     in the previous code, but then the AIX/XLF compiler version 2.2
!     produced wrong code when optimisation (-O) was on.)
!   ..reset null regions
  CALL B2XXGS(nx, ny, 0.0_R8, cony, 2)
!   ..return
  CALL SUBEND()
  RETURN
!     ------------------------------------------------------------------
END SUBROUTINE B2TXFY_NODIFF

