!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 23 Jul 2024 17:41
!
!  Differentiation of gradc_r in forward (tangent) mode (with options multiDirectional context noISIZE r8):
!   variations   of useful results: gfunr funv
!   with respect to varying inputs: funv fun
!   Plus diff mem management of: mpg.intcellr:in geo.fchc:in geo.fcht:in
!                geo.fcqgam:in geo.fcqalf:in geo.fcqbet:in geo.vxvol:in
!
!
!
!
!
!
!
!
!
!
!
!-----------------------------------------------------------------------
!.specification
!
SUBROUTINE GRADC_R_DV(ncv, nfc, nvx, mode, geo, geod, mpg, mpgd, fun, &
& fund, funv, funvd, gfunr, gfunrd, nbdirs)
  USE B2MOD_TYPES
  USE B2US_GEO_DIFFV
  USE B2US_MAP_DIFFV
!  Hint: nbdirsmax should be the maximum number of differentiation directions
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!   ..input arguments
  INTEGER, INTENT(IN) :: ncv, nfc, nvx, mode
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(GEOMETRY_DIFFV), INTENT(IN) :: geod
  TYPE(MAPPING), INTENT(IN) :: mpg
  TYPE(MAPPING_DIFFV), INTENT(IN) :: mpgd
  REAL(kind=r8) :: fun(ncv), funv(nvx)
  REAL(kind=r8) :: fund(nbdirsmax, ncv), funvd(nbdirsmax, nvx)
!   ..output arguments
  REAL(kind=r8) :: gfunr(ncv)
  REAL(kind=r8) :: gfunrd(nbdirsmax, ncv)
!-----------------------------------------------------------------------
!.documentation
!
!     GRADC_R computes gradients of a cell centered quantity fun in the 
!     radial direction, in cell centers. The routine first computes
!     the gradients on faces, and then interpolates to cell centers.
!
!-----------------------------------------------------------------------
!.declarations
!
!   ..local variables
  REAL(kind=r8) :: gfunrf(nfc)
  REAL(kind=r8) :: gfunrfd(nbdirsmax, nfc)
  INTEGER :: nbdirs
!
!-----------------------------------------------------------------------
!.computation      
!
!   ..test mode
  CALL XERTST(0 .LE. mode .AND. mode .LE. 1, &
&       'gradc_r--faulty argument mode')
!
!   ..interpolate fun to cell vertices, using volume weighted averaging
  IF (mode .EQ. 0) CALL INTVERTEX_DV(ncv, nvx, mpg, geo%vxvol, fun, fund&
&                              , funv, funvd, nbdirs)
!
!   ..compute gradients on faces
  gfunrfd = 0.D0
  CALL GRAD_R_DV(ncv, nfc, nvx, 1, geo, mpg, mpgd, fun, fund, funv, &
&          funvd, gfunrf, gfunrfd, nbdirs)
!
!   ..interpolate to centers
  CALL INTCELL_DV(nfc, ncv, mpg, mpg%intcellr, gfunrf, gfunrfd, gfunr, &
&           gfunrd, nbdirs)
!
!   ..return
  RETURN
!
!-----------------------------------------------------------------------
!.end gradc_r
!
END SUBROUTINE GRADC_R_DV

!
!
!
!
!
!
!
!
!
!
!
!-----------------------------------------------------------------------
!.specification
!
SUBROUTINE GRADC_R_NODIFF(ncv, nfc, nvx, mode, geo, mpg, fun, funv, &
& gfunr)
  USE B2MOD_TYPES
  USE B2US_GEO_DIFFV
  USE B2US_MAP_DIFFV
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!   ..input arguments
  INTEGER, INTENT(IN) :: ncv, nfc, nvx, mode
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(MAPPING), INTENT(IN) :: mpg
  REAL(kind=r8) :: fun(ncv), funv(nvx)
!   ..output arguments
  REAL(kind=r8) :: gfunr(ncv)
!-----------------------------------------------------------------------
!.documentation
!
!     GRADC_R computes gradients of a cell centered quantity fun in the 
!     radial direction, in cell centers. The routine first computes
!     the gradients on faces, and then interpolates to cell centers.
!
!-----------------------------------------------------------------------
!.declarations
!
!   ..local variables
  REAL(kind=r8) :: gfunrf(nfc)
!
!-----------------------------------------------------------------------
!.computation      
!
!   ..test mode
  CALL XERTST(0 .LE. mode .AND. mode .LE. 1, &
&       'gradc_r--faulty argument mode')
!
!   ..interpolate fun to cell vertices, using volume weighted averaging
  IF (mode .EQ. 0) CALL INTVERTEX_NODIFF(ncv, nvx, mpg, geo%vxvol, fun, &
&                                  funv)
!
!   ..compute gradients on faces
  CALL GRAD_R_NODIFF(ncv, nfc, nvx, 1, geo, mpg, fun, funv, gfunrf)
!
!   ..interpolate to centers
  CALL INTCELL_NODIFF(nfc, ncv, mpg, mpg%intcellr, gfunrf, gfunr)
!
!   ..return
  RETURN
!
!-----------------------------------------------------------------------
!.end gradc_r
!
END SUBROUTINE GRADC_R_NODIFF

