!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 23 Jul 2024 17:41
!
!  Differentiation of intp_3dtable in forward (tangent) mode (with options multiDirectional context noISIZE r8):
!   variations   of useful results: res
!   with respect to varying inputs: p1 p2 p3
!
!
!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE INTP_3DTABLE_DV(tab, r1, r2, r3, dr1, dr2, dr3, nr1, nr2, nr3&
& , p1, p1d, p2, p2d, p3, p3d, ir1, ir2, ir3, ip1, ip2, ip3, res, resd, &
& nbdirs)
!  linear interpolation in 3 parameter table tab
!  linear extrapolation at all 8 parameter boundaries
!
! input:
!  table: tab(r1,r2,r3)
!  r1(0:nr1):first variable
!  r2(0:nr2):second variable
!  r3(0:nr3):third variable
!  dr1(0:nr1-1),dr2(0:nr2-1); dr3(0:nr3-1); inverse of table spacing
!  parameters:  p1, p2, p3
!
! output:
!  res,  interpolated value at (p1,p2)
!  ir1,ir2,ir3:  Lowest indices of interpolated table values
!  ip1 = 0:  parameter p1 is in valid range of table
!  ip1 =-1:  parameter p1 is below left boundary of tabulated range
!  ip1 =+1:  parameter p1 is above right boundary of tabulated range
!
!  ip2    :  same as ip1, for parameter p2.
!  ip3    :  same as ip1, for parameter p3.
!
  USE B2MOD_TYPES
!  Hint: nbdirsmax should be the maximum number of differentiation directions
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: nr1, nr2, nr3
  REAL(kind=r8), INTENT(IN) :: tab(0:nr1, 0:nr2, 0:nr3), r1(0:nr1), r2(0&
& :nr2), r3(0:nr3), dr1(0:nr1-1), dr2(0:nr2-1), dr3(0:nr3-1)
  REAL(kind=r8), INTENT(IN) :: p1, p2, p3
  REAL(kind=r8), DIMENSION(nbdirsmax), INTENT(IN) :: p1d, p2d, p3d
  INTEGER, INTENT(OUT) :: ir1, ir2, ir3, ip1, ip2, ip3
  INTEGER :: ne1, ne2, ne3
  REAL(kind=r8) :: rx, ry, rz, ff(2, 2, 2)
  REAL(kind=r8), DIMENSION(nbdirsmax) :: rxd, ryd, rzd
  INTEGER :: nd
  REAL(kind=r8), INTENT(OUT) :: resd(nbdirsmax)
  REAL(kind=r8), INTENT(OUT) :: res
  INTEGER :: nbdirs
!
!  Arrays shifted from zero-based to 1-based indexing in subroutines!
  ne1 = nr1 + 1
  ne2 = nr2 + 1
  ne3 = nr3 + 1
!  first parameter, find cell ir1, ir1+1 
  IF (p1 .LT. r1(0)) THEN
    ir1 = 0
    ip1 = -1
  ELSE IF (p1 .GT. r1(nr1)) THEN
    ir1 = nr1 - 1
    ip1 = 1
  ELSE
    CALL BINSEARCH_2(r1, ne1, p1, ir1)
    ir1 = ir1 - 1
    ip1 = 0
  END IF
!  second parameter, find cell ir2, ir2+1  
  IF (p2 .LT. r2(0)) THEN
    ir2 = 0
    ip2 = -1
  ELSE IF (p2 .GT. r2(nr2)) THEN
    ir2 = nr2 - 1
    ip2 = 1
  ELSE
    CALL BINSEARCH_2(r2, ne2, p2, ir2)
    ir2 = ir2 - 1
    ip2 = 0
  END IF
!  third parameter, find cell ir3, ir3+1  
  IF (p3 .LT. r3(0)) THEN
    ir3 = 0
    ip3 = -1
  ELSE IF (p3 .GT. r3(nr3)) THEN
    ir3 = nr3 - 1
    ip3 = 1
  ELSE
    CALL BINSEARCH_2(r3, ne3, p3, ir3)
    ir3 = ir3 - 1
    ip3 = 0
  END IF
  DO nd=1,nbdirs
!
!  cell indices ir1, ir2 and ir3 are found. 
!  the parameter (p1,p2) is in cell [ir1, ir1+1, ir2, ir2+1, ir3, ir3+1].
!
    rxd(nd) = -(dr1(ir1)*p1d(nd))
    ryd(nd) = -(dr2(ir2)*p2d(nd))
    rzd(nd) = -(dr3(ir3)*p3d(nd))
  END DO
  rx = (r1(ir1+1)-p1)*dr1(ir1)
  ry = (r2(ir2+1)-p2)*dr2(ir2)
  rz = (r3(ir3+1)-p3)*dr3(ir3)
!  fill ff: intermediate 2 by 2 by 2 matrix of tabulated values at cell vertices
  ff = tab(ir1:ir1+1, ir2:ir2+1, ir3:ir3+1)
!
  CALL TRILINEAR_INT_DV(ff, rx, rxd, ry, ryd, rz, rzd, res, resd, nbdirs&
&                )
  RETURN
END SUBROUTINE INTP_3DTABLE_DV

!  Differentiation of intp_3dtable00 in forward (tangent) mode (with options multiDirectional context noISIZE r8):
!   variations   of useful results: res
!   with respect to varying inputs: p1 p2 p3
!
SUBROUTINE INTP_3DTABLE00_DV(ff, r1, r2, r3, dr1, dr2, dr3, nr1, nr2, &
& nr3, p1, p1d, p2, p2d, p3, p3d, ir1, ir2, ir3, res, resd, nbdirs)
!  interpolates a table ff which has already been constructed from knowledge of ir1, ir2 and ir3.
!  trilinear interpolation in 3 parameter table ff
!
! input:
!  ff = tab(ir1:ir1+1,ir2:ir2+1,ir3:ir3+1)
!  r1(0:nr1):first variable
!  r2(0:nr2):second variable
!  r3(0:nr3):third variable
!  dr1(0:nr1-1),dr2(0:nr2-1),dr3(0:nr3-1); inverse of table spacing
!  parameters:  p1, p2, p3
!  ir1,ir2,ir3:  Lowest indices of table values
!
! output:
!  res,  interpolated value at (p1,p2,p3)
!
!
  USE B2MOD_TYPES
!  Hint: nbdirsmax should be the maximum number of differentiation directions
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: nr1, nr2, nr3, ir1, ir2, ir3
  REAL(kind=r8), INTENT(IN) :: r1(0:nr1), r2(0:nr2), r3(0:nr3), ff(2, 2&
& , 2), dr1(0:nr1-1), dr2(0:nr2-1), dr3(0:nr3-1)
  REAL(kind=r8), INTENT(IN) :: p1, p2, p3
  REAL(kind=r8), DIMENSION(nbdirsmax), INTENT(IN) :: p1d, p2d, p3d
  REAL(kind=r8) :: rx, ry, rz
  REAL(kind=r8), DIMENSION(nbdirsmax) :: rxd, ryd, rzd
  INTEGER :: nd
  REAL(kind=r8), INTENT(OUT) :: resd(nbdirsmax)
  REAL(kind=r8), INTENT(OUT) :: res
  INTEGER :: nbdirs
  DO nd=1,nbdirs
!
!  cell indices ir1, ir2 and ir3 are know from a previous call to intp_3dtable are 
!  the parameter (p1,p2,p3) is in cell [ir1, ir1+1, ir2, ir2+1, ir3, ir3+1].
!
    rxd(nd) = -(dr1(ir1)*p1d(nd))
    ryd(nd) = -(dr2(ir2)*p2d(nd))
    rzd(nd) = -(dr3(ir3)*p3d(nd))
  END DO
  rx = (r1(ir1+1)-p1)*dr1(ir1)
  ry = (r2(ir2+1)-p2)*dr2(ir2)
  rz = (r3(ir3+1)-p3)*dr3(ir3)
!
  CALL TRILINEAR_INT_DV(ff, rx, rxd, ry, ryd, rz, rzd, res, resd, nbdirs&
&                )
  RETURN
END SUBROUTINE INTP_3DTABLE00_DV

