!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 23 Jul 2024 17:41
!
!
!
!
!
!
!
!
!
!
!
!
!-----------------------------------------------------------------------
!.specification
!
SUBROUTINE B2MXAR_DIFFV_NODIFF(ncv, ns, switch, geo, mpg, pl, dv, diag)
  USE B2MOD_TYPES
  USE B2MOD_CONSTANTS
  USE B2MOD_B2CMPA_DIFFV
  USE B2MOD_SWITCHES_DIFFV_DIFFV
  USE B2US_GEO_DIFFV_DIFFV
  USE B2US_MAP_DIFFV_DIFFV
  USE B2US_PLASMA_DIFFV_DIFFV
  USE B2MOD_SUBSYS
  IMPLICIT NONE
!   ..input arguments (unchanged on exit)
  INTEGER :: ncv, ns, nregionv
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(MAPPING), INTENT(IN) :: mpg
  TYPE(B2PLASMA_DIFFV), INTENT(IN) :: pl
  TYPE(B2DERIVATIVES_DIFFV), INTENT(IN) :: dv
!   ..output arguments (unspecified on entry)
  TYPE(B2DIAGNOSTIC_DIFFV), INTENT(INOUT) :: diag
!   ..common blocks
!-----------------------------------------------------------------------
!.documentation
!
! This is a modified version of b2mxar used in the B2.5 code differentiated
! with TAPENADE. The main difference wrt b2mxar is that some differentiated
! quantities can be .le. 0.0, therefore sqrt gives nans and results cannot
! be plotted against log scale. Therefore all sums are done using absolute
! values of differentiated quantities.
!
!-----------------------------------------------------------------------
!.declarations
!
!   ..local variables
  INTEGER :: icv, is
  REAL(kind=r8) :: navi, movi, mtvi, nevi, prvi, prvn, t0, t1, t2, t3, &
& t4
!   ..procedures
  INTRINSIC SQRT, ABS
  EXTERNAL XERTST
  INTRINSIC NINT
  REAL(kind=r8) :: x1
  REAL(kind=r8) :: x2
  REAL(kind=r8) :: abs0
  REAL(kind=r8) :: abs1
  REAL(r8) :: abs2
  REAL(r8) :: abs3
  REAL(r8) :: abs4
  REAL(kind=r8) :: abs5
  REAL(kind=r8) :: abs6
  REAL(kind=r8) :: abs7
  REAL(kind=r8) :: abs8
  REAL(kind=r8) :: abs9
  REAL(kind=r8) :: abs10
  REAL(r8) :: abs11
  REAL(r8) :: abs12
  REAL(r8) :: abs13
  REAL(r8) :: abs14
  REAL(r8) :: abs15
  REAL(kind=r8) :: abs16
  REAL(kind=r8) :: abs17
  REAL(r8) :: abs18
  REAL(r8) :: abs19
  REAL(kind=r8) :: abs20
  REAL(kind=r8) :: abs21
  REAL(r8) :: abs22
  REAL(r8) :: abs23
  REAL(r8) :: abs24
  REAL(r8) :: abs25
  REAL(r8) :: result1
!   ..initialisation
!
!-----------------------------------------------------------------------
!.computation
!
! ..preliminaries
!   ..subprogram start-up calls
  CALL SUBINI('b2mxar')
!   ..set internal parameters on first call
!   ..test nCv, ns
  CALL XERTST(0 .LT. ncv, 'faulty argument nCv')
  CALL XERTST(1 .LE. ns, 'faulty argument ns')
!
! ..compute scaled norms
!   ..compute aresco, aresmo, mtvi
  mtvi = 0.0_R8
  DO is=0,ns-1
    navi = 0.0_R8
    movi = 0.0_R8
    DO icv=1,mpg%nci
      IF (geo%cvvol(icv)*pl%na(1, icv, is) .GE. 0.) THEN
        abs0 = geo%cvvol(icv)*pl%na(1, icv, is)
      ELSE
        abs0 = -(geo%cvvol(icv)*pl%na(1, icv, is))
      END IF
      navi = navi + abs0
      IF (pl%ti(1, icv)*am(is)*mp .GE. 0.) THEN
        abs24 = pl%ti(1, icv)*am(is)*mp
      ELSE
        abs24 = -(pl%ti(1, icv)*am(is)*mp)
      END IF
      result1 = SQRT(abs24)
      x1 = geo%cvvol(icv)*pl%na(1, icv, is)*result1
      IF (x1 .GE. 0.) THEN
        abs1 = x1
      ELSE
        abs1 = -x1
      END IF
      movi = movi + abs1
!WG_TODO         if (resignore(iCv,1).ne.0)
!WG_TODO     >    navi = navi+geo%cvVol(iCv)*pl%na(iCv,is)
!WG_TODO         if (resignore(iCv,2).ne.0)
!WG_TODO     >    movi = movi+geo%cvVol(iCv)*
!WG_TODO     &     pl%na(iCv,is)*sqrt(pl%ti(iCv)*am(is)*mp)
    END DO
    mtvi = mtvi + movi
    t0 = 0.0_R8
    t1 = 0.0_R8
    DO icv=1,mpg%nci
      IF (dv%resco(1, icv, is) .GE. 0.) THEN
        abs2 = dv%resco(1, icv, is)
      ELSE
        abs2 = -dv%resco(1, icv, is)
      END IF
      t0 = t0 + abs2
      IF (dv%resmo(1, icv, is) .GE. 0.) THEN
        abs3 = dv%resmo(1, icv, is)
      ELSE
        abs3 = -dv%resmo(1, icv, is)
      END IF
      t1 = t1 + abs3
    END DO
    IF (navi .GT. 0.0_R8) THEN
      IF (t0/navi .GE. 0.) THEN
        diag%aresco(1, is) = t0/navi
      ELSE
        diag%aresco(1, is) = -(t0/navi)
      END IF
    END IF
    IF (movi .GT. 0.0_R8) THEN
      IF (t1/movi .GE. 0.) THEN
        diag%aresmo(1, is) = t1/movi
      ELSE
        diag%aresmo(1, is) = -(t1/movi)
      END IF
    END IF
  END DO
!   ..compute aresmt
  t0 = 0.0_R8
  DO icv=1,mpg%nci
    IF (dv%resmt(1, icv) .GE. 0.) THEN
      abs4 = dv%resmt(1, icv)
    ELSE
      abs4 = -dv%resmt(1, icv)
    END IF
    t0 = t0 + abs4
  END DO
  IF (mtvi .GT. 0.0_R8) THEN
    IF (t0/mtvi .GE. 0.) THEN
      diag%aresmt(1) = t0/mtvi
    ELSE
      diag%aresmt(1) = -(t0/mtvi)
    END IF
  END IF
!   ..compute nevi, prvi
  nevi = 0.0_R8
  prvi = 0.0_R8
  prvn = 0.0_R8
  DO icv=1,mpg%nci
    IF (geo%cvvol(icv)*dv%ne(1, icv) .GE. 0.) THEN
      abs5 = geo%cvvol(icv)*dv%ne(1, icv)
    ELSE
      abs5 = -(geo%cvvol(icv)*dv%ne(1, icv))
    END IF
!WG_TODO        if (resignore(iCv,1).eq.0) cycle
    nevi = nevi + abs5
    IF (geo%cvvol(icv)*dv%ne(1, icv)*pl%te(1, icv) .GE. 0.) THEN
      abs6 = geo%cvvol(icv)*dv%ne(1, icv)*pl%te(1, icv)
    ELSE
      abs6 = -(geo%cvvol(icv)*dv%ne(1, icv)*pl%te(1, icv))
    END IF
    prvi = prvi + abs6
    IF (switch%tn_style .EQ. 0) THEN
      DO is=0,ns-1
        IF (geo%cvvol(icv)*pl%na(1, icv, is)*pl%ti(1, icv) .GE. 0.) THEN
          abs7 = geo%cvvol(icv)*pl%na(1, icv, is)*pl%ti(1, icv)
        ELSE
          abs7 = -(geo%cvvol(icv)*pl%na(1, icv, is)*pl%ti(1, icv))
        END IF
        prvi = prvi + abs7
      END DO
!dummy
      prvn = prvi
    ELSE IF (switch%tn_style .EQ. 1) THEN
      DO is=0,ns-1
        IF (.NOT.is_neutral(is)) THEN
          IF (geo%cvvol(icv)*pl%na(1, icv, is)*pl%ti(1, icv) .GE. 0.) &
&         THEN
            abs8 = geo%cvvol(icv)*pl%na(1, icv, is)*pl%ti(1, icv)
          ELSE
            abs8 = -(geo%cvvol(icv)*pl%na(1, icv, is)*pl%ti(1, icv))
          END IF
          prvi = prvi + abs8
        END IF
      END DO
!dummy
      prvn = prvi
    ELSE
      DO is=0,ns-1
        IF ((.NOT.is_neutral(is)) .OR. NINT(zn(is)) .NE. 1) THEN
          IF (geo%cvvol(icv)*pl%na(1, icv, is)*pl%ti(1, icv) .GE. 0.) &
&         THEN
            abs9 = geo%cvvol(icv)*pl%na(1, icv, is)*pl%ti(1, icv)
          ELSE
            abs9 = -(geo%cvvol(icv)*pl%na(1, icv, is)*pl%ti(1, icv))
          END IF
          prvi = prvi + abs9
        ELSE
          IF (geo%cvvol(icv)*pl%na(1, icv, is)*pl%tn(1, icv) .GE. 0.) &
&         THEN
            abs10 = geo%cvvol(icv)*pl%na(1, icv, is)*pl%tn(1, icv)
          ELSE
            abs10 = -(geo%cvvol(icv)*pl%na(1, icv, is)*pl%tn(1, icv))
          END IF
          prvn = prvn + abs10
        END IF
      END DO
    END IF
  END DO
!   ..compute areshe, areshi, arespo
  t0 = 0.0_R8
  t1 = 0.0_R8
  t2 = 0.0_R8
  t3 = 0.0_R8
  t4 = 0.0_R8
  DO icv=1,mpg%nci
    IF (dv%reshe(1, icv) .GE. 0.) THEN
      abs11 = dv%reshe(1, icv)
    ELSE
      abs11 = -dv%reshe(1, icv)
    END IF
    t0 = t0 + abs11
    IF (dv%reshi(1, icv) .GE. 0.) THEN
      abs12 = dv%reshi(1, icv)
    ELSE
      abs12 = -dv%reshi(1, icv)
    END IF
    t1 = t1 + abs12
    IF (dv%respo(1, icv) .GE. 0.) THEN
      abs13 = dv%respo(1, icv)
    ELSE
      abs13 = -dv%respo(1, icv)
    END IF
    t2 = t2 + abs13
    IF (dv%reshn(1, icv) .GE. 0.) THEN
      abs14 = dv%reshn(1, icv)
    ELSE
      abs14 = -dv%reshn(1, icv)
    END IF
    t3 = t3 + abs14
    IF (dv%reskt(1, icv) .GE. 0.) THEN
      abs15 = dv%reskt(1, icv)
    ELSE
      abs15 = -dv%reskt(1, icv)
    END IF
    t4 = t4 + abs15
  END DO
  IF (prvi .GT. 0.0_R8) THEN
    IF (t0/((1.5_R8+switch%boris)*prvi) .GE. 0.) THEN
      diag%areshe = t0/((1.5_R8+switch%boris)*prvi)
    ELSE
      diag%areshe = -(t0/((1.5_R8+switch%boris)*prvi))
    END IF
  END IF
  IF (prvi .GT. 0.0_R8) THEN
    IF (t1/((1.5_R8+switch%boris)*prvi) .GE. 0.) THEN
      diag%areshi = t1/((1.5_R8+switch%boris)*prvi)
    ELSE
      diag%areshi = -(t1/((1.5_R8+switch%boris)*prvi))
    END IF
  END IF
  IF (nevi .GT. 0.0_R8) THEN
    IF (t2/(qe*nevi) .GE. 0.) THEN
      diag%arespo = t2/(qe*nevi)
    ELSE
      diag%arespo = -(t2/(qe*nevi))
    END IF
  END IF
  IF (prvn .GT. 0.0_R8) THEN
    IF (t3/((1.5_R8+switch%boris)*prvn) .GE. 0.) THEN
      diag%areshn = t3/((1.5_R8+switch%boris)*prvn)
    ELSE
      diag%areshn = -(t3/((1.5_R8+switch%boris)*prvn))
    END IF
  END IF
  IF (prvi .GT. 0.0_R8) THEN
    IF (t4/prvi .GE. 0.) THEN
      diag%areskt = t4/prvi
    ELSE
      diag%areskt = -(t4/prvi)
    END IF
  END IF
!
! ..compute regional scaled sums
  diag%rescoreg = 0.0_R8
  diag%resmoreg = 0.0_R8
!   ..compute navi, movi
  DO is=0,ns-1
    navi = 0.0_R8
    movi = 0.0_R8
    DO icv=1,mpg%nci
      IF (geo%cvvol(icv)*pl%na(1, icv, is) .GE. 0.) THEN
        abs16 = geo%cvvol(icv)*pl%na(1, icv, is)
      ELSE
        abs16 = -(geo%cvvol(icv)*pl%na(1, icv, is))
      END IF
!WG_TODO: resignore!
      navi = navi + abs16
      IF (pl%ti(1, icv)*am(is)*mp .GE. 0.) THEN
        abs25 = pl%ti(1, icv)*am(is)*mp
      ELSE
        abs25 = -(pl%ti(1, icv)*am(is)*mp)
      END IF
      result1 = SQRT(abs25)
      x2 = geo%cvvol(icv)*pl%na(1, icv, is)*result1
      IF (x2 .GE. 0.) THEN
        abs17 = x2
      ELSE
        abs17 = -x2
      END IF
      movi = movi + abs17
    END DO
!   ..compute rescoreg, resmoreg
    DO icv=1,mpg%nci
      IF (dv%resco(1, icv, is) .GE. 0.) THEN
        abs18 = dv%resco(1, icv, is)
      ELSE
        abs18 = -dv%resco(1, icv, is)
      END IF
!WG_TODO: resignore!
      diag%rescoreg(1, mpg%cvreg(icv), is) = diag%rescoreg(1, mpg%cvreg(&
&       icv), is) + abs18
      IF (dv%resmo(1, icv, is) .GE. 0.) THEN
        abs19 = dv%resmo(1, icv, is)
      ELSE
        abs19 = -dv%resmo(1, icv, is)
      END IF
      diag%resmoreg(1, mpg%cvreg(icv), is) = diag%resmoreg(1, mpg%cvreg(&
&       icv), is) + abs19
    END DO
    IF (navi .GT. 0.0_R8) THEN
      WHERE (diag%rescoreg(1, :, is)/navi .GE. 0.0) 
        diag%rescoreg(1, :, is) = diag%rescoreg(1, :, is)/navi
      ELSEWHERE
        diag%rescoreg(1, :, is) = -(diag%rescoreg(1, :, is)/navi)
      END WHERE
    END IF
    IF (movi .GT. 0.0_R8) THEN
      WHERE (diag%resmoreg(1, :, is)/movi .GE. 0.0) 
        diag%resmoreg(1, :, is) = diag%resmoreg(1, :, is)/movi
      ELSEWHERE
        diag%resmoreg(1, :, is) = -(diag%resmoreg(1, :, is)/movi)
      END WHERE
    END IF
  END DO
!   ..compute prvi
  prvi = 0.0_R8
  DO icv=1,mpg%nci
    IF (geo%cvvol(icv)*dv%ne(1, icv)*pl%te(1, icv) .GE. 0.) THEN
      abs20 = geo%cvvol(icv)*dv%ne(1, icv)*pl%te(1, icv)
    ELSE
      abs20 = -(geo%cvvol(icv)*dv%ne(1, icv)*pl%te(1, icv))
    END IF
!WG_TODO        if (resignore(iCv,1).eq.0) cycle
    prvi = prvi + abs20
    DO is=0,ns-1
      IF (.NOT.is_neutral(is)) THEN
        IF (geo%cvvol(icv)*pl%na(1, icv, is)*pl%ti(1, icv) .GE. 0.) THEN
          abs21 = geo%cvvol(icv)*pl%na(1, icv, is)*pl%ti(1, icv)
        ELSE
          abs21 = -(geo%cvvol(icv)*pl%na(1, icv, is)*pl%ti(1, icv))
        END IF
        prvi = prvi + abs21
      END IF
    END DO
  END DO
!   ..compute reshereg, reshireg
  diag%reshereg = 0.0_R8
  diag%reshireg = 0.0_R8
  DO icv=1,mpg%nci
    IF (dv%reshe(1, icv) .GE. 0.) THEN
      abs22 = dv%reshe(1, icv)
    ELSE
      abs22 = -dv%reshe(1, icv)
    END IF
!WG_TODO: resignore!
    diag%reshereg(1, mpg%cvreg(icv)) = diag%reshereg(1, mpg%cvreg(icv)) &
&     + abs22
    IF (dv%reshi(1, icv) .GE. 0.) THEN
      abs23 = dv%reshi(1, icv)
    ELSE
      abs23 = -dv%reshi(1, icv)
    END IF
    diag%reshireg(1, mpg%cvreg(icv)) = diag%reshireg(1, mpg%cvreg(icv)) &
&     + abs23
  END DO
  IF (prvi .GT. 0.0_R8) THEN
    WHERE (diag%reshereg(1, :)/((1.5_R8+switch%boris)*prvi) .GE. 0.0) 
      diag%reshereg(1, :) = diag%reshereg(1, :)/((1.5_R8+switch%boris)*&
&       prvi)
    ELSEWHERE
      diag%reshereg(1, :) = -(diag%reshereg(1, :)/((1.5_R8+switch%boris)&
&       *prvi))
    END WHERE
  END IF
  IF (prvi .GT. 0.0_R8) THEN
    WHERE (diag%reshireg(1, :)/((1.5_R8+switch%boris)*prvi) .GE. 0.0) 
      diag%reshireg(1, :) = diag%reshireg(1, :)/((1.5_R8+switch%boris)*&
&       prvi)
    ELSEWHERE
      diag%reshireg(1, :) = -(diag%reshireg(1, :)/((1.5_R8+switch%boris)&
&       *prvi))
    END WHERE
  END IF
!
! ..return
  CALL SUBEND()
  RETURN
!
!-----------------------------------------------------------------------
!.end b2mxar
!
END SUBROUTINE B2MXAR_DIFFV_NODIFF

