!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (feature_llhTests) - 27 May 2021 14:23
!
!
!
!
!
!
!
!
!
!
!
!
!-----------------------------------------------------------------------
!.specification
!
SUBROUTINE B2MXAC_DIFFV_NODIFF(ncv, ns, dv, diag)
  USE B2MOD_TYPES
  USE B2US_PLASMA_DIFFV_DIFFV
  USE B2MOD_SUBSYS
  IMPLICIT NONE
!
!-----------------------------------------------------------------------
!.end b2mxac
!
!   ..input arguments (unchanged on exit)
  INTEGER :: ncv, ns
  TYPE(B2DERIVATIVES_DIFFV), INTENT(IN) :: dv
!   ..output arguments (unspecified on entry)
  TYPE(B2DIAGNOSTIC_DIFFV), INTENT(INOUT) :: diag
!-----------------------------------------------------------------------
!.documentation
! This is a modified version of b2mxac used in the B2.5 code differentiated
! with TAPENADE. The main difference wrt b2mxac is the B2Derivatives_diff
! type used for input argument dv, which differs from the non-diff one.
!-----------------------------------------------------------------------
!.declarations
!
!   ..local variables
  INTEGER :: ncall, is
  SAVE ncall
  EXTERNAL XERTST, damax
!   ..procedures
  REAL(kind=r8) :: damax
!   ..initialisation
  DATA ncall /0/
!
!-----------------------------------------------------------------------
!.computation
!
! ..preliminaries
!   ..subprogram start-up calls
  CALL SUBINI('b2mxac')
!   ..test nCv, ns
  CALL XERTST(0 .LT. ncv, 'faulty argument nCv')
  CALL XERTST(1 .LE. ns, 'faulty argument ns')
!
! ..compute norms of the corrections
!   ..compute acorpa, acorua
  DO is=0,ns-1
    diag%acorpa(1, is) = damax(ncv, dv%corpa(1, 1, is), 1)
    diag%acorua(1, is) = damax(ncv, dv%corua(1, 1, is), 1)
  END DO
!   ..compute acorut, acorte, acorti, acorpo
  diag%acorut = damax(ncv, dv%corut, 1)
  diag%acorte = damax(ncv, dv%corte, 1)
  diag%acorti = damax(ncv, dv%corti, 1)
  diag%acortn = damax(ncv, dv%cortn, 1)
  diag%acorpo = damax(ncv, dv%corpo, 1)
  diag%acorkt = damax(ncv, dv%corkt, 1)
!
! ..return
  ncall = ncall + 1
  CALL SUBEND()
  RETURN
END SUBROUTINE B2MXAC_DIFFV_NODIFF

