!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (feature_llhTests) - 27 May 2021 14:23
!
!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (feature_llhTests) - 27 May 2021 14:23
!
!
!
!
!
!
!
!
!
!
!
!
!-----------------------------------------------------------------------
!.specification
!xpb
!xpb
SUBROUTINE B2STBC_BAS_NODIFF_NODIFF(nx, ny, ns, ismain, facdrift, na, ua&
& , uadia, vaecrb, te, ti, po, ne, ni, fna, fhe, fhi, fch, fne, fni, &
& chce, chve, chci, chvi, calf, sna0, smo0, she0, shi0, sch0, wrong_flow&
& , main_call, diagno, b2stbc_fchy_dia, b2stbc_neoclassical, praverage, &
& b2stbc_fchy_dia_coreonly, secmodel, lbndusr, area_fix, &
& sheath_drift_fix)
  USE B2MOD_TYPES
  USE B2MOD_GEO_DIFFV_DIFFV
  USE B2MOD_RATES
  USE B2MOD_INDIRECT_DIFFV_DIFFV
  USE B2MOD_ANOMALOUS_TRANSPORT_DIFFV_DIFFV
  USE B2MOD_CONSTANTS
  USE B2MOD_GEO_CORNER
  USE B2MOD_B2CMPA_DIFFV_DIFFV
  USE B2MOD_B2CMPB_DIFFV_DIFFV
  USE B2MOD_EXTERNAL_DIFFV_DIFFV
  USE B2MOD_SUBSYS
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!
!-----------------------------------------------------------------------
!.end b2stbc_bas
!
!   ..input arguments (unchanged on exit)
  INTEGER :: nx, ny, ns, ismain, diagno
  REAL(kind=r8) :: facdrift(-1:nx, -1:ny)
  REAL(kind=r8) :: na(-1:nx, -1:ny, 0:ns-1), ua(-1:nx, -1:ny, 0:ns-1), &
& uadia(-1:nx, -1:ny, 0:1, 0:1, 0:ns-1), vaecrb(-1:nx, -1:ny, 0:1, 0:1, &
& 0:ns-1), te(-1:nx, -1:ny), ti(-1:nx, -1:ny), po(-1:nx, -1:ny), ne(-1:&
& nx, -1:ny), ni(-1:nx, -1:ny, 0:1)
  REAL(kind=r8) :: fna(-1:nx, -1:ny, 0:1, 0:1, 0:ns-1), fhe(-1:nx, -1:ny&
& , 0:1, 0:1), fhi(-1:nx, -1:ny, 0:1, 0:1), fch(-1:nx, -1:ny, 0:1, 0:1)&
& , fne(-1:nx, -1:ny, 0:1, 0:1), fni(-1:nx, -1:ny, 0:1, 0:1)
  REAL(kind=r8) :: chce(-1:nx, -1:ny, 0:1, 0:1), chve(-1:nx, -1:ny, 0:1&
& , 0:1), chci(-1:nx, -1:ny, 0:1, 0:1), chvi(-1:nx, -1:ny, 0:1, 0:1), &
& calf(-1:nx, -1:ny, 0:1, 0:1)
  REAL(kind=r8) :: b2stbc_fchy_dia, b2stbc_neoclassical, praverage(2)
!xpb
  LOGICAL :: main_call, lbndusr
  INTEGER :: b2stbc_fchy_dia_coreonly, secmodel, area_fix, &
& sheath_drift_fix
!   ..output arguments (unspecified on entry)
  REAL(kind=r8) :: sna0(-1:nx, -1:ny, 0:1, 0:ns-1), smo0(-1:nx, -1:ny, 0&
& :3, 0:ns-1), she0(-1:nx, -1:ny, 0:3), shi0(-1:nx, -1:ny, 0:3), sch0(-1&
& :nx, -1:ny, 0:3)
!xpb
  LOGICAL :: wrong_flow
!   ..common blocks
!-----------------------------------------------------------------------
!.documentation
!
!  1. purpose
!
!     B2STBC_BAS provides linearised expressions for the sources of
!     density, parallel momentum, electron heat, atom heat, and charge,
!     due to the boundary conditions.
!     Here the boundary conditions are expressed by use of the B2.5
!     format.
!
!-----------------------------------------------------------------------
!.declarations
!
!   ..local variables
  INTEGER :: ncall, n2, ix, iy, is, ireg
  REAL(kind=r8) :: tpz, trz, csb, cst, vte, s0, s1, fche, fchi, t0, csbm&
& , cstm, fchy_dia, seec, naf(0:ns-1), udf(0:ns-1), nef, tef, tif, pof, &
& wdiaf, she_test, shi_test, zaf(0:ns-1), zxf, nxf, taf, prt(-1:nx, -1:&
& ny)
  SAVE ncall
!   ..procedures
  INTRINSIC MAX, ABS, SQRT
  EXTERNAL XERTST, ESEEC0_NODIFF_NODIFF
  EXTERNAL B2XVSG, B2XVFF_NODIFF0, B2XVPS_NODIFF_NODIFF
  INTRINSIC MINVAL
  INTRINSIC MAXVAL
  REAL(r8) :: y1
  REAL(r8) :: max1
  REAL(r8) :: max2
  REAL(r8) :: max3
  REAL(r8) :: max4
  REAL(r8) :: max5
  REAL(r8) :: max6
  REAL(kind=r8) :: max7
  REAL(r8) :: max8
  REAL(r8) :: max9
  REAL(r8) :: max10
  REAL(r8) :: max11
  REAL(r8) :: max12
  REAL(r8) :: max13
  REAL(kind=r8) :: max14
  REAL(kind=r8) :: abs0
  REAL(kind=r8) :: abs1
  REAL(r8) :: max15
  REAL(r8) :: max16
  REAL(r8) :: max17
  REAL(r8) :: max18
  REAL(r8) :: max19
  REAL(r8) :: max20
  REAL(r8) :: max21
  REAL(r8) :: max22
  REAL(kind=r8) :: max23
  REAL(kind=r8) :: abs2
  REAL(kind=r8) :: abs3
  REAL(r8) :: max24
  REAL(r8) :: max25
  REAL(r8) :: max26
  REAL(r8) :: max27
  REAL(r8) :: max28
  REAL(r8) :: max29
  REAL(r8) :: max30
  REAL(r8) :: max31
  REAL(kind=r8) :: max32
  REAL(kind=r8) :: result1
  REAL(kind=r8) :: result2
  REAL(kind=r8) :: result3
  REAL(kind=r8) :: result4
  REAL(kind=r8) :: arg1
  REAL(r8) :: arg10
  REAL(r8) :: result10
  REAL(kind=r8) :: arg2
!   ..initialisation
  DATA ncall /0/
!-----------------------------------------------------------------------
!.computation
!
! ..preliminaries
!   ..subprogram start-up calls
  CALL SUBINI('b2stbc_bas')
!   ..set n2
  n2 = (nx+2)*(ny+2)
!   ..test nx, ny, ns
  CALL XERTST(0 .LE. nx .AND. 0 .LE. ny, 'faulty argument nx, ny')
  CALL XERTST(1 .LE. ns, 'faulty argument ns')
  CALL XERTST(0 .LE. ismain .AND. ismain .LT. ns, &
&       'invalid main plasma species index ismain')
  CALL XERTST(.NOT.is_neutral(ismain), &
&       'invalid main plasma species ismain; must not be neutral')
!   ..test facdrift (not on first call)                                  !xpb
!xpb
  IF (ncall .GT. 0) THEN
    result1 = MINVAL(facdrift)
    result2 = MAXVAL(facdrift)
    CALL XERTST(0.0_R8 .LE. result1 .AND. 1.0_R8 .GE. result2, &
&         'faulty argument facdrift')
  END IF
!   ..extensive tests on first few calls
  IF (ncall .LT. 3) THEN
!    ..test sign of vol, hx, hy
    CALL B2XVSG(n2, vol, 1, 'vol', '.gt.')
    CALL B2XVSG(n2, hx, 1, 'hx', '.gt.')
    CALL B2XVSG(n2, hy, 1, 'hy', '.gt.')
!    ..test state
!    ..test edge values of fne, fni, chce, chve, chci, chvi, calf
    CALL B2XVFF_NODIFF0(nx, ny, fne, 'fne')
    CALL B2XVFF_NODIFF0(nx, ny, fni, 'fni')
    CALL B2XVFF_NODIFF0(nx, ny, chce, 'chce')
    CALL B2XVFF_NODIFF0(nx, ny, chve, 'chve')
    CALL B2XVFF_NODIFF0(nx, ny, chci, 'chci')
    CALL B2XVFF_NODIFF0(nx, ny, chvi, 'chvi')
    CALL B2XVFF_NODIFF0(nx, ny, calf, 'calf')
!    ..test sign of chce, chci
    CALL B2XVSG(n2, chce(-1, -1, 0, 0), 1, 'chce00', '.ge.')
    CALL B2XVSG(n2, chce(-1, -1, 1, 1), 1, 'chce11', '.ge.')
    CALL B2XVSG(n2, chci(-1, -1, 0, 0), 1, 'chci00', '.ge.')
    CALL B2XVSG(n2, chci(-1, -1, 1, 1), 1, 'chci11', '.ge.')
  END IF
!   ..initialise resignore array
  IF (ncall .EQ. 0) THEN
    resignore(-1, -1:ny, 1:2) = 0
    resignore(nx, -1:ny, 1:2) = 0
    resignore(-1:nx, -1, 1:2) = 0
    resignore(-1:nx, ny, 1:2) = 0
  END IF
!  ..compute total pressure
  prt(:, :) = ne(:, :)*te(:, :) + ni(:, :, 0)*ti(:, :)
  DO is=0,ns_ext-1
    prt(:, :) = prt(:, :) + na_ext(:, :, is)*ta_ext(:, :, is)
  END DO
!
  IF (ncall .EQ. 0) WRITE(*, *) 'Doing B2.5-style bc'
!
! ..compute conditions at south boundary
!   ..initialise ireg
  ireg = cbirso
!   ..loop over boundary cells
  DO ix=-1,nx
    IF (region(ix, -1, 0) .NE. 0) THEN
! do not do dead cells
!    ..update ireg
 1    IF (cbrbrk(ireg)*nx .LT. ix + 0.5_R8) THEN
        CALL XERTST(ireg .LT. cbirso + cbnrso - 1, &
&             'error in computing region on south boundary')
        ireg = ireg + 1
        GOTO 1
      ELSE
!    ..compute s0, s1
        s0 = gs(topix(ix, -1), topiy(ix, -1), 1)/qz(ix, -1, 1)
        IF (pbs(topix(ix, -1), topiy(ix, -1), 1) .GE. 0.) THEN
          s1 = pbs(topix(ix, -1), topiy(ix, -1), 1)
        ELSE
          s1 = -pbs(topix(ix, -1), topiy(ix, -1), 1)
        END IF
!    ..compute cell-faced quantities
        DO is=0,ns-1
          result1 = HY1(topix(ix, -1), topiy(ix, -1))
          result2 = HY1(ix, -1)
          result3 = HY1(topix(ix, -1), topiy(ix, -1))
          result4 = HY1(ix, -1)
          naf(is) = (na(ix, -1, is)*result1+na(topix(ix, -1), topiy(ix, &
&           -1), is)*result2)/(result3+result4)
          result1 = HY1(topix(ix, -1), topiy(ix, -1))
          result2 = HY1(ix, -1)
          result3 = HY1(topix(ix, -1), topiy(ix, -1))
          result4 = HY1(ix, -1)
          zaf(is) = (rza(ix, -1, is)*result1+rza(topix(ix, -1), topiy(ix&
&           , -1), is)*result2)/(result3+result4)
        END DO
        result1 = HY1(topix(ix, -1), topiy(ix, -1))
        result2 = HY1(ix, -1)
        result3 = HY1(topix(ix, -1), topiy(ix, -1))
        result4 = HY1(ix, -1)
        tef = (te(ix, -1)*result1+te(topix(ix, -1), topiy(ix, -1))*&
&         result2)/(result3+result4)
        result1 = HY1(topix(ix, -1), topiy(ix, -1))
        result2 = HY1(ix, -1)
        result3 = HY1(topix(ix, -1), topiy(ix, -1))
        result4 = HY1(ix, -1)
        tif = (ti(ix, -1)*result1+ti(topix(ix, -1), topiy(ix, -1))*&
&         result2)/(result3+result4)
        result1 = HY1(topix(ix, -1), topiy(ix, -1))
        result2 = HY1(ix, -1)
        result3 = HY1(topix(ix, -1), topiy(ix, -1))
        result4 = HY1(ix, -1)
        nef = (ne(ix, -1)*result1+ne(topix(ix, -1), topiy(ix, -1))*&
&         result2)/(result3+result4)
        result1 = HY1(topix(ix, -1), topiy(ix, -1))
        result2 = HY1(ix, -1)
        result3 = HY1(topix(ix, -1), topiy(ix, -1))
        result4 = HY1(ix, -1)
        pof = (po(ix, -1)*result1+po(topix(ix, -1), topiy(ix, -1))*&
&         result2)/(result3+result4)
        result1 = HY1(topix(ix, -1), topiy(ix, -1))
        result2 = HY1(ix, -1)
        result3 = HY1(topix(ix, -1), topiy(ix, -1))
        result4 = HY1(ix, -1)
        wdiaf = (prt(ix, -1)*bb(ix, -1, 2)*result1+prt(topix(ix, -1), &
&         topiy(ix, -1))*bb(topix(ix, -1), topiy(ix, -1), 2)*result2)/(&
&         result3+result4)
!    ..compute cst, vte
        tpz = 0.0_R8
        trz = 0.0_R8
        DO is=0,ns-1
          IF (.NOT.is_neutral(is)) THEN
            tpz = tpz + naf(is)*(zaf(is)*tef+tif)
            trz = trz + am(is)*mp*naf(is)
          END IF
        END DO
        DO is=0,ns_ext-1
          IF (.NOT.is_ext_neutral(is)) THEN
            result1 = HY1(topix(ix, -1), topiy(ix, -1))
            result2 = HY1(ix, -1)
            result3 = HY1(topix(ix, -1), topiy(ix, -1))
            result4 = HY1(ix, -1)
            nxf = (na_ext(ix, -1, is)*result1+na_ext(topix(ix, -1), &
&             topiy(ix, -1), is)*result2)/(result3+result4)
            result1 = HY1(topix(ix, -1), topiy(ix, -1))
            result2 = HY1(ix, -1)
            result3 = HY1(topix(ix, -1), topiy(ix, -1))
            result4 = HY1(ix, -1)
            taf = (ta_ext(ix, -1, is)*result1+ta_ext(topix(ix, -1), &
&             topiy(ix, -1), is)*result2)/(result3+result4)
            result1 = HY1(topix(ix, -1), topiy(ix, -1))
            result2 = HY1(ix, -1)
            result3 = HY1(topix(ix, -1), topiy(ix, -1))
            result4 = HY1(ix, -1)
            zxf = (za_ext(ix, -1, is)*result1+za_ext(topix(ix, -1), &
&             topiy(ix, -1), is)*result2)/(result3+result4)
            tpz = tpz + nxf*(zxf*tef+taf)
            trz = trz + am_ext(is)*mp*nxf
          END IF
        END DO
        arg1 = tpz/trz
        cst = SQRT(arg1)
        arg1 = tef/me
        vte = SQRT(arg1)
!    ..compute Bohm fchi, fche
        t0 = 0.0_R8
        DO is=0,ns-1
          t0 = t0 - zaf(is)*fna(topix(ix, -1), topiy(ix, -1), 1, 1, is)
        END DO
        DO is=0,ns_ext-1
          result1 = HY1(topix(ix, -1), topiy(ix, -1))
          result2 = HY1(ix, -1)
          result3 = HY1(topix(ix, -1), topiy(ix, -1))
          result4 = HY1(ix, -1)
          zxf = (za_ext(ix, -1, is)*result1+za_ext(topix(ix, -1), topiy(&
&           ix, -1), is)*result2)/(result3+result4)
          t0 = t0 - zxf*fa_ext(topix(ix, -1), topiy(ix, -1), 1, 1, is)
        END DO
        fchi = qe*t0
!       if(po(ix,-1).ge.0.0_R8) then                                     !xpb
        arg10 = 1.0_R8/(2.0_R8*pi)
        result10 = SQRT(arg10)
        arg2 = -(qe*pof/tef)
        result2 = EXPU2(arg2)
        fche = result10*qe*nef*vte*s1*result2
!       else                                                             !xpb
!         fche = sqrt(1.0_R8/(2.0_R8*pi))*qe*nef*vte*s1                  !xpb
!       endif                                                            !xpb
!sv 01.07.99
        fchy_dia = 0.0_R8
!sv
        result1 = MAXVAL(facdrift)
        IF (result1 .NE. 0.0_R8) THEN
!sv
!xpb
          IF (.NOT.on_closed_surface(ix, -1)) THEN
!xpb
!sv
            IF (periodic_bc .NE. 1 .OR. rightix(ix, -1) .EQ. ix + 1) &
&           THEN
!xpb
!xpb
!sv 01.07.99
!sv
!xpb
              fchy_dia = -(wdiaf*(vol(topix(ix, -1), topiy(ix, -1))+vol(&
&               ix, -1))/(gs(topix(ix, -1), topiy(ix, -1), 2)+gs(ix, -1&
&               , 2))*(onedbsqc(rightix(topix(ix, -1), topiy(ix, -1)), &
&               rightiy(topix(ix, -1), topiy(ix, -1)))-onedbsqc(topix(ix&
&               , -1), topiy(ix, -1)))*facdrift(ix, -1)*b2stbc_fchy_dia)
            ELSE
!xpb
!xpb
!sv 01.07.99
!xpb
!xpb
              fchy_dia = -(wdiaf*(vol(topix(ix, -1), topiy(ix, -1))+vol(&
&               ix, -1))/(gs(topix(ix, -1), topiy(ix, -1), 2)+gs(ix, -1&
&               , 2))*(1.0_R8/wbbv(topix(ix, -1), topiy(ix, -1), 3)**2-&
&               onedbsqc(topix(ix, -1), topiy(ix, -1)))*facdrift(ix, -1)&
&               *b2stbc_fchy_dia)
            END IF
          ELSE IF (on_closed_surface(ix, -1)) THEN
!xpb
!xpb
            IF (periodic_bc .NE. 1 .OR. rightix(ix, -1) .EQ. ix + 1) &
&           THEN
!xpb
!              fchy_dia = -praverage(1)*wbbv(topix(ix,-1),topiy(ix,-1),2)       !xpb
!      &        *(vol(topix(ix,-1),topiy(ix,-1))+vol(ix,-1))
!      &        /(gs(topix(ix,-1),topiy(ix,-1),2)+gs(ix,-1,2))          !sv 01.07.99
!      &        *(OnedBsqc(rightix(topix(ix,-1),topiy(ix,-1)),
!      &                   rightiy(topix(ix,-1),topiy(ix,-1)))
!      &         -OnedBsqc(topix(ix,-1),topiy(ix,-1)))                  !sv
!      &        *facdrift(ix,-1)*b2stbc_fchy_dia                        !xpb
!sv 01.07.99
!sv
              fchy_dia = -(praverage(1)*facdrift(ix, -1)*b2stbc_fchy_dia&
&               *(onedbsqc(rightix(topix(ix, -1), topiy(ix, -1)), &
&               rightiy(topix(ix, -1), topiy(ix, -1)))-onedbsqc(topix(ix&
&               , -1), topiy(ix, -1))))
            ELSE
!xpb
!              fchy_dia = -praverage(1)*wbbv(topix(ix,-1),topiy(ix,-1),2)       !xpb
!      &        *(vol(topix(ix,-1),topiy(ix,-1))+vol(ix,-1))
!      &        /(gs(topix(ix,-1),topiy(ix,-1),2)+gs(ix,-1,2))          !sv 01.07.99
!      &        *(1.0_R8/wbbv(topix(ix,-1),topiy(ix,-1),3)**2
!      &         -OnedBsqc(topix(ix,-1),topiy(ix,-1)))                  !xpb
!      &        *facdrift(ix,-1)*b2stbc_fchy_dia                        !xpb
!sv 01.07.99
!xpb
              fchy_dia = -(praverage(1)*facdrift(ix, -1)*b2stbc_fchy_dia&
&               *(1.0_R8/wbbv(topix(ix, -1), topiy(ix, -1), 3)**2-&
&               onedbsqc(topix(ix, -1), topiy(ix, -1))))
            END IF
          END IF
        ELSE IF (b2stbc_neoclassical .NE. 0.0_R8 .AND. on_closed_surface&
&           (ix, -1)) THEN
!xpb
!xpb
!xpb
          IF (periodic_bc .NE. 1 .OR. rightix(ix, -1) .EQ. ix + 1) THEN
!xpb
!xpb
!xpb
!xpb
            fchy_dia = -(praverage(1)*(onedbsqc(rightix(topix(ix, -1), &
&             topiy(ix, -1)), rightiy(topix(ix, -1), topiy(ix, -1)))-&
&             onedbsqc(topix(ix, -1), topiy(ix, -1)))*&
&             b2stbc_neoclassical)
          ELSE
!xpb
!xpb
!xpb
            fchy_dia = -(praverage(1)*(1.0_R8/wbbv(topix(ix, -1), topiy(&
&             ix, -1), 3)**2-onedbsqc(topix(ix, -1), topiy(ix, -1)))*&
&             b2stbc_neoclassical)
          END IF
        ELSE
!xpb
!xpb
          fchy_dia = 0.0_R8
        END IF
        IF (lbndusr .OR. (.NOT.on_closed_surface(ix, -1) .AND. &
&           b2stbc_fchy_dia_coreonly .EQ. 1)) fchy_dia = 0.0_R8
!    ..loop over species
        DO is=0,ns-1
!     ..compute csb
          arg1 = (zaf(is)*tef+tif)/(am(is)*mp)
          csb = SQRT(arg1)
!     ..compute particle source
!!!     cbsna(6,,) and cbsna(7,,) to be introduced with ua*pbs(,,1)
          sna0(ix, -1, 0, is) = sna0(ix, -1, 0, is) + cbsna(0, is, ireg)&
&           *s0
          sna0(ix, -1, 1, is) = sna0(ix, -1, 1, is) + cbsna(1, is, ireg)&
&           *s0 + cbsna(2, is, ireg)*csb*s0 + cbsna(3, is, ireg)*csb*s1 &
&           + cbsna(4, is, ireg)*cst*s0 + cbsna(5, is, ireg)*cst*s1
!     ..compute parallel momentum source
          smo0(ix, -1, 0, is) = smo0(ix, -1, 0, is) + cbsmo(0, is, ireg)&
&           *s0
!rfs
          smo0(ix, -1, 1, is) = smo0(ix, -1, 1, is) + cbsmo(7, is, ireg)&
&           *s0
          IF (0.0_R8 .LT. fna(topix(ix, -1), topiy(ix, -1), 1, 1, is)) &
&         THEN
            max1 = fna(topix(ix, -1), topiy(ix, -1), 1, 1, is)
          ELSE
            max1 = 0.0_R8
          END IF
          smo0(ix, -1, 2, is) = smo0(ix, -1, 2, is) + cbsmo(1, is, ireg)&
&           *(-csb)*pbs(topix(ix, -1), topiy(ix, -1), 1) + cbsmo(2, is, &
&           ireg)*(-cst)*pbs(topix(ix, -1), topiy(ix, -1), 1) + cbsmo(5&
&           , is, ireg)*max1/na(ix, -1, is)
          IF (0.0_R8 .LT. -fna(topix(ix, -1), topiy(ix, -1), 1, 1, is)) &
&         THEN
            max2 = -fna(topix(ix, -1), topiy(ix, -1), 1, 1, is)
          ELSE
            max2 = 0.0_R8
          END IF
          smo0(ix, -1, 3, is) = smo0(ix, -1, 3, is) + cbsmo(3, is, ireg)&
&           *s0 + cbsmo(4, is, ireg)*s1 + cbsmo(6, is, ireg)*max2/na(ix&
&           , -1, is)
!     ..compute atom heat source
          t0 = na(ix, -1, is)/ni(ix, -1, 0)
          IF (0.0_R8 .LT. fna(topix(ix, -1), topiy(ix, -1), 1, 1, is)) &
&         THEN
            max3 = fna(topix(ix, -1), topiy(ix, -1), 1, 1, is)
          ELSE
            max3 = 0.0_R8
          END IF
          shi0(ix, -1, 0) = shi0(ix, -1, 0) + cbshi(0, is, ireg)*t0*s0 +&
&           cbshi(6, is, ireg)*max3
          shi0(ix, -1, 1) = shi0(ix, -1, 1) + cbshi(1, is, ireg)*t0*s0
          IF (0.0_R8 .LT. -fna(topix(ix, -1), topiy(ix, -1), 1, 1, is)) &
&         THEN
            max4 = -fna(topix(ix, -1), topiy(ix, -1), 1, 1, is)
          ELSE
            max4 = 0.0_R8
          END IF
          shi0(ix, -1, 3) = shi0(ix, -1, 3) + cbshi(2, is, ireg)*t0*csb*&
&           s0 + cbshi(3, is, ireg)*t0*csb*s1 + cbshi(4, is, ireg)*t0*&
&           cst*s0 + cbshi(5, is, ireg)*t0*cst*s1 + cbshi(7, is, ireg)*&
&           max4/ni(ix, -1, 0)
        END DO
        IF (0.0_R8 .LT. fne(topix(ix, -1), topiy(ix, -1), 1, 1)) THEN
          max5 = fne(topix(ix, -1), topiy(ix, -1), 1, 1)
        ELSE
          max5 = 0.0_R8
        END IF
!    ..compute electron heat source
        she0(ix, -1, 0) = she0(ix, -1, 0) + cbshe(0, ireg)*s0 + cbshe(6&
&         , ireg)*max5
        she0(ix, -1, 1) = she0(ix, -1, 1) + cbshe(1, ireg)*s0
        IF (0.0_R8 .LT. -fne(topix(ix, -1), topiy(ix, -1), 1, 1)) THEN
          max6 = -fne(topix(ix, -1), topiy(ix, -1), 1, 1)
        ELSE
          max6 = 0.0_R8
        END IF
        she0(ix, -1, 3) = she0(ix, -1, 3) + cbshe(2, ireg)*vte*s0 + &
&         cbshe(3, ireg)*vte*s1 + cbshe(4, ireg)*cst*s0 + cbshe(5, ireg)&
&         *cst*s1 + cbshe(7, ireg)*max6/ne(ix, -1)
!    ..compute charge source
        sch0(ix, -1, 2) = sch0(ix, -1, 2) + cbsch(0, ireg)*qe*vte*s0 + &
&         cbsch(2, ireg)*qe*vte*s1 + cbsch(4, ireg)*qe*cst*s1
        sch0(ix, -1, 3) = sch0(ix, -1, 3) + cbsch(1, ireg)*qe**2*vte*s0/&
&         te(ix, -1) + cbsch(3, ireg)*qe**2*vte*s1/te(ix, -1) + cbsch(5&
&         , ireg)*qe**2*cst*s1/te(ix, -1)
        IF (secmodel .EQ. 1 .AND. ncall .LT. 3) WRITE(*, *) &
&      'Kin. sec. emiss. coeff. model not available for south boundary!'
        seec = 1.0_R8 - cbsch(7, ireg)
        IF (cbsch(6, ireg)*fchi .LT. (1.0_R8-seec)*fche) THEN
          max7 = (1.0_R8-seec)*fche
        ELSE
          max7 = cbsch(6, ireg)*fchi
        END IF
!       if(po(ix,-1).ge.0.0_R8) then                                     !xpb
        t0 = max7*qe/tef
!       else                                                             !xpb
!         t0 = 0.0_R8                                                    !xpb
!       endif                                                            !xpb
!sv 01.07.99
        sch0(ix, -1, 0) = sch0(ix, -1, 0) + fchy_dia
        sch0(ix, -1, 0) = sch0(ix, -1, 0) + (1.0_R8-seec)*fche - cbsch(6&
&         , ireg)*fchi + t0*po(ix, -1)
        sch0(ix, -1, 1) = sch0(ix, -1, 1) - t0
      END IF
    END IF
  END DO
!
! ..compute conditions at north boundary
!   ..initialise ireg
  ireg = cbirno
!   ..loop over boundary cells
  DO ix=-1,nx
    IF (region(ix, ny, 0) .NE. 0) THEN
! do not do dead cells
!    ..update ireg
 2    IF (cbrbrk(ireg)*nx .LT. ix + 0.5_R8) THEN
        CALL XERTST(ireg .LT. cbirno + cbnrno - 1, &
&             'error in computing region on north boundary')
        ireg = ireg + 1
        GOTO 2
      ELSE
!    ..compute s0, s1
        s0 = gs(ix, ny, 1)/qz(ix, ny, 1)
        IF (pbs(ix, ny, 1) .GE. 0.) THEN
          s1 = pbs(ix, ny, 1)
        ELSE
          s1 = -pbs(ix, ny, 1)
        END IF
!    ..compute cell-faced quantities
        DO is=0,ns-1
          result1 = HY1(bottomix(ix, ny), bottomiy(ix, ny))
          result2 = HY1(ix, ny)
          result3 = HY1(bottomix(ix, ny), bottomiy(ix, ny))
          result4 = HY1(ix, ny)
          naf(is) = (na(ix, ny, is)*result1+na(bottomix(ix, ny), &
&           bottomiy(ix, ny), is)*result2)/(result3+result4)
          result1 = HY1(bottomix(ix, ny), bottomiy(ix, ny))
          result2 = HY1(ix, ny)
          result3 = HY1(bottomix(ix, ny), bottomiy(ix, ny))
          result4 = HY1(ix, ny)
          zaf(is) = (rza(ix, ny, is)*result1+rza(bottomix(ix, ny), &
&           bottomiy(ix, ny), is)*result2)/(result3+result4)
        END DO
        result1 = HY1(bottomix(ix, ny), bottomiy(ix, ny))
        result2 = HY1(ix, ny)
        result3 = HY1(bottomix(ix, ny), bottomiy(ix, ny))
        result4 = HY1(ix, ny)
        tef = (te(ix, ny)*result1+te(bottomix(ix, ny), bottomiy(ix, ny))&
&         *result2)/(result3+result4)
        result1 = HY1(ix, ny)
        result2 = HY1(bottomix(ix, ny), bottomiy(ix, ny))
        result3 = HY1(ix, ny)
        tif = (ti(ix, ny)*hy(bottomix(ix, ny), bottomiy(ix, ny))+ti(&
&         bottomix(ix, ny), bottomiy(ix, ny))*result1)/(result2+result3)
        result1 = HY1(bottomix(ix, ny), bottomiy(ix, ny))
        result2 = HY1(ix, ny)
        result3 = HY1(bottomix(ix, ny), bottomiy(ix, ny))
        result4 = HY1(ix, ny)
        nef = (ne(ix, ny)*result1+ne(bottomix(ix, ny), bottomiy(ix, ny))&
&         *result2)/(result3+result4)
        result1 = HY1(bottomix(ix, ny), bottomiy(ix, ny))
        result2 = HY1(ix, ny)
        result3 = HY1(bottomix(ix, ny), bottomiy(ix, ny))
        result4 = HY1(ix, ny)
        pof = (po(ix, ny)*result1+po(bottomix(ix, ny), bottomiy(ix, ny))&
&         *result2)/(result3+result4)
        result1 = HY1(bottomix(ix, ny), bottomiy(ix, ny))
        result2 = HY1(ix, ny)
        result3 = HY1(bottomix(ix, ny), bottomiy(ix, ny))
        result4 = HY1(ix, ny)
        wdiaf = (prt(ix, ny)*bb(ix, ny, 2)*result1+prt(bottomix(ix, ny)&
&         , bottomiy(ix, ny))*bb(bottomix(ix, ny), bottomiy(ix, ny), 2)*&
&         result2)/(result3+result4)
!    ..compute cst, vte
        tpz = 0.0_R8
        trz = 0.0_R8
        DO is=0,ns-1
          IF (.NOT.is_neutral(is)) THEN
            tpz = tpz + naf(is)*(zaf(is)*tef+tif)
            trz = trz + am(is)*mp*naf(is)
          END IF
        END DO
        DO is=0,ns_ext-1
          IF (.NOT.is_ext_neutral(is)) THEN
            result1 = HY1(bottomix(ix, -1), bottomiy(ix, -1))
            result2 = HY1(ix, -1)
            result3 = HY1(bottomix(ix, -1), bottomiy(ix, -1))
            result4 = HY1(ix, -1)
            nxf = (na_ext(ix, -1, is)*result1+na_ext(bottomix(ix, -1), &
&             bottomiy(ix, -1), is)*result2)/(result3+result4)
            result1 = HY1(bottomix(ix, -1), bottomiy(ix, -1))
            result2 = HY1(ix, -1)
            result3 = HY1(bottomix(ix, -1), bottomiy(ix, -1))
            result4 = HY1(ix, -1)
            taf = (ta_ext(ix, -1, is)*result1+ta_ext(bottomix(ix, -1), &
&             bottomiy(ix, -1), is)*result2)/(result3+result4)
            result1 = HY1(bottomix(ix, -1), bottomiy(ix, -1))
            result2 = HY1(ix, -1)
            result3 = HY1(bottomix(ix, -1), bottomiy(ix, -1))
            result4 = HY1(ix, -1)
            zxf = (za_ext(ix, -1, is)*result1+za_ext(bottomix(ix, -1), &
&             bottomiy(ix, -1), is)*result2)/(result3+result4)
            tpz = tpz + nxf*(zxf*tef+taf)
            trz = trz + am_ext(is)*mp*nxf
          END IF
        END DO
        arg1 = tpz/trz
        cst = SQRT(arg1)
        arg1 = tef/me
        vte = SQRT(arg1)
!    ..compute Bohm fchi, fche
        t0 = 0.0_R8
        DO is=0,ns-1
          t0 = t0 + zaf(is)*fna(ix, ny, 1, 1, is)
        END DO
        DO is=0,ns_ext-1
          result1 = HY1(bottomix(ix, -1), bottomiy(ix, -1))
          result2 = HY1(ix, -1)
          result3 = HY1(bottomix(ix, -1), bottomiy(ix, -1))
          result4 = HY1(ix, -1)
          zxf = (za_ext(ix, -1, is)*result1+za_ext(bottomix(ix, -1), &
&           bottomiy(ix, -1), is)*result2)/(result3+result4)
          t0 = t0 + zxf*fa_ext(ix, ny, 1, 1, is)
        END DO
        fchi = qe*t0
!       if(po(ix,ny).ge.0.0_R8) then                                     !xpb
        arg10 = 1.0_R8/(2.0_R8*pi)
        result10 = SQRT(arg10)
        arg2 = -(qe*pof/tef)
        result2 = EXPU2(arg2)
        fche = result10*qe*nef*vte*s1*result2
!       else                                                             !xpb
!         fche = sqrt(1.0_R8/(2.0_R8*pi))*qe*nef*vte*s1                  !xpb
!       endif                                                            !xpb
!sv 01.07.99
        fchy_dia = 0.0_R8
!sv
        result1 = MAXVAL(facdrift)
        IF (result1 .NE. 0.0_R8) THEN
!xpb
!xpb
          IF (region(ix, ny, 0) .NE. 5) THEN
!xpb
!sv
!sv 01.07.99
!sv 01.07.99
!xpb
            fchy_dia = -(wdiaf*(vol(ix, ny)+vol(bottomix(ix, ny), &
&             bottomiy(ix, ny)))/(gs(ix, ny, 2)+gs(bottomix(ix, ny), &
&             bottomiy(ix, ny), 2))*(onedbsqc(rightix(ix, ny), rightiy(&
&             ix, ny))-onedbsqc(ix, ny))*facdrift(ix, ny)*&
&             b2stbc_fchy_dia)
          ELSE
!xpb
!            fchy_dia = -praverage(2)*wbbv(ix,ny,2)                     !xpb
!      .      *(vol(bottomix(ix,ny),bottomiy(ix,ny))+vol(ix,ny))
!      .      /(gs(bottomix(ix,ny),bottomiy(ix,ny),2)+gs(ix,ny,2))      !xpb
!      .      *(OnedBsqc(rightix(bottomix(ix,ny),bottomiy(ix,ny)),
!      .                 rightiy(bottomix(ix,ny),bottomiy(ix,ny)))      !xpb
!      .       -OnedBsqc(bottomix(ix,ny),bottomiy(ix,ny)))
!      .      *facdrift(ix,ny)*b2stbc_fchy_dia                          !xpb
!sv 01.07.99
!sv
            fchy_dia = -(praverage(2)*facdrift(ix, ny)*b2stbc_fchy_dia*(&
&             onedbsqc(rightix(ix, ny), rightiy(ix, ny))-onedbsqc(ix, ny&
&             )))
          END IF
        ELSE IF (b2stbc_neoclassical .NE. 0.0_R8 .AND. on_closed_surface&
&           (ix, ny)) THEN
!xpb
!xpb
!xpb
          fchy_dia = -(praverage(2)*(onedbsqc(rightix(ix, ny), rightiy(&
&           ix, ny))-onedbsqc(ix, ny))*b2stbc_neoclassical)
        ELSE
!xpb
!sv
          fchy_dia = 0.0_R8
        END IF
        IF (lbndusr .OR. b2stbc_fchy_dia_coreonly .EQ. 1) fchy_dia = &
&           0.0_R8
!    ..loop over species
        DO is=0,ns-1
!     ..compute csb
          arg1 = (zaf(is)*tef+tif)/(am(is)*mp)
          csb = SQRT(arg1)
!     ..compute particle source
!!!     cbsna(6,,) and cbsna(7,,) to be introduced with ua*pbs(,,1)
          sna0(ix, ny, 0, is) = sna0(ix, ny, 0, is) + cbsna(0, is, ireg)&
&           *s0
          sna0(ix, ny, 1, is) = sna0(ix, ny, 1, is) + cbsna(1, is, ireg)&
&           *s0 + cbsna(2, is, ireg)*csb*s0 + cbsna(3, is, ireg)*csb*s1 &
&           + cbsna(4, is, ireg)*cst*s0 + cbsna(5, is, ireg)*cst*s1
!     ..compute parallel momentum source
          smo0(ix, ny, 0, is) = smo0(ix, ny, 0, is) + cbsmo(0, is, ireg)&
&           *s0
!rfs
          smo0(ix, ny, 1, is) = smo0(ix, ny, 1, is) + cbsmo(7, is, ireg)&
&           *s0
          IF (0.0_R8 .LT. -fna(ix, ny, 1, 1, is)) THEN
            max8 = -fna(ix, ny, 1, 1, is)
          ELSE
            max8 = 0.0_R8
          END IF
          smo0(ix, ny, 2, is) = smo0(ix, ny, 2, is) + cbsmo(1, is, ireg)&
&           *csb*pbs(ix, ny, 1) + cbsmo(2, is, ireg)*cst*pbs(ix, ny, 1) &
&           + cbsmo(5, is, ireg)*max8/na(ix, ny, is)
          IF (0.0_R8 .LT. fna(ix, ny, 1, 1, is)) THEN
            max9 = fna(ix, ny, 1, 1, is)
          ELSE
            max9 = 0.0_R8
          END IF
          smo0(ix, ny, 3, is) = smo0(ix, ny, 3, is) + cbsmo(3, is, ireg)&
&           *s0 + cbsmo(4, is, ireg)*s1 + cbsmo(6, is, ireg)*max9/na(ix&
&           , ny, is)
!     ..compute atom heat source
          t0 = na(ix, ny, is)/ni(ix, ny, 0)
          IF (0.0_R8 .LT. -fna(ix, ny, 1, 1, is)) THEN
            max10 = -fna(ix, ny, 1, 1, is)
          ELSE
            max10 = 0.0_R8
          END IF
          shi0(ix, ny, 0) = shi0(ix, ny, 0) + cbshi(0, is, ireg)*t0*s0 +&
&           cbshi(6, is, ireg)*max10
          shi0(ix, ny, 1) = shi0(ix, ny, 1) + cbshi(1, is, ireg)*t0*s0
          IF (0.0_R8 .LT. fna(ix, ny, 1, 1, is)) THEN
            max11 = fna(ix, ny, 1, 1, is)
          ELSE
            max11 = 0.0_R8
          END IF
          shi0(ix, ny, 3) = shi0(ix, ny, 3) + cbshi(2, is, ireg)*t0*csb*&
&           s0 + cbshi(3, is, ireg)*t0*csb*s1 + cbshi(4, is, ireg)*t0*&
&           cst*s0 + cbshi(5, is, ireg)*t0*cst*s1 + cbshi(7, is, ireg)*&
&           max11/ni(ix, ny, 0)
        END DO
        IF (0.0_R8 .LT. -fne(ix, ny, 1, 1)) THEN
          max12 = -fne(ix, ny, 1, 1)
        ELSE
          max12 = 0.0_R8
        END IF
!    ..compute electron heat source
        she0(ix, ny, 0) = she0(ix, ny, 0) + cbshe(0, ireg)*s0 + cbshe(6&
&         , ireg)*max12
        she0(ix, ny, 1) = she0(ix, ny, 1) + cbshe(1, ireg)*s0
        IF (0.0_R8 .LT. fne(ix, ny, 1, 1)) THEN
          max13 = fne(ix, ny, 1, 1)
        ELSE
          max13 = 0.0_R8
        END IF
        she0(ix, ny, 3) = she0(ix, ny, 3) + cbshe(2, ireg)*vte*s0 + &
&         cbshe(3, ireg)*vte*s1 + cbshe(4, ireg)*cst*s0 + cbshe(5, ireg)&
&         *cst*s1 + cbshe(7, ireg)*max13/ne(ix, ny)
!    ..compute charge source
        sch0(ix, ny, 2) = sch0(ix, ny, 2) + cbsch(0, ireg)*qe*vte*s0 + &
&         cbsch(2, ireg)*qe*vte*s1 + cbsch(4, ireg)*qe*cst*s1
        sch0(ix, ny, 3) = sch0(ix, ny, 3) + cbsch(1, ireg)*qe**2*vte*s0/&
&         te(ix, ny) + cbsch(3, ireg)*qe**2*vte*s1/te(ix, ny) + cbsch(5&
&         , ireg)*qe**2*cst*s1/te(ix, ny)
        IF (secmodel .EQ. 1 .AND. ncall .LT. 3) WRITE(*, *) &
&      'Kin. sec. emiss. coeff. model not available for north boundary!'
        seec = 1.0_R8 - cbsch(7, ireg)
        IF (cbsch(6, ireg)*fchi .LT. (1.0_R8-seec)*fche) THEN
          max14 = (1.0_R8-seec)*fche
        ELSE
          max14 = cbsch(6, ireg)*fchi
        END IF
!       if(po(ix,ny).ge.0.0_R8) then                                     !xpb
        t0 = max14*qe/tef
!       else                                                             !xpb
!         t0 = 0.0_R8                                                    !xpb
!       endif                                                            !xpb
!sv  minus 01.07.99
        sch0(ix, ny, 0) = sch0(ix, ny, 0) - fchy_dia
        sch0(ix, ny, 0) = sch0(ix, ny, 0) + (1.0_R8-seec)*fche - cbsch(6&
&         , ireg)*fchi + t0*po(ix, ny)
        sch0(ix, ny, 1) = sch0(ix, ny, 1) - t0
      END IF
    END IF
  END DO
!
! ..compute conditions at west boundary
!   ..initialise ireg
  ireg = cbirwe
!   ..loop over boundary cells
  DO iy=-1,ny
    IF (region(-1, iy, 0) .NE. 0) THEN
! do not do dead cells
!    ..update ireg
 3    IF (cbrbrk(ireg)*ny .LT. iy + 0.5_R8) THEN
        CALL XERTST(ireg .LT. cbirwe + cbnrwe - 1, &
&             'error in computing region on west boundary')
        ireg = ireg + 1
        GOTO 3
      ELSE
!    ..compute s0, s1: hb
        s0 = gs(rightix(-1, iy), rightiy(-1, iy), 0)
!srv 09.03.09
        IF (area_fix .GE. 3) s0 = s0*qc(rightix(-1, iy), rightiy(-1, iy)&
&           , 0)
        IF (pbs(rightix(-1, iy), rightiy(-1, iy), 0) .GE. 0.) THEN
          s1 = pbs(rightix(-1, iy), rightiy(-1, iy), 0)
        ELSE
          s1 = -pbs(rightix(-1, iy), rightiy(-1, iy), 0)
        END IF
!    ..compute cell-faced quantities
        DO is=0,ns-1
          naf(is) = (na(-1, iy, is)*hx(rightix(-1, iy), rightiy(-1, iy))&
&           +na(rightix(-1, iy), rightiy(-1, iy), is)*hx(-1, iy))/(hx(&
&           rightix(-1, iy), rightiy(-1, iy))+hx(-1, iy))
          zaf(is) = (rza(-1, iy, is)*hx(rightix(-1, iy), rightiy(-1, iy)&
&           )+rza(rightix(-1, iy), rightiy(-1, iy), is)*hx(-1, iy))/(hx(&
&           rightix(-1, iy), rightiy(-1, iy))+hx(-1, iy))
!xpb  Following suggestion from Russians, the drift velocity should
!xpb  only include ExB terms and not diamagnetic contributions
          IF (sheath_drift_fix .EQ. 0) THEN
            udf(is) = (uadia(-1, iy, 0, 0, is)*hx(rightix(-1, iy), &
&             rightiy(-1, iy))+uadia(rightix(-1, iy), rightiy(-1, iy), 0&
&             , 0, is)*hx(-1, iy))/(hx(rightix(-1, iy), rightiy(-1, iy))&
&             +hx(-1, iy))
          ELSE
            udf(is) = (vaecrb(-1, iy, 0, 0, is)*hx(rightix(-1, iy), &
&             rightiy(-1, iy))+vaecrb(rightix(-1, iy), rightiy(-1, iy), &
&             0, 0, is)*hx(-1, iy))/(hx(rightix(-1, iy), rightiy(-1, iy)&
&             )+hx(-1, iy))
          END IF
        END DO
        tef = (te(-1, iy)*hx(rightix(-1, iy), rightiy(-1, iy))+te(&
&         rightix(-1, iy), rightiy(-1, iy))*hx(-1, iy))/(hx(rightix(-1, &
&         iy), rightiy(-1, iy))+hx(-1, iy))
        tif = (ti(-1, iy)*hx(rightix(-1, iy), rightiy(-1, iy))+ti(&
&         rightix(-1, iy), rightiy(-1, iy))*hx(-1, iy))/(hx(rightix(-1, &
&         iy), rightiy(-1, iy))+hx(-1, iy))
        nef = (ne(-1, iy)*hx(rightix(-1, iy), rightiy(-1, iy))+ne(&
&         rightix(-1, iy), rightiy(-1, iy))*hx(-1, iy))/(hx(rightix(-1, &
&         iy), rightiy(-1, iy))+hx(-1, iy))
        pof = (po(-1, iy)*hx(rightix(-1, iy), rightiy(-1, iy))+po(&
&         rightix(-1, iy), rightiy(-1, iy))*hx(-1, iy))/(hx(rightix(-1, &
&         iy), rightiy(-1, iy))+hx(-1, iy))
!    ..compute cst, vte
        tpz = 0.0_R8
        trz = 0.0_R8
        DO is=0,ns-1
          IF (.NOT.is_neutral(is)) THEN
            tpz = tpz + naf(is)*(zaf(is)*tef+tif)
            trz = trz + am(is)*mp*naf(is)
          END IF
        END DO
        DO is=0,ns_ext-1
          IF (.NOT.is_ext_neutral(is)) THEN
            nxf = (na_ext(-1, iy, is)*hx(rightix(-1, iy), rightiy(-1, iy&
&             ))+na_ext(rightix(-1, iy), rightiy(-1, iy), is)*hx(-1, iy)&
&             )/(hx(rightix(-1, iy), rightiy(-1, iy))+hx(-1, iy))
            zxf = (za_ext(-1, iy, is)*hx(rightix(-1, iy), rightiy(-1, iy&
&             ))+za_ext(rightix(-1, iy), rightiy(-1, iy), is)*hx(-1, iy)&
&             )/(hx(rightix(-1, iy), rightiy(-1, iy))+hx(-1, iy))
            taf = (ta_ext(-1, iy, is)*hx(rightix(-1, iy), rightiy(-1, iy&
&             ))+ta_ext(rightix(-1, iy), rightiy(-1, iy), is)*hx(-1, iy)&
&             )/(hx(rightix(-1, iy), rightiy(-1, iy))+hx(-1, iy))
            tpz = tpz + nxf*(zxf*tef+taf)
            trz = trz + am_ext(is)*mp*nxf
          END IF
        END DO
        arg1 = tpz/trz
        cst = SQRT(arg1)
        arg1 = tef/me
        vte = SQRT(arg1)
!    ..compute Bohm fchi, fche
        t0 = 0.0_R8
        DO is=0,ns-1
          t0 = t0 - zaf(is)*fna(rightix(-1, iy), rightiy(-1, iy), 0, 0, &
&           is)
        END DO
        DO is=0,ns_ext-1
          zxf = (za_ext(-1, iy, is)*hx(rightix(-1, iy), rightiy(-1, iy))&
&           +za_ext(rightix(-1, iy), rightiy(-1, iy), is)*hx(-1, iy))/(&
&           hx(rightix(-1, iy), rightiy(-1, iy))+hx(-1, iy))
          t0 = t0 - zxf*fa_ext(rightix(-1, iy), rightiy(-1, iy), 0, 0, &
&           is)
        END DO
        fchi = qe*t0
        IF (t0 .LT. 0.0_R8 .AND. region(-1, iy, 0) .NE. 0 .AND. bottomiy&
&           (-1, iy) .NE. -2 .AND. topiy(-1, iy) .NE. ny + 1) THEN
!xpb
          wrong_flow = .true.
          IF (diagno .GE. 0) THEN
            WRITE(*, *) 'b2stbc_west:iy,fchi', iy, fchi
            WRITE(*, *) zaf(ismain), fna(rightix(-1, iy), rightiy(-1, iy&
&           ), 0, 0, ismain)
            WRITE(*, '(a,4g14.7)') 'Bx,Bz,Ud,-Ua =', wbbr(-1, iy, 0), &
&           wbbr(-1, iy, 2), udf(ismain), -ua(-1, iy, ismain)
          END IF
        END IF
!         fchi=0.0_R8
!       if (po(-1,iy).ge.0.0_R8) then                                    !sv
!sv
        arg10 = 1.0_R8/(2.0_R8*pi)
        result10 = SQRT(arg10)
        arg2 = -(qe*pof/tef)
        result2 = EXPU2(arg2)
        fche = result10*qe*nef*vte*s1*result2
!       else                                                             !sv
!         fche = sqrt(1.0_R8/(2.0_R8*pi))*qe*nef*vte*s1                  !sv
!       endif
!    ..loop over species
        DO is=0,ns-1
!     ..compute csb
          arg1 = (zaf(is)*tef+tif)/(am(is)*mp)
          csb = SQRT(arg1)
          IF (wbbr(-1, iy, 2)/wbbr(-1, iy, 0) .GE. 0.) THEN
            abs0 = wbbr(-1, iy, 2)/wbbr(-1, iy, 0)
          ELSE
            abs0 = -(wbbr(-1, iy, 2)/wbbr(-1, iy, 0))
          END IF
!     .. account for diamagnetic drifts
!xpb
          csbm = csb + udf(is)*abs0
          IF (wbbr(-1, iy, 2)/wbbr(-1, iy, 0) .GE. 0.) THEN
            abs1 = wbbr(-1, iy, 2)/wbbr(-1, iy, 0)
          ELSE
            abs1 = -(wbbr(-1, iy, 2)/wbbr(-1, iy, 0))
          END IF
!xpb
          cstm = cst + udf(is)*abs1
!xpb
          IF (.NOT.is_neutral(is)) THEN
            IF (0.0_R8 .LT. csbm) THEN
              csbm = csbm
            ELSE
              csbm = 0.0_R8
            END IF
            IF (0.0_R8 .LT. cstm) THEN
              cstm = cstm
            ELSE
              cstm = 0.0_R8
            END IF
          END IF
          IF (csbm .GT. csb .AND. diagno .GE. 2) WRITE(*, *) &
&                                                'west:iy,is,csb,csbm', &
&                                                iy, is, csb, csbm
          IF (cstm .GT. cst .AND. diagno .GE. 2) WRITE(*, *) &
&                                                'west:iy,is,cst,cstm', &
&                                                iy, is, cst, cstm
          y1 = ua(-1, iy, is)*pbs(rightix(-1, iy), rightiy(-1, iy), 0)
          IF (0.0_R8 .LT. y1) THEN
            max15 = y1
          ELSE
            max15 = 0.0_R8
          END IF
!     ..compute particle source hb
          sna0(-1, iy, 0, is) = sna0(-1, iy, 0, is) + cbsna(0, is, ireg)&
&           *s0 + cbsna(6, is, ireg)*max15
          IF (0.0_R8 .LT. -(ua(-1, iy, is)*pbs(rightix(-1, iy), rightiy(&
&             -1, iy), 0))) THEN
            max16 = -(ua(-1, iy, is)*pbs(rightix(-1, iy), rightiy(-1, iy&
&             ), 0))
          ELSE
            max16 = 0.0_R8
          END IF
          sna0(-1, iy, 1, is) = sna0(-1, iy, 1, is) + cbsna(1, is, ireg)&
&           *s0 + cbsna(2, is, ireg)*csbm*s0 + cbsna(3, is, ireg)*csbm*&
&           s1 + cbsna(4, is, ireg)*cstm*s0 + cbsna(5, is, ireg)*cstm*s1&
&           + cbsna(7, is, ireg)*max16
!     ..compute parallel momentum source
          smo0(-1, iy, 0, is) = smo0(-1, iy, 0, is) + cbsmo(0, is, ireg)&
&           *s0
!rfs
          smo0(-1, iy, 1, is) = smo0(-1, iy, 1, is) + cbsmo(7, is, ireg)&
&           *s0
          IF (0.0_R8 .LT. -fna(rightix(-1, iy), rightiy(-1, iy), 0, 0, &
&             is)) THEN
            max17 = -fna(rightix(-1, iy), rightiy(-1, iy), 0, 0, is)
          ELSE
            max17 = 0.0_R8
          END IF
!xpb
!xpb
!sv
          smo0(-1, iy, 2, is) = smo0(-1, iy, 2, is) + cbsmo(1, is, ireg)&
&           *(-csbm)*pbs(rightix(-1, iy), rightiy(-1, iy), 0) + cbsmo(2&
&           , is, ireg)*(-cstm)*pbs(rightix(-1, iy), rightiy(-1, iy), 0)&
&           + cbsmo(5, is, ireg)*max17/na(-1, iy, is)
          IF (0.0_R8 .LT. -fna(rightix(-1, iy), rightiy(-1, iy), 0, 0, &
&             is)) THEN
            max18 = -fna(rightix(-1, iy), rightiy(-1, iy), 0, 0, is)
          ELSE
            max18 = 0.0_R8
          END IF
          smo0(-1, iy, 3, is) = smo0(-1, iy, 3, is) + cbsmo(3, is, ireg)&
&           *s0 + cbsmo(4, is, ireg)*s1 + cbsmo(6, is, ireg)*max18/na(-1&
&           , iy, is)
!     ..compute atom heat source
          t0 = na(-1, iy, is)/ni(-1, iy, 0)
          IF (0.0_R8 .LT. fna(rightix(-1, iy), rightiy(-1, iy), 0, 0, is&
&             )) THEN
            max19 = fna(rightix(-1, iy), rightiy(-1, iy), 0, 0, is)
          ELSE
            max19 = 0.0_R8
          END IF
          shi0(-1, iy, 0) = shi0(-1, iy, 0) + cbshi(0, is, ireg)*t0*s0 +&
&           cbshi(6, is, ireg)*max19
          shi0(-1, iy, 1) = shi0(-1, iy, 1) + cbshi(1, is, ireg)*t0*s0
          IF (0.0_R8 .LT. -fna(rightix(-1, iy), rightiy(-1, iy), 0, 0, &
&             is)) THEN
            max20 = -fna(rightix(-1, iy), rightiy(-1, iy), 0, 0, is)
          ELSE
            max20 = 0.0_R8
          END IF
          shi0(-1, iy, 3) = shi0(-1, iy, 3) + cbshi(2, is, ireg)*t0*csbm&
&           *s0 + cbshi(3, is, ireg)*t0*csbm*s1 + cbshi(4, is, ireg)*t0*&
&           cstm*s0 + cbshi(5, is, ireg)*t0*cstm*s1 + cbshi(7, is, ireg)&
&           *max20/ni(-1, iy, 0)
        END DO
        shi_test = shi0(-1, iy, 0) + shi0(-1, iy, 1)*ti(-1, iy) + shi0(-&
&         1, iy, 2)*ni(-1, iy, 0) + shi0(-1, iy, 3)*ni(-1, iy, 0)*ti(-1&
&         , iy)
        IF (shi_test .GT. 0.0_R8 .AND. diagno .GE. 2) WRITE(*, *) &
&                                                     'shi_test>0: W ', &
&                                                     iy, shi0(-1, iy, :&
&                                                     ), ti(-1, iy)/qe, &
&                                                     ni(-1, iy, 0), s0&
&                                                     , s1, csbm, cstm, &
&                                                     ireg, cbshi(:, :, &
&                                                     ireg)
        IF (0.0_R8 .LT. fne(rightix(-1, iy), rightiy(-1, iy), 0, 0)) &
&       THEN
          max21 = fne(rightix(-1, iy), rightiy(-1, iy), 0, 0)
        ELSE
          max21 = 0.0_R8
        END IF
!    ..compute electron heat source
        she0(-1, iy, 0) = she0(-1, iy, 0) + cbshe(0, ireg)*s0 + cbshe(6&
&         , ireg)*max21
        she0(-1, iy, 1) = she0(-1, iy, 1) + cbshe(1, ireg)*s0
        IF (0.0_R8 .LT. -fne(rightix(-1, iy), rightiy(-1, iy), 0, 0)) &
&       THEN
          max22 = -fne(rightix(-1, iy), rightiy(-1, iy), 0, 0)
        ELSE
          max22 = 0.0_R8
        END IF
        she0(-1, iy, 3) = she0(-1, iy, 3) + cbshe(2, ireg)*vte*s0 + &
&         cbshe(3, ireg)*vte*s1 + cbshe(4, ireg)*cstm*s0 + cbshe(5, ireg&
&         )*cstm*s1 + cbshe(7, ireg)*max22/ne(-1, iy)
        she_test = she0(-1, iy, 0) + she0(-1, iy, 1)*te(-1, iy) + she0(-&
&         1, iy, 2)*ne(-1, iy) + she0(-1, iy, 3)*ne(-1, iy)*te(-1, iy)
        IF (she_test .GT. 0.0_R8 .AND. diagno .GE. 2) WRITE(*, *) &
&                                                     'she_test>0: W ', &
&                                                     iy, she0(-1, iy, :&
&                                                     ), te(-1, iy)/qe, &
&                                                     ne(-1, iy), s0, s1&
&                                                     , vte, cstm, ireg&
&                                                     , cbshe(:, ireg)
!    ..compute charge source
        sch0(-1, iy, 2) = sch0(-1, iy, 2) + cbsch(0, ireg)*qe*vte*s0 + &
&         cbsch(2, ireg)*qe*vte*s1 + cbsch(4, ireg)*qe*cstm*s1
        sch0(-1, iy, 3) = sch0(-1, iy, 3) + cbsch(1, ireg)*qe**2*vte*s0/&
&         te(-1, iy) + cbsch(3, ireg)*qe**2*vte*s1/te(-1, iy) + cbsch(5&
&         , ireg)*qe**2*cstm*s1/te(-1, iy)
        IF (secmodel .EQ. 1) THEN
          IF (ne(-1, iy)/(rza(-1, iy, ismain)*na(-1, iy, ismain)) .GT. &
&             1.1_R8) THEN
            WRITE(*, *) 'Large ne contribution from impurities!'
            WRITE(*, *) 'Kinetic s.e.c. model may not be valid!'
          END IF
          CALL ESEEC0_NODIFF_NODIFF(tef, tif, nef, pof, wbbr(-1, iy, 0)&
&                             , wbbr(-1, iy, 3), 0, -1, iy, nx, ny, ns, &
&                             ismain, seec, diagno)
!cfs
        ELSE
          seec = 1.0_R8 - cbsch(7, ireg)
        END IF
        IF (cbsch(6, ireg)*fchi .LT. (1.0_R8-seec)*fche) THEN
          max23 = (1.0_R8-seec)*fche
        ELSE
          max23 = cbsch(6, ireg)*fchi
        END IF
!       if (po(-1,iy).ge.0.0_R8) then                                   !sv
        t0 = max23*qe/tef
!       else                                                            !sv
!         t0 = 0.0_R8                                                   !sv
!       endif                                                           !sv
        sch0(-1, iy, 0) = sch0(-1, iy, 0) + (1.0_R8-seec)*fche - cbsch(6&
&         , ireg)*fchi + t0*po(-1, iy)
        sch0(-1, iy, 1) = sch0(-1, iy, 1) - t0
      END IF
    END IF
  END DO
!
! ..compute conditions at east boundary
!   ..initialise ireg
  ireg = cbirea
!   ..loop over boundary cells
  DO iy=-1,ny
    IF (region(nx, iy, 0) .NE. 0) THEN
! do not do dead cells
!    ..update ireg
 4    IF (cbrbrk(ireg)*ny .LT. iy + 0.5_R8) THEN
        CALL XERTST(ireg .LT. cbirea + cbnrea - 1, &
&             'error in computing region on east boundary')
        ireg = ireg + 1
        GOTO 4
      ELSE
!    ..compute s0, s1
        s0 = gs(nx, iy, 0)
!srv 09.03.09
        IF (area_fix .GE. 3) s0 = s0*qc(nx, iy, 0)
        IF (pbs(nx, iy, 0) .GE. 0.) THEN
          s1 = pbs(nx, iy, 0)
        ELSE
          s1 = -pbs(nx, iy, 0)
        END IF
!    ..compute cell-faced quantities
        DO is=0,ns-1
          naf(is) = (na(nx, iy, is)*hx(leftix(nx, iy), leftiy(nx, iy))+&
&           na(leftix(nx, iy), leftiy(nx, iy), is)*hx(nx, iy))/(hx(&
&           leftix(nx, iy), leftiy(nx, iy))+hx(nx, iy))
          zaf(is) = (rza(nx, iy, is)*hx(leftix(nx, iy), leftiy(nx, iy))+&
&           rza(leftix(nx, iy), leftiy(nx, iy), is)*hx(nx, iy))/(hx(&
&           leftix(nx, iy), leftiy(nx, iy))+hx(nx, iy))
!xpb  Following suggestion from Russians, the drift velocity should
!xpb  only include ExB terms and not diamagnetic contributions
          IF (sheath_drift_fix .EQ. 0) THEN
            udf(is) = (uadia(nx, iy, 0, 0, is)*hx(leftix(nx, iy), leftiy&
&             (nx, iy))+uadia(leftix(nx, iy), leftiy(nx, iy), 0, 0, is)*&
&             hx(nx, iy))/(hx(leftix(nx, iy), leftiy(nx, iy))+hx(nx, iy)&
&             )
          ELSE
            udf(is) = (vaecrb(nx, iy, 0, 0, is)*hx(leftix(nx, iy), &
&             leftiy(nx, iy))+vaecrb(leftix(nx, iy), leftiy(nx, iy), 0, &
&             0, is)*hx(nx, iy))/(hx(leftix(nx, iy), leftiy(nx, iy))+hx(&
&             nx, iy))
          END IF
        END DO
        tef = (te(nx, iy)*hx(leftix(nx, iy), leftiy(nx, iy))+te(leftix(&
&         nx, iy), leftiy(nx, iy))*hx(nx, iy))/(hx(leftix(nx, iy), &
&         leftiy(nx, iy))+hx(nx, iy))
        tif = (ti(nx, iy)*hx(leftix(nx, iy), leftiy(nx, iy))+ti(leftix(&
&         nx, iy), leftiy(nx, iy))*hx(nx, iy))/(hx(leftix(nx, iy), &
&         leftiy(nx, iy))+hx(nx, iy))
        nef = (ne(nx, iy)*hx(leftix(nx, iy), leftiy(nx, iy))+ne(leftix(&
&         nx, iy), leftiy(nx, iy))*hx(nx, iy))/(hx(leftix(nx, iy), &
&         leftiy(nx, iy))+hx(nx, iy))
        pof = (po(nx, iy)*hx(leftix(nx, iy), leftiy(nx, iy))+po(leftix(&
&         nx, iy), leftiy(nx, iy))*hx(nx, iy))/(hx(leftix(nx, iy), &
&         leftiy(nx, iy))+hx(nx, iy))
!    ..compute cst, vte
        tpz = 0.0_R8
        trz = 0.0_R8
        DO is=0,ns-1
          IF (.NOT.is_neutral(is)) THEN
            tpz = tpz + naf(is)*(zaf(is)*tef+tif)
            trz = trz + am(is)*mp*naf(is)
          END IF
        END DO
        DO is=0,ns_ext-1
          IF (.NOT.is_ext_neutral(is)) THEN
            nxf = (na_ext(nx, iy, is)*hx(leftix(nx, iy), leftiy(nx, iy))&
&             +na_ext(leftix(nx, iy), leftiy(nx, iy), is)*hx(nx, iy))/(&
&             hx(leftix(nx, iy), leftiy(nx, iy))+hx(nx, iy))
            zxf = (za_ext(nx, iy, is)*hx(leftix(nx, iy), leftiy(nx, iy))&
&             +za_ext(leftix(nx, iy), leftiy(nx, iy), is)*hx(nx, iy))/(&
&             hx(leftix(nx, iy), leftiy(nx, iy))+hx(nx, iy))
            taf = (ta_ext(nx, iy, is)*hx(leftix(nx, iy), leftiy(nx, iy))&
&             +ta_ext(leftix(nx, iy), leftiy(nx, iy), is)*hx(nx, iy))/(&
&             hx(leftix(nx, iy), leftiy(nx, iy))+hx(nx, iy))
            tpz = tpz + nxf*(zxf*tef+taf)
            trz = trz + am_ext(is)*mp*nxf
          END IF
        END DO
        arg1 = tpz/trz
        cst = SQRT(arg1)
        arg1 = tef/me
        vte = SQRT(arg1)
!    ..compute Bohm fchi, fche
        t0 = 0.0_R8
        DO is=0,ns-1
          t0 = t0 + zaf(is)*fna(nx, iy, 0, 0, is)
        END DO
        DO is=0,ns_ext-1
          zxf = (za_ext(nx, iy, is)*hx(leftix(nx, iy), leftiy(nx, iy))+&
&           za_ext(leftix(nx, iy), leftiy(nx, iy), is)*hx(nx, iy))/(hx(&
&           leftix(nx, iy), leftiy(nx, iy))+hx(nx, iy))
          t0 = t0 - zxf*fa_ext(nx, iy, 0, 0, is)
        END DO
        fchi = qe*t0
        IF (t0 .LT. 0.0_R8 .AND. region(nx, iy, 0) .NE. 0 .AND. bottomiy&
&           (nx, iy) .NE. -2 .AND. topiy(nx, iy) .NE. ny + 1) THEN
!xpb
          wrong_flow = .true.
          IF (diagno .GE. 0) THEN
            WRITE(*, *) 'b2stbc_east:iy,fchi', iy, fchi
            WRITE(*, *) zaf(ismain), fna(nx, iy, 0, 0, ismain)
            WRITE(*, '(a,4g14.7)') 'Bx,Bz,Ud,Ua =', wbbl(nx, iy, 0), &
&           wbbl(nx, iy, 2), -udf(ismain), ua(nx, iy, ismain)
          END IF
        END IF
!         fchi=0.0_R8
!       if (po(nx,iy).ge.0.0_R8) then                                    !sv
        arg10 = 1.0_R8/(2.0_R8*pi)
        result10 = SQRT(arg10)
        arg2 = -(qe*pof/tef)
        result2 = EXPU2(arg2)
        fche = result10*qe*nef*vte*s1*result2
!       else                                                             !sv
!         fche = sqrt(1.0_R8/(2.0_R8*pi))*qe*nef*vte*s1                  !sv
!       endif                                                            !sv
!    ..loop over species
        DO is=0,ns-1
!     ..compute csb
          arg1 = (zaf(is)*tef+tif)/(am(is)*mp)
          csb = SQRT(arg1)
          IF (wbbl(nx, iy, 2)/wbbl(nx, iy, 0) .GE. 0.) THEN
            abs2 = wbbl(nx, iy, 2)/wbbl(nx, iy, 0)
          ELSE
            abs2 = -(wbbl(nx, iy, 2)/wbbl(nx, iy, 0))
          END IF
!     .. account for diamagnetic drifts
!xpb
          csbm = csb - udf(is)*abs2
          IF (wbbl(nx, iy, 2)/wbbl(nx, iy, 0) .GE. 0.) THEN
            abs3 = wbbl(nx, iy, 2)/wbbl(nx, iy, 0)
          ELSE
            abs3 = -(wbbl(nx, iy, 2)/wbbl(nx, iy, 0))
          END IF
!xpb
          cstm = cst - udf(is)*abs3
!xpb
          IF (.NOT.is_neutral(is)) THEN
            IF (0.0_R8 .LT. csbm) THEN
              csbm = csbm
            ELSE
              csbm = 0.0_R8
            END IF
            IF (0.0_R8 .LT. cstm) THEN
              cstm = cstm
            ELSE
              cstm = 0.0_R8
            END IF
          END IF
          IF (csbm .GT. csb .AND. diagno .GE. 2) WRITE(*, *) &
&                                                'east:iy,is,csb,csbm', &
&                                                iy, is, csb, csbm
          IF (cstm .GT. cst .AND. diagno .GE. 2) WRITE(*, *) &
&                                                'east:iy,is,cst,cstm', &
&                                                iy, is, cst, cstm
          IF (0.0_R8 .LT. -(ua(nx, iy, is)*pbs(nx, iy, 0))) THEN
            max24 = -(ua(nx, iy, is)*pbs(nx, iy, 0))
          ELSE
            max24 = 0.0_R8
          END IF
!     ..compute particle source
          sna0(nx, iy, 0, is) = sna0(nx, iy, 0, is) + cbsna(0, is, ireg)&
&           *s0 + cbsna(6, is, ireg)*max24
          IF (0.0_R8 .LT. ua(nx, iy, is)*pbs(nx, iy, 0)) THEN
            max25 = ua(nx, iy, is)*pbs(nx, iy, 0)
          ELSE
            max25 = 0.0_R8
          END IF
          sna0(nx, iy, 1, is) = sna0(nx, iy, 1, is) + cbsna(1, is, ireg)&
&           *s0 + cbsna(2, is, ireg)*csbm*s0 + cbsna(3, is, ireg)*csbm*&
&           s1 + cbsna(4, is, ireg)*cstm*s0 + cbsna(5, is, ireg)*cstm*s1&
&           + cbsna(7, is, ireg)*max25
!     ..compute parallel momentum source
          smo0(nx, iy, 0, is) = smo0(nx, iy, 0, is) + cbsmo(0, is, ireg)&
&           *s0
!rfs
          smo0(nx, iy, 1, is) = smo0(nx, iy, 1, is) + cbsmo(7, is, ireg)&
&           *s0
          IF (0.0_R8 .LT. fna(nx, iy, 0, 0, is)) THEN
            max26 = fna(nx, iy, 0, 0, is)
          ELSE
            max26 = 0.0_R8
          END IF
!xpb
!xpb
!sv
          smo0(nx, iy, 2, is) = smo0(nx, iy, 2, is) + cbsmo(1, is, ireg)&
&           *csbm*pbs(nx, iy, 0) + cbsmo(2, is, ireg)*cstm*pbs(nx, iy, 0&
&           ) + cbsmo(5, is, ireg)*max26/na(nx, iy, is)
          IF (0.0_R8 .LT. fna(nx, iy, 0, 0, is)) THEN
            max27 = fna(nx, iy, 0, 0, is)
          ELSE
            max27 = 0.0_R8
          END IF
          smo0(nx, iy, 3, is) = smo0(nx, iy, 3, is) + cbsmo(3, is, ireg)&
&           *s0 + cbsmo(4, is, ireg)*s1 + cbsmo(6, is, ireg)*max27/na(nx&
&           , iy, is)
!     ..compute atom heat source
          t0 = na(nx, iy, is)/ni(nx, iy, 0)
          IF (0.0_R8 .LT. -fna(nx, iy, 0, 0, is)) THEN
            max28 = -fna(nx, iy, 0, 0, is)
          ELSE
            max28 = 0.0_R8
          END IF
          shi0(nx, iy, 0) = shi0(nx, iy, 0) + cbshi(0, is, ireg)*t0*s0 +&
&           cbshi(6, is, ireg)*max28
          shi0(nx, iy, 1) = shi0(nx, iy, 1) + cbshi(1, is, ireg)*t0*s0
          IF (0.0_R8 .LT. fna(nx, iy, 0, 0, is)) THEN
            max29 = fna(nx, iy, 0, 0, is)
          ELSE
            max29 = 0.0_R8
          END IF
          shi0(nx, iy, 3) = shi0(nx, iy, 3) + cbshi(2, is, ireg)*t0*csbm&
&           *s0 + cbshi(3, is, ireg)*t0*csbm*s1 + cbshi(4, is, ireg)*t0*&
&           cstm*s0 + cbshi(5, is, ireg)*t0*cstm*s1 + cbshi(7, is, ireg)&
&           *max29/ni(nx, iy, 0)
        END DO
        shi_test = shi0(nx, iy, 0) + shi0(nx, iy, 1)*ti(nx, iy) + shi0(&
&         nx, iy, 2)*ni(nx, iy, 0) + shi0(nx, iy, 3)*ni(nx, iy, 0)*ti(nx&
&         , iy)
        IF (shi_test .GT. 0.0_R8 .AND. diagno .GE. 2) WRITE(*, *) &
&                                                     'shi_test>0: E ', &
&                                                     iy, shi0(nx, iy, :&
&                                                     ), ti(nx, iy)/qe, &
&                                                     ni(nx, iy, 0), s0&
&                                                     , s1, csbm, cstm, &
&                                                     ireg, cbshi(:, :, &
&                                                     ireg)
        IF (0.0_R8 .LT. -fne(nx, iy, 0, 0)) THEN
          max30 = -fne(nx, iy, 0, 0)
        ELSE
          max30 = 0.0_R8
        END IF
!    ..compute electron heat source
        she0(nx, iy, 0) = she0(nx, iy, 0) + cbshe(0, ireg)*s0 + cbshe(6&
&         , ireg)*max30
        she0(nx, iy, 1) = she0(nx, iy, 1) + cbshe(1, ireg)*s0
        IF (0.0_R8 .LT. fne(nx, iy, 0, 0)) THEN
          max31 = fne(nx, iy, 0, 0)
        ELSE
          max31 = 0.0_R8
        END IF
        she0(nx, iy, 3) = she0(nx, iy, 3) + cbshe(2, ireg)*vte*s0 + &
&         cbshe(3, ireg)*vte*s1 + cbshe(4, ireg)*cstm*s0 + cbshe(5, ireg&
&         )*cstm*s1 + cbshe(7, ireg)*max31/ne(nx, iy)
        she_test = she0(nx, iy, 0) + she0(nx, iy, 1)*te(nx, iy) + she0(&
&         nx, iy, 2)*ne(nx, iy) + she0(nx, iy, 3)*ne(nx, iy)*te(nx, iy)
        IF (she_test .GT. 0.0_R8 .AND. diagno .GE. 2) WRITE(*, *) &
&                                                     'she_test>0: E ', &
&                                                     iy, she0(nx, iy, :&
&                                                     ), te(nx, iy)/qe, &
&                                                     ne(nx, iy), s0, s1&
&                                                     , vte, cstm, ireg&
&                                                     , cbshe(:, ireg)
!    ..compute charge source
        sch0(nx, iy, 2) = sch0(nx, iy, 2) + cbsch(0, ireg)*qe*vte*s0 + &
&         cbsch(2, ireg)*qe*vte*s1 + cbsch(4, ireg)*qe*cstm*s1
        sch0(nx, iy, 3) = sch0(nx, iy, 3) + cbsch(1, ireg)*qe**2*vte*s0/&
&         te(nx, iy) + cbsch(3, ireg)*qe**2*vte*s1/te(nx, iy) + cbsch(5&
&         , ireg)*qe**2*cstm*s1/te(nx, iy)
        IF (secmodel .EQ. 1) THEN
          IF (ne(nx, iy)/(rza(nx, iy, ismain)*na(nx, iy, ismain)) .GT. &
&             1.1_R8) THEN
            WRITE(*, *) 'Large ne contribution from impurities!'
            WRITE(*, *) 'Kinetic s.e.c. model may not be valid!'
          END IF
          CALL ESEEC0_NODIFF_NODIFF(tef, tif, nef, pof, wbbl(nx, iy, 0)&
&                             , wbbl(nx, iy, 3), 0, nx, iy, nx, ny, ns, &
&                             ismain, seec, diagno)
!cfs
        ELSE
          seec = 1.0_R8 - cbsch(7, ireg)
        END IF
        IF (cbsch(6, ireg)*fchi .LT. (1.0_R8-seec)*fche) THEN
          max32 = (1.0_R8-seec)*fche
        ELSE
          max32 = cbsch(6, ireg)*fchi
        END IF
!       if (po(nx,iy).ge.0.0_R8) then                                    !sv
        t0 = max32*qe/tef
!       else                                                             !sv
!         t0 = 0.0_R8                                                    !sv
!       endif                                                            !sv
        sch0(nx, iy, 0) = sch0(nx, iy, 0) + (1.0_R8-seec)*fche - cbsch(6&
&         , ireg)*fchi + t0*po(nx, iy)
        sch0(nx, iy, 1) = sch0(nx, iy, 1) - t0
      END IF
    END IF
  END DO
!
! ..return
  IF (ncall .EQ. 0 .OR. main_call) ncall = ncall + 1
  CALL SUBEND()
  RETURN
END SUBROUTINE B2STBC_BAS_NODIFF_NODIFF

