!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 23 Jul 2024 17:41
!
!  Differentiation of b2tlh0_dv in forward (tangent) mode (with options multiDirectional context noISIZE r8):
!   variations   of useful results: chcbd chcb
!   with respect to varying inputs: tn na nad chcbd chcb chcib
!                tnd chcibd
!   Plus diff mem management of: geo.fcs:in geo.fchc:in geo.fcht:in
!                geo.fcqalf:in geo.fcqbet:in geo.vxvol:in
!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 23 Jul 2024 17:41
!
!  Differentiation of b2tlh0 in forward (tangent) mode (with options multiDirectional context noISIZE r8):
!   variations   of useful results: chcb
!   with respect to varying inputs: tn na chcb chcib
!   Plus diff mem management of: geo.fcs:in geo.fchc:in geo.fcht:in
!                geo.fcqalf:in geo.fcqbet:in geo.vxvol:in
!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE B2TLH0_DV_DV(ncv, nfc, nvx, ns, switch, switchd, geo, geod0, &
& geod, mpg, mpgd, na, nad0, nad, nadd, ti, tn, tnd0, tnd, tndd, chcib, &
& chcibd0, chcibd, chcibdd, chcb, chcbd0, chcbd, chcbdd, fllim0fhi, &
& fllim0fhid, nbdirs, nbdirs0)
  USE B2MOD_TYPES
  USE B2MOD_CONSTANTS
  USE B2MOD_B2CMPA_DIFFV
  USE B2MOD_SWITCHES_DIFFV_DIFFV
  USE B2US_GEO_DIFFV_DIFFV
  USE B2US_MAP_DIFFV_DIFFV
! csc The following are not necessary for computation but are needed
!     for adjoint AD to avoid side-effect variables
  USE B2MOD_AD_DIFFV_DIFFV, ONLY : ncall_b2tlh0, b2tlh0_cutlo
  USE B2MOD_AD_DIFFV_DIFFV, ONLY : my_out_folder
  USE B2MOD_SUBSYS
!  Hint: nbdirsmax should be the maximum number of differentiation directions
  USE B2MOD_DIFFSIZES
!  Hint: nbdirsmax0 should be the maximum number of differentiation directions
  IMPLICIT NONE
!   ..input arguments (unchanged on exit)
  INTEGER :: ncv, nfc, nvx, ns
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(SWITCHES_DIFFV), INTENT(IN) :: switchd
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(GEOMETRY_DIFFV0), INTENT(IN) :: geod0
  TYPE(GEOMETRY_DIFFV), INTENT(IN) :: geod
  TYPE(MAPPING), INTENT(IN) :: mpg
  TYPE(MAPPING_DIFFV), INTENT(IN) :: mpgd
  REAL(kind=r8) :: na(ncv, 0:ns-1), ti(ncv), tn(ncv), chcib(nfc, 0:ns-1)&
& , chcb(nfc, 0:1, 0:ns-1)
  REAL(kind=r8) :: nad0(nbdirsmax0, ncv, 0:ns-1), tnd0(nbdirsmax0, ncv)&
& , chcibd0(nbdirsmax0, nfc, 0:ns-1), chcbd0(nbdirsmax0, nfc, 0:1, 0:ns-&
& 1)
  REAL(kind=r8) :: nad(nbdirsmax, ncv, 0:ns-1), tnd(nbdirsmax, ncv), &
& chcibd(nbdirsmax, nfc, 0:ns-1), chcbd(nbdirsmax, nfc, 0:1, 0:ns-1)
  REAL(kind=r8) :: nadd(nbdirsmax0, nbdirsmax, ncv, 0:ns-1), tndd(&
& nbdirsmax0, nbdirsmax, ncv), chcibdd(nbdirsmax0, nbdirsmax, nfc, 0:ns-&
& 1), chcbdd(nbdirsmax0, nbdirsmax, nfc, 0:1, 0:ns-1)
!   ..output arguments (unspecified on entry)
  REAL(kind=r8) :: fllim0fhi(nfc, 0:1, 0:ns-1)
  REAL(kind=r8) :: fllim0fhid(nbdirsmax, nfc, 0:1, 0:ns-1)
!   ..common blocks
!     ------------------------------------------------------------------
!     B2TLH0 computes the conductive neutral heat transport flux limit.
!     ------------------------------------------------------------------
!   ..local variables
  INTEGER :: ifc, is
!srv 13.01.04 {
  REAL(kind=r8), ALLOCATABLE :: w1(:)
!srv 13.01.04 }
  CHARACTER :: charns*3
  REAL(kind=r8) :: alpha, gamma, t0, t1, t2, dtn, vthi, maxfluxlimit(0:1&
& ), tnv(nvx), dtnf(nfc, 0:1)
  REAL(kind=r8) :: t0d0(nbdirsmax0), t1d0(nbdirsmax0), t2d0(nbdirsmax0)&
& , dtnd0(nbdirsmax0), vthid0(nbdirsmax0), tnvd0(nbdirsmax0, nvx), &
& dtnfd0(nbdirsmax0, nfc, 0:1)
  REAL(kind=r8) :: t0d(nbdirsmax), t1d(nbdirsmax), t2d(nbdirsmax), dtnd(&
& nbdirsmax), vthid(nbdirsmax), tnvd(nbdirsmax, nvx), dtnfd(nbdirsmax, &
& nfc, 0:1)
  REAL(kind=r8) :: t0dd(nbdirsmax0, nbdirsmax), t1dd(nbdirsmax0, &
& nbdirsmax), t2dd(nbdirsmax0, nbdirsmax), dtndd(nbdirsmax0, nbdirsmax)&
& , vthidd(nbdirsmax0, nbdirsmax), tnvdd(nbdirsmax0, nbdirsmax, nvx), &
& dtnfdd(nbdirsmax0, nbdirsmax, nfc, 0:1)
!   ..initialisation
!   ..procedures
  INTRINSIC MAX, ABS, SQRT
  EXTERNAL XERTST, IPGETR, IPGETI
  REAL(kind=r8) :: abs0
  REAL(kind=r8) :: abs1
  INTEGER :: arg1
  REAL(r8) :: arg10
  REAL(r8), DIMENSION(nbdirsmax0) :: arg10d0
  REAL(r8), DIMENSION(nbdirsmax) :: arg10d
  REAL(r8), DIMENSION(nbdirsmax0, nbdirsmax) :: arg10dd
  REAL(kind=r8) :: result1
  REAL(kind=r8), DIMENSION(nbdirsmax0) :: result1d0
  REAL(kind=r8), DIMENSION(nbdirsmax) :: result1d
  REAL(kind=r8), DIMENSION(nbdirsmax0, nbdirsmax) :: result1dd
  REAL(kind=r8) :: arg11
  REAL(kind=r8), DIMENSION(nbdirsmax0) :: arg11d0
  REAL(kind=r8), DIMENSION(nbdirsmax) :: arg11d
  REAL(kind=r8), DIMENSION(nbdirsmax0, nbdirsmax) :: arg11dd
  CHARACTER(len=12) :: arg12
  CHARACTER(len=11) :: arg13
  CHARACTER(len=7) :: arg14
  CHARACTER(len=6) :: arg15
  INTEGER :: nd
  REAL(kind=r8) :: temp
  REAL(kind=r8), DIMENSION(nbdirsmax0) :: tempd3
  REAL(kind=r8) :: temp0
  REAL(kind=r8), DIMENSION(nbdirsmax0) :: temp0d
  REAL(kind=r8) :: temp1
  REAL(kind=r8), DIMENSION(nbdirsmax0) :: temp1d
  REAL(kind=r8) :: temp2
  REAL(kind=r8), DIMENSION(nbdirsmax0) :: temp2d
  REAL(kind=r8) :: temp3
  REAL(kind=r8), DIMENSION(nbdirsmax0) :: temp3d
  REAL(kind=r8) :: temp4
  REAL(kind=r8), DIMENSION(nbdirsmax0) :: temp4d
  REAL(kind=r8), DIMENSION(nbdirsmax) :: tempd
  REAL(kind=r8), DIMENSION(nbdirsmax0, nbdirsmax) :: tempdd
  REAL(kind=r8) :: temp5
  REAL(kind=r8), DIMENSION(nbdirsmax0) :: temp5d
  REAL(kind=r8), DIMENSION(nbdirsmax) :: tempd0
  REAL(kind=r8), DIMENSION(nbdirsmax0, nbdirsmax) :: tempd0d
  REAL(kind=r8), DIMENSION(nbdirsmax) :: tempd1
  REAL(kind=r8), DIMENSION(nbdirsmax0, nbdirsmax) :: tempd1d
  REAL(kind=r8), DIMENSION(nbdirsmax) :: tempd2
  REAL(kind=r8), DIMENSION(nbdirsmax0, nbdirsmax) :: tempd2d
  INTEGER :: nbdirs
  INTRINSIC INT
  INTEGER :: nd0
  REAL(r8) :: temp6
  REAL(kind=r8) :: temp7
  REAL(kind=r8) :: temp8
  REAL(kind=r8) :: temp9
  REAL(kind=r8) :: temp10
  REAL(kind=r8), DIMENSION(nbdirsmax0) :: tempd4
  REAL(kind=r8) :: temp11
  REAL(kind=r8), DIMENSION(nbdirsmax0) :: tempd5
  REAL(kind=r8), DIMENSION(nbdirsmax0) :: tempd6
  INTEGER :: nbdirs0
!     ------------------------------------------------------------------
!   ..subprogram start-up calls
  CALL SUBINI('b2tlh0')
!   ..test nCv, nFc, ns
  CALL XERTST(0 .LT. ncv .AND. 0 .LT. nfc, 'faulty argument nCv, nFc')
  CALL XERTST(1 .LE. ns, 'faulty argument ns')
!   ..read input on first call
! The following switches are only used in 'WG-TODO' blocks, i.e. not yet converted to wide grid functionality
!        call ipgetr ('b2tlh0_flux_limit_min_ti', flux_limit_min_tn) !! do not change name of switch for compatibility with exist
!ing input files?
!        flux_limit_min_tn=flux_limit_min_tn*ev
!
  alpha = switch%b2tlh0_alpha
  gamma = switch%b2tlh0_gamma
  arg1 = nfc*2*ns
  CALL SFILL_NODIFF_NODIFF(arg1, 1.0_R8, fllim0fhi, 1)
  maxfluxlimit = 0.0_R8
!
  IF (alpha .NE. 0.0_R8) THEN
!   .. compute differences of temperature
    dtnfd = 0.d0
    tnvd = 0.d0
    dtnfd0 = 0.D0
    dtnfdd = 0.D0
    tnvdd = 0.D0
    tnvd0 = 0.D0
    CALL DIFF_DV_DV(ncv, nfc, nvx, 0, geo, geod0, geod, mpg, mpgd, tn, &
&             tnd0, tnd, tndd, tnv, tnvd0, tnvd, tnvdd, dtnf, dtnfd0, &
&             dtnfd, dtnfdd, nbdirs, nbdirs0)
    IF (switch%b2tlh0_style .EQ. 0) THEN
      t2dd = 0.D0
      vthidd = 0.D0
      tempd0d = 0.D0
      tempd1d = 0.D0
      tempd2d = 0.D0
      tempdd = 0.D0
      t0dd = 0.D0
      dtndd = 0.D0
      result1dd = 0.D0
      arg10dd = 0.D0
      t1dd = 0.D0
      DO is=0,ns-1
        IF (is_neutral(is)) THEN
          DO ifc=1,nfc
            DO nd=1,nbdirs
              DO nd0=nd,nbdirs0
                t0dd(nd0, nd) = (tndd(nd0, nd, mpg%fccv(ifc, 1))+tndd(&
&                 nd0, nd, mpg%fccv(ifc, 2)))/2.0_R8
                t1dd(nd0, nd) = (nadd(nd0, nd, mpg%fccv(ifc, 1), is)+&
&                 nadd(nd0, nd, mpg%fccv(ifc, 2), is))/2.0_R8
              END DO
              t0d(nd) = (tnd(nd, mpg%fccv(ifc, 1))+tnd(nd, mpg%fccv(ifc&
&               , 2)))/2.0_R8
              t1d(nd) = (nad(nd, mpg%fccv(ifc, 1), is)+nad(nd, mpg%fccv(&
&               ifc, 2), is))/2.0_R8
            END DO
            DO nd0=1,nbdirs0
              t0d0(nd0) = (tnd0(nd0, mpg%fccv(ifc, 1))+tnd0(nd0, mpg%&
&               fccv(ifc, 2)))/2.0_R8
              t1d0(nd0) = (nad0(nd0, mpg%fccv(ifc, 1), is)+nad0(nd0, mpg&
&               %fccv(ifc, 2), is))/2.0_R8
            END DO
            t0 = (tn(mpg%fccv(ifc, 1))+tn(mpg%fccv(ifc, 2)))/2.0_R8
            t1 = (na(mpg%fccv(ifc, 1), is)+na(mpg%fccv(ifc, 2), is))/&
&             2.0_R8
            IF (chcb(ifc, 0, is)*dtnf(ifc, 0) .GE. 0.) THEN
              DO nd=1,nbdirs
                DO nd0=nd,nbdirs0
                  dtndd(nd0, nd) = chcbd(nd, ifc, 0, is)*dtnfd0(nd0, ifc&
&                   , 0) + dtnf(ifc, 0)*chcbdd(nd0, nd, ifc, 0, is) + &
&                   dtnfd(nd, ifc, 0)*chcbd0(nd0, ifc, 0, is) + chcb(ifc&
&                   , 0, is)*dtnfdd(nd0, nd, ifc, 0)
                END DO
                dtnd(nd) = dtnf(ifc, 0)*chcbd(nd, ifc, 0, is) + chcb(ifc&
&                 , 0, is)*dtnfd(nd, ifc, 0)
              END DO
              DO nd0=1,nbdirs0
                dtnd0(nd0) = dtnf(ifc, 0)*chcbd0(nd0, ifc, 0, is) + chcb&
&                 (ifc, 0, is)*dtnfd0(nd0, ifc, 0)
              END DO
              dtn = chcb(ifc, 0, is)*dtnf(ifc, 0)
            ELSE
              DO nd=1,nbdirs
                DO nd0=nd,nbdirs0
                  dtndd(nd0, nd) = -(chcbd(nd, ifc, 0, is)*dtnfd0(nd0, &
&                   ifc, 0)) - dtnf(ifc, 0)*chcbdd(nd0, nd, ifc, 0, is) &
&                   - dtnfd(nd, ifc, 0)*chcbd0(nd0, ifc, 0, is) - chcb(&
&                   ifc, 0, is)*dtnfdd(nd0, nd, ifc, 0)
                END DO
                dtnd(nd) = -(dtnf(ifc, 0)*chcbd(nd, ifc, 0, is)+chcb(ifc&
&                 , 0, is)*dtnfd(nd, ifc, 0))
              END DO
              DO nd0=1,nbdirs0
                dtnd0(nd0) = -(dtnf(ifc, 0)*chcbd0(nd0, ifc, 0, is)+chcb&
&                 (ifc, 0, is)*dtnfd0(nd0, ifc, 0))
              END DO
              dtn = -(chcb(ifc, 0, is)*dtnf(ifc, 0))
            END IF
            IF (geo%fcqalf(ifc, 0) .GE. 0.) THEN
              abs0 = geo%fcqalf(ifc, 0)
            ELSE
              abs0 = -geo%fcqalf(ifc, 0)
            END IF
            arg10 = 2.0_R8*t0/(am(is)*mp)
            temp6 = SQRT(arg10)
            temp = temp6
            result1 = temp
            vthi = result1*geo%fcs(ifc)*abs0
            temp0 = b2tlh0_cutlo + alpha*vthi*t1*t0
            DO nd0=1,nbdirs0
              arg10d0(nd0) = 2.0_R8*t0d0(nd0)/(am(is)*mp)
              IF (arg10 .EQ. 0.D0) THEN
                tempd3(nd0) = 0.D0
              ELSE
                tempd3(nd0) = arg10d0(nd0)/(2.0*temp6)
              END IF
              result1d0(nd0) = tempd3(nd0)
              vthid0(nd0) = geo%fcs(ifc)*abs0*result1d0(nd0)
              temp0d(nd0) = alpha*(t0*(t1*vthid0(nd0)+vthi*t1d0(nd0))+&
&               vthi*t1*t0d0(nd0))
              temp1d(nd0) = (dtnd0(nd0)-dtn*temp0d(nd0)/temp0)/temp0
            END DO
            temp1 = dtn/temp0
            DO nd=1,nbdirs
              DO nd0=nd,nbdirs0
                arg10dd(nd0, nd) = 2.0_R8*t0dd(nd0, nd)/(am(is)*mp)
              END DO
              arg10d(nd) = 2.0_R8*t0d(nd)/(am(is)*mp)
              IF (arg10 .EQ. 0.d0) THEN
                DO nd0=1,nbdirs0
                  result1dd(nd0, nd) = 0.D0
                END DO
                result1d(nd) = 0.d0
              ELSE
                temp6 = arg10d(nd)/(2.0*temp)
                DO nd0=1,nbdirs0
                  result1dd(nd0, nd) = (arg10dd(nd0, nd)-temp6*2.0*&
&                   tempd3(nd0))/(2.0*temp)
                END DO
                result1d(nd) = temp6
              END IF
              DO nd0=1,nbdirs0
                vthidd(nd0, nd) = geo%fcs(ifc)*abs0*result1dd(nd0, nd)
              END DO
              vthid(nd) = geo%fcs(ifc)*abs0*result1d(nd)
              IF (temp1 .LE. 0.d0 .AND. (gamma .EQ. 0.d0 .OR. gamma .NE.&
&                 INT(gamma))) THEN
                DO nd0=1,nbdirs0
                  tempd0d(nd0, nd) = 0.D0
                END DO
                tempd0(nd) = 0.d0
              ELSE
                temp7 = t1*vthid(nd) + vthi*t1d(nd)
                temp8 = t0*temp7 + vthi*t1*t0d(nd)
                temp9 = dtnd(nd) - alpha*temp1*temp8
                temp11 = temp1**(gamma-1)/temp0
                DO nd0=1,nbdirs0
                  IF (temp1 .LE. 0.D0 .AND. (gamma - 1 .EQ. 0.D0 .OR. &
&                     gamma - 1 .NE. INT(gamma - 1))) THEN
                    tempd4(nd0) = 0.D0
                  ELSE
                    tempd4(nd0) = (gamma-1)*temp1**(gamma-2)*temp1d(nd0)
                  END IF
                  tempd0d(nd0, nd) = gamma*(temp9*(tempd4(nd0)-temp11*&
&                   temp0d(nd0))/temp0+temp11*(dtndd(nd0, nd)-alpha*(&
&                   temp8*temp1d(nd0)+temp1*(temp7*t0d0(nd0)+t0*(vthid(&
&                   nd)*t1d0(nd0)+t1*vthidd(nd0, nd)+t1d(nd)*vthid0(nd0)&
&                   +vthi*t1dd(nd0, nd))+t0d(nd)*(t1*vthid0(nd0)+vthi*&
&                   t1d0(nd0))+vthi*t1*t0dd(nd0, nd)))))
                END DO
                tempd0(nd) = gamma*(temp11*temp9)
              END IF
            END DO
            temp = 1.0/gamma
            temp2 = temp1**gamma + 1.0_R8
            temp11 = 1.0/temp2**temp
            DO nd0=1,nbdirs0
              IF (temp1 .LE. 0.D0 .AND. (gamma .EQ. 0.D0 .OR. gamma &
&                 .NE. INT(gamma))) THEN
                temp2d(nd0) = 0.D0
              ELSE
                temp2d(nd0) = gamma*temp1**(gamma-1)*temp1d(nd0)
              END IF
              IF (temp2 .LE. 0.D0 .AND. (temp .EQ. 0.D0 .OR. temp .NE.&
&                 INT(temp))) THEN
                tempd4(nd0) = 0.D0
              ELSE
                tempd4(nd0) = temp*temp2**(temp-1)*temp2d(nd0)
              END IF
              temp3d(nd0) = -(temp11*tempd4(nd0)/temp2**temp)
              t2d0(nd0) = temp3d(nd0)
            END DO
            temp3 = temp11
            t2 = temp3
            DO nd=1,nbdirs
              IF (temp2 .LE. 0.d0 .AND. (temp .EQ. 0.d0 .OR. temp .NE. &
&                 INT(temp))) THEN
                DO nd0=1,nbdirs0
                  tempdd(nd0, nd) = 0.D0
                END DO
                tempd(nd) = 0.d0
              ELSE
                temp11 = temp2**(temp-1)
                DO nd0=1,nbdirs0
                  IF (temp2 .LE. 0.D0 .AND. (temp - 1 .EQ. 0.D0 .OR. &
&                     temp - 1 .NE. INT(temp - 1))) THEN
                    tempd5(nd0) = 0.D0
                  ELSE
                    tempd5(nd0) = (temp-1)*temp2**(temp-2)*temp2d(nd0)
                  END IF
                  tempdd(nd0, nd) = temp*(tempd0(nd)*tempd5(nd0)+temp11*&
&                   tempd0d(nd0, nd))
                END DO
                tempd(nd) = temp*(temp11*tempd0(nd))
              END IF
              temp11 = temp2**temp
              temp10 = temp3*tempd(nd)/temp11
              t2d(nd) = -temp10
              DO nd0=1,nbdirs0
                IF (temp2 .LE. 0.D0 .AND. (temp .EQ. 0.D0 .OR. temp &
&                   .NE. INT(temp))) THEN
                  tempd5(nd0) = 0.D0
                ELSE
                  tempd5(nd0) = temp*temp2**(temp-1)*temp2d(nd0)
                END IF
                t2dd(nd0, nd) = -((tempd(nd)*temp3d(nd0)+temp3*tempdd(&
&                 nd0, nd)-temp10*tempd5(nd0))/temp11)
                chcbdd(nd0, nd, ifc, 0, is) = chcbd(nd, ifc, 0, is)*t2d0&
&                 (nd0) + t2*chcbdd(nd0, nd, ifc, 0, is) + t2d(nd)*&
&                 chcbd0(nd0, ifc, 0, is) + chcb(ifc, 0, is)*t2dd(nd0, &
&                 nd)
              END DO
              chcbd(nd, ifc, 0, is) = t2*chcbd(nd, ifc, 0, is) + chcb(&
&               ifc, 0, is)*t2d(nd)
            END DO
            DO nd0=1,nbdirs0
              chcbd0(nd0, ifc, 0, is) = t2*chcbd0(nd0, ifc, 0, is) + &
&               chcb(ifc, 0, is)*t2d0(nd0)
            END DO
            chcb(ifc, 0, is) = chcb(ifc, 0, is)*t2
            fllim0fhi(ifc, 0, is) = t2
            IF (maxfluxlimit(0) .LT. t2) THEN
              maxfluxlimit(0) = t2
            ELSE
              maxfluxlimit(0) = maxfluxlimit(0)
            END IF
            IF (chcb(ifc, 1, is)*dtnf(ifc, 1) .GE. 0.) THEN
              DO nd=1,nbdirs
                DO nd0=nd,nbdirs0
                  dtndd(nd0, nd) = chcbd(nd, ifc, 1, is)*dtnfd0(nd0, ifc&
&                   , 1) + dtnf(ifc, 1)*chcbdd(nd0, nd, ifc, 1, is) + &
&                   dtnfd(nd, ifc, 1)*chcbd0(nd0, ifc, 1, is) + chcb(ifc&
&                   , 1, is)*dtnfdd(nd0, nd, ifc, 1)
                END DO
                dtnd(nd) = dtnf(ifc, 1)*chcbd(nd, ifc, 1, is) + chcb(ifc&
&                 , 1, is)*dtnfd(nd, ifc, 1)
              END DO
              DO nd0=1,nbdirs0
                dtnd0(nd0) = dtnf(ifc, 1)*chcbd0(nd0, ifc, 1, is) + chcb&
&                 (ifc, 1, is)*dtnfd0(nd0, ifc, 1)
              END DO
              dtn = chcb(ifc, 1, is)*dtnf(ifc, 1)
            ELSE
              DO nd=1,nbdirs
                DO nd0=nd,nbdirs0
                  dtndd(nd0, nd) = -(chcbd(nd, ifc, 1, is)*dtnfd0(nd0, &
&                   ifc, 1)) - dtnf(ifc, 1)*chcbdd(nd0, nd, ifc, 1, is) &
&                   - dtnfd(nd, ifc, 1)*chcbd0(nd0, ifc, 1, is) - chcb(&
&                   ifc, 1, is)*dtnfdd(nd0, nd, ifc, 1)
                END DO
                dtnd(nd) = -(dtnf(ifc, 1)*chcbd(nd, ifc, 1, is)+chcb(ifc&
&                 , 1, is)*dtnfd(nd, ifc, 1))
              END DO
              DO nd0=1,nbdirs0
                dtnd0(nd0) = -(dtnf(ifc, 1)*chcbd0(nd0, ifc, 1, is)+chcb&
&                 (ifc, 1, is)*dtnfd0(nd0, ifc, 1))
              END DO
              dtn = -(chcb(ifc, 1, is)*dtnf(ifc, 1))
            END IF
            IF (geo%fcqalf(ifc, 1) .GE. 0.) THEN
              abs1 = geo%fcqalf(ifc, 1)
            ELSE
              abs1 = -geo%fcqalf(ifc, 1)
            END IF
            arg10 = 2.0_R8*t0/(am(is)*mp)
            temp6 = SQRT(arg10)
            temp5 = temp6
            result1 = temp5
            vthi = result1*geo%fcs(ifc)*abs1
            temp4 = b2tlh0_cutlo + alpha*vthi*t1*t0
            DO nd0=1,nbdirs0
              arg10d0(nd0) = 2.0_R8*t0d0(nd0)/(am(is)*mp)
              IF (arg10 .EQ. 0.D0) THEN
                temp5d(nd0) = 0.D0
              ELSE
                temp5d(nd0) = arg10d0(nd0)/(2.0*temp6)
              END IF
              result1d0(nd0) = temp5d(nd0)
              vthid0(nd0) = geo%fcs(ifc)*abs1*result1d0(nd0)
              temp4d(nd0) = alpha*(t0*(t1*vthid0(nd0)+vthi*t1d0(nd0))+&
&               vthi*t1*t0d0(nd0))
              temp3d(nd0) = (dtnd0(nd0)-dtn*temp4d(nd0)/temp4)/temp4
            END DO
            temp3 = dtn/temp4
            DO nd=1,nbdirs
              DO nd0=nd,nbdirs0
                arg10dd(nd0, nd) = 2.0_R8*t0dd(nd0, nd)/(am(is)*mp)
              END DO
              arg10d(nd) = 2.0_R8*t0d(nd)/(am(is)*mp)
              IF (arg10 .EQ. 0.d0) THEN
                DO nd0=1,nbdirs0
                  result1dd(nd0, nd) = 0.D0
                END DO
                result1d(nd) = 0.d0
              ELSE
                temp6 = arg10d(nd)/(2.0*temp5)
                DO nd0=1,nbdirs0
                  result1dd(nd0, nd) = (arg10dd(nd0, nd)-temp6*2.0*&
&                   temp5d(nd0))/(2.0*temp5)
                END DO
                result1d(nd) = temp6
              END IF
              DO nd0=1,nbdirs0
                vthidd(nd0, nd) = geo%fcs(ifc)*abs1*result1dd(nd0, nd)
              END DO
              vthid(nd) = geo%fcs(ifc)*abs1*result1d(nd)
              IF (temp3 .LE. 0.d0 .AND. (gamma .EQ. 0.d0 .OR. gamma .NE.&
&                 INT(gamma))) THEN
                DO nd0=1,nbdirs0
                  tempd2d(nd0, nd) = 0.D0
                END DO
                tempd2(nd) = 0.d0
              ELSE
                temp11 = t1*vthid(nd) + vthi*t1d(nd)
                temp10 = t0*temp11 + vthi*t1*t0d(nd)
                temp9 = dtnd(nd) - alpha*temp3*temp10
                temp7 = temp3**(gamma-1)/temp4
                DO nd0=1,nbdirs0
                  IF (temp3 .LE. 0.D0 .AND. (gamma - 1 .EQ. 0.D0 .OR. &
&                     gamma - 1 .NE. INT(gamma - 1))) THEN
                    tempd6(nd0) = 0.D0
                  ELSE
                    tempd6(nd0) = (gamma-1)*temp3**(gamma-2)*temp3d(nd0)
                  END IF
                  tempd2d(nd0, nd) = gamma*(temp9*(tempd6(nd0)-temp7*&
&                   temp4d(nd0))/temp4+temp7*(dtndd(nd0, nd)-alpha*(&
&                   temp10*temp3d(nd0)+temp3*(temp11*t0d0(nd0)+t0*(vthid&
&                   (nd)*t1d0(nd0)+t1*vthidd(nd0, nd)+t1d(nd)*vthid0(nd0&
&                   )+vthi*t1dd(nd0, nd))+t0d(nd)*(t1*vthid0(nd0)+vthi*&
&                   t1d0(nd0))+vthi*t1*t0dd(nd0, nd)))))
                END DO
                tempd2(nd) = gamma*(temp7*temp9)
              END IF
            END DO
            temp5 = 1.0/gamma
            temp2 = temp3**gamma + 1.0_R8
            temp11 = 1.0/temp2**temp5
            DO nd0=1,nbdirs0
              IF (temp3 .LE. 0.D0 .AND. (gamma .EQ. 0.D0 .OR. gamma &
&                 .NE. INT(gamma))) THEN
                temp2d(nd0) = 0.D0
              ELSE
                temp2d(nd0) = gamma*temp3**(gamma-1)*temp3d(nd0)
              END IF
              IF (temp2 .LE. 0.D0 .AND. (temp5 .EQ. 0.D0 .OR. temp5 &
&                 .NE. INT(temp5))) THEN
                tempd4(nd0) = 0.D0
              ELSE
                tempd4(nd0) = temp5*temp2**(temp5-1)*temp2d(nd0)
              END IF
              temp1d(nd0) = -(temp11*tempd4(nd0)/temp2**temp5)
              t2d0(nd0) = temp1d(nd0)
            END DO
            temp1 = temp11
            t2 = temp1
            DO nd=1,nbdirs
              IF (temp2 .LE. 0.d0 .AND. (temp5 .EQ. 0.d0 .OR. temp5 .NE.&
&                 INT(temp5))) THEN
                DO nd0=1,nbdirs0
                  tempd1d(nd0, nd) = 0.D0
                END DO
                tempd1(nd) = 0.d0
              ELSE
                temp11 = temp2**(temp5-1)
                DO nd0=1,nbdirs0
                  IF (temp2 .LE. 0.D0 .AND. (temp5 - 1 .EQ. 0.D0 .OR. &
&                     temp5 - 1 .NE. INT(temp5 - 1))) THEN
                    tempd5(nd0) = 0.D0
                  ELSE
                    tempd5(nd0) = (temp5-1)*temp2**(temp5-2)*temp2d(nd0)
                  END IF
                  tempd1d(nd0, nd) = temp5*(tempd2(nd)*tempd5(nd0)+&
&                   temp11*tempd2d(nd0, nd))
                END DO
                tempd1(nd) = temp5*(temp11*tempd2(nd))
              END IF
              temp11 = temp2**temp5
              temp10 = temp1*tempd1(nd)/temp11
              t2d(nd) = -temp10
              DO nd0=1,nbdirs0
                IF (temp2 .LE. 0.D0 .AND. (temp5 .EQ. 0.D0 .OR. temp5 &
&                   .NE. INT(temp5))) THEN
                  tempd5(nd0) = 0.D0
                ELSE
                  tempd5(nd0) = temp5*temp2**(temp5-1)*temp2d(nd0)
                END IF
                t2dd(nd0, nd) = -((tempd1(nd)*temp1d(nd0)+temp1*tempd1d(&
&                 nd0, nd)-temp10*tempd5(nd0))/temp11)
                chcbdd(nd0, nd, ifc, 1, is) = chcbd(nd, ifc, 1, is)*t2d0&
&                 (nd0) + t2*chcbdd(nd0, nd, ifc, 1, is) + t2d(nd)*&
&                 chcbd0(nd0, ifc, 1, is) + chcb(ifc, 1, is)*t2dd(nd0, &
&                 nd)
              END DO
              chcbd(nd, ifc, 1, is) = t2*chcbd(nd, ifc, 1, is) + chcb(&
&               ifc, 1, is)*t2d(nd)
            END DO
            DO nd0=1,nbdirs0
              chcbd0(nd0, ifc, 1, is) = t2*chcbd0(nd0, ifc, 1, is) + &
&               chcb(ifc, 1, is)*t2d0(nd0)
            END DO
            chcb(ifc, 1, is) = chcb(ifc, 1, is)*t2
            fllim0fhi(ifc, 1, is) = t2
            IF (maxfluxlimit(1) .LT. t2) THEN
              maxfluxlimit(1) = t2
            ELSE
              maxfluxlimit(1) = maxfluxlimit(1)
            END IF
          END DO
        END IF
      END DO
    ELSE
      arg11dd = 0.D0
      t2dd = 0.D0
      vthidd = 0.D0
      tempd1d = 0.D0
      tempd2d = 0.D0
      t0dd = 0.D0
      dtndd = 0.D0
      result1dd = 0.D0
      arg10dd = 0.D0
      t1dd = 0.D0
!wdk    flux limit total gradient-driven flow, not individual poloidal
!wdk    or radial contributions, since neutral transport is isotropic
      DO is=0,ns-1
        IF (is_neutral(is)) THEN
          DO ifc=1,nfc
            arg11 = dtnf(ifc, 0)**2 + dtnf(ifc, 1)**2
            temp11 = SQRT(arg11)
            DO nd0=1,nbdirs0
              arg11d0(nd0) = 2*dtnf(ifc, 0)*dtnfd0(nd0, ifc, 0) + 2*dtnf&
&               (ifc, 1)*dtnfd0(nd0, ifc, 1)
              IF (arg11 .EQ. 0.D0) THEN
                temp5d(nd0) = 0.D0
              ELSE
                temp5d(nd0) = arg11d0(nd0)/(2.0*temp11)
              END IF
              result1d0(nd0) = temp5d(nd0)
            END DO
            temp5 = temp11
            result1 = temp5
            DO nd=1,nbdirs
              DO nd0=nd,nbdirs0
                t0dd(nd0, nd) = (tndd(nd0, nd, mpg%fccv(ifc, 1))+tndd(&
&                 nd0, nd, mpg%fccv(ifc, 2)))/2.0_R8
                t1dd(nd0, nd) = (nadd(nd0, nd, mpg%fccv(ifc, 1), is)+&
&                 nadd(nd0, nd, mpg%fccv(ifc, 2), is))/2.0_R8
!   .. compute neutral heat conductivity flux limit
                arg11dd(nd0, nd) = dtnfd(nd, ifc, 0)*2*dtnfd0(nd0, ifc, &
&                 0) + 2*dtnf(ifc, 0)*dtnfdd(nd0, nd, ifc, 0) + dtnfd(nd&
&                 , ifc, 1)*2*dtnfd0(nd0, ifc, 1) + 2*dtnf(ifc, 1)*&
&                 dtnfdd(nd0, nd, ifc, 1)
              END DO
              t0d(nd) = (tnd(nd, mpg%fccv(ifc, 1))+tnd(nd, mpg%fccv(ifc&
&               , 2)))/2.0_R8
              t1d(nd) = (nad(nd, mpg%fccv(ifc, 1), is)+nad(nd, mpg%fccv(&
&               ifc, 2), is))/2.0_R8
              arg11d(nd) = 2*dtnf(ifc, 0)*dtnfd(nd, ifc, 0) + 2*dtnf(ifc&
&               , 1)*dtnfd(nd, ifc, 1)
              IF (arg11 .EQ. 0.d0) THEN
                DO nd0=1,nbdirs0
                  result1dd(nd0, nd) = 0.D0
                END DO
                result1d(nd) = 0.d0
              ELSE
                temp11 = arg11d(nd)/(2.0*temp5)
                DO nd0=1,nbdirs0
                  result1dd(nd0, nd) = (arg11dd(nd0, nd)-temp11*2.0*&
&                   temp5d(nd0))/(2.0*temp5)
                END DO
                result1d(nd) = temp11
              END IF
              DO nd0=1,nbdirs0
                dtndd(nd0, nd) = chcibd(nd, ifc, is)*result1d0(nd0) + &
&                 result1*chcibdd(nd0, nd, ifc, is) + result1d(nd)*&
&                 chcibd0(nd0, ifc, is) + chcib(ifc, is)*result1dd(nd0, &
&                 nd)
                arg10dd(nd0, nd) = 2.0_R8*t0dd(nd0, nd)/(am(is)*mp)
              END DO
              dtnd(nd) = result1*chcibd(nd, ifc, is) + chcib(ifc, is)*&
&               result1d(nd)
              arg10d(nd) = 2.0_R8*t0d(nd)/(am(is)*mp)
            END DO
            t0 = (tn(mpg%fccv(ifc, 1))+tn(mpg%fccv(ifc, 2)))/2.0_R8
            arg10 = 2.0_R8*t0/(am(is)*mp)
            temp6 = SQRT(arg10)
            DO nd0=1,nbdirs0
              t0d0(nd0) = (tnd0(nd0, mpg%fccv(ifc, 1))+tnd0(nd0, mpg%&
&               fccv(ifc, 2)))/2.0_R8
              t1d0(nd0) = (nad0(nd0, mpg%fccv(ifc, 1), is)+nad0(nd0, mpg&
&               %fccv(ifc, 2), is))/2.0_R8
              dtnd0(nd0) = result1*chcibd0(nd0, ifc, is) + chcib(ifc, is&
&               )*result1d0(nd0)
              arg10d0(nd0) = 2.0_R8*t0d0(nd0)/(am(is)*mp)
              IF (arg10 .EQ. 0.D0) THEN
                temp5d(nd0) = 0.D0
              ELSE
                temp5d(nd0) = arg10d0(nd0)/(2.0*temp6)
              END IF
              result1d0(nd0) = temp5d(nd0)
              vthid0(nd0) = geo%fcs(ifc)*result1d0(nd0)
            END DO
            t1 = (na(mpg%fccv(ifc, 1), is)+na(mpg%fccv(ifc, 2), is))/&
&             2.0_R8
            dtn = chcib(ifc, is)*result1
            temp5 = temp6
            result1 = temp5
            vthi = result1*geo%fcs(ifc)
            temp4 = b2tlh0_cutlo + alpha*vthi*t1*t0
            DO nd0=1,nbdirs0
              temp4d(nd0) = alpha*(t0*(t1*vthid0(nd0)+vthi*t1d0(nd0))+&
&               vthi*t1*t0d0(nd0))
              temp3d(nd0) = (dtnd0(nd0)-dtn*temp4d(nd0)/temp4)/temp4
            END DO
            temp3 = dtn/temp4
            DO nd=1,nbdirs
              IF (arg10 .EQ. 0.d0) THEN
                DO nd0=1,nbdirs0
                  result1dd(nd0, nd) = 0.D0
                END DO
                result1d(nd) = 0.d0
              ELSE
                temp6 = arg10d(nd)/(2.0*temp5)
                DO nd0=1,nbdirs0
                  result1dd(nd0, nd) = (arg10dd(nd0, nd)-temp6*2.0*&
&                   temp5d(nd0))/(2.0*temp5)
                END DO
                result1d(nd) = temp6
              END IF
              DO nd0=1,nbdirs0
                vthidd(nd0, nd) = geo%fcs(ifc)*result1dd(nd0, nd)
              END DO
              vthid(nd) = geo%fcs(ifc)*result1d(nd)
              IF (temp3 .LE. 0.d0 .AND. (gamma .EQ. 0.d0 .OR. gamma .NE.&
&                 INT(gamma))) THEN
                DO nd0=1,nbdirs0
                  tempd2d(nd0, nd) = 0.D0
                END DO
                tempd2(nd) = 0.d0
              ELSE
                temp11 = t1*vthid(nd) + vthi*t1d(nd)
                temp10 = t0*temp11 + vthi*t1*t0d(nd)
                temp9 = dtnd(nd) - alpha*temp3*temp10
                temp7 = temp3**(gamma-1)/temp4
                DO nd0=1,nbdirs0
                  IF (temp3 .LE. 0.D0 .AND. (gamma - 1 .EQ. 0.D0 .OR. &
&                     gamma - 1 .NE. INT(gamma - 1))) THEN
                    tempd6(nd0) = 0.D0
                  ELSE
                    tempd6(nd0) = (gamma-1)*temp3**(gamma-2)*temp3d(nd0)
                  END IF
                  tempd2d(nd0, nd) = gamma*(temp9*(tempd6(nd0)-temp7*&
&                   temp4d(nd0))/temp4+temp7*(dtndd(nd0, nd)-alpha*(&
&                   temp10*temp3d(nd0)+temp3*(temp11*t0d0(nd0)+t0*(vthid&
&                   (nd)*t1d0(nd0)+t1*vthidd(nd0, nd)+t1d(nd)*vthid0(nd0&
&                   )+vthi*t1dd(nd0, nd))+t0d(nd)*(t1*vthid0(nd0)+vthi*&
&                   t1d0(nd0))+vthi*t1*t0dd(nd0, nd)))))
                END DO
                tempd2(nd) = gamma*(temp7*temp9)
              END IF
            END DO
            temp5 = 1.0/gamma
            temp2 = temp3**gamma + 1.0_R8
            temp11 = 1.0/temp2**temp5
            DO nd0=1,nbdirs0
              IF (temp3 .LE. 0.D0 .AND. (gamma .EQ. 0.D0 .OR. gamma &
&                 .NE. INT(gamma))) THEN
                temp2d(nd0) = 0.D0
              ELSE
                temp2d(nd0) = gamma*temp3**(gamma-1)*temp3d(nd0)
              END IF
              IF (temp2 .LE. 0.D0 .AND. (temp5 .EQ. 0.D0 .OR. temp5 &
&                 .NE. INT(temp5))) THEN
                tempd4(nd0) = 0.D0
              ELSE
                tempd4(nd0) = temp5*temp2**(temp5-1)*temp2d(nd0)
              END IF
              temp1d(nd0) = -(temp11*tempd4(nd0)/temp2**temp5)
              t2d0(nd0) = temp1d(nd0)
            END DO
            temp1 = temp11
            t2 = temp1
            DO nd=1,nbdirs
              IF (temp2 .LE. 0.d0 .AND. (temp5 .EQ. 0.d0 .OR. temp5 .NE.&
&                 INT(temp5))) THEN
                DO nd0=1,nbdirs0
                  tempd1d(nd0, nd) = 0.D0
                END DO
                tempd1(nd) = 0.d0
              ELSE
                temp11 = temp2**(temp5-1)
                DO nd0=1,nbdirs0
                  IF (temp2 .LE. 0.D0 .AND. (temp5 - 1 .EQ. 0.D0 .OR. &
&                     temp5 - 1 .NE. INT(temp5 - 1))) THEN
                    tempd5(nd0) = 0.D0
                  ELSE
                    tempd5(nd0) = (temp5-1)*temp2**(temp5-2)*temp2d(nd0)
                  END IF
                  tempd1d(nd0, nd) = temp5*(tempd2(nd)*tempd5(nd0)+&
&                   temp11*tempd2d(nd0, nd))
                END DO
                tempd1(nd) = temp5*(temp11*tempd2(nd))
              END IF
              temp11 = temp2**temp5
              temp10 = temp1*tempd1(nd)/temp11
              t2d(nd) = -temp10
              DO nd0=1,nbdirs0
                IF (temp2 .LE. 0.D0 .AND. (temp5 .EQ. 0.D0 .OR. temp5 &
&                   .NE. INT(temp5))) THEN
                  tempd5(nd0) = 0.D0
                ELSE
                  tempd5(nd0) = temp5*temp2**(temp5-1)*temp2d(nd0)
                END IF
                t2dd(nd0, nd) = -((tempd1(nd)*temp1d(nd0)+temp1*tempd1d(&
&                 nd0, nd)-temp10*tempd5(nd0))/temp11)
!   .. limit in poloidal direction
                chcbdd(nd0, nd, ifc, 0, is) = chcbd(nd, ifc, 0, is)*t2d0&
&                 (nd0) + t2*chcbdd(nd0, nd, ifc, 0, is) + t2d(nd)*&
&                 chcbd0(nd0, ifc, 0, is) + chcb(ifc, 0, is)*t2dd(nd0, &
&                 nd)
              END DO
              chcbd(nd, ifc, 0, is) = t2*chcbd(nd, ifc, 0, is) + chcb(&
&               ifc, 0, is)*t2d(nd)
            END DO
            DO nd0=1,nbdirs0
              chcbd0(nd0, ifc, 0, is) = t2*chcbd0(nd0, ifc, 0, is) + &
&               chcb(ifc, 0, is)*t2d0(nd0)
            END DO
            chcb(ifc, 0, is) = chcb(ifc, 0, is)*t2
            fllim0fhi(ifc, 0, is) = t2
            IF (maxfluxlimit(0) .LT. t2) THEN
              maxfluxlimit(0) = t2
            ELSE
              maxfluxlimit(0) = maxfluxlimit(0)
            END IF
!   .. limit in radial diretion
            DO nd=1,nbdirs
              DO nd0=nd,nbdirs0
                chcbdd(nd0, nd, ifc, 1, is) = chcbd(nd, ifc, 1, is)*t2d0&
&                 (nd0) + t2*chcbdd(nd0, nd, ifc, 1, is) + t2d(nd)*&
&                 chcbd0(nd0, ifc, 1, is) + chcb(ifc, 1, is)*t2dd(nd0, &
&                 nd)
              END DO
              chcbd(nd, ifc, 1, is) = t2*chcbd(nd, ifc, 1, is) + chcb(&
&               ifc, 1, is)*t2d(nd)
            END DO
            DO nd0=1,nbdirs0
              chcbd0(nd0, ifc, 1, is) = t2*chcbd0(nd0, ifc, 1, is) + &
&               chcb(ifc, 1, is)*t2d0(nd0)
            END DO
            chcb(ifc, 1, is) = chcb(ifc, 1, is)*t2
            fllim0fhi(ifc, 1, is) = t2
            IF (maxfluxlimit(1) .LT. t2) THEN
              maxfluxlimit(1) = t2
            ELSE
              maxfluxlimit(1) = maxfluxlimit(1)
            END IF
          END DO
        END IF
      END DO
    END IF
  END IF
!
  IF (ncall_b2tlh0 .LT. 100) WRITE(*, '(1x,a,1p,2e10.2)') &
&                            'b2tlh0: maxfluxlimit = ', maxfluxlimit
!
  IF (switch%b2tlh0_iout .NE. 0) THEN
    ALLOCATE(w1(ncv))
!srv 13.01.04 {
    DO is=0,ns-1
      WRITE(charns, '(i3.3)') is
      arg12 = 'fllim0fhi_th'//charns
      CALL MY_OUT_US(70, nfc, 1, fllim0fhi(1, 0, is), arg12)
      arg13 = 'fllim0fhi_r'//charns
      CALL MY_OUT_US(70, nfc, 1, fllim0fhi(1, 1, is), arg13)
      arg14 = 'chci_th'//charns
      CALL MY_OUT_US(70, nfc, 1, chcb(1, 0, is), arg14)
      arg15 = 'chci_r'//charns
      CALL MY_OUT_US(70, nfc, 1, chcb(1, 1, is), arg15)
!srv 13.01.04 }
    END DO
    DEALLOCATE(w1)
  END IF
!
!   ..return
  ncall_b2tlh0 = ncall_b2tlh0 + 1
  CALL SUBEND()
  RETURN
!     ------------------------------------------------------------------
END SUBROUTINE B2TLH0_DV_DV

!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 23 Jul 2024 17:41
!
!  Differentiation of b2tlh0 in forward (tangent) mode (with options multiDirectional context noISIZE r8):
!   variations   of useful results: chcb
!   with respect to varying inputs: tn na chcb chcib
!   Plus diff mem management of: geo.fcs:in geo.fchc:in geo.fcht:in
!                geo.fcqalf:in geo.fcqbet:in geo.vxvol:in
!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE B2TLH0_DV_NODIFF(ncv, nfc, nvx, ns, switch, switchd, geo, &
& geod, mpg, mpgd, na, nad, ti, tn, tnd, chcib, chcibd, chcb, chcbd, &
& fllim0fhi, fllim0fhid, nbdirs)
  USE B2MOD_TYPES
  USE B2MOD_CONSTANTS
  USE B2MOD_B2CMPA_DIFFV
  USE B2MOD_SWITCHES_DIFFV_DIFFV
  USE B2US_GEO_DIFFV_DIFFV
  USE B2US_MAP_DIFFV_DIFFV
! csc The following are not necessary for computation but are needed
!     for adjoint AD to avoid side-effect variables
  USE B2MOD_AD_DIFFV_DIFFV, ONLY : ncall_b2tlh0, b2tlh0_cutlo
  USE B2MOD_AD_DIFFV_DIFFV, ONLY : my_out_folder
  USE B2MOD_SUBSYS
!  Hint: nbdirsmax should be the maximum number of differentiation directions
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!   ..input arguments (unchanged on exit)
  INTEGER :: ncv, nfc, nvx, ns
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(SWITCHES_DIFFV), INTENT(IN) :: switchd
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(GEOMETRY_DIFFV), INTENT(IN) :: geod
  TYPE(MAPPING), INTENT(IN) :: mpg
  TYPE(MAPPING_DIFFV), INTENT(IN) :: mpgd
  REAL(kind=r8) :: na(ncv, 0:ns-1), ti(ncv), tn(ncv), chcib(nfc, 0:ns-1)&
& , chcb(nfc, 0:1, 0:ns-1)
  REAL(kind=r8) :: nad(nbdirsmax, ncv, 0:ns-1), tnd(nbdirsmax, ncv), &
& chcibd(nbdirsmax, nfc, 0:ns-1), chcbd(nbdirsmax, nfc, 0:1, 0:ns-1)
!   ..output arguments (unspecified on entry)
  REAL(kind=r8) :: fllim0fhi(nfc, 0:1, 0:ns-1)
  REAL(kind=r8) :: fllim0fhid(nbdirsmax, nfc, 0:1, 0:ns-1)
!   ..common blocks
!     ------------------------------------------------------------------
!     B2TLH0 computes the conductive neutral heat transport flux limit.
!     ------------------------------------------------------------------
!   ..local variables
  INTEGER :: ifc, is
!srv 13.01.04 {
  REAL(kind=r8), ALLOCATABLE :: w1(:)
!srv 13.01.04 }
  CHARACTER :: charns*3
  REAL(kind=r8) :: alpha, gamma, t0, t1, t2, dtn, vthi, maxfluxlimit(0:1&
& ), tnv(nvx), dtnf(nfc, 0:1)
  REAL(kind=r8) :: t0d(nbdirsmax), t1d(nbdirsmax), t2d(nbdirsmax), dtnd(&
& nbdirsmax), vthid(nbdirsmax), tnvd(nbdirsmax, nvx), dtnfd(nbdirsmax, &
& nfc, 0:1)
!   ..initialisation
!   ..procedures
  INTRINSIC MAX, ABS, SQRT
  EXTERNAL XERTST, IPGETR, IPGETI
  REAL(kind=r8) :: abs0
  REAL(kind=r8) :: abs1
  INTEGER :: arg1
  REAL(r8) :: arg10
  REAL(r8), DIMENSION(nbdirsmax) :: arg10d
  REAL(kind=r8) :: result1
  REAL(kind=r8), DIMENSION(nbdirsmax) :: result1d
  REAL(kind=r8) :: arg11
  REAL(kind=r8), DIMENSION(nbdirsmax) :: arg11d
  CHARACTER(len=12) :: arg12
  CHARACTER(len=11) :: arg13
  CHARACTER(len=7) :: arg14
  CHARACTER(len=6) :: arg15
  INTEGER :: nd
  REAL(kind=r8) :: temp
  REAL(kind=r8) :: temp0
  REAL(kind=r8) :: temp1
  REAL(kind=r8) :: temp2
  REAL(kind=r8) :: temp3
  REAL(kind=r8) :: temp4
  REAL(kind=r8), DIMENSION(nbdirsmax) :: tempd
  REAL(kind=r8) :: temp5
  REAL(kind=r8), DIMENSION(nbdirsmax) :: tempd0
  REAL(kind=r8), DIMENSION(nbdirsmax) :: tempd1
  REAL(kind=r8), DIMENSION(nbdirsmax) :: tempd2
  INTEGER :: nbdirs
  INTRINSIC INT
!     ------------------------------------------------------------------
!   ..subprogram start-up calls
  CALL SUBINI('b2tlh0')
!   ..test nCv, nFc, ns
  CALL XERTST(0 .LT. ncv .AND. 0 .LT. nfc, 'faulty argument nCv, nFc')
  CALL XERTST(1 .LE. ns, 'faulty argument ns')
!   ..read input on first call
! The following switches are only used in 'WG-TODO' blocks, i.e. not yet converted to wide grid functionality
!        call ipgetr ('b2tlh0_flux_limit_min_ti', flux_limit_min_tn) !! do not change name of switch for compatibility with exist
!ing input files?
!        flux_limit_min_tn=flux_limit_min_tn*ev
!
  alpha = switch%b2tlh0_alpha
  gamma = switch%b2tlh0_gamma
  arg1 = nfc*2*ns
  CALL SFILL_NODIFF_NODIFF(arg1, 1.0_R8, fllim0fhi, 1)
  maxfluxlimit = 0.0_R8
!
  IF (alpha .NE. 0.0_R8) THEN
!   .. compute differences of temperature
    dtnfd = 0.d0
    tnvd = 0.d0
    CALL DIFF_DV_NODIFF(ncv, nfc, nvx, 0, geo, geod, mpg, mpgd, tn, tnd&
&                 , tnv, tnvd, dtnf, dtnfd, nbdirs)
    IF (switch%b2tlh0_style .EQ. 0) THEN
      DO is=0,ns-1
        IF (is_neutral(is)) THEN
          DO ifc=1,nfc
            DO nd=1,nbdirs
              t0d(nd) = (tnd(nd, mpg%fccv(ifc, 1))+tnd(nd, mpg%fccv(ifc&
&               , 2)))/2.0_R8
              t1d(nd) = (nad(nd, mpg%fccv(ifc, 1), is)+nad(nd, mpg%fccv(&
&               ifc, 2), is))/2.0_R8
            END DO
            t0 = (tn(mpg%fccv(ifc, 1))+tn(mpg%fccv(ifc, 2)))/2.0_R8
            t1 = (na(mpg%fccv(ifc, 1), is)+na(mpg%fccv(ifc, 2), is))/&
&             2.0_R8
            IF (chcb(ifc, 0, is)*dtnf(ifc, 0) .GE. 0.) THEN
              DO nd=1,nbdirs
                dtnd(nd) = dtnf(ifc, 0)*chcbd(nd, ifc, 0, is) + chcb(ifc&
&                 , 0, is)*dtnfd(nd, ifc, 0)
              END DO
              dtn = chcb(ifc, 0, is)*dtnf(ifc, 0)
            ELSE
              DO nd=1,nbdirs
                dtnd(nd) = -(dtnf(ifc, 0)*chcbd(nd, ifc, 0, is)+chcb(ifc&
&                 , 0, is)*dtnfd(nd, ifc, 0))
              END DO
              dtn = -(chcb(ifc, 0, is)*dtnf(ifc, 0))
            END IF
            IF (geo%fcqalf(ifc, 0) .GE. 0.) THEN
              abs0 = geo%fcqalf(ifc, 0)
            ELSE
              abs0 = -geo%fcqalf(ifc, 0)
            END IF
            arg10 = 2.0_R8*t0/(am(is)*mp)
            temp = SQRT(arg10)
            result1 = temp
            vthi = result1*geo%fcs(ifc)*abs0
            temp0 = b2tlh0_cutlo + alpha*vthi*t1*t0
            temp1 = dtn/temp0
            DO nd=1,nbdirs
              arg10d(nd) = 2.0_R8*t0d(nd)/(am(is)*mp)
              IF (arg10 .EQ. 0.d0) THEN
                result1d(nd) = 0.d0
              ELSE
                result1d(nd) = arg10d(nd)/(2.0*temp)
              END IF
              vthid(nd) = geo%fcs(ifc)*abs0*result1d(nd)
              IF (temp1 .LE. 0.d0 .AND. (gamma .EQ. 0.d0 .OR. gamma .NE.&
&                 INT(gamma))) THEN
                tempd0(nd) = 0.d0
              ELSE
                tempd0(nd) = gamma*temp1**(gamma-1)*(dtnd(nd)-temp1*&
&                 alpha*(t0*(t1*vthid(nd)+vthi*t1d(nd))+vthi*t1*t0d(nd))&
&                 )/temp0
              END IF
            END DO
            temp = 1.0/gamma
            temp2 = temp1**gamma + 1.0_R8
            temp3 = 1.0/temp2**temp
            t2 = temp3
            DO nd=1,nbdirs
              IF (temp2 .LE. 0.d0 .AND. (temp .EQ. 0.d0 .OR. temp .NE. &
&                 INT(temp))) THEN
                tempd(nd) = 0.d0
              ELSE
                tempd(nd) = temp*temp2**(temp-1)*tempd0(nd)
              END IF
              t2d(nd) = -(temp3*tempd(nd)/temp2**temp)
              chcbd(nd, ifc, 0, is) = t2*chcbd(nd, ifc, 0, is) + chcb(&
&               ifc, 0, is)*t2d(nd)
            END DO
            chcb(ifc, 0, is) = chcb(ifc, 0, is)*t2
            fllim0fhi(ifc, 0, is) = t2
            IF (maxfluxlimit(0) .LT. t2) THEN
              maxfluxlimit(0) = t2
            ELSE
              maxfluxlimit(0) = maxfluxlimit(0)
            END IF
            IF (chcb(ifc, 1, is)*dtnf(ifc, 1) .GE. 0.) THEN
              DO nd=1,nbdirs
                dtnd(nd) = dtnf(ifc, 1)*chcbd(nd, ifc, 1, is) + chcb(ifc&
&                 , 1, is)*dtnfd(nd, ifc, 1)
              END DO
              dtn = chcb(ifc, 1, is)*dtnf(ifc, 1)
            ELSE
              DO nd=1,nbdirs
                dtnd(nd) = -(dtnf(ifc, 1)*chcbd(nd, ifc, 1, is)+chcb(ifc&
&                 , 1, is)*dtnfd(nd, ifc, 1))
              END DO
              dtn = -(chcb(ifc, 1, is)*dtnf(ifc, 1))
            END IF
            IF (geo%fcqalf(ifc, 1) .GE. 0.) THEN
              abs1 = geo%fcqalf(ifc, 1)
            ELSE
              abs1 = -geo%fcqalf(ifc, 1)
            END IF
            arg10 = 2.0_R8*t0/(am(is)*mp)
            temp5 = SQRT(arg10)
            result1 = temp5
            vthi = result1*geo%fcs(ifc)*abs1
            temp4 = b2tlh0_cutlo + alpha*vthi*t1*t0
            temp3 = dtn/temp4
            DO nd=1,nbdirs
              arg10d(nd) = 2.0_R8*t0d(nd)/(am(is)*mp)
              IF (arg10 .EQ. 0.d0) THEN
                result1d(nd) = 0.d0
              ELSE
                result1d(nd) = arg10d(nd)/(2.0*temp5)
              END IF
              vthid(nd) = geo%fcs(ifc)*abs1*result1d(nd)
              IF (temp3 .LE. 0.d0 .AND. (gamma .EQ. 0.d0 .OR. gamma .NE.&
&                 INT(gamma))) THEN
                tempd2(nd) = 0.d0
              ELSE
                tempd2(nd) = gamma*temp3**(gamma-1)*(dtnd(nd)-temp3*&
&                 alpha*(t0*(t1*vthid(nd)+vthi*t1d(nd))+vthi*t1*t0d(nd))&
&                 )/temp4
              END IF
            END DO
            temp5 = 1.0/gamma
            temp2 = temp3**gamma + 1.0_R8
            temp1 = 1.0/temp2**temp5
            t2 = temp1
            DO nd=1,nbdirs
              IF (temp2 .LE. 0.d0 .AND. (temp5 .EQ. 0.d0 .OR. temp5 .NE.&
&                 INT(temp5))) THEN
                tempd1(nd) = 0.d0
              ELSE
                tempd1(nd) = temp5*temp2**(temp5-1)*tempd2(nd)
              END IF
              t2d(nd) = -(temp1*tempd1(nd)/temp2**temp5)
              chcbd(nd, ifc, 1, is) = t2*chcbd(nd, ifc, 1, is) + chcb(&
&               ifc, 1, is)*t2d(nd)
            END DO
            chcb(ifc, 1, is) = chcb(ifc, 1, is)*t2
            fllim0fhi(ifc, 1, is) = t2
            IF (maxfluxlimit(1) .LT. t2) THEN
              maxfluxlimit(1) = t2
            ELSE
              maxfluxlimit(1) = maxfluxlimit(1)
            END IF
          END DO
        END IF
      END DO
    ELSE
!wdk    flux limit total gradient-driven flow, not individual poloidal
!wdk    or radial contributions, since neutral transport is isotropic
      DO is=0,ns-1
        IF (is_neutral(is)) THEN
          DO ifc=1,nfc
            arg11 = dtnf(ifc, 0)**2 + dtnf(ifc, 1)**2
            temp5 = SQRT(arg11)
            result1 = temp5
            DO nd=1,nbdirs
              t0d(nd) = (tnd(nd, mpg%fccv(ifc, 1))+tnd(nd, mpg%fccv(ifc&
&               , 2)))/2.0_R8
              t1d(nd) = (nad(nd, mpg%fccv(ifc, 1), is)+nad(nd, mpg%fccv(&
&               ifc, 2), is))/2.0_R8
!   .. compute neutral heat conductivity flux limit
              arg11d(nd) = 2*dtnf(ifc, 0)*dtnfd(nd, ifc, 0) + 2*dtnf(ifc&
&               , 1)*dtnfd(nd, ifc, 1)
              IF (arg11 .EQ. 0.d0) THEN
                result1d(nd) = 0.d0
              ELSE
                result1d(nd) = arg11d(nd)/(2.0*temp5)
              END IF
              dtnd(nd) = result1*chcibd(nd, ifc, is) + chcib(ifc, is)*&
&               result1d(nd)
              arg10d(nd) = 2.0_R8*t0d(nd)/(am(is)*mp)
            END DO
            t0 = (tn(mpg%fccv(ifc, 1))+tn(mpg%fccv(ifc, 2)))/2.0_R8
            t1 = (na(mpg%fccv(ifc, 1), is)+na(mpg%fccv(ifc, 2), is))/&
&             2.0_R8
            dtn = chcib(ifc, is)*result1
            arg10 = 2.0_R8*t0/(am(is)*mp)
            temp5 = SQRT(arg10)
            result1 = temp5
            vthi = result1*geo%fcs(ifc)
            temp4 = b2tlh0_cutlo + alpha*vthi*t1*t0
            temp3 = dtn/temp4
            DO nd=1,nbdirs
              IF (arg10 .EQ. 0.d0) THEN
                result1d(nd) = 0.d0
              ELSE
                result1d(nd) = arg10d(nd)/(2.0*temp5)
              END IF
              vthid(nd) = geo%fcs(ifc)*result1d(nd)
              IF (temp3 .LE. 0.d0 .AND. (gamma .EQ. 0.d0 .OR. gamma .NE.&
&                 INT(gamma))) THEN
                tempd2(nd) = 0.d0
              ELSE
                tempd2(nd) = gamma*temp3**(gamma-1)*(dtnd(nd)-temp3*&
&                 alpha*(t0*(t1*vthid(nd)+vthi*t1d(nd))+vthi*t1*t0d(nd))&
&                 )/temp4
              END IF
            END DO
            temp5 = 1.0/gamma
            temp2 = temp3**gamma + 1.0_R8
            temp1 = 1.0/temp2**temp5
            t2 = temp1
            DO nd=1,nbdirs
              IF (temp2 .LE. 0.d0 .AND. (temp5 .EQ. 0.d0 .OR. temp5 .NE.&
&                 INT(temp5))) THEN
                tempd1(nd) = 0.d0
              ELSE
                tempd1(nd) = temp5*temp2**(temp5-1)*tempd2(nd)
              END IF
              t2d(nd) = -(temp1*tempd1(nd)/temp2**temp5)
!   .. limit in poloidal direction
              chcbd(nd, ifc, 0, is) = t2*chcbd(nd, ifc, 0, is) + chcb(&
&               ifc, 0, is)*t2d(nd)
            END DO
            chcb(ifc, 0, is) = chcb(ifc, 0, is)*t2
            fllim0fhi(ifc, 0, is) = t2
            IF (maxfluxlimit(0) .LT. t2) THEN
              maxfluxlimit(0) = t2
            ELSE
              maxfluxlimit(0) = maxfluxlimit(0)
            END IF
!   .. limit in radial diretion
            DO nd=1,nbdirs
              chcbd(nd, ifc, 1, is) = t2*chcbd(nd, ifc, 1, is) + chcb(&
&               ifc, 1, is)*t2d(nd)
            END DO
            chcb(ifc, 1, is) = chcb(ifc, 1, is)*t2
            fllim0fhi(ifc, 1, is) = t2
            IF (maxfluxlimit(1) .LT. t2) THEN
              maxfluxlimit(1) = t2
            ELSE
              maxfluxlimit(1) = maxfluxlimit(1)
            END IF
          END DO
        END IF
      END DO
    END IF
  END IF
!
  IF (ncall_b2tlh0 .LT. 100) WRITE(*, '(1x,a,1p,2e10.2)') &
&                            'b2tlh0: maxfluxlimit = ', maxfluxlimit
!
  IF (switch%b2tlh0_iout .NE. 0) THEN
    ALLOCATE(w1(ncv))
!srv 13.01.04 {
    DO is=0,ns-1
      WRITE(charns, '(i3.3)') is
      arg12 = 'fllim0fhi_th'//charns
      CALL MY_OUT_US(70, nfc, 1, fllim0fhi(1, 0, is), arg12)
      arg13 = 'fllim0fhi_r'//charns
      CALL MY_OUT_US(70, nfc, 1, fllim0fhi(1, 1, is), arg13)
      arg14 = 'chci_th'//charns
      CALL MY_OUT_US(70, nfc, 1, chcb(1, 0, is), arg14)
      arg15 = 'chci_r'//charns
      CALL MY_OUT_US(70, nfc, 1, chcb(1, 1, is), arg15)
!srv 13.01.04 }
    END DO
    DEALLOCATE(w1)
  END IF
!
!   ..return
  ncall_b2tlh0 = ncall_b2tlh0 + 1
  CALL SUBEND()
  RETURN
!     ------------------------------------------------------------------
END SUBROUTINE B2TLH0_DV_NODIFF

!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE B2TLH0_NODIFF_NODIFF(ncv, nfc, nvx, ns, switch, geo, mpg, na&
& , ti, tn, chcib, chcb, fllim0fhi)
  USE B2MOD_TYPES
  USE B2MOD_CONSTANTS
  USE B2MOD_B2CMPA_DIFFV
  USE B2MOD_SWITCHES_DIFFV_DIFFV
  USE B2US_GEO_DIFFV_DIFFV
  USE B2US_MAP_DIFFV_DIFFV
! csc The following are not necessary for computation but are needed
!     for adjoint AD to avoid side-effect variables
  USE B2MOD_AD_DIFFV_DIFFV, ONLY : ncall_b2tlh0, b2tlh0_cutlo
  USE B2MOD_AD_DIFFV_DIFFV, ONLY : my_out_folder
  USE B2MOD_SUBSYS
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!   ..input arguments (unchanged on exit)
  INTEGER :: ncv, nfc, nvx, ns
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(MAPPING), INTENT(IN) :: mpg
  REAL(kind=r8) :: na(ncv, 0:ns-1), ti(ncv), tn(ncv), chcib(nfc, 0:ns-1)&
& , chcb(nfc, 0:1, 0:ns-1)
!   ..output arguments (unspecified on entry)
  REAL(kind=r8) :: fllim0fhi(nfc, 0:1, 0:ns-1)
!   ..common blocks
!     ------------------------------------------------------------------
!     B2TLH0 computes the conductive neutral heat transport flux limit.
!     ------------------------------------------------------------------
!   ..local variables
  INTEGER :: ifc, is
!srv 13.01.04 {
  REAL(kind=r8), ALLOCATABLE :: w1(:)
!srv 13.01.04 }
  CHARACTER :: charns*3
  REAL(kind=r8) :: alpha, gamma, t0, t1, t2, dtn, vthi, maxfluxlimit(0:1&
& ), tnv(nvx), dtnf(nfc, 0:1)
!   ..initialisation
!   ..procedures
  INTRINSIC MAX, ABS, SQRT
  EXTERNAL XERTST, IPGETR, IPGETI
  REAL(kind=r8) :: abs0
  REAL(kind=r8) :: abs1
  INTEGER :: arg1
  REAL(r8) :: arg10
  REAL(kind=r8) :: result1
  REAL(kind=r8) :: arg11
  CHARACTER(len=12) :: arg12
  CHARACTER(len=11) :: arg13
  CHARACTER(len=7) :: arg14
  CHARACTER(len=6) :: arg15
!     ------------------------------------------------------------------
!   ..subprogram start-up calls
  CALL SUBINI('b2tlh0')
!   ..test nCv, nFc, ns
  CALL XERTST(0 .LT. ncv .AND. 0 .LT. nfc, 'faulty argument nCv, nFc')
  CALL XERTST(1 .LE. ns, 'faulty argument ns')
!   ..read input on first call
! The following switches are only used in 'WG-TODO' blocks, i.e. not yet converted to wide grid functionality
!        call ipgetr ('b2tlh0_flux_limit_min_ti', flux_limit_min_tn) !! do not change name of switch for compatibility with exist
!ing input files?
!        flux_limit_min_tn=flux_limit_min_tn*ev
!
  alpha = switch%b2tlh0_alpha
  gamma = switch%b2tlh0_gamma
  arg1 = nfc*2*ns
  CALL SFILL_NODIFF_NODIFF(arg1, 1.0_R8, fllim0fhi, 1)
  maxfluxlimit = 0.0_R8
!
  IF (alpha .NE. 0.0_R8) THEN
!   .. compute differences of temperature
    CALL DIFF_NODIFF_NODIFF(ncv, nfc, nvx, 0, geo, mpg, tn, tnv, dtnf)
    IF (switch%b2tlh0_style .EQ. 0) THEN
      DO is=0,ns-1
        IF (is_neutral(is)) THEN
          DO ifc=1,nfc
            t0 = (tn(mpg%fccv(ifc, 1))+tn(mpg%fccv(ifc, 2)))/2.0_R8
            t1 = (na(mpg%fccv(ifc, 1), is)+na(mpg%fccv(ifc, 2), is))/&
&             2.0_R8
            IF (chcb(ifc, 0, is)*dtnf(ifc, 0) .GE. 0.) THEN
              dtn = chcb(ifc, 0, is)*dtnf(ifc, 0)
            ELSE
              dtn = -(chcb(ifc, 0, is)*dtnf(ifc, 0))
            END IF
            IF (geo%fcqalf(ifc, 0) .GE. 0.) THEN
              abs0 = geo%fcqalf(ifc, 0)
            ELSE
              abs0 = -geo%fcqalf(ifc, 0)
            END IF
            arg10 = 2.0_R8*t0/(am(is)*mp)
            result1 = SQRT(arg10)
            vthi = result1*geo%fcs(ifc)*abs0
            t2 = 1.0_R8/(1.0_R8+(dtn/(alpha*vthi*t1*t0+b2tlh0_cutlo))**&
&             gamma)**(1.0_R8/gamma)
            chcb(ifc, 0, is) = chcb(ifc, 0, is)*t2
            fllim0fhi(ifc, 0, is) = t2
            IF (maxfluxlimit(0) .LT. t2) THEN
              maxfluxlimit(0) = t2
            ELSE
              maxfluxlimit(0) = maxfluxlimit(0)
            END IF
            IF (chcb(ifc, 1, is)*dtnf(ifc, 1) .GE. 0.) THEN
              dtn = chcb(ifc, 1, is)*dtnf(ifc, 1)
            ELSE
              dtn = -(chcb(ifc, 1, is)*dtnf(ifc, 1))
            END IF
            IF (geo%fcqalf(ifc, 1) .GE. 0.) THEN
              abs1 = geo%fcqalf(ifc, 1)
            ELSE
              abs1 = -geo%fcqalf(ifc, 1)
            END IF
            arg10 = 2.0_R8*t0/(am(is)*mp)
            result1 = SQRT(arg10)
            vthi = result1*geo%fcs(ifc)*abs1
            t2 = 1.0_R8/(1.0_R8+(dtn/(alpha*vthi*t1*t0+b2tlh0_cutlo))**&
&             gamma)**(1.0_R8/gamma)
            chcb(ifc, 1, is) = chcb(ifc, 1, is)*t2
            fllim0fhi(ifc, 1, is) = t2
            IF (maxfluxlimit(1) .LT. t2) THEN
              maxfluxlimit(1) = t2
            ELSE
              maxfluxlimit(1) = maxfluxlimit(1)
            END IF
          END DO
        END IF
      END DO
    ELSE
!wdk    flux limit total gradient-driven flow, not individual poloidal
!wdk    or radial contributions, since neutral transport is isotropic
      DO is=0,ns-1
        IF (is_neutral(is)) THEN
          DO ifc=1,nfc
            t0 = (tn(mpg%fccv(ifc, 1))+tn(mpg%fccv(ifc, 2)))/2.0_R8
            t1 = (na(mpg%fccv(ifc, 1), is)+na(mpg%fccv(ifc, 2), is))/&
&             2.0_R8
!   .. compute neutral heat conductivity flux limit
            arg11 = dtnf(ifc, 0)**2 + dtnf(ifc, 1)**2
            result1 = SQRT(arg11)
            dtn = chcib(ifc, is)*result1
            arg10 = 2.0_R8*t0/(am(is)*mp)
            result1 = SQRT(arg10)
            vthi = result1*geo%fcs(ifc)
            t2 = 1.0_R8/(1.0_R8+(dtn/(alpha*vthi*t1*t0+b2tlh0_cutlo))**&
&             gamma)**(1.0_R8/gamma)
!   .. limit in poloidal direction
            chcb(ifc, 0, is) = chcb(ifc, 0, is)*t2
            fllim0fhi(ifc, 0, is) = t2
            IF (maxfluxlimit(0) .LT. t2) THEN
              maxfluxlimit(0) = t2
            ELSE
              maxfluxlimit(0) = maxfluxlimit(0)
            END IF
!   .. limit in radial diretion
            chcb(ifc, 1, is) = chcb(ifc, 1, is)*t2
            fllim0fhi(ifc, 1, is) = t2
            IF (maxfluxlimit(1) .LT. t2) THEN
              maxfluxlimit(1) = t2
            ELSE
              maxfluxlimit(1) = maxfluxlimit(1)
            END IF
          END DO
        END IF
      END DO
    END IF
  END IF
!
  IF (ncall_b2tlh0 .LT. 100) WRITE(*, '(1x,a,1p,2e10.2)') &
&                            'b2tlh0: maxfluxlimit = ', maxfluxlimit
!
  IF (switch%b2tlh0_iout .NE. 0) THEN
    ALLOCATE(w1(ncv))
!srv 13.01.04 {
    DO is=0,ns-1
      WRITE(charns, '(i3.3)') is
      arg12 = 'fllim0fhi_th'//charns
      CALL MY_OUT_US(70, nfc, 1, fllim0fhi(1, 0, is), arg12)
      arg13 = 'fllim0fhi_r'//charns
      CALL MY_OUT_US(70, nfc, 1, fllim0fhi(1, 1, is), arg13)
      arg14 = 'chci_th'//charns
      CALL MY_OUT_US(70, nfc, 1, chcb(1, 0, is), arg14)
      arg15 = 'chci_r'//charns
      CALL MY_OUT_US(70, nfc, 1, chcb(1, 1, is), arg15)
!srv 13.01.04 }
    END DO
    DEALLOCATE(w1)
  END IF
!
!   ..return
  ncall_b2tlh0 = ncall_b2tlh0 + 1
  CALL SUBEND()
  RETURN
!     ------------------------------------------------------------------
END SUBROUTINE B2TLH0_NODIFF_NODIFF

