!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 23 Jul 2024 17:41
!
!  Differentiation of b2tnpsch_dv in forward (tangent) mode (with options multiDirectional context noISIZE r8):
!   variations   of useful results: flob fnbpschd conbd flobd conb
!                fnbpsch
!   with respect to varying inputs: ti cddb nb cddbd tid nbd kmprtid
!                kmprti
!   Plus diff mem management of: geo.fchc:in geo.fcht:in geo.fcqalf:in
!                geo.fcqbet:in geo.vxvol:in
!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 23 Jul 2024 17:41
!
!  Differentiation of b2tnpsch in forward (tangent) mode (with options multiDirectional context noISIZE r8):
!   variations   of useful results: flob conb fnbpsch
!   with respect to varying inputs: ti cddb nb kmprti
!   Plus diff mem management of: geo.fchc:in geo.fcht:in geo.fcqalf:in
!                geo.fcqbet:in geo.vxvol:in
!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE B2TNPSCH_DV_DV(ncv, nfc, nvx, switch, geo, geod0, geod, mpg, &
& mpgd, facdrift, cddb, cddbd0, cddbd, cddbdd, ti, tid0, tid, tidd, nb, &
& nbd0, nbd, nbdd, kmprti, kmprtid0, kmprtid, kmprtidd, flob, flobd0, &
& flobd, flobdd, conb, conbd0, conbd, conbdd, fnbpsch, fnbpschd0, &
& fnbpschd, fnbpschdd, nbdirs, nbdirs0)
  USE B2MOD_TYPES
  USE B2MOD_B2CMPA_DIFFV
  USE B2MOD_SWITCHES_DIFFV_DIFFV
  USE B2US_GEO_DIFFV_DIFFV
  USE B2US_MAP_DIFFV_DIFFV
  USE B2MOD_SUBSYS
!  Hint: nbdirsmax should be the maximum number of differentiation directions
  USE B2MOD_DIFFSIZES
!  Hint: nbdirsmax0 should be the maximum number of differentiation directions
  IMPLICIT NONE
!   ..input arguments (unchanged on exit)
  INTEGER :: ncv, nfc, nvx
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(GEOMETRY_DIFFV0), INTENT(IN) :: geod0
  TYPE(GEOMETRY_DIFFV), INTENT(IN) :: geod
  TYPE(MAPPING), INTENT(IN) :: mpg
  TYPE(MAPPING_DIFFV), INTENT(IN) :: mpgd
  REAL(kind=r8) :: facdrift(nfc), cddb(nfc, 0:1), ti(ncv), nb(ncv), &
& kmprti(ncv)
  REAL(kind=r8) :: cddbd0(nbdirsmax0, nfc, 0:1), tid0(nbdirsmax0, ncv), &
& nbd0(nbdirsmax0, ncv), kmprtid0(nbdirsmax0, ncv)
  REAL(kind=r8) :: cddbd(nbdirsmax, nfc, 0:1), tid(nbdirsmax, ncv), nbd(&
& nbdirsmax, ncv), kmprtid(nbdirsmax, ncv)
  REAL(kind=r8) :: cddbdd(nbdirsmax0, nbdirsmax, nfc, 0:1), tidd(&
& nbdirsmax0, nbdirsmax, ncv), nbdd(nbdirsmax0, nbdirsmax, ncv), &
& kmprtidd(nbdirsmax0, nbdirsmax, ncv)
!   ..output arguments (unspecified on entry)
  REAL(kind=r8) :: flob(nfc, 0:1), conb(nfc, 0:1, 0:2), fnbpsch(nfc, 0:1&
& )
  REAL(kind=r8) :: flobd0(nbdirsmax0, nfc, 0:1), conbd0(nbdirsmax0, nfc&
& , 0:1, 0:2), fnbpschd0(nbdirsmax0, nfc, 0:1)
  REAL(kind=r8) :: flobd(nbdirsmax, nfc, 0:1), conbd(nbdirsmax, nfc, 0:1&
& , 0:2), fnbpschd(nbdirsmax, nfc, 0:1)
  REAL(kind=r8) :: flobdd(nbdirsmax0, nbdirsmax, nfc, 0:1), conbdd(&
& nbdirsmax0, nbdirsmax, nfc, 0:1, 0:2), fnbpschdd(nbdirsmax0, nbdirsmax&
& , nfc, 0:1)
!-----------------------------------------------------------------------
!.documentation
!
!  1. purpose
!
!     B2TNPSCH computes the poloidal and radial components of the
!     Pfirsch-Schlueter particle flux of one atomic species, and the
!     coefficients that specify its linearization.
!
!  8. further comments
!
!-----------------------------------------------------------------------
!.declarations
!
!   ..local variables
  INTEGER :: ifc
  INTEGER, SAVE :: ncall=0
  REAL(kind=r8) :: facdriftm, nbti(ncv), nbtiv(nvx), kmprtiv(nvx), dnbti&
& (nfc, 0:1), flob0(nfc, 0:1), conb0(nfc, 0:1), cddb_eff(nfc, 0:1), &
& dumm0(nfc, 0:1)
  REAL(kind=r8) :: nbtid0(nbdirsmax0, ncv), nbtivd0(nbdirsmax0, nvx), &
& kmprtivd0(nbdirsmax0, nvx), dnbtid0(nbdirsmax0, nfc, 0:1), flob0d0(&
& nbdirsmax0, nfc, 0:1), conb0d0(nbdirsmax0, nfc, 0:1), cddb_effd0(&
& nbdirsmax0, nfc, 0:1), dumm0d0(nbdirsmax0, nfc, 0:1)
  REAL(kind=r8) :: nbtid(nbdirsmax, ncv), nbtivd(nbdirsmax, nvx), &
& kmprtivd(nbdirsmax, nvx), dnbtid(nbdirsmax, nfc, 0:1), flob0d(&
& nbdirsmax, nfc, 0:1), conb0d(nbdirsmax, nfc, 0:1), cddb_effd(nbdirsmax&
& , nfc, 0:1), dumm0d(nbdirsmax, nfc, 0:1)
  REAL(kind=r8) :: nbtidd(nbdirsmax0, nbdirsmax, ncv), nbtivdd(&
& nbdirsmax0, nbdirsmax, nvx), kmprtivdd(nbdirsmax0, nbdirsmax, nvx), &
& dnbtidd(nbdirsmax0, nbdirsmax, nfc, 0:1), flob0dd(nbdirsmax0, &
& nbdirsmax, nfc, 0:1), conb0dd(nbdirsmax0, nbdirsmax, nfc, 0:1), &
& cddb_effdd(nbdirsmax0, nbdirsmax, nfc, 0:1), dumm0dd(nbdirsmax0, &
& nbdirsmax, nfc, 0:1)
  INTRINSIC MAXVAL
  INTEGER :: nd
  REAL(kind=r8), DIMENSION(nfc) :: temp
  REAL(kind=r8) :: temp0
  REAL(kind=r8), DIMENSION(nbdirsmax0) :: temp0d
  INTEGER :: nbdirs
  INTEGER :: nd0
  REAL(kind=r8) :: temp1
  INTEGER :: nbdirs0
!-----------------------------------------------------------------------
!.computation
!
! ..preliminaries
!   ..subprogram start-up calls
  CALL SUBINI('b2tnpsch')
!   ..test nCv, nFc
  CALL XERTST(0 .LE. ncv .AND. 0 .LE. nfc, 'faulty argument nCv, nFc')
!
!   ..set dummy arrays
  dumm0 = 0.0_R8
!
!srv 13.10.06
  fnbpsch = 0.0e0_R8
!srv 02.01.07
  DO nd=1,nbdirs
    conbd(nd, :, :, :) = 0.d0
  END DO
  conb = 0.0e0_R8
  flob = 0.0e0_R8
  facdriftm = MAXVAL(facdrift)
  IF (facdriftm .NE. 0.0e0_R8) THEN
!
!     ..linearization coefficients for P.Sch flows
    cddb_effd = 0.d0
    cddb_effdd = 0.D0
    nbtidd = 0.D0
    DO nd=1,nbdirs
      DO nd0=nd,nbdirs0
!
!     ..precompute face and vertex values of nbti and kmprti
        nbtidd(nd0, nd, :) = nbd(nd, :)*tid0(nd0, :) + ti*nbdd(nd0, nd, &
&         :) + tid(nd, :)*nbd0(nd0, :) + nb*tidd(nd0, nd, :)
        cddb_effdd(nd0, nd, :, 0) = -(switch%fnbpsch*facdrift*geo%fcqalf&
&         (:, 1)*cddbdd(nd0, nd, :, 1))
        cddb_effdd(nd0, nd, :, 1) = switch%fnbpsch*facdrift*geo%fcqalf(:&
&         , 0)*cddbdd(nd0, nd, :, 0)
      END DO
      nbtid(nd, :) = ti*nbd(nd, :) + nb*tid(nd, :)
      cddb_effd(nd, :, 0) = -(switch%fnbpsch*facdrift*geo%fcqalf(:, 1)*&
&       cddbd(nd, :, 1))
      cddb_effd(nd, :, 1) = switch%fnbpsch*facdrift*geo%fcqalf(:, 0)*&
&       cddbd(nd, :, 0)
    END DO
    DO nd0=1,nbdirs0
      nbtid0(nd0, :) = ti*nbd0(nd0, :) + nb*tid0(nd0, :)
    END DO
    nbti = nb*ti
    nbtivd = 0.d0
    nbtivdd = 0.D0
    nbtivd0 = 0.D0
    CALL INTVERTEX_DV_DV(ncv, nvx, mpg, geo%vxvol, nbti, nbtid0, nbtid, &
&                  nbtidd, nbtiv, nbtivd0, nbtivd, nbtivdd, nbdirs, &
&                  nbdirs0)
    kmprtivd = 0.d0
    kmprtivd0 = 0.D0
    kmprtivdd = 0.D0
    CALL INTVERTEX_DV_DV(ncv, nvx, mpg, geo%vxvol, kmprti, kmprtid0, &
&                  kmprtid, kmprtidd, kmprtiv, kmprtivd0, kmprtivd, &
&                  kmprtivdd, nbdirs, nbdirs0)
    dnbtid = 0.d0
    dnbtid0 = 0.D0
    dnbtidd = 0.D0
    CALL DIFF_DV_DV(ncv, nfc, nvx, 1, geo, geod0, geod, mpg, mpgd, nbti&
&             , nbtid0, nbtid, nbtidd, nbtiv, nbtivd0, nbtivd, nbtivdd, &
&             dnbti, dnbtid0, dnbtid, dnbtidd, nbdirs, nbdirs0)
!
!     ..compute P.Sch heat flux
    fnbpschd = 0.d0
    temp = switch%fnbpsch*facdrift*geo%fcqalf(:, 0)
    fnbpschdd = 0.D0
    DO nd=1,nbdirs
      DO nd0=nd,nbdirs0
        fnbpschdd(nd0, nd, :, 0) = temp*(cddbd(nd, :, 0)*dnbtid0(nd0, :&
&         , 1)+dnbti(:, 1)*cddbdd(nd0, nd, :, 0)+dnbtid(nd, :, 1)*cddbd0&
&         (nd0, :, 0)+cddb(:, 0)*dnbtidd(nd0, nd, :, 1))
      END DO
      fnbpschd(nd, :, 0) = temp*(dnbti(:, 1)*cddbd(nd, :, 0)+cddb(:, 0)*&
&       dnbtid(nd, :, 1))
    END DO
    fnbpschd0 = 0.D0
    DO nd0=1,nbdirs0
      fnbpschd0(nd0, :, 0) = temp*(dnbti(:, 1)*cddbd0(nd0, :, 0)+cddb(:&
&       , 0)*dnbtid0(nd0, :, 1))
    END DO
    fnbpsch(:, 0) = temp*(cddb(:, 0)*dnbti(:, 1))
    temp = switch%fnbpsch*facdrift*geo%fcqalf(:, 1)
    DO nd=1,nbdirs
      DO nd0=nd,nbdirs0
        fnbpschdd(nd0, nd, :, 1) = -(temp*(cddbd(nd, :, 1)*dnbtid0(nd0, &
&         :, 0)+dnbti(:, 0)*cddbdd(nd0, nd, :, 1)+dnbtid(nd, :, 0)*&
&         cddbd0(nd0, :, 1)+cddb(:, 1)*dnbtidd(nd0, nd, :, 0)))
      END DO
      fnbpschd(nd, :, 1) = -(temp*(dnbti(:, 0)*cddbd(nd, :, 1)+cddb(:, 1&
&       )*dnbtid(nd, :, 0)))
    END DO
    cddb_effd0 = 0.D0
    DO nd0=1,nbdirs0
      fnbpschd0(nd0, :, 1) = -(temp*(dnbti(:, 0)*cddbd0(nd0, :, 1)+cddb(&
&       :, 1)*dnbtid0(nd0, :, 0)))
      cddb_effd0(nd0, :, 0) = -(switch%fnbpsch*facdrift*geo%fcqalf(:, 1)&
&       *cddbd0(nd0, :, 1))
      cddb_effd0(nd0, :, 1) = switch%fnbpsch*facdrift*geo%fcqalf(:, 0)*&
&       cddbd0(nd0, :, 0)
    END DO
    fnbpsch(:, 1) = -(temp*(cddb(:, 1)*dnbti(:, 0)))
    cddb_eff(:, 0) = -(switch%fnbpsch*facdrift*cddb(:, 1)*geo%fcqalf(:, &
&     1))
    cddb_eff(:, 1) = switch%fnbpsch*facdrift*cddb(:, 0)*geo%fcqalf(:, 0)
    conb0d = 0.d0
    flob0d = 0.d0
    dumm0d = 0.d0
    conb0d0 = 0.D0
    conb0dd = 0.D0
    flob0dd = 0.D0
    flob0d0 = 0.D0
    dumm0dd = 0.D0
    dumm0d0 = 0.D0
    CALL CALCCOEF_DV_DV(ncv, nfc, nvx, 0, geo, dumm0, dumm0d0, dumm0d, &
&                 dumm0dd, cddb_eff, cddb_effd0, cddb_effd, cddb_effdd, &
&                 flob0, flob0d0, flob0d, flob0dd, conb0, conb0d0, &
&                 conb0d, conb0dd, nbdirs, nbdirs0)
    flobd = 0.d0
    conbd = 0.d0
    flobd0 = 0.D0
    conbdd = 0.D0
    flobdd = 0.D0
    conbd0 = 0.D0
    DO ifc=1,nfc
      DO nd0=1,nbdirs0
        temp0d(nd0) = kmprtid0(nd0, mpg%fccv(ifc, 2)) - kmprtid0(nd0, &
&         mpg%fccv(ifc, 1))
      END DO
      temp0 = kmprti(mpg%fccv(ifc, 2)) - kmprti(mpg%fccv(ifc, 1))
      DO nd=1,nbdirs
        temp1 = kmprtid(nd, mpg%fccv(ifc, 2)) - kmprtid(nd, mpg%fccv(ifc&
&         , 1))
        DO nd0=1,nbdirs0
          flobdd(nd0, nd, ifc, 0) = flob0(ifc, 0)*0.5_R8*(kmprtidd(nd0, &
&           nd, mpg%fccv(ifc, 1))+kmprtidd(nd0, nd, mpg%fccv(ifc, 2))) -&
&           conb0d(nd, ifc, 0)*temp0d(nd0) - temp0*conb0dd(nd0, nd, ifc&
&           , 0) - temp1*conb0d0(nd0, ifc, 0) - conb0(ifc, 0)*(kmprtidd(&
&           nd0, nd, mpg%fccv(ifc, 2))-kmprtidd(nd0, nd, mpg%fccv(ifc, 1&
&           )))
        END DO
        flobd(nd, ifc, 0) = flob0(ifc, 0)*0.5_R8*(kmprtid(nd, mpg%fccv(&
&         ifc, 1))+kmprtid(nd, mpg%fccv(ifc, 2))) - temp0*conb0d(nd, ifc&
&         , 0) - conb0(ifc, 0)*temp1
      END DO
      DO nd0=1,nbdirs0
        flobd0(nd0, ifc, 0) = flob0(ifc, 0)*0.5_R8*(kmprtid0(nd0, mpg%&
&         fccv(ifc, 1))+kmprtid0(nd0, mpg%fccv(ifc, 2))) - temp0*conb0d0&
&         (nd0, ifc, 0) - conb0(ifc, 0)*temp0d(nd0)
        temp0d(nd0) = kmprtivd0(nd0, mpg%fcvx(ifc, 2)) - kmprtivd0(nd0, &
&         mpg%fcvx(ifc, 1))
      END DO
      flob(ifc, 0) = flob0(ifc, 0)*0.5_R8*(kmprti(mpg%fccv(ifc, 1))+&
&       kmprti(mpg%fccv(ifc, 2))) - conb0(ifc, 0)*temp0
      temp0 = kmprtiv(mpg%fcvx(ifc, 2)) - kmprtiv(mpg%fcvx(ifc, 1))
      DO nd=1,nbdirs
        temp1 = kmprtivd(nd, mpg%fcvx(ifc, 2)) - kmprtivd(nd, mpg%fcvx(&
&         ifc, 1))
        DO nd0=1,nbdirs0
          flobdd(nd0, nd, ifc, 1) = flob0(ifc, 1)*0.5_R8*(kmprtivdd(nd0&
&           , nd, mpg%fcvx(ifc, 1))+kmprtivdd(nd0, nd, mpg%fcvx(ifc, 2))&
&           ) - conb0d(nd, ifc, 1)*temp0d(nd0) - temp0*conb0dd(nd0, nd, &
&           ifc, 1) - temp1*conb0d0(nd0, ifc, 1) - conb0(ifc, 1)*(&
&           kmprtivdd(nd0, nd, mpg%fcvx(ifc, 2))-kmprtivdd(nd0, nd, mpg%&
&           fcvx(ifc, 1)))
        END DO
        flobd(nd, ifc, 1) = flob0(ifc, 1)*0.5_R8*(kmprtivd(nd, mpg%fcvx(&
&         ifc, 1))+kmprtivd(nd, mpg%fcvx(ifc, 2))) - temp0*conb0d(nd, &
&         ifc, 1) - conb0(ifc, 1)*temp1
      END DO
      DO nd0=1,nbdirs0
        flobd0(nd0, ifc, 1) = flob0(ifc, 1)*0.5_R8*(kmprtivd0(nd0, mpg%&
&         fcvx(ifc, 1))+kmprtivd0(nd0, mpg%fcvx(ifc, 2))) - temp0*&
&         conb0d0(nd0, ifc, 1) - conb0(ifc, 1)*temp0d(nd0)
!wdk      For now, directly add these contributions into conb(,,0),
!wdk      so they are directly added into the stencil.
!wdk      Might need to move back to conb(,,3) and dedicated treatment
!wdk      in b2ux9p if we decide to move away from inverse volume weighting
!wdk      to compute vertex values of drifts!
        temp0d(nd0) = kmprtid0(nd0, mpg%fccv(ifc, 1)) + kmprtid0(nd0, &
&         mpg%fccv(ifc, 2))
      END DO
      flob(ifc, 1) = flob0(ifc, 1)*0.5_R8*(kmprtiv(mpg%fcvx(ifc, 1))+&
&       kmprtiv(mpg%fcvx(ifc, 2))) - conb0(ifc, 1)*temp0
      temp0 = kmprti(mpg%fccv(ifc, 1)) + kmprti(mpg%fccv(ifc, 2))
      DO nd=1,nbdirs
        temp1 = kmprtid(nd, mpg%fccv(ifc, 1)) + kmprtid(nd, mpg%fccv(ifc&
&         , 2))
        DO nd0=1,nbdirs0
          conbdd(nd0, nd, ifc, 0, 0) = 0.5_R8*(conb0d(nd, ifc, 0)*temp0d&
&           (nd0)+temp0*conb0dd(nd0, nd, ifc, 0)+temp1*conb0d0(nd0, ifc&
&           , 0)+conb0(ifc, 0)*(kmprtidd(nd0, nd, mpg%fccv(ifc, 1))+&
&           kmprtidd(nd0, nd, mpg%fccv(ifc, 2)))) - flob0(ifc, 0)*&
&           0.25_R8*(kmprtidd(nd0, nd, mpg%fccv(ifc, 2))-kmprtidd(nd0, &
&           nd, mpg%fccv(ifc, 1)))
        END DO
        conbd(nd, ifc, 0, 0) = 0.5_R8*(temp0*conb0d(nd, ifc, 0)+conb0(&
&         ifc, 0)*temp1) - flob0(ifc, 0)*0.25_R8*(kmprtid(nd, mpg%fccv(&
&         ifc, 2))-kmprtid(nd, mpg%fccv(ifc, 1)))
      END DO
      DO nd0=1,nbdirs0
        conbd0(nd0, ifc, 0, 0) = 0.5_R8*(temp0*conb0d0(nd0, ifc, 0)+&
&         conb0(ifc, 0)*temp0d(nd0)) - flob0(ifc, 0)*0.25_R8*(kmprtid0(&
&         nd0, mpg%fccv(ifc, 2))-kmprtid0(nd0, mpg%fccv(ifc, 1)))
        temp0d(nd0) = kmprtivd0(nd0, mpg%fcvx(ifc, 1)) + kmprtivd0(nd0, &
&         mpg%fcvx(ifc, 2))
      END DO
      conb(ifc, 0, 0) = 0.5_R8*(conb0(ifc, 0)*temp0) - flob0(ifc, 0)*&
&       0.25_R8*(kmprti(mpg%fccv(ifc, 2))-kmprti(mpg%fccv(ifc, 1)))
      temp0 = kmprtiv(mpg%fcvx(ifc, 1)) + kmprtiv(mpg%fcvx(ifc, 2))
      DO nd=1,nbdirs
        temp1 = kmprtivd(nd, mpg%fcvx(ifc, 1)) + kmprtivd(nd, mpg%fcvx(&
&         ifc, 2))
        DO nd0=1,nbdirs0
          conbdd(nd0, nd, ifc, 1, 0) = 0.5_R8*(conb0d(nd, ifc, 1)*temp0d&
&           (nd0)+temp0*conb0dd(nd0, nd, ifc, 1)+temp1*conb0d0(nd0, ifc&
&           , 1)+conb0(ifc, 1)*(kmprtivdd(nd0, nd, mpg%fcvx(ifc, 1))+&
&           kmprtivdd(nd0, nd, mpg%fcvx(ifc, 2)))) - flob0(ifc, 1)*&
&           0.25_R8*(kmprtivdd(nd0, nd, mpg%fcvx(ifc, 2))-kmprtivdd(nd0&
&           , nd, mpg%fcvx(ifc, 1)))
        END DO
        conbd(nd, ifc, 1, 0) = 0.5_R8*(temp0*conb0d(nd, ifc, 1)+conb0(&
&         ifc, 1)*temp1) - flob0(ifc, 1)*0.25_R8*(kmprtivd(nd, mpg%fcvx(&
&         ifc, 2))-kmprtivd(nd, mpg%fcvx(ifc, 1)))
      END DO
      DO nd0=1,nbdirs0
        conbd0(nd0, ifc, 1, 0) = 0.5_R8*(temp0*conb0d0(nd0, ifc, 1)+&
&         conb0(ifc, 1)*temp0d(nd0)) - flob0(ifc, 1)*0.25_R8*(kmprtivd0(&
&         nd0, mpg%fcvx(ifc, 2))-kmprtivd0(nd0, mpg%fcvx(ifc, 1)))
      END DO
      conb(ifc, 1, 0) = 0.5_R8*(conb0(ifc, 1)*temp0) - flob0(ifc, 1)*&
&       0.25_R8*(kmprtiv(mpg%fcvx(ifc, 2))-kmprtiv(mpg%fcvx(ifc, 1)))
    END DO
  ELSE
    flobd = 0.d0
    conbd = 0.d0
    fnbpschd = 0.d0
    flobd0 = 0.D0
    fnbpschdd = 0.D0
    conbdd = 0.D0
    flobdd = 0.D0
    conbd0 = 0.D0
    fnbpschd0 = 0.D0
  END IF
!
! ..return
  ncall = ncall + 1
  CALL SUBEND()
  RETURN
!-----------------------------------------------------------------------
!.end b2tnpsch
END SUBROUTINE B2TNPSCH_DV_DV

!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 23 Jul 2024 17:41
!
!  Differentiation of b2tnpsch in forward (tangent) mode (with options multiDirectional context noISIZE r8):
!   variations   of useful results: flob conb fnbpsch
!   with respect to varying inputs: ti cddb nb kmprti
!   Plus diff mem management of: geo.fchc:in geo.fcht:in geo.fcqalf:in
!                geo.fcqbet:in geo.vxvol:in
!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE B2TNPSCH_DV_NODIFF(ncv, nfc, nvx, switch, geo, geod, mpg, &
& mpgd, facdrift, cddb, cddbd, ti, tid, nb, nbd, kmprti, kmprtid, flob, &
& flobd, conb, conbd, fnbpsch, fnbpschd, nbdirs)
  USE B2MOD_TYPES
  USE B2MOD_B2CMPA_DIFFV
  USE B2MOD_SWITCHES_DIFFV_DIFFV
  USE B2US_GEO_DIFFV_DIFFV
  USE B2US_MAP_DIFFV_DIFFV
  USE B2MOD_SUBSYS
!  Hint: nbdirsmax should be the maximum number of differentiation directions
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!   ..input arguments (unchanged on exit)
  INTEGER :: ncv, nfc, nvx
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(GEOMETRY_DIFFV), INTENT(IN) :: geod
  TYPE(MAPPING), INTENT(IN) :: mpg
  TYPE(MAPPING_DIFFV), INTENT(IN) :: mpgd
  REAL(kind=r8) :: facdrift(nfc), cddb(nfc, 0:1), ti(ncv), nb(ncv), &
& kmprti(ncv)
  REAL(kind=r8) :: cddbd(nbdirsmax, nfc, 0:1), tid(nbdirsmax, ncv), nbd(&
& nbdirsmax, ncv), kmprtid(nbdirsmax, ncv)
!   ..output arguments (unspecified on entry)
  REAL(kind=r8) :: flob(nfc, 0:1), conb(nfc, 0:1, 0:2), fnbpsch(nfc, 0:1&
& )
  REAL(kind=r8) :: flobd(nbdirsmax, nfc, 0:1), conbd(nbdirsmax, nfc, 0:1&
& , 0:2), fnbpschd(nbdirsmax, nfc, 0:1)
!-----------------------------------------------------------------------
!.documentation
!
!  1. purpose
!
!     B2TNPSCH computes the poloidal and radial components of the
!     Pfirsch-Schlueter particle flux of one atomic species, and the
!     coefficients that specify its linearization.
!
!  8. further comments
!
!-----------------------------------------------------------------------
!.declarations
!
!   ..local variables
  INTEGER :: ifc
  INTEGER, SAVE :: ncall=0
  REAL(kind=r8) :: facdriftm, nbti(ncv), nbtiv(nvx), kmprtiv(nvx), dnbti&
& (nfc, 0:1), flob0(nfc, 0:1), conb0(nfc, 0:1), cddb_eff(nfc, 0:1), &
& dumm0(nfc, 0:1)
  REAL(kind=r8) :: nbtid(nbdirsmax, ncv), nbtivd(nbdirsmax, nvx), &
& kmprtivd(nbdirsmax, nvx), dnbtid(nbdirsmax, nfc, 0:1), flob0d(&
& nbdirsmax, nfc, 0:1), conb0d(nbdirsmax, nfc, 0:1), cddb_effd(nbdirsmax&
& , nfc, 0:1), dumm0d(nbdirsmax, nfc, 0:1)
  INTRINSIC MAXVAL
  INTEGER :: nd
  REAL(kind=r8), DIMENSION(nfc) :: temp
  REAL(kind=r8) :: temp0
  INTEGER :: nbdirs
!-----------------------------------------------------------------------
!.computation
!
! ..preliminaries
!   ..subprogram start-up calls
  CALL SUBINI('b2tnpsch')
!   ..test nCv, nFc
  CALL XERTST(0 .LE. ncv .AND. 0 .LE. nfc, 'faulty argument nCv, nFc')
!
!   ..set dummy arrays
  dumm0 = 0.0_R8
!
!srv 13.10.06
  fnbpsch = 0.0e0_R8
!srv 02.01.07
  DO nd=1,nbdirs
    conbd(nd, :, :, :) = 0.d0
  END DO
  conb = 0.0e0_R8
  flob = 0.0e0_R8
  facdriftm = MAXVAL(facdrift)
  IF (facdriftm .NE. 0.0e0_R8) THEN
!
!     ..linearization coefficients for P.Sch flows
    cddb_effd = 0.d0
    DO nd=1,nbdirs
!
!     ..precompute face and vertex values of nbti and kmprti
      nbtid(nd, :) = ti*nbd(nd, :) + nb*tid(nd, :)
      cddb_effd(nd, :, 0) = -(switch%fnbpsch*facdrift*geo%fcqalf(:, 1)*&
&       cddbd(nd, :, 1))
      cddb_effd(nd, :, 1) = switch%fnbpsch*facdrift*geo%fcqalf(:, 0)*&
&       cddbd(nd, :, 0)
    END DO
    nbti = nb*ti
    nbtivd = 0.d0
    CALL INTVERTEX_DV_NODIFF(ncv, nvx, mpg, geo%vxvol, nbti, nbtid, &
&                      nbtiv, nbtivd, nbdirs)
    kmprtivd = 0.d0
    CALL INTVERTEX_DV_NODIFF(ncv, nvx, mpg, geo%vxvol, kmprti, kmprtid, &
&                      kmprtiv, kmprtivd, nbdirs)
    dnbtid = 0.d0
    CALL DIFF_DV_NODIFF(ncv, nfc, nvx, 1, geo, geod, mpg, mpgd, nbti, &
&                 nbtid, nbtiv, nbtivd, dnbti, dnbtid, nbdirs)
!
!     ..compute P.Sch heat flux
    fnbpschd = 0.d0
    temp = switch%fnbpsch*facdrift*geo%fcqalf(:, 0)
    DO nd=1,nbdirs
      fnbpschd(nd, :, 0) = temp*(dnbti(:, 1)*cddbd(nd, :, 0)+cddb(:, 0)*&
&       dnbtid(nd, :, 1))
    END DO
    fnbpsch(:, 0) = temp*(cddb(:, 0)*dnbti(:, 1))
    temp = switch%fnbpsch*facdrift*geo%fcqalf(:, 1)
    DO nd=1,nbdirs
      fnbpschd(nd, :, 1) = -(temp*(dnbti(:, 0)*cddbd(nd, :, 1)+cddb(:, 1&
&       )*dnbtid(nd, :, 0)))
    END DO
    fnbpsch(:, 1) = -(temp*(cddb(:, 1)*dnbti(:, 0)))
    cddb_eff(:, 0) = -(switch%fnbpsch*facdrift*cddb(:, 1)*geo%fcqalf(:, &
&     1))
    cddb_eff(:, 1) = switch%fnbpsch*facdrift*cddb(:, 0)*geo%fcqalf(:, 0)
    conb0d = 0.d0
    flob0d = 0.d0
    dumm0d = 0.d0
    CALL CALCCOEF_DV_NODIFF(ncv, nfc, nvx, 0, geo, dumm0, dumm0d, &
&                     cddb_eff, cddb_effd, flob0, flob0d, conb0, conb0d&
&                     , nbdirs)
    flobd = 0.d0
    conbd = 0.d0
    DO ifc=1,nfc
      temp0 = kmprti(mpg%fccv(ifc, 2)) - kmprti(mpg%fccv(ifc, 1))
      DO nd=1,nbdirs
        flobd(nd, ifc, 0) = flob0(ifc, 0)*0.5_R8*(kmprtid(nd, mpg%fccv(&
&         ifc, 1))+kmprtid(nd, mpg%fccv(ifc, 2))) - temp0*conb0d(nd, ifc&
&         , 0) - conb0(ifc, 0)*(kmprtid(nd, mpg%fccv(ifc, 2))-kmprtid(nd&
&         , mpg%fccv(ifc, 1)))
      END DO
      flob(ifc, 0) = flob0(ifc, 0)*0.5_R8*(kmprti(mpg%fccv(ifc, 1))+&
&       kmprti(mpg%fccv(ifc, 2))) - conb0(ifc, 0)*temp0
      temp0 = kmprtiv(mpg%fcvx(ifc, 2)) - kmprtiv(mpg%fcvx(ifc, 1))
      DO nd=1,nbdirs
        flobd(nd, ifc, 1) = flob0(ifc, 1)*0.5_R8*(kmprtivd(nd, mpg%fcvx(&
&         ifc, 1))+kmprtivd(nd, mpg%fcvx(ifc, 2))) - temp0*conb0d(nd, &
&         ifc, 1) - conb0(ifc, 1)*(kmprtivd(nd, mpg%fcvx(ifc, 2))-&
&         kmprtivd(nd, mpg%fcvx(ifc, 1)))
      END DO
      flob(ifc, 1) = flob0(ifc, 1)*0.5_R8*(kmprtiv(mpg%fcvx(ifc, 1))+&
&       kmprtiv(mpg%fcvx(ifc, 2))) - conb0(ifc, 1)*temp0
!wdk      For now, directly add these contributions into conb(,,0),
!wdk      so they are directly added into the stencil.
!wdk      Might need to move back to conb(,,3) and dedicated treatment
!wdk      in b2ux9p if we decide to move away from inverse volume weighting
!wdk      to compute vertex values of drifts!
      temp0 = kmprti(mpg%fccv(ifc, 1)) + kmprti(mpg%fccv(ifc, 2))
      DO nd=1,nbdirs
        conbd(nd, ifc, 0, 0) = 0.5_R8*(temp0*conb0d(nd, ifc, 0)+conb0(&
&         ifc, 0)*(kmprtid(nd, mpg%fccv(ifc, 1))+kmprtid(nd, mpg%fccv(&
&         ifc, 2)))) - flob0(ifc, 0)*0.25_R8*(kmprtid(nd, mpg%fccv(ifc, &
&         2))-kmprtid(nd, mpg%fccv(ifc, 1)))
      END DO
      conb(ifc, 0, 0) = 0.5_R8*(conb0(ifc, 0)*temp0) - flob0(ifc, 0)*&
&       0.25_R8*(kmprti(mpg%fccv(ifc, 2))-kmprti(mpg%fccv(ifc, 1)))
      temp0 = kmprtiv(mpg%fcvx(ifc, 1)) + kmprtiv(mpg%fcvx(ifc, 2))
      DO nd=1,nbdirs
        conbd(nd, ifc, 1, 0) = 0.5_R8*(temp0*conb0d(nd, ifc, 1)+conb0(&
&         ifc, 1)*(kmprtivd(nd, mpg%fcvx(ifc, 1))+kmprtivd(nd, mpg%fcvx(&
&         ifc, 2)))) - flob0(ifc, 1)*0.25_R8*(kmprtivd(nd, mpg%fcvx(ifc&
&         , 2))-kmprtivd(nd, mpg%fcvx(ifc, 1)))
      END DO
      conb(ifc, 1, 0) = 0.5_R8*(conb0(ifc, 1)*temp0) - flob0(ifc, 1)*&
&       0.25_R8*(kmprtiv(mpg%fcvx(ifc, 2))-kmprtiv(mpg%fcvx(ifc, 1)))
    END DO
  ELSE
    flobd = 0.d0
    conbd = 0.d0
    fnbpschd = 0.d0
  END IF
!
! ..return
  ncall = ncall + 1
  CALL SUBEND()
  RETURN
!-----------------------------------------------------------------------
!.end b2tnpsch
END SUBROUTINE B2TNPSCH_DV_NODIFF

!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE B2TNPSCH_NODIFF_NODIFF(ncv, nfc, nvx, switch, geo, mpg, &
& facdrift, cddb, ti, nb, kmprti, flob, conb, fnbpsch)
  USE B2MOD_TYPES
  USE B2MOD_B2CMPA_DIFFV
  USE B2MOD_SWITCHES_DIFFV_DIFFV
  USE B2US_GEO_DIFFV_DIFFV
  USE B2US_MAP_DIFFV_DIFFV
  USE B2MOD_SUBSYS
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!   ..input arguments (unchanged on exit)
  INTEGER :: ncv, nfc, nvx
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(MAPPING), INTENT(IN) :: mpg
  REAL(kind=r8) :: facdrift(nfc), cddb(nfc, 0:1), ti(ncv), nb(ncv), &
& kmprti(ncv)
!   ..output arguments (unspecified on entry)
  REAL(kind=r8) :: flob(nfc, 0:1), conb(nfc, 0:1, 0:2), fnbpsch(nfc, 0:1&
& )
!-----------------------------------------------------------------------
!.documentation
!
!  1. purpose
!
!     B2TNPSCH computes the poloidal and radial components of the
!     Pfirsch-Schlueter particle flux of one atomic species, and the
!     coefficients that specify its linearization.
!
!  8. further comments
!
!-----------------------------------------------------------------------
!.declarations
!
!   ..local variables
  INTEGER :: ifc
  INTEGER, SAVE :: ncall=0
  REAL(kind=r8) :: facdriftm, nbti(ncv), nbtiv(nvx), kmprtiv(nvx), dnbti&
& (nfc, 0:1), flob0(nfc, 0:1), conb0(nfc, 0:1), cddb_eff(nfc, 0:1), &
& dumm0(nfc, 0:1)
  INTRINSIC MAXVAL
!-----------------------------------------------------------------------
!.computation
!
! ..preliminaries
!   ..subprogram start-up calls
  CALL SUBINI('b2tnpsch')
!   ..test nCv, nFc
  CALL XERTST(0 .LE. ncv .AND. 0 .LE. nfc, 'faulty argument nCv, nFc')
!
!   ..set dummy arrays
  dumm0 = 0.0_R8
!
!srv 13.10.06
  fnbpsch = 0.0e0_R8
!srv 02.01.07
  conb = 0.0e0_R8
  flob = 0.0e0_R8
  facdriftm = MAXVAL(facdrift)
  IF (facdriftm .NE. 0.0e0_R8) THEN
!
!     ..precompute face and vertex values of nbti and kmprti
    nbti = nb*ti
    CALL INTVERTEX_NODIFF_NODIFF(ncv, nvx, mpg, geo%vxvol, nbti, nbtiv)
    CALL INTVERTEX_NODIFF_NODIFF(ncv, nvx, mpg, geo%vxvol, kmprti, &
&                          kmprtiv)
    CALL DIFF_NODIFF_NODIFF(ncv, nfc, nvx, 1, geo, mpg, nbti, nbtiv, &
&                     dnbti)
!
!     ..compute P.Sch heat flux
    fnbpsch(:, 0) = switch%fnbpsch*facdrift*cddb(:, 0)*geo%fcqalf(:, 0)*&
&     dnbti(:, 1)
    fnbpsch(:, 1) = -(switch%fnbpsch*facdrift*cddb(:, 1)*geo%fcqalf(:, 1&
&     )*dnbti(:, 0))
!
!     ..linearization coefficients for P.Sch flows
    cddb_eff(:, 0) = -(switch%fnbpsch*facdrift*cddb(:, 1)*geo%fcqalf(:, &
&     1))
    cddb_eff(:, 1) = switch%fnbpsch*facdrift*cddb(:, 0)*geo%fcqalf(:, 0)
    CALL CALCCOEF_NODIFF_NODIFF(ncv, nfc, nvx, 0, geo, dumm0, cddb_eff, &
&                         flob0, conb0)
    DO ifc=1,nfc
      flob(ifc, 0) = 0.5_R8*flob0(ifc, 0)*(kmprti(mpg%fccv(ifc, 1))+&
&       kmprti(mpg%fccv(ifc, 2))) - conb0(ifc, 0)*(kmprti(mpg%fccv(ifc, &
&       2))-kmprti(mpg%fccv(ifc, 1)))
      flob(ifc, 1) = 0.5_R8*flob0(ifc, 1)*(kmprtiv(mpg%fcvx(ifc, 1))+&
&       kmprtiv(mpg%fcvx(ifc, 2))) - conb0(ifc, 1)*(kmprtiv(mpg%fcvx(ifc&
&       , 2))-kmprtiv(mpg%fcvx(ifc, 1)))
!wdk      For now, directly add these contributions into conb(,,0),
!wdk      so they are directly added into the stencil.
!wdk      Might need to move back to conb(,,3) and dedicated treatment
!wdk      in b2ux9p if we decide to move away from inverse volume weighting
!wdk      to compute vertex values of drifts!
      conb(ifc, 0, 0) = 0.5_R8*conb0(ifc, 0)*(kmprti(mpg%fccv(ifc, 1))+&
&       kmprti(mpg%fccv(ifc, 2))) - 0.25_R8*flob0(ifc, 0)*(kmprti(mpg%&
&       fccv(ifc, 2))-kmprti(mpg%fccv(ifc, 1)))
      conb(ifc, 1, 0) = 0.5_R8*conb0(ifc, 1)*(kmprtiv(mpg%fcvx(ifc, 1))+&
&       kmprtiv(mpg%fcvx(ifc, 2))) - 0.25_R8*flob0(ifc, 1)*(kmprtiv(mpg%&
&       fcvx(ifc, 2))-kmprtiv(mpg%fcvx(ifc, 1)))
    END DO
  END IF
!
! ..return
  ncall = ncall + 1
  CALL SUBEND()
  RETURN
!-----------------------------------------------------------------------
!.end b2tnpsch
END SUBROUTINE B2TNPSCH_NODIFF_NODIFF

