!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 23 Jul 2024 17:41
!
!  Differentiation of b2trfl_dv in forward (tangent) mode (with options multiDirectional context noISIZE r8):
!   variations   of useful results: cf_limb cf_limd cf_limhd cf_limh
!                cf_limbd cf_limbh cf_limbhd cf_lim
!   with respect to varying inputs: *nal *gtalc *nald *gtalcd zeffned
!                cf_limb cf_limd cf_limhd cf_limh cf_limbd cf_limbh
!                cf_limbhd zetap ainvd ainv zeffne amti amtid cf_lim
!                zetapd
!   Plus diff mem management of: nal:in gtalc:in nald:in gtalcd:in
!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 23 Jul 2024 17:41
!
!  Differentiation of b2trfl in forward (tangent) mode (with options multiDirectional context noISIZE r8):
!   variations   of useful results: cf_limb cf_limh cf_limbh cf_lim
!   with respect to varying inputs: *nal *gtalc cf_limb cf_limh
!                cf_limbh zetap ainv zeffne amti cf_lim
!   Plus diff mem management of: nal:in gtalc:in
!
!
!
!
!
!
!
!
!
!
!
!.specification
!
SUBROUTINE B2TRFL_DV_DV(icv, switch, mpg, ainv, ainvd0, ainvd, ainvdd, &
& zeffne, zeffned0, zeffned, zeffnedd, amti, amtid0, amtid, amtidd, &
& zetap, zetapd0, zetapd, zetapdd, gamma, cf_lim, cf_limd0, cf_limd, &
& cf_limdd, cf_limh, cf_limhd0, cf_limhd, cf_limhdd, cf_limb, cf_limbd0&
& , cf_limbd, cf_limbdd, cf_limbh, cf_limbhd0, cf_limbhd, cf_limbhdd, &
& nbdirs, nbdirs0)
  USE B2MOD_TYPES
  USE B2MOD_B2CMPA_DIFFV
  USE B2MOD_B2CMPT_DIFFV_DIFFV
  USE B2MOD_CONSTANTS
  USE B2US_MAP_DIFFV_DIFFV
  USE B2MOD_SWITCHES_DIFFV_DIFFV
  USE B2MOD_ZHFRTF_DIFFV_DIFFV, ONLY : gtalc, gtalcd0, gtalcd, gtalcdd, &
& nal, nald0, nald, naldd
  USE B2MOD_SUBSYS
!  Hint: nbdirsmax should be the maximum number of differentiation directions
  USE B2MOD_DIFFSIZES
!  Hint: nbdirsmax0 should be the maximum number of differentiation directions
  IMPLICIT NONE
!   ..input arguments (unchanged on exit)
  INTEGER :: icv
!som 20.03.21
  REAL(kind=r8) :: gamma
  REAL(kind=r8) :: zeffne, zetap, amti(0:nspecies-1), ainv(0:2*nspecies-&
& 1, 0:2*nspecies-1)
  REAL(kind=r8) :: zeffned0(nbdirsmax0), zetapd0(nbdirsmax0), amtid0(&
& nbdirsmax0, 0:nspecies-1), ainvd0(nbdirsmax0, 0:2*nspecies-1, 0:2*&
& nspecies-1)
  REAL(kind=r8) :: zeffned(nbdirsmax), zetapd(nbdirsmax), amtid(&
& nbdirsmax, 0:nspecies-1), ainvd(nbdirsmax, 0:2*nspecies-1, 0:2*&
& nspecies-1)
  REAL(kind=r8) :: zeffnedd(nbdirsmax0, nbdirsmax), zetapdd(nbdirsmax0, &
& nbdirsmax), amtidd(nbdirsmax0, nbdirsmax, 0:nspecies-1), ainvdd(&
& nbdirsmax0, nbdirsmax, 0:2*nspecies-1, 0:2*nspecies-1)
  TYPE(MAPPING), INTENT(IN) :: mpg
  TYPE(SWITCHES), INTENT(IN) :: switch
!   ..output arguments (unspecified on entry)
  REAL(kind=r8) :: cf_lim(0:nspecies-1), cf_limh(0:nspecies-1), cf_limb(&
& 0:nspecies-1), cf_limbh(0:nspecies-1)
  REAL(kind=r8) :: cf_limd0(nbdirsmax0, 0:nspecies-1), cf_limhd0(&
& nbdirsmax0, 0:nspecies-1), cf_limbd0(nbdirsmax0, 0:nspecies-1), &
& cf_limbhd0(nbdirsmax0, 0:nspecies-1)
  REAL(kind=r8) :: cf_limd(nbdirsmax, 0:nspecies-1), cf_limhd(nbdirsmax&
& , 0:nspecies-1), cf_limbd(nbdirsmax, 0:nspecies-1), cf_limbhd(&
& nbdirsmax, 0:nspecies-1)
  REAL(kind=r8) :: cf_limdd(nbdirsmax0, nbdirsmax, 0:nspecies-1), &
& cf_limhdd(nbdirsmax0, nbdirsmax, 0:nspecies-1), cf_limbdd(nbdirsmax0, &
& nbdirsmax, 0:nspecies-1), cf_limbhdd(nbdirsmax0, nbdirsmax, 0:nspecies&
& -1)
!-----------------------------------------------------------------------
!.documentation
!
!  1. purpose
!
!     B2TRFL computes the flux-limiting coefficients.
!
!  3. description
!
!     This routine computes:
!     - cF_lim: the flux-limiting coefficient for the thermal force coefficient
!     - cF_limh: the flux-limiting coefficient for the heat flux
!     - cF_limB: the flux-limiting coefficient for the charge state correction
!     - cF_limBh: the flux-limiting coefficient for the charge state correction for the heat flux
!-----------------------------------------------------------------------
!.declarations
!   ..local variables
  INTEGER :: i
  REAL(kind=r8) :: coef, t0, t1, t2
  REAL(kind=r8), DIMENSION(nbdirsmax0) :: coefd0, t0d0, t1d0, t2d0
  REAL(kind=r8), DIMENSION(nbdirsmax) :: coefd, t0d, t1d, t2d
  REAL(kind=r8), DIMENSION(nbdirsmax0, nbdirsmax) :: coefdd, t0dd, t1dd&
& , t2dd
  INTRINSIC SUM
  INTRINSIC ABS
  INTRINSIC SQRT
  INTRINSIC TANH
  REAL(kind=r8) :: x1
  REAL(kind=r8), DIMENSION(nbdirsmax0) :: x1d0
  REAL(kind=r8), DIMENSION(nbdirsmax) :: x1d
  REAL(kind=r8), DIMENSION(nbdirsmax0, nbdirsmax) :: x1dd
  REAL(kind=r8), DIMENSION(nspecies) :: arg1
  REAL(kind=r8), DIMENSION(nbdirsmax0, nspecies) :: arg1d0
  REAL(kind=r8), DIMENSION(nbdirsmax, nspecies) :: arg1d
  REAL(kind=r8), DIMENSION(nbdirsmax0, nbdirsmax, nspecies) :: arg1dd
  REAL(kind=r8) :: result1
  REAL(kind=r8), DIMENSION(nbdirsmax0) :: result1d0
  REAL(kind=r8), DIMENSION(nbdirsmax) :: result1d
  REAL(kind=r8), DIMENSION(nbdirsmax0, nbdirsmax) :: result1dd
  REAL(r8) :: arg10
  REAL(r8), DIMENSION(nbdirsmax0) :: arg10d0
  REAL(r8), DIMENSION(nbdirsmax) :: arg10d
  REAL(r8), DIMENSION(nbdirsmax0, nbdirsmax) :: arg10dd
  INTEGER :: nd
  REAL(kind=r8) :: temp
  REAL(kind=r8), DIMENSION(nbdirsmax0) :: tempd3
  REAL(kind=r8), DIMENSION(nspecies) :: temp0
  REAL(kind=r8), DIMENSION(nbdirsmax0, nspecies) :: temp0d
  REAL(kind=r8) :: temp1
  REAL(kind=r8), DIMENSION(nbdirsmax0) :: temp1d
  REAL(kind=r8) :: temp2
  REAL(kind=r8), DIMENSION(nbdirsmax0) :: temp2d
  REAL(kind=r8) :: temp3
  REAL(kind=r8), DIMENSION(nbdirsmax0) :: temp3d
  REAL(kind=r8) :: temp4
  REAL(kind=r8), DIMENSION(nbdirsmax0) :: temp4d
  REAL(kind=r8), DIMENSION(nbdirsmax) :: tempd
  REAL(kind=r8), DIMENSION(nbdirsmax0, nbdirsmax) :: tempdd
  REAL(kind=r8) :: temp5
  REAL(kind=r8), DIMENSION(nbdirsmax0) :: temp5d
  REAL(kind=r8), DIMENSION(nbdirsmax) :: tempd0
  REAL(kind=r8), DIMENSION(nbdirsmax0, nbdirsmax) :: tempd0d
  REAL(kind=r8), DIMENSION(nbdirsmax) :: tempd1
  REAL(kind=r8), DIMENSION(nbdirsmax0, nbdirsmax) :: tempd1d
  REAL(kind=r8), DIMENSION(nbdirsmax) :: tempd2
  REAL(kind=r8), DIMENSION(nbdirsmax0, nbdirsmax) :: tempd2d
  INTEGER :: nbdirs
  INTRINSIC INT
  INTEGER :: nd0
  REAL(kind=r8) :: temp6
  REAL(kind=r8) :: temp7
  REAL(kind=r8), DIMENSION(nspecies) :: temp8
  REAL(kind=r8), DIMENSION(nbdirsmax0) :: tempd4
  REAL(kind=r8) :: temp9
  REAL(kind=r8), DIMENSION(nbdirsmax0) :: tempd5
  REAL(kind=r8), DIMENSION(nbdirsmax0) :: tempd6
  REAL(r8) :: temp10
  INTEGER :: nbdirs0
!-----------------------------------------------------------------------
!.computation
!
!   ..subprogram start-up calls
  CALL SUBINI('b2trfl')
!   ..main
  IF (cflim(4) .NE. 0.0_R8 .AND. (.NOT.mpg%cvonclosedsurface(icv))) THEN
    DO nd0=1,nbdirs0
      tempd3(nd0) = mp*2*zeffne*zeffned0(nd0)
    END DO
    temp = mp*(zeffne*zeffne)
    coefdd = 0.D0
    DO nd=1,nbdirs
      temp6 = zeffned(nd)/temp
      temp7 = (zetapd(nd)-2*mp*zetap*zeffne*temp6)/temp
      DO nd0=1,nbdirs0
        coefdd(nd0, nd) = 2.5_R8*(zetapdd(nd0, nd)-mp*2*(temp6*(zeffne*&
&         zetapd0(nd0)+zetap*zeffned0(nd0))+zetap*zeffne*(zeffnedd(nd0, &
&         nd)-temp6*tempd3(nd0))/temp)-temp7*tempd3(nd0))/temp
      END DO
      coefd(nd) = 2.5_R8*temp7
    END DO
    DO nd0=1,nbdirs0
      coefd0(nd0) = 2.5_R8*(zetapd0(nd0)-zetap*tempd3(nd0)/temp)/temp
    END DO
    coef = 2.5_R8*(zetap/temp)
    arg1dd = 0.D0
    t2dd = 0.D0
    x1dd = 0.D0
    tempd0d = 0.D0
    tempd1d = 0.D0
    tempd2d = 0.D0
    tempdd = 0.D0
    t0dd = 0.D0
    result1dd = 0.D0
    arg10dd = 0.D0
    t1dd = 0.D0
    DO i=0,nspecies-1
      DO nd0=1,nbdirs0
        temp0d(nd0, :) = nal(icv, 0:nspecies-1)*ainvd0(nd0, i, 0:&
&         nspecies-1) + ainv(i, 0:nspecies-1)*nald0(nd0, icv, 0:nspecies&
&         -1)
      END DO
      temp0 = ainv(i, 0:nspecies-1)*nal(icv, 0:nspecies-1)
      DO nd=1,nbdirs
        temp8 = nal(icv, 0:nspecies-1)*ainvd(nd, i, 0:nspecies-1) + ainv&
&         (i, 0:nspecies-1)*nald(nd, icv, 0:nspecies-1)
        DO nd0=1,nbdirs0
          arg1dd(nd0, nd, :) = temp8*gtalcd0(nd0, icv, 0:nspecies-1) + &
&           gtalc(icv, 0:nspecies-1)*(ainvd(nd, i, 0:nspecies-1)*nald0(&
&           nd0, icv, 0:nspecies-1)+nal(icv, 0:nspecies-1)*ainvdd(nd0, &
&           nd, i, 0:nspecies-1)+nald(nd, icv, 0:nspecies-1)*ainvd0(nd0&
&           , i, 0:nspecies-1)+ainv(i, 0:nspecies-1)*naldd(nd0, nd, icv&
&           , 0:nspecies-1)) + gtalcd(nd, icv, 0:nspecies-1)*temp0d(nd0&
&           , :) + temp0*gtalcdd(nd0, nd, icv, 0:nspecies-1)
          x1dd(nd0, nd) = SUM(arg1dd(nd0, nd, :))
        END DO
        arg1d(nd, :) = gtalc(icv, 0:nspecies-1)*temp8 + temp0*gtalcd(nd&
&         , icv, 0:nspecies-1)
        x1d(nd) = SUM(arg1d(nd, :))
      END DO
      DO nd0=1,nbdirs0
        arg1d0(nd0, :) = gtalc(icv, 0:nspecies-1)*temp0d(nd0, :) + temp0&
&         *gtalcd0(nd0, icv, 0:nspecies-1)
        x1d0(nd0) = SUM(arg1d0(nd0, :))
      END DO
      arg1 = temp0*gtalc(icv, 0:nspecies-1)
      x1 = SUM(arg1)
      IF (x1 .GE. 0.) THEN
        DO nd=1,nbdirs
          DO nd0=nd,nbdirs0
            t0dd(nd0, nd) = x1dd(nd0, nd)
          END DO
          t0d(nd) = x1d(nd)
        END DO
        DO nd0=1,nbdirs0
          t0d0(nd0) = x1d0(nd0)
        END DO
        t0 = x1
      ELSE
        DO nd=1,nbdirs
          DO nd0=nd,nbdirs0
            t0dd(nd0, nd) = -x1dd(nd0, nd)
          END DO
          t0d(nd) = -x1d(nd)
        END DO
        DO nd0=1,nbdirs0
          t0d0(nd0) = -x1d0(nd0)
        END DO
        t0 = -x1
      END IF
      temp7 = SQRT(amti(i))
      temp = temp7
      result1 = temp
      DO nd0=1,nbdirs0
        IF (amti(i) .EQ. 0.D0) THEN
          tempd3(nd0) = 0.D0
        ELSE
          tempd3(nd0) = amtid0(nd0, i)/(2.0*temp7)
        END IF
        result1d0(nd0) = tempd3(nd0)
        t1d0(nd0) = -(cflim(4)*switch%zhflcorr*result1d0(nd0)/result1**2&
&         )
      END DO
      t1 = switch%zhflcorr*cflim(4)/result1
      temp7 = coef*t0/t1
      DO nd0=1,nbdirs0
        temp1d(nd0) = (t0*coefd0(nd0)+coef*t0d0(nd0)-temp7*t1d0(nd0))/t1
      END DO
      temp1 = temp7
      DO nd=1,nbdirs
        IF (amti(i) .EQ. 0.d0) THEN
          DO nd0=1,nbdirs0
            result1dd(nd0, nd) = 0.D0
          END DO
          result1d(nd) = 0.d0
        ELSE
          temp7 = amtid(nd, i)/(2.0*temp)
          DO nd0=1,nbdirs0
            result1dd(nd0, nd) = (amtidd(nd0, nd, i)-temp7*2.0*tempd3(&
&             nd0))/(2.0*temp)
          END DO
          result1d(nd) = temp7
        END IF
        temp7 = result1d(nd)/(result1*result1)
        DO nd0=1,nbdirs0
          t1dd(nd0, nd) = -(cflim(4)*switch%zhflcorr*(result1dd(nd0, nd)&
&           -temp7*2*result1*result1d0(nd0))/result1**2)
        END DO
        t1d(nd) = -(cflim(4)*switch%zhflcorr*temp7)
        IF (temp1 .LE. 0.d0 .AND. (gamma .EQ. 0.d0 .OR. gamma .NE. INT(&
&           gamma))) THEN
          DO nd0=1,nbdirs0
            tempd0d(nd0, nd) = 0.D0
          END DO
          tempd0(nd) = 0.d0
        ELSE
          temp7 = t0*coefd(nd) + coef*t0d(nd) - temp1*t1d(nd)
          temp9 = temp1**(gamma-1)/t1
          DO nd0=1,nbdirs0
            IF (temp1 .LE. 0.D0 .AND. (gamma - 1 .EQ. 0.D0 .OR. gamma &
&               - 1 .NE. INT(gamma - 1))) THEN
              tempd4(nd0) = 0.D0
            ELSE
              tempd4(nd0) = (gamma-1)*temp1**(gamma-2)*temp1d(nd0)
            END IF
            tempd0d(nd0, nd) = gamma*(temp7*(tempd4(nd0)-temp9*t1d0(nd0)&
&             )/t1+temp9*(coefd(nd)*t0d0(nd0)+t0*coefdd(nd0, nd)+t0d(nd)&
&             *coefd0(nd0)+coef*t0dd(nd0, nd)-t1d(nd)*temp1d(nd0)-temp1*&
&             t1dd(nd0, nd)))
          END DO
          tempd0(nd) = gamma*(temp9*temp7)
        END IF
      END DO
      temp9 = SQRT(amti(i))
      DO nd0=1,nbdirs0
        IF (amti(i) .EQ. 0.D0) THEN
          tempd3(nd0) = 0.D0
        ELSE
          tempd3(nd0) = amtid0(nd0, i)/(2.0*temp9)
        END IF
      END DO
      temp = temp9
      DO nd=1,nbdirs
        IF (amti(i) .EQ. 0.d0) THEN
          DO nd0=1,nbdirs0
            result1dd(nd0, nd) = 0.D0
          END DO
          result1d(nd) = 0.d0
        ELSE
          temp9 = amtid(nd, i)/(2.0*temp)
          DO nd0=1,nbdirs0
            result1dd(nd0, nd) = (amtidd(nd0, nd, i)-temp9*2.0*tempd3(&
&             nd0))/(2.0*temp)
          END DO
          result1d(nd) = temp9
        END IF
      END DO
      result1 = temp
      temp9 = cflim(4)/result1
      DO nd0=1,nbdirs0
        result1d0(nd0) = tempd3(nd0)
        tempd3(nd0) = -(temp9*result1d0(nd0)/result1)
        t2d0(nd0) = switch%zhflcorrh*switch%zhflcorr*tempd3(nd0)
      END DO
      temp = temp9
      t2 = switch%zhflcorrh*switch%zhflcorr*temp
      temp9 = coef*t0/t2
      DO nd0=1,nbdirs0
        temp4d(nd0) = (t0*coefd0(nd0)+coef*t0d0(nd0)-temp9*t2d0(nd0))/t2
      END DO
      temp4 = temp9
      DO nd=1,nbdirs
        temp9 = temp/result1
        DO nd0=1,nbdirs0
          t2dd(nd0, nd) = -(switch%zhflcorrh*switch%zhflcorr*(temp9*&
&           result1dd(nd0, nd)+result1d(nd)*(tempd3(nd0)-temp9*result1d0&
&           (nd0))/result1))
        END DO
        t2d(nd) = -(switch%zhflcorrh*switch%zhflcorr*(result1d(nd)*temp9&
&         ))
        IF (temp4 .LE. 0.d0 .AND. (gamma .EQ. 0.d0 .OR. gamma .NE. INT(&
&           gamma))) THEN
          DO nd0=1,nbdirs0
            tempd2d(nd0, nd) = 0.D0
          END DO
          tempd2(nd) = 0.d0
        ELSE
          temp9 = t0*coefd(nd) + coef*t0d(nd) - temp4*t2d(nd)
          temp6 = temp4**(gamma-1)/t2
          DO nd0=1,nbdirs0
            IF (temp4 .LE. 0.D0 .AND. (gamma - 1 .EQ. 0.D0 .OR. gamma &
&               - 1 .NE. INT(gamma - 1))) THEN
              tempd5(nd0) = 0.D0
            ELSE
              tempd5(nd0) = (gamma-1)*temp4**(gamma-2)*temp4d(nd0)
            END IF
            tempd2d(nd0, nd) = gamma*(temp9*(tempd5(nd0)-temp6*t2d0(nd0)&
&             )/t2+temp6*(coefd(nd)*t0d0(nd0)+t0*coefdd(nd0, nd)+t0d(nd)&
&             *coefd0(nd0)+coef*t0dd(nd0, nd)-t2d(nd)*temp4d(nd0)-temp4*&
&             t2dd(nd0, nd)))
          END DO
          tempd2(nd) = gamma*(temp6*temp9)
        END IF
      END DO
!
      temp = 1.0/gamma
      temp2 = temp1**gamma + 1.0_R8
      temp9 = 1.0/temp2**temp
      DO nd0=1,nbdirs0
        IF (temp1 .LE. 0.D0 .AND. (gamma .EQ. 0.D0 .OR. gamma .NE. INT&
&           (gamma))) THEN
          temp2d(nd0) = 0.D0
        ELSE
          temp2d(nd0) = gamma*temp1**(gamma-1)*temp1d(nd0)
        END IF
        IF (temp2 .LE. 0.D0 .AND. (temp .EQ. 0.D0 .OR. temp .NE. INT(&
&           temp))) THEN
          tempd5(nd0) = 0.D0
        ELSE
          tempd5(nd0) = temp*temp2**(temp-1)*temp2d(nd0)
        END IF
        temp3d(nd0) = -(temp9*tempd5(nd0)/temp2**temp)
      END DO
      temp3 = temp9
      DO nd=1,nbdirs
        IF (temp2 .LE. 0.d0 .AND. (temp .EQ. 0.d0 .OR. temp .NE. INT(&
&           temp))) THEN
          DO nd0=1,nbdirs0
            tempdd(nd0, nd) = 0.D0
          END DO
          tempd(nd) = 0.d0
        ELSE
          temp9 = temp2**(temp-1)
          DO nd0=1,nbdirs0
            IF (temp2 .LE. 0.D0 .AND. (temp - 1 .EQ. 0.D0 .OR. temp - &
&               1 .NE. INT(temp - 1))) THEN
              tempd6(nd0) = 0.D0
            ELSE
              tempd6(nd0) = (temp-1)*temp2**(temp-2)*temp2d(nd0)
            END IF
            tempdd(nd0, nd) = temp*(tempd0(nd)*tempd6(nd0)+temp9*tempd0d&
&             (nd0, nd))
          END DO
          tempd(nd) = temp*(temp9*tempd0(nd))
        END IF
        temp9 = temp2**temp
        temp7 = temp3*tempd(nd)/temp9
        DO nd0=1,nbdirs0
          IF (temp2 .LE. 0.D0 .AND. (temp .EQ. 0.D0 .OR. temp .NE. INT&
&             (temp))) THEN
            tempd6(nd0) = 0.D0
          ELSE
            tempd6(nd0) = temp*temp2**(temp-1)*temp2d(nd0)
          END IF
          cf_limdd(nd0, nd, i) = -((tempd(nd)*temp3d(nd0)+temp3*tempdd(&
&           nd0, nd)-temp7*tempd6(nd0))/temp9)
        END DO
        cf_limd(nd, i) = -temp7
      END DO
      cf_lim(i) = temp3
      temp5 = 1.0/gamma
      temp3 = temp4**gamma + 1.0_R8
      temp9 = 1.0/temp3**temp5
      DO nd0=1,nbdirs0
        cf_limd0(nd0, i) = temp3d(nd0)
        IF (temp4 .LE. 0.D0 .AND. (gamma .EQ. 0.D0 .OR. gamma .NE. INT&
&           (gamma))) THEN
          temp3d(nd0) = 0.D0
        ELSE
          temp3d(nd0) = gamma*temp4**(gamma-1)*temp4d(nd0)
        END IF
        IF (temp3 .LE. 0.D0 .AND. (temp5 .EQ. 0.D0 .OR. temp5 .NE. INT&
&           (temp5))) THEN
          tempd5(nd0) = 0.D0
        ELSE
          tempd5(nd0) = temp5*temp3**(temp5-1)*temp3d(nd0)
        END IF
        temp2d(nd0) = -(temp9*tempd5(nd0)/temp3**temp5)
      END DO
      temp2 = temp9
      DO nd=1,nbdirs
        IF (temp3 .LE. 0.d0 .AND. (temp5 .EQ. 0.d0 .OR. temp5 .NE. INT(&
&           temp5))) THEN
          DO nd0=1,nbdirs0
            tempd1d(nd0, nd) = 0.D0
          END DO
          tempd1(nd) = 0.d0
        ELSE
          temp9 = temp3**(temp5-1)
          DO nd0=1,nbdirs0
            IF (temp3 .LE. 0.D0 .AND. (temp5 - 1 .EQ. 0.D0 .OR. temp5 &
&               - 1 .NE. INT(temp5 - 1))) THEN
              tempd6(nd0) = 0.D0
            ELSE
              tempd6(nd0) = (temp5-1)*temp3**(temp5-2)*temp3d(nd0)
            END IF
            tempd1d(nd0, nd) = temp5*(tempd2(nd)*tempd6(nd0)+temp9*&
&             tempd2d(nd0, nd))
          END DO
          tempd1(nd) = temp5*(temp9*tempd2(nd))
        END IF
        temp9 = temp3**temp5
        temp7 = temp2*tempd1(nd)/temp9
        DO nd0=1,nbdirs0
          IF (temp3 .LE. 0.D0 .AND. (temp5 .EQ. 0.D0 .OR. temp5 .NE. &
&             INT(temp5))) THEN
            tempd6(nd0) = 0.D0
          ELSE
            tempd6(nd0) = temp5*temp3**(temp5-1)*temp3d(nd0)
          END IF
          cf_limhdd(nd0, nd, i) = -((tempd1(nd)*temp2d(nd0)+temp2*&
&           tempd1d(nd0, nd)-temp7*tempd6(nd0))/temp9)
        END DO
        cf_limhd(nd, i) = -temp7
      END DO
      temp9 = t1/(coef*t0)
      DO nd0=1,nbdirs0
        cf_limhd0(nd0, i) = temp2d(nd0)
        temp5d(nd0) = (t1d0(nd0)-temp9*(t0*coefd0(nd0)+coef*t0d0(nd0)))/&
&         (coef*t0)
        arg10d0(nd0) = 10.0_R8*temp5d(nd0)
      END DO
      cf_limh(i) = temp2
      temp5 = temp9
      arg10 = 10.0_R8*(temp5-1.0_R8)
      DO nd=1,nbdirs
        temp9 = t0*coefd(nd) + coef*t0d(nd)
        temp7 = (t1d(nd)-temp5*temp9)/(coef*t0)
        arg10d(nd) = 10.0_R8*temp7
        temp10 = TANH(arg10)
        DO nd0=1,nbdirs0
          arg10dd(nd0, nd) = 10.0_R8*(t1dd(nd0, nd)-temp9*temp5d(nd0)-&
&           temp5*(coefd(nd)*t0d0(nd0)+t0*coefdd(nd0, nd)+t0d(nd)*coefd0&
&           (nd0)+coef*t0dd(nd0, nd))-temp7*(t0*coefd0(nd0)+coef*t0d0(&
&           nd0)))/(coef*t0)
          cf_limbdd(nd0, nd, i) = 0.5_R8*((1.0-temp10**2)*arg10dd(nd0, &
&           nd)-arg10d(nd)*2*temp10*(1.0-TANH(arg10)**2)*arg10d0(nd0))
        END DO
        cf_limbd(nd, i) = 0.5_R8*((1.0-temp10*temp10)*arg10d(nd))
      END DO
      temp9 = t2/(coef*t0)
      DO nd0=1,nbdirs0
        cf_limbd0(nd0, i) = 0.5_R8*(1.0-TANH(arg10)**2)*arg10d0(nd0)
        temp5d(nd0) = (t2d0(nd0)-temp9*(t0*coefd0(nd0)+coef*t0d0(nd0)))/&
&         (coef*t0)
        arg10d0(nd0) = 10.0_R8*temp5d(nd0)
      END DO
      cf_limb(i) = 0.5_R8 + 0.5_R8*TANH(arg10)
      temp5 = temp9
      arg10 = 10.0_R8*(temp5-1.0_R8)
      DO nd=1,nbdirs
        temp9 = t0*coefd(nd) + coef*t0d(nd)
        temp7 = (t2d(nd)-temp5*temp9)/(coef*t0)
        arg10d(nd) = 10.0_R8*temp7
        temp10 = TANH(arg10)
        DO nd0=1,nbdirs0
          arg10dd(nd0, nd) = 10.0_R8*(t2dd(nd0, nd)-temp9*temp5d(nd0)-&
&           temp5*(coefd(nd)*t0d0(nd0)+t0*coefdd(nd0, nd)+t0d(nd)*coefd0&
&           (nd0)+coef*t0dd(nd0, nd))-temp7*(t0*coefd0(nd0)+coef*t0d0(&
&           nd0)))/(coef*t0)
          cf_limbhdd(nd0, nd, i) = 0.5_R8*((1.0-temp10**2)*arg10dd(nd0, &
&           nd)-arg10d(nd)*2*temp10*(1.0-TANH(arg10)**2)*arg10d0(nd0))
        END DO
        cf_limbhd(nd, i) = 0.5_R8*((1.0-temp10*temp10)*arg10d(nd))
      END DO
      DO nd0=1,nbdirs0
        cf_limbhd0(nd0, i) = 0.5_R8*(1.0-TANH(arg10)**2)*arg10d0(nd0)
      END DO
      cf_limbh(i) = 0.5_R8 + 0.5_R8*TANH(arg10)
    END DO
  ELSE
    cf_lim(0:nspecies-1) = 1.0_R8
    cf_limh(0:nspecies-1) = 1.0_R8
    cf_limb(0:nspecies-1) = 1.0_R8
    cf_limbh(0:nspecies-1) = 1.0_R8
    cf_limbd = 0.d0
    cf_limhd = 0.d0
    cf_limbhd = 0.d0
    cf_limd = 0.d0
    cf_limbd0 = 0.D0
    cf_limdd = 0.D0
    cf_limhdd = 0.D0
    cf_limhd0 = 0.D0
    cf_limbdd = 0.D0
    cf_limbhd0 = 0.D0
    cf_limbhdd = 0.D0
    cf_limd0 = 0.D0
  END IF
!
  CALL SUBEND()
  RETURN
!
END SUBROUTINE B2TRFL_DV_DV

!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 23 Jul 2024 17:41
!
!  Differentiation of b2trfl in forward (tangent) mode (with options multiDirectional context noISIZE r8):
!   variations   of useful results: cf_limb cf_limh cf_limbh cf_lim
!   with respect to varying inputs: *nal *gtalc cf_limb cf_limh
!                cf_limbh zetap ainv zeffne amti cf_lim
!   Plus diff mem management of: nal:in gtalc:in
!
!
!
!
!
!
!
!
!
!
!
!.specification
!
SUBROUTINE B2TRFL_DV_NODIFF(icv, switch, mpg, ainv, ainvd, zeffne, &
& zeffned, amti, amtid, zetap, zetapd, gamma, cf_lim, cf_limd, cf_limh, &
& cf_limhd, cf_limb, cf_limbd, cf_limbh, cf_limbhd, nbdirs)
  USE B2MOD_TYPES
  USE B2MOD_B2CMPA_DIFFV
  USE B2MOD_B2CMPT_DIFFV_DIFFV
  USE B2MOD_CONSTANTS
  USE B2US_MAP_DIFFV_DIFFV
  USE B2MOD_SWITCHES_DIFFV_DIFFV
  USE B2MOD_ZHFRTF_DIFFV_DIFFV, ONLY : gtalc, gtalcd, nal, nald
  USE B2MOD_SUBSYS
!  Hint: nbdirsmax should be the maximum number of differentiation directions
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!   ..input arguments (unchanged on exit)
  INTEGER :: icv
!som 20.03.21
  REAL(kind=r8) :: gamma
  REAL(kind=r8) :: zeffne, zetap, amti(0:nspecies-1), ainv(0:2*nspecies-&
& 1, 0:2*nspecies-1)
  REAL(kind=r8) :: zeffned(nbdirsmax), zetapd(nbdirsmax), amtid(&
& nbdirsmax, 0:nspecies-1), ainvd(nbdirsmax, 0:2*nspecies-1, 0:2*&
& nspecies-1)
  TYPE(MAPPING), INTENT(IN) :: mpg
  TYPE(SWITCHES), INTENT(IN) :: switch
!   ..output arguments (unspecified on entry)
  REAL(kind=r8) :: cf_lim(0:nspecies-1), cf_limh(0:nspecies-1), cf_limb(&
& 0:nspecies-1), cf_limbh(0:nspecies-1)
  REAL(kind=r8) :: cf_limd(nbdirsmax, 0:nspecies-1), cf_limhd(nbdirsmax&
& , 0:nspecies-1), cf_limbd(nbdirsmax, 0:nspecies-1), cf_limbhd(&
& nbdirsmax, 0:nspecies-1)
!-----------------------------------------------------------------------
!.documentation
!
!  1. purpose
!
!     B2TRFL computes the flux-limiting coefficients.
!
!  3. description
!
!     This routine computes:
!     - cF_lim: the flux-limiting coefficient for the thermal force coefficient
!     - cF_limh: the flux-limiting coefficient for the heat flux
!     - cF_limB: the flux-limiting coefficient for the charge state correction
!     - cF_limBh: the flux-limiting coefficient for the charge state correction for the heat flux
!-----------------------------------------------------------------------
!.declarations
!   ..local variables
  INTEGER :: i
  REAL(kind=r8) :: coef, t0, t1, t2
  REAL(kind=r8), DIMENSION(nbdirsmax) :: coefd, t0d, t1d, t2d
  INTRINSIC SUM
  INTRINSIC ABS
  INTRINSIC SQRT
  INTRINSIC TANH
  REAL(kind=r8) :: x1
  REAL(kind=r8), DIMENSION(nbdirsmax) :: x1d
  REAL(kind=r8), DIMENSION(nspecies) :: arg1
  REAL(kind=r8), DIMENSION(nbdirsmax, nspecies) :: arg1d
  REAL(kind=r8) :: result1
  REAL(kind=r8), DIMENSION(nbdirsmax) :: result1d
  REAL(r8) :: arg10
  REAL(r8), DIMENSION(nbdirsmax) :: arg10d
  INTEGER :: nd
  REAL(kind=r8) :: temp
  REAL(kind=r8), DIMENSION(nspecies) :: temp0
  REAL(kind=r8) :: temp1
  REAL(kind=r8) :: temp2
  REAL(kind=r8) :: temp3
  REAL(kind=r8) :: temp4
  REAL(kind=r8), DIMENSION(nbdirsmax) :: tempd
  REAL(kind=r8) :: temp5
  REAL(kind=r8), DIMENSION(nbdirsmax) :: tempd0
  REAL(kind=r8), DIMENSION(nbdirsmax) :: tempd1
  REAL(kind=r8), DIMENSION(nbdirsmax) :: tempd2
  INTEGER :: nbdirs
  INTRINSIC INT
!-----------------------------------------------------------------------
!.computation
!
!   ..subprogram start-up calls
  CALL SUBINI('b2trfl')
!   ..main
  IF (cflim(4) .NE. 0.0_R8 .AND. (.NOT.mpg%cvonclosedsurface(icv))) THEN
    temp = mp*(zeffne*zeffne)
    DO nd=1,nbdirs
      coefd(nd) = 2.5_R8*(zetapd(nd)-zetap*mp*2*zeffne*zeffned(nd)/temp)&
&       /temp
    END DO
    coef = 2.5_R8*(zetap/temp)
    DO i=0,nspecies-1
      temp0 = ainv(i, 0:nspecies-1)*nal(icv, 0:nspecies-1)
      DO nd=1,nbdirs
        arg1d(nd, :) = gtalc(icv, 0:nspecies-1)*(nal(icv, 0:nspecies-1)*&
&         ainvd(nd, i, 0:nspecies-1)+ainv(i, 0:nspecies-1)*nald(nd, icv&
&         , 0:nspecies-1)) + temp0*gtalcd(nd, icv, 0:nspecies-1)
        x1d(nd) = SUM(arg1d(nd, :))
      END DO
      arg1 = temp0*gtalc(icv, 0:nspecies-1)
      x1 = SUM(arg1)
      IF (x1 .GE. 0.) THEN
        DO nd=1,nbdirs
          t0d(nd) = x1d(nd)
        END DO
        t0 = x1
      ELSE
        DO nd=1,nbdirs
          t0d(nd) = -x1d(nd)
        END DO
        t0 = -x1
      END IF
      temp = SQRT(amti(i))
      result1 = temp
      t1 = switch%zhflcorr*cflim(4)/result1
      temp1 = coef*t0/t1
      DO nd=1,nbdirs
        IF (amti(i) .EQ. 0.d0) THEN
          result1d(nd) = 0.d0
        ELSE
          result1d(nd) = amtid(nd, i)/(2.0*temp)
        END IF
        t1d(nd) = -(cflim(4)*switch%zhflcorr*result1d(nd)/result1**2)
        IF (temp1 .LE. 0.d0 .AND. (gamma .EQ. 0.d0 .OR. gamma .NE. INT(&
&           gamma))) THEN
          tempd0(nd) = 0.d0
        ELSE
          tempd0(nd) = gamma*temp1**(gamma-1)*(t0*coefd(nd)+coef*t0d(nd)&
&           -temp1*t1d(nd))/t1
        END IF
      END DO
      temp = SQRT(amti(i))
      DO nd=1,nbdirs
        IF (amti(i) .EQ. 0.d0) THEN
          result1d(nd) = 0.d0
        ELSE
          result1d(nd) = amtid(nd, i)/(2.0*temp)
        END IF
      END DO
      result1 = temp
      temp = cflim(4)/result1
      t2 = switch%zhflcorrh*switch%zhflcorr*temp
      temp4 = coef*t0/t2
      DO nd=1,nbdirs
        t2d(nd) = -(switch%zhflcorrh*switch%zhflcorr*temp*result1d(nd)/&
&         result1)
        IF (temp4 .LE. 0.d0 .AND. (gamma .EQ. 0.d0 .OR. gamma .NE. INT(&
&           gamma))) THEN
          tempd2(nd) = 0.d0
        ELSE
          tempd2(nd) = gamma*temp4**(gamma-1)*(t0*coefd(nd)+coef*t0d(nd)&
&           -temp4*t2d(nd))/t2
        END IF
      END DO
!
      temp = 1.0/gamma
      temp2 = temp1**gamma + 1.0_R8
      temp3 = 1.0/temp2**temp
      DO nd=1,nbdirs
        IF (temp2 .LE. 0.d0 .AND. (temp .EQ. 0.d0 .OR. temp .NE. INT(&
&           temp))) THEN
          tempd(nd) = 0.d0
        ELSE
          tempd(nd) = temp*temp2**(temp-1)*tempd0(nd)
        END IF
        cf_limd(nd, i) = -(temp3*tempd(nd)/temp2**temp)
      END DO
      cf_lim(i) = temp3
      temp5 = 1.0/gamma
      temp3 = temp4**gamma + 1.0_R8
      temp2 = 1.0/temp3**temp5
      DO nd=1,nbdirs
        IF (temp3 .LE. 0.d0 .AND. (temp5 .EQ. 0.d0 .OR. temp5 .NE. INT(&
&           temp5))) THEN
          tempd1(nd) = 0.d0
        ELSE
          tempd1(nd) = temp5*temp3**(temp5-1)*tempd2(nd)
        END IF
        cf_limhd(nd, i) = -(temp2*tempd1(nd)/temp3**temp5)
      END DO
      cf_limh(i) = temp2
      temp5 = t1/(coef*t0)
      arg10 = 10.0_R8*(temp5-1.0_R8)
      DO nd=1,nbdirs
        arg10d(nd) = 10.0_R8*(t1d(nd)-temp5*(t0*coefd(nd)+coef*t0d(nd)))&
&         /(coef*t0)
        cf_limbd(nd, i) = 0.5_R8*(1.0-TANH(arg10)**2)*arg10d(nd)
      END DO
      cf_limb(i) = 0.5_R8 + 0.5_R8*TANH(arg10)
      temp5 = t2/(coef*t0)
      arg10 = 10.0_R8*(temp5-1.0_R8)
      DO nd=1,nbdirs
        arg10d(nd) = 10.0_R8*(t2d(nd)-temp5*(t0*coefd(nd)+coef*t0d(nd)))&
&         /(coef*t0)
        cf_limbhd(nd, i) = 0.5_R8*(1.0-TANH(arg10)**2)*arg10d(nd)
      END DO
      cf_limbh(i) = 0.5_R8 + 0.5_R8*TANH(arg10)
    END DO
  ELSE
    cf_lim(0:nspecies-1) = 1.0_R8
    cf_limh(0:nspecies-1) = 1.0_R8
    cf_limb(0:nspecies-1) = 1.0_R8
    cf_limbh(0:nspecies-1) = 1.0_R8
    cf_limbd = 0.d0
    cf_limhd = 0.d0
    cf_limbhd = 0.d0
    cf_limd = 0.d0
  END IF
!
  CALL SUBEND()
  RETURN
!
END SUBROUTINE B2TRFL_DV_NODIFF

!
!
!
!
!
!
!
!
!
!
!
!.specification
!
SUBROUTINE B2TRFL_NODIFF_NODIFF(icv, switch, mpg, ainv, zeffne, amti, &
& zetap, gamma, cf_lim, cf_limh, cf_limb, cf_limbh)
  USE B2MOD_TYPES
  USE B2MOD_B2CMPA_DIFFV
  USE B2MOD_B2CMPT_DIFFV_DIFFV
  USE B2MOD_CONSTANTS
  USE B2US_MAP_DIFFV_DIFFV
  USE B2MOD_SWITCHES_DIFFV_DIFFV
  USE B2MOD_ZHFRTF_DIFFV_DIFFV, ONLY : gtalc, nal
  USE B2MOD_SUBSYS
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!   ..input arguments (unchanged on exit)
  INTEGER :: icv
!som 20.03.21
  REAL(kind=r8) :: gamma
  REAL(kind=r8) :: zeffne, zetap, amti(0:nspecies-1), ainv(0:2*nspecies-&
& 1, 0:2*nspecies-1)
  TYPE(MAPPING), INTENT(IN) :: mpg
  TYPE(SWITCHES), INTENT(IN) :: switch
!   ..output arguments (unspecified on entry)
  REAL(kind=r8) :: cf_lim(0:nspecies-1), cf_limh(0:nspecies-1), cf_limb(&
& 0:nspecies-1), cf_limbh(0:nspecies-1)
!-----------------------------------------------------------------------
!.documentation
!
!  1. purpose
!
!     B2TRFL computes the flux-limiting coefficients.
!
!  3. description
!
!     This routine computes:
!     - cF_lim: the flux-limiting coefficient for the thermal force coefficient
!     - cF_limh: the flux-limiting coefficient for the heat flux
!     - cF_limB: the flux-limiting coefficient for the charge state correction
!     - cF_limBh: the flux-limiting coefficient for the charge state correction for the heat flux
!-----------------------------------------------------------------------
!.declarations
!   ..local variables
  INTEGER :: i
  REAL(kind=r8) :: coef, t0, t1, t2
  INTRINSIC SUM
  INTRINSIC ABS
  INTRINSIC SQRT
  INTRINSIC TANH
  REAL(kind=r8) :: x1
  REAL(kind=r8), DIMENSION(nspecies) :: arg1
  REAL(kind=r8) :: result1
  REAL(r8) :: arg10
!-----------------------------------------------------------------------
!.computation
!
!   ..subprogram start-up calls
  CALL SUBINI('b2trfl')
!   ..main
  IF (cflim(4) .NE. 0.0_R8 .AND. (.NOT.mpg%cvonclosedsurface(icv))) THEN
    coef = 2.5_R8*zetap/mp/zeffne**2
    DO i=0,nspecies-1
      arg1 = ainv(i, 0:nspecies-1)*nal(icv, 0:nspecies-1)*gtalc(icv, 0:&
&       nspecies-1)
      x1 = SUM(arg1)
      IF (x1 .GE. 0.) THEN
        t0 = x1
      ELSE
        t0 = -x1
      END IF
      result1 = SQRT(amti(i))
      t1 = switch%zhflcorr*cflim(4)/result1
      result1 = SQRT(amti(i))
      t2 = switch%zhflcorrh*switch%zhflcorr*cflim(4)/result1
!
      cf_lim(i) = 1.0_R8/(1.0_R8+(coef*t0/t1)**gamma)**(1.0_R8/gamma)
      cf_limh(i) = 1.0_R8/(1.0_R8+(coef*t0/t2)**gamma)**(1.0_R8/gamma)
      arg10 = 10.0_R8*(t1/(coef*t0)-1.0_R8)
      cf_limb(i) = 0.5_R8 + 0.5_R8*TANH(arg10)
      arg10 = 10.0_R8*(t2/(coef*t0)-1.0_R8)
      cf_limbh(i) = 0.5_R8 + 0.5_R8*TANH(arg10)
    END DO
  ELSE
    cf_lim(0:nspecies-1) = 1.0_R8
    cf_limh(0:nspecies-1) = 1.0_R8
    cf_limb(0:nspecies-1) = 1.0_R8
    cf_limbh(0:nspecies-1) = 1.0_R8
  END IF
!
  CALL SUBEND()
  RETURN
!
END SUBROUTINE B2TRFL_NODIFF_NODIFF

