!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 23 Jul 2024 17:41
!
!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 23 Jul 2024 17:41
!
!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE B2TXFX_NODIFF_NODIFF(nx, ny, ns, mode, vol, gs, hx, qz, kapx&
& , conx)
  USE B2MOD_TYPES
  USE B2MOD_MATH_DIFFV_DIFFV
  USE B2MOD_INDIRECT_DIFFV_DIFFV
  USE B2MOD_SUBSYS
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
  INTEGER :: nx, ny, ns, mode
  REAL(kind=r8) :: vol(-1:nx, -1:ny), hx(-1:nx, -1:ny), gs(-1:nx, -1:ny&
& , 0:2), qz(-1:nx, -1:ny, 0:1), kapx(-1:nx, -1:ny, 0:1, 0:ns-1), conx(-&
& 1:nx, -1:ny)
!     ------------------------------------------------------------------
!     B2TXFX computes conductances between neighbouring cells in the
!     x-direction, given the flux-limited conductivities.
!     ------------------------------------------------------------------
  INTEGER :: n2, ix, iy, is
  REAL(kind=r8) :: t0, t1, kaps, kapsn
  INTRINSIC MAX, SQRT
  EXTERNAL XERTST, smin, smax
  EXTERNAL B2XVSG, B2XXGS, HARM
  REAL(kind=r8) :: HARM, smin, smax
  REAL(r8) :: y1
  REAL(r8) :: max1
  REAL(kind=r8) :: result1
  REAL(kind=r8) :: result2
  REAL(r8) :: result10
!     ------------------------------------------------------------------
!   ..subprogram start-up calls
  CALL SUBINI('b2txfx')
!   ..test nx, ny, ns
  CALL XERTST(0 .LE. nx .AND. 0 .LE. ny, 'faulty argument nx, ny')
  CALL XERTST(1 .LE. ns, 'faulty argument ns')
!   ..set n2
  n2 = (nx+2)*(ny+2)
!   ..test mode
  CALL XERTST(-1 .LE. mode .AND. mode .LE. 2, &
&       'b2txfx--faulty argument mode')
!   ..test sign of vol, hx
  CALL B2XVSG(n2, vol, 1, 'vol', '.gt.')
  CALL B2XVSG(n2, hx, 1, 'hx', '.gt.')
!   ..test range of qz
  result1 = smin(n2, qz(-1, -1, 0), 1)
  result2 = smax(n2, qz(-1, -1, 0), 1)
  CALL XERTST(-1.0_R8 .LT. result1 .AND. result2 .LT. 1.0_R8, &
&       'faulty argument range qz(,,0)')
  result1 = smin(n2, qz(-1, -1, 1), 1)
  result2 = smax(n2, qz(-1, -1, 1), 1)
  CALL XERTST(0.0_R8 .LT. result1 .AND. result2 .LE. 1.0_R8, &
&       'faulty argument range qz(,,1)')
!
!   ..compute conx
  DO iy=-1,ny
    DO ix=-1,nx
      IF (leftix(ix, iy) .EQ. -2) THEN
        conx(ix, iy) = 0.0_R8
      ELSE
        kaps = 0.0_R8
        kapsn = 0.0_R8
        DO is=0,ns-1
          kaps = kaps + kapx(ix, iy, 0, is)
          kapsn = kapsn + kapx(leftix(ix, iy), leftiy(ix, iy), 0, is)
        END DO
        IF (mode .EQ. -1) THEN
!    ..use harmonic averaging
!      (needs somewhat messy code because the harmonic average is only
!      defined for two quantities of the same sign.)
          t0 = vol(leftix(ix, iy), leftiy(ix, iy))*kapsn/hx(leftix(ix, &
&           iy), leftiy(ix, iy))**2
          t1 = vol(ix, iy)*kaps/hx(ix, iy)**2
          IF (t0*t1 .LE. 0.0_R8) THEN
            conx(ix, iy) = 0.0_R8
          ELSE
            conx(ix, iy) = HARM(t0, t1)
          END IF
        ELSE IF (mode .EQ. 0) THEN
          y1 = vol(leftix(ix, iy), leftiy(ix, iy))*kapsn/hx(leftix(ix, &
&           iy), leftiy(ix, iy))*(vol(ix, iy)*kaps/hx(ix, iy))
          IF (0.0_R8 .LT. y1) THEN
            max1 = y1
          ELSE
            max1 = 0.0_R8
          END IF
!    ..use geometric averaging
          result10 = SQRT(max1)
          conx(ix, iy) = 2.0_R8*result10/(hx(leftix(ix, iy), leftiy(ix, &
&           iy))+hx(ix, iy))
        ELSE IF (mode .EQ. 1) THEN
!    ..use arithmetic averaging (SOLPS5.0 formulation)
          conx(ix, iy) = 2.0_R8*(vol(leftix(ix, iy), leftiy(ix, iy))*&
&           kapsn+vol(ix, iy)*kaps)/(hx(leftix(ix, iy), leftiy(ix, iy))+&
&           hx(ix, iy))**2
        ELSE IF (mode .EQ. 2) THEN
!    ..use arithmetic averaging (SOLPS4.0 formulation)
          conx(ix, iy) = gs(ix, iy, 0)*qz(ix, iy, 1)*2.0_R8*(hx(leftix(&
&           ix, iy), leftiy(ix, iy))*kapsn+hx(ix, iy)*kaps)/(hx(leftix(&
&           ix, iy), leftiy(ix, iy))+hx(ix, iy))**2
        END IF
      END IF
    END DO
  END DO
!   ..reset null regions
  CALL B2XXGS(nx, ny, 0.0_R8, conx, 1)
!   ..return
  CALL SUBEND()
  RETURN
!     ------------------------------------------------------------------
END SUBROUTINE B2TXFX_NODIFF_NODIFF

