!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (feature_llhTests) - 27 May 2021 14:23
!
!  Differentiation of b2xpro_dv in forward (tangent) mode (with options multiDirectional context noISIZE r8):
!   variations   of useful results: ro rod
!   with respect to varying inputs: na nad
!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (feature_llhTests) - 27 May 2021 14:23
!
!  Differentiation of b2xpro in forward (tangent) mode (with options multiDirectional context noISIZE r8):
!   variations   of useful results: ro
!   with respect to varying inputs: na
!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE B2XPRO_DV_DV(ncv, ns, mp, am, na, nad0, nad, nadd, ro, rod0, &
& rod, rodd, st_ext, nbdirs, nbdirs0)
  USE B2MOD_TYPES
  USE B2US_PLASMA_DIFFV_DIFFV
!  Hint: nbdirsmax should be the maximum number of differentiation directions
  USE B2MOD_DIFFSIZES
!  Hint: nbdirsmax0 should be the maximum number of differentiation directions
  IMPLICIT NONE
!     ------------------------------------------------------------------
  INTEGER :: ncv, ns
  TYPE(B2STATEEXT), INTENT(IN) :: st_ext
  REAL(kind=r8) :: mp, am(0:ns-1), na(ncv, 0:ns-1), ro(ncv)
  REAL(kind=r8) :: nad0(nbdirsmax0, ncv, 0:ns-1), rod0(nbdirsmax0, ncv)
  REAL(kind=r8) :: nad(nbdirsmax, ncv, 0:ns-1), rod(nbdirsmax, ncv)
  REAL(kind=r8) :: nadd(nbdirsmax0, nbdirsmax, ncv, 0:ns-1), rodd(&
& nbdirsmax0, nbdirsmax, ncv)
!     ------------------------------------------------------------------
!     B2XPRO computes the mass density, ro:
!       ro() = (sum is :: am(is)*mp*na(,is)) .
!     ------------------------------------------------------------------
  INTEGER :: is
  INTEGER :: nd
  INTEGER :: nbdirs
  INTEGER :: nd0
  INTEGER :: nbdirs0
!     ------------------------------------------------------------------
!$$$  call subini ('b2xpro')
  DO nd=1,nbdirs
    rod(nd, :) = 0.d0
  END DO
  ro = 0.0_R8
  DO nd=1,nbdirsmax
    rod(nd, :) = 0.d0
  END DO
  rod0(:, :) = 0.0_8
  rodd(:, :, :) = 0.0_8
  DO is=0,ns-1
    DO nd=1,nbdirs
      DO nd0=nd,nbdirs0
        rodd(nd0, nd, :) = rodd(nd0, nd, :) + mp*am(is)*nadd(nd0, nd, :&
&         , is)
      END DO
      rod(nd, :) = rod(nd, :) + mp*am(is)*nad(nd, :, is)
    END DO
    DO nd0=1,nbdirs0
      rod0(nd0, :) = rod0(nd0, :) + mp*am(is)*nad0(nd0, :, is)
    END DO
    ro = ro + mp*am(is)*na(:, is)
  END DO
  DO is=0,st_ext%ns-1
    ro = ro + mp*st_ext%am(is)*st_ext%na(:, is)
  END DO
!$$$  call subend ()
  RETURN
END SUBROUTINE B2XPRO_DV_DV

!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (feature_llhTests) - 27 May 2021 14:23
!
!  Differentiation of b2xpro in forward (tangent) mode (with options multiDirectional context noISIZE r8):
!   variations   of useful results: ro
!   with respect to varying inputs: na
!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE B2XPRO_DV_NODIFF(ncv, ns, mp, am, na, nad, ro, rod, st_ext, &
& nbdirs)
  USE B2MOD_TYPES
  USE B2US_PLASMA_DIFFV_DIFFV
!  Hint: nbdirsmax should be the maximum number of differentiation directions
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!     ------------------------------------------------------------------
  INTEGER :: ncv, ns
  TYPE(B2STATEEXT), INTENT(IN) :: st_ext
  REAL(kind=r8) :: mp, am(0:ns-1), na(ncv, 0:ns-1), ro(ncv)
  REAL(kind=r8) :: nad(nbdirsmax, ncv, 0:ns-1), rod(nbdirsmax, ncv)
!     ------------------------------------------------------------------
!     B2XPRO computes the mass density, ro:
!       ro() = (sum is :: am(is)*mp*na(,is)) .
!     ------------------------------------------------------------------
  INTEGER :: is
  INTEGER :: nd
  INTEGER :: nbdirs
!     ------------------------------------------------------------------
!$$$  call subini ('b2xpro')
  DO nd=1,nbdirs
    rod(nd, :) = 0.d0
  END DO
  ro = 0.0_R8
  DO nd=1,nbdirsmax
    rod(nd, :) = 0.d0
  END DO
  DO is=0,ns-1
    DO nd=1,nbdirs
      rod(nd, :) = rod(nd, :) + mp*am(is)*nad(nd, :, is)
    END DO
    ro = ro + mp*am(is)*na(:, is)
  END DO
  DO is=0,st_ext%ns-1
    ro = ro + mp*st_ext%am(is)*st_ext%na(:, is)
  END DO
!$$$  call subend ()
  RETURN
END SUBROUTINE B2XPRO_DV_NODIFF

!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE B2XPRO_NODIFF_NODIFF(ncv, ns, mp, am, na, ro, st_ext)
  USE B2MOD_TYPES
  USE B2US_PLASMA_DIFFV_DIFFV
  USE B2MOD_DIFFSIZES
  IMPLICIT NONE
!     ------------------------------------------------------------------
  INTEGER :: ncv, ns
  TYPE(B2STATEEXT), INTENT(IN) :: st_ext
  REAL(kind=r8) :: mp, am(0:ns-1), na(ncv, 0:ns-1), ro(ncv)
!     ------------------------------------------------------------------
!     B2XPRO computes the mass density, ro:
!       ro() = (sum is :: am(is)*mp*na(,is)) .
!     ------------------------------------------------------------------
  INTEGER :: is
!     ------------------------------------------------------------------
!$$$  call subini ('b2xpro')
  ro = 0.0_R8
  DO is=0,ns-1
    ro = ro + mp*am(is)*na(:, is)
  END DO
  DO is=0,st_ext%ns-1
    ro = ro + mp*st_ext%am(is)*st_ext%na(:, is)
  END DO
!$$$  call subend ()
  RETURN
END SUBROUTINE B2XPRO_NODIFF_NODIFF

