      subroutine sysend
      use b2mod_types
      implicit none
*     ------------------------------------------------------------------
*     SYSEND performs any system dependent calls that may be required
*     at the finish of program execution.
*!!   This routine may contain system dependencies.
*     ------------------------------------------------------------------
      return
*     ------------------------------------------------------------------
      end subroutine sysend
