      subroutine sysini
      use b2mod_types
      implicit none
*     ------------------------------------------------------------------
*     SYSINI performs any system dependent calls that may be required
*     at the start of program execution.
*!!   This routine may contain system dependencies.
*     ------------------------------------------------------------------
      return
*     ------------------------------------------------------------------
      end subroutine sysini
