!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 13 Feb 2024 17:09
!
!  Differentiation of b2nppo in reverse (adjoint) mode (with options context noISIZE r8):
!   gradient     of useful results: *(dv.fch) *(dv.conc) *(dv.respo)
!                *(dv.corpo) *(dv.ne) *(sr.sch) *(pl.po) *(pl.te)
!   with respect to varying inputs: *(dv.fch) *(dv.conc) *(dv.respo)
!                *(dv.corpo) *(dv.ne) *(sr.sch) *(pl.po) *(pl.te)
!   Plus diff mem management of: dv.fch:in dv.conc:in dv.respo:in
!                dv.corpo:in dv.ne:in geo.vxvol:in sr.sch:in pl.po:in
!                pl.te:in
!
!
!
!
!
!
!
!
!
!
!
!-----------------------------------------------------------------------
!.specification
!
!srv 22.05.18
SUBROUTINE B2NPPO_B(ncv, nfc, nvx, nregionv, solving, solvereg, itcnt, &
& rxf, switch, switchb, geo, geob, mpg, mpgb, pl, plb, dv, dvb, sr, srb&
& , ierr)
  USE B2MOD_TYPES
  USE B2MOD_CONSTANTS
  USE B2MOD_B2CMPA_DIFF
  USE B2MOD_SWITCHES_DIFF
  USE B2US_GEO_DIFF
  USE B2US_MAP_DIFF
  USE B2US_PLASMA_DIFF
  USE B2MOD_AD_DIFF, ONLY : ncall_b2nppo
! csc The following are not necessary for computation but are needed
!     for adjoint AD to avoid side-effect variables
  USE B2MOD_AD_DIFF, ONLY : ncall_b2uspo, my_out_folder, ncall_b2ursd
  USE B2MOD_SUBSYS
  IMPLICIT NONE
!   ..input arguments (unchanged on exit)
  INTEGER :: ncv, nfc, nvx, nregionv, itcnt
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(SWITCHES) :: switchb
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(GEOMETRY_DIFF) :: geob
  TYPE(MAPPING), INTENT(IN) :: mpg
  TYPE(MAPPING_DIFF) :: mpgb
  REAL(kind=r8) :: rxf
!srv 22.05.18
  LOGICAL :: solving, solvereg(0:nregionv)
!   ..input/output arguments
  TYPE(B2PLASMA), INTENT(INOUT) :: pl
  TYPE(B2PLASMA_DIFF), INTENT(INOUT) :: plb
  TYPE(B2DERIVATIVES), INTENT(INOUT) :: dv
  TYPE(B2DERIVATIVES), INTENT(INOUT) :: dvb
  TYPE(B2SOURCE), INTENT(INOUT) :: sr
  TYPE(B2SOURCE), INTENT(INOUT) :: srb
!   ..output arguments (unspecified on entry)
  INTEGER :: ierr
!   ..common blocks
!-----------------------------------------------------------------------
!.documentation
!
!  1. purpose
!
!     B2NPPO performs one iteration of a relaxation process for the
!     solution of the charge conservation equation, which governs the
!     electric potential.
!
!
!  3. description (see also routine b2cdca)
!
!     For a detailed description of the equations and the method of
!     solution, see the references cited in the main program unit.
!
!     This routine performs one inner iteration for the equation that
!     governs the electric potential po.
!     An outline of the procedure follows.
!     ..compute residual
!     ..compute correction
!     ..apply correction
!
!-----------------------------------------------------------------------
!.declarations
!
!   ..local variables
  INTEGER :: icv
  REAL(kind=r8) :: aa(mpg%ncmxnv), wrk0(ncv), wrk
  REAL(kind=r8) :: aab(mpg%ncmxnv)
  REAL(kind=r8), SAVE :: b2nppo_restr_po=0.0_R8
!   ..procedures
  EXTERNAL XERTST
  EXTERNAL B2XVSG, B2URSD_NODIFF, B2USPO_NODIFF, B2UPPO
  EXTERNAL B2URSD_B, B2USPO_B, B2UPPO_B
  INTRINSIC ANY
  INTRINSIC ABS
  INTRINSIC SIGN
  REAL(kind=r8) :: abs0
  REAL(kind=r8) :: abs1
  REAL(kind=r8) :: abs2
  REAL(kind=r8) :: temp
  INTEGER*4 :: branch
!   ..initialisation
!
!-----------------------------------------------------------------------
!.computation
!
! ..preliminaries
!   ..subprogram start-up calls
!   ..test nCv, nFc
!   ..test rxf
!   ..read switches
  IF (ncall_b2nppo .EQ. 0) CALL IPGETR('b2nppo_restr_po', &
&                                b2nppo_restr_po)
!srv 22.05.18
!
! ..main computation
!   ..compute residual
  IF ((solving .AND. ANY(solvereg(0:nregionv))) .OR. switch%&
&     get_residuals .EQ. 1) THEN
!srv 22.05.18
    CALL B2URSD_NODIFF(ncv, nfc, mpg, dv%ne, pl%po, sr%sch, dv%fch, dv%&
&                respo)
    CALL PUSHCONTROL1B(0)
  ELSE
    CALL PUSHCONTROL1B(1)
  END IF
!srv 22.05.18
!-rfs      write(6,*) 'ix=20, iy=-1, po ',po(20,-1), po(21,-1)
!-rfs      write(6,*) 'ix=20, iy=-1, sch ',
!-rfs     .  sch(20,-1,0), sch(20,-1,1),
!-rfs     .  sch(20,-1,2), sch(20,-1,3)
!-rfs      write(6,*) 'ix=20, iy=-1, fch, respo',
!-rfs     .  fch(20,-1,0), fch(20,-1,1),
!-rfs     .  fch(20,0,1), respo(20,-1)
!-rfs      write(6,*) 'ix=21, iy=-1, fch, respo',
!-rfs     .  fch(21,-1,0), fch(21,-1,1),
!-rfs     .  fch(21,0,1), respo(21,-1)
!   ..compute correction
  IF (solving .AND. ANY(solvereg(0:nregionv))) THEN
!srv 22.05.18
    CALL PUSHREAL8ARRAY(dv%respo, r8*SIZE(dv%respo, 1)/8)
    CALL B2USPO_NODIFF(ncv, nfc, nvx, nregionv, solvereg, itcnt, switch&
&                , geo, mpg, dv%ne, pl%te, dv%conc, sr%sch, dv%respo, dv&
&                %corpo, aa, 'b2nppo')
!   ..apply correction
    CALL PUSHREAL8ARRAY(pl%po, r8*SIZE(pl%po, 1)/8)
    CALL B2UPPO(ncv, rxf, dv%corpo, pl%po)
    IF (b2nppo_restr_po .NE. 0.0_R8) THEN
      DO icv=1,mpg%ncv
        IF (mpg%cvonclosedsurface(icv)) THEN
          CALL PUSHCONTROL3B(0)
        ELSE IF (b2nppo_restr_po .GT. 0.0_R8) THEN
          IF (qe*pl%po(icv) .GE. 0.) THEN
            abs0 = qe*pl%po(icv)
          ELSE
            abs0 = -(qe*pl%po(icv))
          END IF
          IF (abs0/pl%te(icv) .GT. b2nppo_restr_po) THEN
            CALL PUSHREAL8(pl%po(icv), r8/8)
            pl%po(icv) = SIGN(b2nppo_restr_po*pl%te(icv)/qe, pl%po(icv))
            CALL PUSHCONTROL3B(4)
          ELSE
            CALL PUSHCONTROL3B(3)
          END IF
        ELSE
          IF (qe*pl%po(icv) .GE. 0.) THEN
            abs1 = qe*pl%po(icv)
          ELSE
            abs1 = -(qe*pl%po(icv))
          END IF
          IF (b2nppo_restr_po .GE. 0.) THEN
            abs2 = b2nppo_restr_po
          ELSE
            abs2 = -b2nppo_restr_po
          END IF
          IF (abs1/pl%te(icv) .GT. abs2 .AND. pl%po(icv) .LT. 0.0_R8) &
&         THEN
            CALL PUSHREAL8(pl%po(icv), r8/8)
            pl%po(icv) = SIGN(b2nppo_restr_po*pl%te(icv)/qe, pl%po(icv))
            CALL PUSHCONTROL3B(2)
          ELSE
            CALL PUSHCONTROL3B(1)
          END IF
        END IF
      END DO
      DO icv=mpg%ncv,1,-1
        CALL POPCONTROL3B(branch)
        IF (branch .GE. 2) THEN
          IF (branch .EQ. 2) THEN
            CALL POPREAL8(pl%po(icv), r8/8)
            temp = b2nppo_restr_po*pl%te(icv)/qe
            plb%te(icv) = plb%te(icv) + b2nppo_restr_po*SIGN(1.d0, temp*&
&             pl%po(icv))*plb%po(icv)/qe
            plb%po(icv) = 0.D0
          ELSE IF (branch .NE. 3) THEN
            CALL POPREAL8(pl%po(icv), r8/8)
            temp = b2nppo_restr_po*pl%te(icv)/qe
            plb%te(icv) = plb%te(icv) + b2nppo_restr_po*SIGN(1.d0, temp*&
&             pl%po(icv))*plb%po(icv)/qe
            plb%po(icv) = 0.D0
          END IF
        END IF
      END DO
    END IF
    CALL POPREAL8ARRAY(pl%po, r8*SIZE(pl%po, 1)/8)
    CALL B2UPPO_B(ncv, rxf, dv%corpo, dvb%corpo, pl%po, plb%po)
    CALL POPREAL8ARRAY(dv%respo, r8*SIZE(dv%respo, 1)/8)
    CALL B2USPO_B(ncv, nfc, nvx, nregionv, solvereg, itcnt, switch, geo&
&           , mpg, mpgb, dv%ne, dvb%ne, pl%te, plb%te, dv%conc, dvb%conc&
&           , sr%sch, srb%sch, dv%respo, dvb%respo, dv%corpo, dvb%corpo&
&           , aa, aab, 'b2nppo')
  END IF
  CALL POPCONTROL1B(branch)
  IF (branch .EQ. 0) THEN
    CALL B2URSD_B(ncv, nfc, mpg, dv%ne, dvb%ne, pl%po, plb%po, sr%sch, &
&           srb%sch, dv%fch, dvb%fch, dv%respo, dvb%respo)
    dvb%respo = 0.D0
  END IF
END SUBROUTINE B2NPPO_B

!
!
!
!
!
!
!
!
!
!
!
!-----------------------------------------------------------------------
!.specification
!
!srv 22.05.18
SUBROUTINE B2NPPO_NODIFF(ncv, nfc, nvx, nregionv, solving, solvereg, &
& itcnt, rxf, switch, geo, mpg, pl, dv, sr, ierr)
  USE B2MOD_TYPES
  USE B2MOD_CONSTANTS
  USE B2MOD_B2CMPA_DIFF
  USE B2MOD_SWITCHES_DIFF
  USE B2US_GEO_DIFF
  USE B2US_MAP_DIFF
  USE B2US_PLASMA_DIFF
  USE B2MOD_AD_DIFF, ONLY : ncall_b2nppo
! csc The following are not necessary for computation but are needed
!     for adjoint AD to avoid side-effect variables
  USE B2MOD_AD_DIFF, ONLY : ncall_b2uspo, my_out_folder, ncall_b2ursd
  USE B2MOD_SUBSYS
  IMPLICIT NONE
!   ..input arguments (unchanged on exit)
  INTEGER :: ncv, nfc, nvx, nregionv, itcnt
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(MAPPING), INTENT(IN) :: mpg
  REAL(kind=r8) :: rxf
!srv 22.05.18
  LOGICAL :: solving, solvereg(0:nregionv)
!   ..input/output arguments
  TYPE(B2PLASMA), INTENT(INOUT) :: pl
  TYPE(B2DERIVATIVES), INTENT(INOUT) :: dv
  TYPE(B2SOURCE), INTENT(INOUT) :: sr
!   ..output arguments (unspecified on entry)
  INTEGER :: ierr
!   ..common blocks
!-----------------------------------------------------------------------
!.documentation
!
!  1. purpose
!
!     B2NPPO performs one iteration of a relaxation process for the
!     solution of the charge conservation equation, which governs the
!     electric potential.
!
!
!  3. description (see also routine b2cdca)
!
!     For a detailed description of the equations and the method of
!     solution, see the references cited in the main program unit.
!
!     This routine performs one inner iteration for the equation that
!     governs the electric potential po.
!     An outline of the procedure follows.
!     ..compute residual
!     ..compute correction
!     ..apply correction
!
!-----------------------------------------------------------------------
!.declarations
!
!   ..local variables
  INTEGER :: icv
  REAL(kind=r8) :: aa(mpg%ncmxnv), wrk0(ncv), wrk
  REAL(kind=r8), SAVE :: b2nppo_restr_po=0.0_R8
!   ..procedures
  EXTERNAL XERTST
  EXTERNAL B2XVSG, B2URSD_NODIFF, B2USPO_NODIFF, B2UPPO
  INTRINSIC ANY
  INTRINSIC ABS
  INTRINSIC SIGN
  REAL(kind=r8) :: abs0
  REAL(kind=r8) :: abs1
  REAL(kind=r8) :: abs2
!   ..initialisation
!
!-----------------------------------------------------------------------
!.computation
!
! ..preliminaries
!   ..subprogram start-up calls
  CALL SUBINI('b2nppo')
!   ..test nCv, nFc
  CALL XERTST(0 .LT. ncv .AND. 0 .LT. nfc, 'faulty argument nCv, nFc')
!   ..test rxf
  CALL XERTST(0.0_R8 .LE. rxf .AND. rxf .LE. 1.0_R8, &
&       'faulty argument rxf')
!   ..read switches
  IF (ncall_b2nppo .EQ. 0) CALL IPGETR('b2nppo_restr_po', &
&                                b2nppo_restr_po)
!   ..extensive tests on first few calls
  IF (ncall_b2nppo .LT. 3) THEN
!    ..test sign of ne, te
    CALL B2XVSG(ncv, dv%ne, 1, 'ne', '.gt.')
    CALL B2XVSG(ncv, pl%te, 1, 'te', '.gt.')
!    ..test sign of sch
    CALL B2XVSG(ncv, sr%sch(1, 1), 1, 'sch1', '.le.')
    CALL B2XVSG(ncv, sr%sch(1, 3), 1, 'sch3', '.le.')
  END IF
!srv 22.05.18
!
! ..main computation
!   ..compute residual
  IF ((solving .AND. ANY(solvereg(0:nregionv))) .OR. switch%&
&     get_residuals .EQ. 1) THEN
!srv 22.05.18
    CALL B2URSD_NODIFF(ncv, nfc, mpg, dv%ne, pl%po, sr%sch, dv%fch, dv%&
&                respo)
  END IF
!srv 22.05.18
!-rfs      write(6,*) 'ix=20, iy=-1, po ',po(20,-1), po(21,-1)
!-rfs      write(6,*) 'ix=20, iy=-1, sch ',
!-rfs     .  sch(20,-1,0), sch(20,-1,1),
!-rfs     .  sch(20,-1,2), sch(20,-1,3)
!-rfs      write(6,*) 'ix=20, iy=-1, fch, respo',
!-rfs     .  fch(20,-1,0), fch(20,-1,1),
!-rfs     .  fch(20,0,1), respo(20,-1)
!-rfs      write(6,*) 'ix=21, iy=-1, fch, respo',
!-rfs     .  fch(21,-1,0), fch(21,-1,1),
!-rfs     .  fch(21,0,1), respo(21,-1)
!   ..compute correction
  IF (solving .AND. ANY(solvereg(0:nregionv))) THEN
!srv 22.05.18
    CALL B2USPO_NODIFF(ncv, nfc, nvx, nregionv, solvereg, itcnt, switch&
&                , geo, mpg, dv%ne, pl%te, dv%conc, sr%sch, dv%respo, dv&
&                %corpo, aa, 'b2nppo')
!   ..apply correction
    CALL B2UPPO(ncv, rxf, dv%corpo, pl%po)
    IF (b2nppo_restr_po .NE. 0.0_R8) THEN
      DO icv=1,mpg%ncv
        IF (.NOT.mpg%cvonclosedsurface(icv)) THEN
          IF (b2nppo_restr_po .GT. 0.0_R8) THEN
            IF (qe*pl%po(icv) .GE. 0.) THEN
              abs0 = qe*pl%po(icv)
            ELSE
              abs0 = -(qe*pl%po(icv))
            END IF
            IF (abs0/pl%te(icv) .GT. b2nppo_restr_po) THEN
              wrk = pl%po(icv)
              pl%po(icv) = SIGN(b2nppo_restr_po*pl%te(icv)/qe, pl%po(icv&
&               ))
              WRITE(*, *) 'Applied po/Te ratio limit', icv, wrk, pl%po(&
&             icv)
            END IF
          ELSE
            IF (qe*pl%po(icv) .GE. 0.) THEN
              abs1 = qe*pl%po(icv)
            ELSE
              abs1 = -(qe*pl%po(icv))
            END IF
            IF (b2nppo_restr_po .GE. 0.) THEN
              abs2 = b2nppo_restr_po
            ELSE
              abs2 = -b2nppo_restr_po
            END IF
            IF (abs1/pl%te(icv) .GT. abs2 .AND. pl%po(icv) .LT. 0.0_R8) &
&           THEN
              wrk = pl%po(icv)
              pl%po(icv) = SIGN(b2nppo_restr_po*pl%te(icv)/qe, pl%po(icv&
&               ))
              WRITE(*, *) 'Applied po/Te ratio limit', icv, wrk, pl%po(&
&             icv)
            END IF
          END IF
        END IF
      END DO
    END IF
  END IF
!srv 11.09.09 }
!
  IF (switch%b2nppo_iout .EQ. 1 .OR. switch%iout_b2wdat .EQ. 4) THEN
!srv 11.09.09 {
!       call my_out_us(70,nCv,0,pl%te,'b2nppo_te')
!       call my_out_us(70,nCv,0,dv%ne,'b2nppo_ne')
    CALL MY_OUT_US(70, ncv, 0, pl%po, 'b2nppo_po')
    CALL MY_OUT_US(70, ncv, 0, dv%respo, 'b2nppo_respo')
    CALL MY_OUT_US(70, nfc, 1, dv%fch(1, 0), 'b2nppo_fch_th')
    CALL MY_OUT_US(70, nfc, 1, dv%fch(1, 1), 'b2nppo_fch_r')
!       call my_out_us(70,nCv,0,sr%sch(1,0),'b2nppo_sch0')
!       call my_out_us(70,nCv,0,sr%sch(1,1),'b2nppo_sch1')
!       call my_out_us(70,nCv,0,sr%sch(1,2),'b2nppo_sch2')
!       call my_out_us(70,nCv,0,sr%sch(1,3),'b2nppo_sch3')
    wrk0 = sr%sch(:, 0) + sr%sch(:, 1)*pl%po + sr%sch(:, 2)*dv%ne + sr%&
&     sch(:, 3)*dv%ne*pl%po
    CALL MY_OUT_US(70, ncv, 0, wrk0, 'b2nppo_sch')
  END IF
!
!   ..set error parameter and return
!     (at present all errors cause an abort through xertst)
  ierr = 0
! ..return
  ncall_b2nppo = ncall_b2nppo + 1
  CALL SUBEND()
  RETURN
!
!-----------------------------------------------------------------------
!.end b2nppo
!
END SUBROUTINE B2NPPO_NODIFF

