!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 13 Feb 2024 17:09
!
!  Differentiation of b2nxdp in reverse (adjoint) mode (with options context noISIZE r8):
!   gradient     of useful results: ne nep delpo te
!   with respect to varying inputs: ne nep delpo te
!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE B2NXDP_B(ncv, mpg, solvereg, qe, te, teb, nep, nepb, ne, neb&
& , delpo, delpob)
  USE B2MOD_TYPES
  USE B2US_MAP_DIFF
! csc The following are not necessary for computation but are needed
!     for adjoint AD to avoid side-effect variables
  USE B2MOD_AD_DIFF, ONLY : ncall_b2nxdp
  USE B2MOD_SUBSYS
  IMPLICIT NONE
  INTEGER :: ncv
  TYPE(MAPPING), INTENT(IN) :: mpg
  REAL(kind=r8) :: qe, te(ncv), nep(ncv), ne(ncv), delpo(ncv)
  REAL(kind=r8) :: teb(ncv), nepb(ncv), neb(ncv), delpob(ncv)
  LOGICAL :: solvereg(0:mpg%nnreg(0))
!     ------------------------------------------------------------------
!     B2NXDP computes the correction to the electric potential following
!     an update to the electron density.
!     ------------------------------------------------------------------
  INTEGER :: icv, ireg
  EXTERNAL XERTST
  EXTERNAL B2XVSG
!   ..initialisation
!     ------------------------------------------------------------------
!   ..extensive tests on first few calls
  REAL(kind=r8) :: temp
  REAL(kind=r8) :: tempb
  REAL(kind=r8) :: tempb0
  INTEGER*4 :: branch
!   ..compute delpo
  DO icv=1,ncv
    ireg = mpg%cvreg(icv)
    IF (solvereg(ireg)) THEN
      CALL PUSHCONTROL1B(1)
    ELSE
      CALL PUSHCONTROL1B(0)
    END IF
  END DO
  DO icv=ncv,1,-1
    CALL POPCONTROL1B(branch)
    IF (branch .EQ. 0) THEN
      delpob(icv) = 0.D0
    ELSE
      temp = qe*(ne(icv)+nep(icv))
      tempb = 2.0_R8*delpob(icv)/temp
      delpob(icv) = 0.D0
      teb(icv) = teb(icv) + (ne(icv)-nep(icv))*tempb
      tempb0 = -(qe*te(icv)*(ne(icv)-nep(icv))*tempb/temp)
      neb(icv) = neb(icv) + te(icv)*tempb + tempb0
      nepb(icv) = nepb(icv) + tempb0 - te(icv)*tempb
    END IF
  END DO
END SUBROUTINE B2NXDP_B

!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE B2NXDP_NODIFF(ncv, mpg, solvereg, qe, te, nep, ne, delpo)
  USE B2MOD_TYPES
  USE B2US_MAP_DIFF
! csc The following are not necessary for computation but are needed
!     for adjoint AD to avoid side-effect variables
  USE B2MOD_AD_DIFF, ONLY : ncall_b2nxdp
  USE B2MOD_SUBSYS
  IMPLICIT NONE
  INTEGER :: ncv
  TYPE(MAPPING), INTENT(IN) :: mpg
  REAL(kind=r8) :: qe, te(ncv), nep(ncv), ne(ncv), delpo(ncv)
  LOGICAL :: solvereg(0:mpg%nnreg(0))
!     ------------------------------------------------------------------
!     B2NXDP computes the correction to the electric potential following
!     an update to the electron density.
!     ------------------------------------------------------------------
  INTEGER :: icv, ireg
  EXTERNAL XERTST
  EXTERNAL B2XVSG
!   ..initialisation
!     ------------------------------------------------------------------
  CALL SUBINI('b2nxdp')
  CALL XERTST(0 .LT. ncv, 'faulty argument nCv')
  CALL XERTST(0.0_R8 .LT. qe, 'faulty argument qe')
!   ..extensive tests on first few calls
  IF (ncall_b2nxdp .LT. 3) THEN
    CALL B2XVSG(ncv, te, 1, 'te', '.gt.')
    CALL B2XVSG(ncv, nep, 1, 'nep', '.gt.')
    CALL B2XVSG(ncv, ne, 1, 'ne', '.gt.')
  END IF
!   ..compute delpo
  DO icv=1,ncv
    ireg = mpg%cvreg(icv)
    IF (solvereg(ireg)) THEN
      delpo(icv) = te(icv)/qe*(ne(icv)-nep(icv))*2.0_R8/(ne(icv)+nep(icv&
&       ))
    ELSE
      delpo(icv) = 0.0_R8
    END IF
  END DO
  ncall_b2nxdp = ncall_b2nxdp + 1
  CALL SUBEND()
  RETURN
!     ------------------------------------------------------------------
END SUBROUTINE B2NXDP_NODIFF

