!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 13 Feb 2024 17:09
!
!  Differentiation of b2tepsch in reverse (adjoint) mode (with options context noISIZE r8):
!   gradient     of useful results: ne floe cddi fhepsch cone te
!   with respect to varying inputs: ne cddi te
!   Plus diff mem management of: geo.fchc:in geo.fcht:in geo.fcqalf:in
!                geo.fcqbet:in geo.vxvol:in
!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE B2TEPSCH_B(ncv, nfc, nvx, ns, switch, geo, geob, mpg, mpgb, &
& facdrift, cddi, cddib, te, teb, ne, neb, floe, floeb, cone, coneb, &
& fhepsch, fhepschb)
  USE B2MOD_TYPES
  USE B2MOD_B2CMPA_DIFF
  USE B2MOD_SWITCHES_DIFF
  USE B2US_GEO_DIFF
  USE B2US_MAP_DIFF
  USE B2MOD_SUBSYS
  IMPLICIT NONE
!   ..input arguments (unchanged on exit)
  INTEGER :: ncv, nfc, nvx, ns
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(GEOMETRY_DIFF) :: geob
  TYPE(MAPPING), INTENT(IN) :: mpg
  TYPE(MAPPING_DIFF) :: mpgb
  REAL(kind=r8) :: facdrift(nfc), cddi(nfc, 0:1, 0:ns-1), te(ncv), ne(&
& ncv)
  REAL(kind=r8) :: cddib(nfc, 0:1, 0:ns-1), teb(ncv), neb(ncv)
!   ..output arguments (unspecified on entry)
  REAL(kind=r8) :: floe(nfc, 0:1), cone(nfc, 0:1, 0:2), fhepsch(nfc, 0:1&
& )
  REAL(kind=r8) :: floeb(nfc, 0:1), coneb(nfc, 0:1, 0:2), fhepschb(nfc, &
& 0:1)
!-----------------------------------------------------------------------
!.documentation
!
!  1. purpose
!
!     B2ETPSCH computes the X and Y components of the Pfirsch-Schlueter
!     heat flux.
!
!  8. further comments
!
!-----------------------------------------------------------------------
!.declarations
!
!   ..local variables
  INTEGER :: ifc, is
  INTEGER, SAVE :: ncall=0
  REAL(kind=r8) :: facdriftm, nete(ncv), nete2(ncv), netev(nvx), nete2v(&
& nvx), dnete2(nfc, 0:1), floe0(nfc, 0:1), cone0(nfc, 0:1), cddi_eff(nfc&
& , 0:1), dumm0(nfc, 0:1)
  REAL(kind=r8) :: neteb(ncv), nete2b(ncv), netevb(nvx), nete2vb(nvx), &
& dnete2b(nfc, 0:1), floe0b(nfc, 0:1), cone0b(nfc, 0:1), cddi_effb(nfc, &
& 0:1), dumm0b(nfc, 0:1)
  INTRINSIC MAXVAL
  INTRINSIC NINT
  REAL(kind=r8), DIMENSION(nfc) :: tempb
  REAL(kind=r8) :: tempb0
  REAL(kind=r8) :: tempb1
  INTEGER*4 :: branch
!-----------------------------------------------------------------------
!.computation
!
! ..preliminaries
!   ..subprogram start-up calls
!   ..test nCv, nFc
!
!   ..set dummy arrays
  dumm0 = 0.0_R8
!
!srv 13.10.06
!srv 02.01.07
  facdriftm = MAXVAL(facdrift)
  IF (facdriftm .NE. 0.0_R8) THEN
!srv 12.05.11
    DO is=0,ns-1
      IF (NINT(zn(is)) .EQ. 1 .AND. NINT(zamax(is)) .EQ. 1) THEN
!srv 12.05.11
!
!   ..precompute face and vertex values of nete2
        CALL PUSHREAL8ARRAY(nete, r8*ncv/8)
        nete = ne*te
        nete2 = ne*te*te
        CALL INTVERTEX_FWD(ncv, nvx, mpg, geo%vxvol, nete, netev)
        CALL INTVERTEX_FWD(ncv, nvx, mpg, geo%vxvol, nete2, nete2v)
        CALL DIFF_FWD(ncv, nfc, nvx, 1, geo, geob, mpg, mpgb, nete2, &
&               nete2v, dnete2)
!
!   ..compute P.Sch heat flux
!     ..linearization coefficients for P.Sch flows
        CALL PUSHREAL8ARRAY(cddi_eff(:, 0), r8*nfc/8)
        cddi_eff(:, 0) = 5.0_R8*switch%fhepsch*facdrift*cddi(:, 1, is)
        CALL PUSHREAL8ARRAY(cddi_eff(:, 1), r8*nfc/8)
        cddi_eff(:, 1) = -(5.0_R8*switch%fhepsch*facdrift*cddi(:, 0, is)&
&         )
        CALL CALCCOEF_FWD(ncv, nfc, nvx, 0, geo, dumm0, cddi_eff, floe0&
&                   , cone0)
        CALL PUSHCONTROL1B(1)
      ELSE
        CALL PUSHCONTROL1B(0)
      END IF
    END DO
    dnete2b = 0.D0
    cone0b = 0.D0
    cddi_effb = 0.D0
    DO is=ns-1,0,-1
      CALL POPCONTROL1B(branch)
      IF (branch .NE. 0) THEN
        netevb = 0.D0
        neteb = 0.D0
        DO ifc=nfc,1,-1
          cone0b(ifc, 1) = cone0b(ifc, 1) + (netev(mpg%fcvx(ifc, 1))+&
&           netev(mpg%fcvx(ifc, 2)))*0.5_R8*coneb(ifc, 1, 0) - (netev(&
&           mpg%fcvx(ifc, 2))-netev(mpg%fcvx(ifc, 1)))*floeb(ifc, 1)
          tempb1 = cone0(ifc, 1)*0.5_R8*coneb(ifc, 1, 0)
          tempb0 = -(floe0(ifc, 1)*0.25_R8*coneb(ifc, 1, 0))
          coneb(ifc, 1, 0) = 0.D0
          netevb(mpg%fcvx(ifc, 2)) = netevb(mpg%fcvx(ifc, 2)) + tempb0
          netevb(mpg%fcvx(ifc, 1)) = netevb(mpg%fcvx(ifc, 1)) + tempb1 -&
&           tempb0
          netevb(mpg%fcvx(ifc, 2)) = netevb(mpg%fcvx(ifc, 2)) + tempb1
          cone0b(ifc, 0) = cone0b(ifc, 0) + (nete(mpg%fccv(ifc, 1))+nete&
&           (mpg%fccv(ifc, 2)))*0.5_R8*coneb(ifc, 0, 0) - (nete(mpg%fccv&
&           (ifc, 2))-nete(mpg%fccv(ifc, 1)))*floeb(ifc, 0)
          tempb1 = cone0(ifc, 0)*0.5_R8*coneb(ifc, 0, 0)
          tempb0 = -(floe0(ifc, 0)*0.25_R8*coneb(ifc, 0, 0))
          coneb(ifc, 0, 0) = 0.D0
          neteb(mpg%fccv(ifc, 2)) = neteb(mpg%fccv(ifc, 2)) + tempb0
          neteb(mpg%fccv(ifc, 1)) = neteb(mpg%fccv(ifc, 1)) + tempb1 - &
&           tempb0
          neteb(mpg%fccv(ifc, 2)) = neteb(mpg%fccv(ifc, 2)) + tempb1
          tempb1 = floe0(ifc, 1)*0.5_R8*floeb(ifc, 1)
          tempb0 = -(cone0(ifc, 1)*floeb(ifc, 1))
          floeb(ifc, 1) = 0.D0
          netevb(mpg%fcvx(ifc, 2)) = netevb(mpg%fcvx(ifc, 2)) + tempb0
          netevb(mpg%fcvx(ifc, 1)) = netevb(mpg%fcvx(ifc, 1)) + tempb1 -&
&           tempb0
          netevb(mpg%fcvx(ifc, 2)) = netevb(mpg%fcvx(ifc, 2)) + tempb1
          tempb0 = floe0(ifc, 0)*0.5_R8*floeb(ifc, 0)
          tempb1 = -(cone0(ifc, 0)*floeb(ifc, 0))
          floeb(ifc, 0) = 0.D0
          neteb(mpg%fccv(ifc, 2)) = neteb(mpg%fccv(ifc, 2)) + tempb1
          neteb(mpg%fccv(ifc, 1)) = neteb(mpg%fccv(ifc, 1)) + tempb0 - &
&           tempb1
          neteb(mpg%fccv(ifc, 2)) = neteb(mpg%fccv(ifc, 2)) + tempb0
        END DO
        tempb = switch%fhepsch*2.5_R8*facdrift*fhepschb(:, 1)
        dumm0b = 0.D0
        floe0b = 0.D0
        CALL CALCCOEF_BWD(ncv, nfc, nvx, 0, geo, dumm0, dumm0b, cddi_eff&
&                   , cddi_effb, floe0, floe0b, cone0, cone0b)
        CALL POPREAL8ARRAY(cddi_eff(:, 1), r8*nfc/8)
        CALL POPREAL8ARRAY(cddi_eff(:, 0), r8*nfc/8)
        cddib(:, 1, is) = cddib(:, 1, is) + switch%fhepsch*5.0_R8*&
&         facdrift*cddi_effb(:, 0) + dnete2(:, 0)*tempb
        cddi_effb(:, 0) = 0.D0
        fhepschb(:, 1) = 0.D0
        dnete2b(:, 0) = dnete2b(:, 0) + cddi(:, 1, is)*tempb
        tempb = -(switch%fhepsch*2.5_R8*facdrift*fhepschb(:, 0))
        cddib(:, 0, is) = cddib(:, 0, is) + dnete2(:, 1)*tempb - switch%&
&         fhepsch*5.0_R8*facdrift*cddi_effb(:, 1)
        cddi_effb(:, 1) = 0.D0
        fhepschb(:, 0) = 0.D0
        dnete2b(:, 1) = dnete2b(:, 1) + cddi(:, 0, is)*tempb
        nete2 = ne*te*te
        nete2b = 0.D0
        nete2vb = 0.D0
        CALL DIFF_BWD(ncv, nfc, nvx, 1, geo, geob, mpg, mpgb, nete2, &
&               nete2b, nete2v, nete2vb, dnete2, dnete2b)
        CALL INTVERTEX_BWD(ncv, nvx, mpg, geo%vxvol, nete2, nete2b, &
&                    nete2v, nete2vb)
        CALL INTVERTEX_BWD(ncv, nvx, mpg, geo%vxvol, nete, neteb, netev&
&                    , netevb)
        neb = neb + te**2*nete2b + te*neteb
        teb = teb + 2*te*ne*nete2b + ne*neteb
        CALL POPREAL8ARRAY(nete, r8*ncv/8)
      END IF
    END DO
  END IF
END SUBROUTINE B2TEPSCH_B

!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE B2TEPSCH_NODIFF(ncv, nfc, nvx, ns, switch, geo, mpg, facdrift&
& , cddi, te, ne, floe, cone, fhepsch)
  USE B2MOD_TYPES
  USE B2MOD_B2CMPA_DIFF
  USE B2MOD_SWITCHES_DIFF
  USE B2US_GEO_DIFF
  USE B2US_MAP_DIFF
  USE B2MOD_SUBSYS
  IMPLICIT NONE
!   ..input arguments (unchanged on exit)
  INTEGER :: ncv, nfc, nvx, ns
  TYPE(SWITCHES), INTENT(IN) :: switch
  TYPE(GEOMETRY), INTENT(IN) :: geo
  TYPE(MAPPING), INTENT(IN) :: mpg
  REAL(kind=r8) :: facdrift(nfc), cddi(nfc, 0:1, 0:ns-1), te(ncv), ne(&
& ncv)
!   ..output arguments (unspecified on entry)
  REAL(kind=r8) :: floe(nfc, 0:1), cone(nfc, 0:1, 0:2), fhepsch(nfc, 0:1&
& )
!-----------------------------------------------------------------------
!.documentation
!
!  1. purpose
!
!     B2ETPSCH computes the X and Y components of the Pfirsch-Schlueter
!     heat flux.
!
!  8. further comments
!
!-----------------------------------------------------------------------
!.declarations
!
!   ..local variables
  INTEGER :: ifc, is
  INTEGER, SAVE :: ncall=0
  REAL(kind=r8) :: facdriftm, nete(ncv), nete2(ncv), netev(nvx), nete2v(&
& nvx), dnete2(nfc, 0:1), floe0(nfc, 0:1), cone0(nfc, 0:1), cddi_eff(nfc&
& , 0:1), dumm0(nfc, 0:1)
  INTRINSIC MAXVAL
  INTRINSIC NINT
!-----------------------------------------------------------------------
!.computation
!
! ..preliminaries
!   ..subprogram start-up calls
  CALL SUBINI('b2tepsch')
!   ..test nCv, nFc
  CALL XERTST(0 .LT. ncv .AND. 0 .LT. nfc, 'faulty argument nCv, nFc')
!
!   ..set dummy arrays
  dumm0 = 0.0_R8
!
!srv 13.10.06
  fhepsch = 0.0_R8
!srv 02.01.07
  cone = 0.0_R8
  floe = 0.0_R8
  facdriftm = MAXVAL(facdrift)
  IF (facdriftm .NE. 0.0_R8) THEN
!srv 12.05.11
    DO is=0,ns-1
      IF (NINT(zn(is)) .EQ. 1 .AND. NINT(zamax(is)) .EQ. 1) THEN
!srv 12.05.11
!
!   ..precompute face and vertex values of nete2
        nete = ne*te
        nete2 = ne*te*te
        CALL INTVERTEX_NODIFF(ncv, nvx, mpg, geo%vxvol, nete, netev)
        CALL INTVERTEX_NODIFF(ncv, nvx, mpg, geo%vxvol, nete2, nete2v)
        CALL DIFF_NODIFF(ncv, nfc, nvx, 1, geo, mpg, nete2, nete2v, &
&                  dnete2)
!
!   ..compute P.Sch heat flux
        fhepsch(:, 0) = -(2.5_R8*switch%fhepsch*facdrift*cddi(:, 0, is)*&
&         dnete2(:, 1))
        fhepsch(:, 1) = 2.5_R8*switch%fhepsch*facdrift*cddi(:, 1, is)*&
&         dnete2(:, 0)
!     ..linearization coefficients for P.Sch flows
        cddi_eff(:, 0) = 5.0_R8*switch%fhepsch*facdrift*cddi(:, 1, is)
        cddi_eff(:, 1) = -(5.0_R8*switch%fhepsch*facdrift*cddi(:, 0, is)&
&         )
        CALL CALCCOEF_NODIFF(ncv, nfc, nvx, 0, geo, dumm0, cddi_eff, &
&                      floe0, cone0)
        DO ifc=1,nfc
          floe(ifc, 0) = 0.5_R8*floe0(ifc, 0)*(nete(mpg%fccv(ifc, 1))+&
&           nete(mpg%fccv(ifc, 2))) - cone0(ifc, 0)*(nete(mpg%fccv(ifc, &
&           2))-nete(mpg%fccv(ifc, 1)))
          floe(ifc, 1) = 0.5_R8*floe0(ifc, 1)*(netev(mpg%fcvx(ifc, 1))+&
&           netev(mpg%fcvx(ifc, 2))) - cone0(ifc, 1)*(netev(mpg%fcvx(ifc&
&           , 2))-netev(mpg%fcvx(ifc, 1)))
!wdk      For now, directly add these contributions into cone(,,0),
!wdk      so they are directly added into the stencil.
!wdk      Might need to move back to cone(,,1) and dedicated treatment
!wdk      in b2ux9p if we decide to move away from inverse volume weighting
!wdk      to compute vertex values of drifts!
          cone(ifc, 0, 0) = 0.5_R8*cone0(ifc, 0)*(nete(mpg%fccv(ifc, 1))&
&           +nete(mpg%fccv(ifc, 2))) - 0.25_R8*floe0(ifc, 0)*(nete(mpg%&
&           fccv(ifc, 2))-nete(mpg%fccv(ifc, 1)))
          cone(ifc, 1, 0) = 0.5_R8*cone0(ifc, 1)*(netev(mpg%fcvx(ifc, 1)&
&           )+netev(mpg%fcvx(ifc, 2))) - 0.25_R8*floe0(ifc, 1)*(netev(&
&           mpg%fcvx(ifc, 2))-netev(mpg%fcvx(ifc, 1)))
        END DO
      END IF
    END DO
  END IF
! ..return
  ncall = ncall + 1
  CALL SUBEND()
  RETURN
!-----------------------------------------------------------------------
!.end b2tepsch
END SUBROUTINE B2TEPSCH_NODIFF

