!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 13 Feb 2024 17:09
!
!  Differentiation of b2xpnm in reverse (adjoint) mode (with options context noISIZE r8):
!   gradient     of useful results: na ne2m rz2
!   with respect to varying inputs: na ne2m rz2
!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE B2XPNM_B(ncv, ns, rz2, rz2b, am, na, nab, ne2m, ne2mb)
  USE B2MOD_TYPES
  IMPLICIT NONE
  INTEGER :: ncv, ns
  REAL(kind=r8) :: rz2(ncv, 0:ns-1), am(0:ns-1), na(ncv, 0:ns-1), ne2m(&
& ncv)
  REAL(kind=r8) :: rz2b(ncv, 0:ns-1), nab(ncv, 0:ns-1), ne2mb(ncv)
!     ------------------------------------------------------------------
!     B2XPNM computes the atom density weighted by rz2/am, ne2m:
!       ne2m() = (sum is :: (rz2(,is)/am(is))*na(,is)) .
!     ------------------------------------------------------------------
  INTEGER :: is
  EXTERNAL SFILL_NODIFF
  EXTERNAL SFILL_FWD, SFILL_BWD
  REAL(r8) :: dummydiffb
!     ------------------------------------------------------------------
!$$$  call subini ('b2xpnm')
  CALL SFILL_FWD(ncv, 0.0_R8, ne2m, ne2mb, 1)
  DO is=ns-1,0,-1
    rz2b(:, is) = rz2b(:, is) + na(:, is)*ne2mb/am(is)
    nab(:, is) = nab(:, is) + rz2(:, is)*ne2mb/am(is)
  END DO
  CALL SFILL_BWD(ncv, 0.0_R8, dummydiffb, ne2m, ne2mb, 1)
END SUBROUTINE B2XPNM_B

!
!
!
!
!
!
!
!
!
!
!
SUBROUTINE B2XPNM_NODIFF(ncv, ns, rz2, am, na, ne2m)
  USE B2MOD_TYPES
  IMPLICIT NONE
  INTEGER :: ncv, ns
  REAL(kind=r8) :: rz2(ncv, 0:ns-1), am(0:ns-1), na(ncv, 0:ns-1), ne2m(&
& ncv)
!     ------------------------------------------------------------------
!     B2XPNM computes the atom density weighted by rz2/am, ne2m:
!       ne2m() = (sum is :: (rz2(,is)/am(is))*na(,is)) .
!     ------------------------------------------------------------------
  INTEGER :: is
  EXTERNAL SFILL_NODIFF
!     ------------------------------------------------------------------
!$$$  call subini ('b2xpnm')
  CALL SFILL_NODIFF(ncv, 0.0_R8, ne2m, 1)
  DO is=0,ns-1
    ne2m = ne2m + rz2(:, is)/am(is)*na(:, is)
  END DO
!$$$  call subend ()
  RETURN
!     ------------------------------------------------------------------
END SUBROUTINE B2XPNM_NODIFF

