*-----------------------------------------------------------------------
*.specification

      subroutine b2ypdr (ninp, nout, nx, ny, ns)
      use b2mod_types
      use b2mod_rates
      use b2mod_version
      use b2mod_geo
      use b2mod_math
      use b2mod_work
      use b2mod_plasma
      use b2mod_indirect
      use b2mod_constants
      use b2mod_b2cmrc
      use b2mod_b2cmpa
      use b2mod_b2cmpt
      use b2mod_b2cmwg
      use b2mod_ppout
      use b2mod_geo_corner
      use b2mod_external
      use b2mod_ipmain
      use b2mod_lbfill
      use b2mod_subsys
      implicit none
*   ..input arguments (unchanged on exit)
      integer ninp(0:5), nout(0:2), nx, ny, ns
*   ..output arguments (unspecified on entry)
*     (none)
*   ..common blocks
*-----------------------------------------------------------------------
*.documentation
*
*  1. purpose
*
*     B2YPDR is a postprocessor for B2. It displays the plasma state,
*     making use also of the geometric information.
*
*
*  3. description (see also routine b2cdca)
*
*     This routine is a postprocessor for the B2 code. It reads the
*     result of a B2 calculation, and produces printed and graphical
*     summaries. Special purpose output may also be produced.
*
*
*  5. parameters (see also routine b2cdcv)
*
*     ninp - (0:5) integer array, input.
*     ninp specifies the input unit numbers as follows.
*     ninp(0): formatted; provides output control parameters.
*     ninp(1): un*formatted; provides the geometry.
*     ninp(2): un*formatted; provides the physics parameters.
*     ninp(3): un*formatted; provides the plasma state.
*     ninp(4): un*formatted; provides atomic rate data.
*     ninp(5): formatted; provides run switches.
*
*     nout - (0:2) integer array, input.
*     nout specifies the output unit numbers, as follows.
*     nout(0): formatted; provides printed output.
*     nout(1): graphical; provides graphical output.
*     nout(2): formatted; may provide special purpose output.
*
*     nx, ny - integer, input.
*     nx and ny specify the number of interior cells along the first
*     and the second coordinate, respectively. The total number of
*     cells is (nx+2)*(ny+2); they are indexed by (-1:nx,-1:ny).
*     It will hold that 0.le.nx and 0.le.ny.
*
*     ns - integer, input.
*     ns specifies the number of atomic species in the calculation.
*     The species are indexed by (0:ns-1).
*     It will hold that 1.le.ns.
*
*     (parameters in common:)
*
*-----------------------------------------------------------------------
*.declarations

*   ..common blocks
*   ..local variables
      integer is, iftp, iplot, idum(0:9), ismain, external_species
#ifdef WG_TODO
      real (kind=R8) ::
     *  rsa(-1:nx,-1:ny,0:ns-1), rra(-1:nx,-1:ny,0:ns-1),
     &  rqa(-1:nx,-1:ny,0:ns-1), rrd(-1:nx,-1:ny,0:ns-1),
     &  rbr(-1:nx,-1:ny,0:ns-1)
#endif
      character lblgm*120, lblcp*120, lblmn*120, lblrc*120, idout*80,
     &  id*8, cnamip*80, cvalip*80, line*500
*   ..initialisation
      save ismain, external_species
      data ismain/1/, external_species/0/
*   ..procedures
      logical streql, is_comment
      external xertst, xerrab, streql, gacwk,
     &  gdawk, cfruch, cfruin, ipgeti, is_comment
      external b2rugm, b2rups, b2rucp, b2wfgm, b2wfcp, b2wfps, b2xvps,
     &  b2wggm, b2wgps, b2wscp, b2wsps, b2ruzd, b2rurc, b2spel, b2sqel,
     &  b2xvcp, b2rfcp, b2rflb, b2xxid

*-----------------------------------------------------------------------
*.documentation-internal
*
*     The workspace array w is used as a stack for storage of dynamic
*     real*8 arrays. An array 'name' in w(0:*) will be stored starting at
*     location w(l'name').
*
*     The following common blocks have their outermost declaration in
*     this routine; they need not be preserved between calls.
*
*     /b2cmpa/ specifies basic physics parameters.
*      me, mp, ev, qe, eps0, mu0 - real*8 constant.
*     These parameters are included with /b2cmpa/.
*       me = electron mass (kg)
*       mp = proton mass (kg)
*       ev = 1 electron-Volt (Joule)
*       qe = elementary charge (Coulomb)
*       eps0 = vacuum dielectric permittivity (SI)
*       mu0 = vacuum magnetic permeability (SI)
*      nsdecl - integer constant.
*     nsdecl is an upper bound for the number of species (ns), and is
*     used in dimension specifications.
*      zamin, zamax, zn, am - (0:nsdecl-1) real*8 array.
*     For (is) in (0:ns-1), zn(is) specifies the nuclear charge of
*     species (is), am(is) specifies its atomic mass, and zamin(is) and
*     zamax(is) specify its atomic charge range. All are dimensionless.
*     It will hold that 0.le.zamin(is).le.zamax(is), 0.lt.zn(is) and
*     0.lt.am(is). It is required that neutral species not be bundled
*     with charged species.
*     For ns.le.is.lt.nsdecl, zamin(is), zamax(is), zn(is), am(is)
*     are undefined.
*
*   ..transport coefficients, parameters
*
*     /b2cmpt/ - common block.
*     (Note: the integer constant nsdecl, which comes with /b2cmpa/,
*     is used instead of (ns) in dimension specifications.)
*      cfdf0 - (0:7,0:ns-1) real*8 array.
*     cfdf0 contains some auxiliary coefficients. For 0.le.is.lt.ns,
*     the local expression
*       df0(,is) = cfdf0(0,is)+cfdf0(1,is)/(ni(,0)/1.0e20)+
*         cfdf0(2,is)*sqrt(ti()/(am(is)*mp))/
*          (cfdf0(3,is)*ni(,0)+cfdf0(4,is)*ne())
*     is used in the definition of the anomalous transport coefficients.
*     df0 is meant to represent a diffusivity. If cfdf0(2,is).eq.0 then
*     the corresponding term in df0 is understood as 0 independent of
*     cfdf0(3:4,is).
*      cfdna - (0:7,0:ns-1) real*8 array.
*     For 0.le.is.lt.ns, cfdna(,is) are the coefficients in the
*     local expression
*       difna(,is) = cfdna(0,is)+cfdna(1,is)/(ne()/1.0e20)+
*         cfdna(2,is)*df0(,is)+
*         cfdna(3,is)*te()/ev/abs(bb(,3))/16
*     that specifies the anomalous diffusivity with respect to
*     grad.na; the transport equation for species (is) contains a term
*     difna(,is)*'grad.na'.
*     If cfdna(7,is) is not zero, the dna0 array is flux-scaled with
*     a scaling factor of cfdna(7,is)*(hy1()/hy1(omp))**2
*     where hy1 is the radial width of the cell and omp refers
*     to the cell from the sam flux tube intersecting the outer midplane.
*     cfdna(4:6,) are not used in the default version of the code.
*      cfdpa - (0:7,0:ns-1) real*8 array.
*     For 0.le.is.lt.ns, cfdpa(,is) are the coefficients in the
*     local expression
*       difpa(,is) = cfdpa(0,is)+cfdpa(1,is)/(ne()/1.0e20)+
*         cfdpa(2,is)*df0(,is)+
*         cfdpa(3,is)*te()/ev/abs(bb(,3))/16
*     that specifies the anomalous diffusivity with respect to
*     grad.pa; the transport equation for species (is) contains a term
*     (1/(rza(,is)*te()+ti()))*difpa(,is)*'grad.pa'.
*     If cfdpa(7,is) is not zero, the dpa0 array is flux-scaled with
*     a scaling factor of cfdpa(7,is)*(hy1()/hy1(omp))**2
*     where hy1 is the radial width of the cell and omp refers
*     to the cell from the sam flux tube intersecting the outer midplane.
*     cfdpa(4:6,) are not used in the default version of the code.
*      cfvla - (0:7,0:ns-1) real*8 array.
*     For 0.le.is.lt.ns, cfvla(,is) are the coefficients in the
*     local expression
*       vlay(,is) = cfvla(0,is)+cfvla(1,is)/(ne()/1.0e20)+
*         cfvla(2,is)*df0(,is)+
*         cfvla(3,is)*te()/ev/abs(bb(,3))/16
*     that specifies the anomalous y-velocity of species (is); the
*     transport equation for species (is) contains a term
*     vlay(,is)*na(,is).
*     If cfvla(7,is) is not zero, the vla0 array is flux-scaled with
*     a scaling factor of cfvla(7,is)*(hy1()/hy1(omp))**2
*     where hy1 is the radial width of the cell and omp refers
*     to the cell from the sam flux tube intersecting the outer midplane.
*     cfvla(4:6,) are not used in the default version of the code.
*      cfvsa - (0:7,0:ns-1) real*8 array.
*     For 0.le.is.lt.ns, cfvsa(,is) are the coefficients in the
*     local expression
*       dfvsa(,is) = cfvsa(0,is)+cfvsa(1,is)/(ne()/1.0e20)+
*         cfvsa(2,is)*df0(,is)+
*         cfvsa(3,is)*te()/ev/abs(bb(,3))/16
*     that specifies the diffusivity corresponding to the anomalous
*     transverse viscosity, so that this viscosity is
*       vsa(,is) = mp*am(is)*na(,is)*dfvsa
*     If cfvsa(7,is) is not zero, the vsa0 array is flux-scaled with
*     a scaling factor of cfvsa(7,is)*(hy1()/hy1(omp))**2
*     where hy1 is the radial width of the cell and omp refers
*     to the cell from the sam flux tube intersecting the outer midplane.
*     cfvsa(4:6,) are not used in the default version of the code.
*      cfhci - (0:7,0:ns-1) real*8 array.
*     For 0.le.is.lt.ns, cfhci(,is) are the coefficients in the
*     local expression
*       dfhca(,is) = cfhci(0,is)+cfhci(1,is)/(ne()/1.0e20)+
*         cfhci(2,is)*df0(,is)+
*         cfhci(3,is)*te()/ev/abs(bb(,3))/16
*     that specifies the anomalous atom heat conductivity associated
*     with species (is), so that the atom heat conduction coefficient
*     contains a term dfhca(,is)*na(,is).
*     If cfhci(7,is) is not zero, the hci arrays are flux-scaled with
*     a scaling factor of cfhci(7,is)*(hy1()/hy1(omp))**2
*     where hy1 is the radial width of the cell and omp refers
*     to the cell from the sam flux tube intersecting the outer midplane.
*     cfhci(4:6,) are not used in the default version of the code.
*      cfhce - (0:7) real*8 array.
*     cfhce() are the coefficients in the local expression
*       dfhce() = cfhce(0)+cfhce(1)/(ne()/1.0e20)+
*         cfhce(3)*te()/ev/abs(bb(,3))/16
*     that specifies the anomalous electron heat conductivity, so that
*     the electron heat conduction coefficient is dfhce()*ne().
*     If cfhce(7) is not zero, the hce0 array is flux-scaled with
*     a scaling factor of cfhce(7)*(hy1()/hy1(omp))**2
*     where hy1 is the radial width of the cell and omp refers
*     to the cell from the sam flux tube intersecting the outer midplane.
*     cfhce(2) and (4:6) are not used in the default version of the code.
*      cfsig - (0:7) real*8 array.
*     cfsig() are the coefficients in the local expression
*       dfsig() = cfsig(0)+cfsig(1)/(ne()/1.0e20)+
*         cfsig(3)*te()/ev/abs(bb(,3))/16+
*         cfsig(4)*exp(-cfsig(5)*(y/L)**2)
*     that specifies the diffusivity corresponding to the anomalous
*     electrical conductivity, which is
*       sig() = qe*ne()*dfsig().
*     L is the local radial width of the plasma and
*     y is the radial distance from the inner (South) boundary.
*     If cfsig(7) is not zero, the sig0 array is flux-scaled with
*     a scaling factor of cfsig(7)*(hy1()/hy1(omp))**2
*     where hy1 is the radial width of the cell and omp refers
*     to the cell from the sam flux tube intersecting the outer midplane.
*     cfsig(2) and (6) are not used in the default version of the code.
*      cfalf - (0:7) real*8 array.
*     cfalf() are the coefficients in the local expression
*       dfalf() = cfalf(0)+cfalf(1)/(ne()/1.0e20)+
*         cfalf(3)*te()/ev/abs(bb(,3))/16
*     that specifies the diffusivity corresponding to the anomalous
*     thermo-electric coefficient, which is
*       alf() = ne()*sqrt(qe/te())*dfalf().
*     If cfalf(7) is not zero, the alf0 array is flux-scaled with
*     a scaling factor of cfalf(7)*(hy1()/hy1(omp))**2
*     where hy1 is the radial width of the cell and omp refers
*     to the cell from the sam flux tube intersecting the outer midplane.
*     cfalf(2) and (4:6) are not used in the default version of the code.
*      cflim - (0:7) real*8 array.
*     cflim contains coefficients for flux limiting. cflim(0)=cflme
*     specifies the flux limit factor for poloidal electron heat
*     transport. cflim(1)=cflmi specifies the flux limit factor for
*     poloidal all atom heat transport. cflim(2)=cflmv specifies the
*     flux limit factor for poloidal atom momentum transport.
*     cflim(3)=cflal specifies the flux limit factor for the
*     thermo-electric coefficient.
*     cflim(4)=cflab specifies the flux limit factor for the
*     friction force.
*     Zero settings turn off these flux limits.
*     cflim(5:7) are not used in the default version of the code.
*
*     /b2cmwg/ contains some parameters to control graphical output.
*      nmbpmx - integer constant.
*     nmbpmx is used in dimension declarations instead of nmbpcc or
*     nmbpdm.
*      nmbpcc - integer.
*     nmbpcc specifies the number of cartesian domains on which any
*     quantity may be plotted.
*      nmbpdm - integer.
*     nmbpdm specifies the number of physical domains on which any
*     quantity may be plotted.
*      cwaxr, cwayr - (0:nmbpmx-1) real*8 array.
*     For each iplot in (0:nmbpcc-1), cwaxr(iplot) and cwayr(iplot)
*     specify coordinates for a cartesian domain plot. The coordinates
*     are obtained by integrating the grid metric along two reference
*     lines. The reference line for the x-coordinate is at position
*     nint(cwaxr*nx), and the reference line for the y-coordinate is
*     at nint(cwayr*ny). It will hold that 0.le.cwaxr.le.1 and
*     0.le.cwayr.le.1.
*      cwxmin, cwxmax, cwymin, cwymax - (0:nmbpmx-1) real*8 array.
*     For each iplot in (0:nmbpdm-1), the quadruple of cwxmin(iplot)
*     through cwymax(iplot) specifies a domain in the physical plane
*     for contour plots.
*
*     Description of some local variables (including arrays in w(0:*):
*
*     crx, cry - (-1:nx,-1:ny,0:3) real*8 array.
*     For (ix,iy) in (-1:nx,-1:ny), crx(ix,iy,0:3) specify the
*     horizontal coordinates and cry(ix,iy,0:3) specify the vertical
*     coordinates (in the physical plane) of the four corners of the
*     (ix,iy) cell, mapped as follows:
*     (,,0): lower left corner,  (,,1): lower right corner,
*     (,,2): upper left corner,  (,,3): upper right corner.
*     One expects the following identities to hold away from the
*     boundaries:
*     crx(ix,iy,0)=crx(ix-1,iy,1)=crx(ix,iy-1,2)=crx(ix-1,iy-1,3),
*     cry(ix,iy,0)=cry(ix-1,iy,1)=cry(ix,iy-1,2)=cry(ix-1,iy-1,3),
*     However, there may be cuts in the geometry, in which case these
*     identities need not hold.
*
*     fpsi - (-1:nx,-1:ny,0:3,0:2) real*8 array.
*     For (ix,iy,i) in (-1:nx,-1:ny,0:3), fpsi(ix,iy,i,0) specifies the
*     potential for the magnetic field components (bx,by) at the
*     (ix,iy,i) position.
*     fpsi(ix,iy,i,1) specifies the (dpsi/dx) derivative.
*     fpsi(ix,iy,i,2) specifies the (dpsi/dy) derivative.
*     (In the case of straight symmetry, bx=dpsi/dy and by=-dpsi/dx.
*     In the case of toroidal or cylindrical symmetry,
*       bx=(dpsi/dy)/(2*pi*R) and by=-(dpsi/dx)/(2*pi*R),
*     where R is the distance to the axis of symmetry.)
*
*     ffbz - (-1:nx,-1:ny,0:3) real*8 array.
*     For (ix,iy,i) in (-1:nx,-1:ny,0:3), ffbz(ix,iy,i) specifies the
*     field function for the magnetic field component bz at the
*     (ix,iy,i) position.
*     (In the case of straight symmetry, bz=ffbz. In the case of
*     toroidal or cylindrical symmetry, bz=ffbz/(2*pi*R), where R is
*     the distance to the axis of symmetry.)
*
*     bb - (-1:nx,-1:ny,0:3) real*8 array.
*     For (ix,iy) in (-1:nx,-1:ny), bb(ix,iy,0:3) specifies the
*     magnetic field at the center of the (ix,iy) cell.
*     bb(ix,iy,0:2) are the (x,y,z)-components and bb(ix,iy,3) is
*     the absolute magnetic field strength.
*     (bb(,,3)=sqrt(bb(,,0)**2+bb(,,1)**2+bb(,,2)**2.)
*     It will hold that 0.lt.bb(,,3).
*
*     vol - (-1:nx,-1:ny) real*8 array.
*     For (ix,iy) in (-1:nx,-1:ny), vol(ix,iy) specifies the volume of
*     the (ix,iy) cell. (In the case of toroidal symmetry this volume
*     includes a factor 2*pi*crx, while in the case of cylindrical
*     symmetry it includes a factor 2*pi*cry.)
*     It will hold that 0.lt.vol(,).
*
*     hx, hy - (-1:nx,-1:ny) real*8 array.
*     For (ix,iy) in (-1:nx,-1:ny), hx(ix,iy) and hy(ix,iy) specify the
*     x-diameter and the y-diameter, respectively, of the (ix,iy) cell.
*     It will hold that 0.lt.hx(,) and 0.lt.hy(,).
*
*     qz - (-1:nx,-1:ny,0:1) real*8 array.
*     For (ix,iy) in (-1:nx,-1:ny), qz(ix,iy,0) specifies sin(t) and
*     qz(ix,iy,1) specifies cos(t), where t is the complementary angle
*     between the x-direction and the y-direction on the (ix,iy) cell.
*     t is in the range (-pi/2 to pi/2) and vanishes for an orthogonal
*     geometry. (qz(ix,iy,0) is the inner product of the x and y unit
*     vectors.)
*     It will hold that -1.lt.qz(,,0).lt.1 and 0.lt.qz(,,1).le.1.
*
*     qc - (-1:nx,-1:ny) real*8 array, output.
*     For (ix,iy) in (-1:nx,-1:ny), qc(ix,iy) specifies cos(t), where
*     t is the complementary angle between the x-direction of the
*     (ix,iy) cell and its left face.
*     t is in the range (-pi/2 to pi/2) and vanishes for an orthogonal
*     geometry.
*     It will hold that 0.lt.qc(,).le.1.
*
*     gs - (-1:nx,-1:ny,0:2) real*8 array.
*     (Let gsx(,)=gs(,,0), gsy(,)=gs(,,1) and gsz(,)=gs(,,2).)
*     For (ix,iy) in (0:nx,-1:ny), gsx(ix,iy) specifies the area of the
*     face between the (ix,iy) cell and its left neighbor. For ix.eq.-1,
*     gsx(ix,-1:ny) will hold 0.
*     For (ix,iy) in (-1:nx,0:ny), gsy(ix,iy) specifies the area of the
*     face between the (ix,iy) cell and its bottom neighbor. For iy.eq.-1,
*     gsy(-1:nx,iy) will hold 0.
*     For (ix,iy) in (-1:nx,-1:ny), gsz(ix,iy) specifies the area of the
*     (ix,iy) cell normal to the third (ignorable) coordinate.
*
*     pbs - (-1:nx,-1:ny,0:1) real*8 array.
*     (Let pbsx(,)=pbs(,,0) and pbsy(,)=pbs(,,1).)
*     For (ix,iy) in (-1:nx,-1:ny), pbsx(ix,iy) specifies the product
*     (bx/bb)*sx and pbsy(ix,iy) specifies (by/bb)*sy, or (magnetic
*     field pitch)*(surface area), namely the parallel contact area,
*     on the (ix,iy) cell left and bottom faces respectively.
*     See routine b2xgbs for the form of interpolation employed.
*
*     ne - (-1:nx,-1:ny) real*8 array.
*     For (ix,iy) in (-1:nx,-1:ny), ne(ix,iy) specifies
*     the electron density on the (ix,iy) cell.
*     It will hold that 0.lt.ne(,).
*
*     na - (-1:nx,-1:ny,0:ns-1) real*8 array.
*     For (ix,iy,is) in (-1:nx,-1:ny,0:ns-1), na(ix,iy,is) specifies
*     the density of atomic species (is) on the (ix,iy) cell.
*     It will hold that 0.lt.na(,,).
*
*     ua - (-1:nx,-1:ny,0:ns-1) real*8 array.
*     For (ix,iy,is) in (-1:nx,-1:ny,0:ns-1), ua(ix,iy,is) specifies
*     the parallel velocity of atomic species (is) on the (ix,iy) cell.
*     The sign of the parallel velocity indicates whether it is flowing
*     in the same direction as the local poloidal magnetic field.
*
*     uadia - (-1:nx,-1:ny,0:1,0:ns-1) real*8 array.
*     For (ix,iy,is) in (-1:nx,-1:ny,0:ns-1), uadia(ix,iy,0,is) specifies
*     the diamagnetic drift velocity of species (is) on the (ix,iy) cell, and
*     uadia(ix,iy,1,is) the radial drift velocity.
*
*     te - (-1:nx,-1:ny) real*8 array.
*     For (ix,iy) in (-1:nx,-1:ny), te(ix,iy) specifies the electron
*     temperature on the (ix,iy) cell. It will hold that 0.lt.te(,).
*
*     ti - (-1:nx,-1:ny) real*8 array.
*     For (ix,iy) in (-1:nx,-1:ny), ti(ix,iy) specifies the all atom
*     temperature on the (ix,iy) cell. It will hold that 0.lt.ti(,).
*
*     po - (-1:nx,-1:ny) real*8 array.
*     For (ix,iy) in (-1:nx,-1:ny), po(ix,iy) specifies the electric
*     potential on the (ix,iy) cell.
*
*     fna - (-1:nx,-1:ny,0:1,0:ns-1) real*8 array.
*     (Let fnax(,,)=fna(,,0,) and fnay(,,)=fna(,,1,).)
*     For (ix,iy,is) in (0:nx,-1:ny,0:ns-1), fnax(ix,iy,is) specifies
*     the flux of atoms of species (is) through the face between the
*     (ix,iy) cell and its left neighbor.
*     For ix.eq.-1, fnax(ix,-1:ny,0:ns-1) will hold 0.
*     For (ix,iy,is) in (-1:nx,0:ny,0:ns-1), fnay(ix,iy,is) specifies
*     the flux of atoms of species (is) through the face between the
*     (ix,iy) cell and its bottom neighbor.
*     For iy.eq.-1, fnay(-1:nx,iy,0:ns-1) will hold 0.
*
*     fhe - (-1:nx,-1:ny,0:1) real*8 array.
*     (Let fhex(,)=fhe(,,0) and fhey(,)=fhe(,,1).)
*     For (ix,iy) in (0:nx,-1:ny), fhex(ix,iy) specifies the electron
*     heat flux through the face between the (ix,iy) cell and its
*     left neighbor. For ix.eq.-1, fhex(ix,-1:ny) will hold 0.
*     For (ix,iy) in (-1:nx,0:ny), fhey(ix,iy) specifies the electron
*     heat flux through the face between the (ix,iy) cell and its
*     bottom neighbor. For iy.eq.-1, fhey(-1:nx,iy) will hold 0.
*
*     fhi - (-1:nx,-1:ny,0:1) real*8 array.
*     (Let fhix(,)=fhi(,,0) and fhiy(,)=fhi(,,1).)
*     For (ix,iy) in (0:nx,-1:ny), fhix(ix,iy) specifies the all atom
*     heat flux through the face between the (ix,iy) cell and its
*     left neighbor. For ix.eq.-1, fhix(ix,-1:ny) will hold 0.
*     For (ix,iy) in (-1:nx,0:ny), fhiy(ix,iy) specifies the all atom
*     heat flux through the face between the (ix,iy) cell and its
*     bottom neighbor. For iy.eq.-1, fhiy(-1:nx,iy) will hold 0.
*
*     fch - (-1:nx,-1:ny,0:1) real*8 array.
*     (Let fchx(,)=fch(,,0) and fchy(,)=fch(,,1).)
*     For (ix,iy) in (0:nx,-1:ny), fchx(ix,iy) specifies the electric
*     current through the face between the (ix,iy) cell and its left
*     neighbor. For ix.eq.-1, fchx(ix,-1:ny) will hold 0.
*     For (ix,iy) in (-1:nx,0:ny), fchy(ix,iy) specifies the electric
*     current through the face between the (ix,iy) cell and its bottom
*     neighbor. For iy.eq.-1, fchy(-1:nx,iy) will hold 0.
*
*     lblgm - character*120
*     lblgm identifies the instance of the program employed to prepare
*     the geometry.
*
*     lblcp - character*120
*     lblcp identifies the instance of the program employed to prepare
*     the table of physics parameters.
*
*     lblmn - character*120
*     lblmn identifies the instance of the program employed for the main
*     calculation.
*
*     ismain - integer.
*     ismain identifies the index of the main plasma species.
*     This cannot be a neutral species.
*
*-----------------------------------------------------------------------
*.computation

* ..preliminaries
*   ..subprogram start-up calls
      call subini ('b2ypdr')
*   ..test ninp, nout
      call xertst (1.le.ninp(0).and.1.le.ninp(1).and.1.le.ninp(2).and.
     &             1.le.ninp(3).and.1.le.ninp(4).and.1.le.ninp(5).and.
     &             1.le.nout(0).and.1.le.nout(1).and.1.le.nout(2),
     &  'faulty argument ninp, nout')
*   ..test dimensions
      call xertst (0.le.nx.and.0.le.ny, 'faulty argument nx, ny')
      call xertst (1.le.ns, 'faulty argument ns')
      call xertst (ns.le.nsdecl, 'faulty parameter nsdecl')

* ..computation
*   ..read output control
      read (ninp(0),'(a8)',err=91) id
      call xertst (streql(id,'*idout'),
     &  'faulty input instead of *idout, id='//id)
      read (ninp(0),*,err=92) iftp, idout
      read (ninp(0),'(a8)',err=93) id
      call xertst (streql(id,'*nmbpcc'),
     &  'faulty input instead of *nmbpcc, id='//id)
      read (ninp(0),*,err=94) nmbpcc
      call xertst (0.le.nmbpcc.and.nmbpcc.le.nmbpmx,
     &  'faulty data for nmbpcc')
      do iplot = 0, nmbpcc-1
       read (ninp(0),*,err=94) cwaxr(iplot), cwayr(iplot)
       call xertst (0.le.cwaxr(iplot).and.cwaxr(iplot).le.1.and.
     &   0.le.cwayr(iplot).and.cwayr(iplot).le.1,
     &   'faulty data for cwaxr, cwayr')
      enddo
      read (ninp(0),'(a8)',err=95) id
      call xertst (streql(id,'*nmbpdm'),
     &  'faulty input instead of *nmbpdm, id='//id)
      read (ninp(0),*,err=96) nmbpdm
      call xertst (0.le.nmbpdm.and.nmbpdm.le.nmbpmx,
     &  'faulty data for nmbpdm')
      do iplot = 0, nmbpdm-1
       read (ninp(0),*,err=96) cwxmin(iplot), cwxmax(iplot),
     &   cwymin(iplot), cwymax(iplot)
       call xertst (cwxmin(iplot).lt.cwxmax(iplot).and.
     &   cwymin(iplot).lt.cwymax(iplot),
     &   'faulty data for cwxmin, cwxmax, cwymin, cwymax')
      enddo
*   ..write output control
      write (nout(0),'(/2x,a,2x,i3/2x,a,2x,a)')
     &  'style of contour plots:', iftp,
     &  'idout:', idout
      write (nout(0),'(2x,a,2x,i3/(2x,0p,2f8.4))')
     &  'selection of cartesian plots', nmbpcc,
     &  (cwaxr(iplot), cwayr(iplot), iplot=0,nmbpcc-1)
      write (nout(0),'(2x,a,2x,i3/(2x,1p,4e12.3))')
     &  'selection of physical domain plots', nmbpdm,
     &  (cwxmin(iplot), cwxmax(iplot),cwymin(iplot), cwymax(iplot),
     &   iplot=0,nmbpdm-1)
*   ..obtain lblmn
      call b2xxid ('b2mn', lblmn(1:60))
      call b2rflb (ninp(5), lblmn(61:120))
*   ..read revised parameters in physics common
*     (ninp(5) need supply only parameters that are to be changed from
*     the values read in as default physics common.)
      call b2rfcp (ninp(5), ns)
*   ..read and echo code internal parameters
    1 continue
       read (ninp(5),'(a)',end=2,err=97) line
       if (.not.is_comment(line)) then
         read (line,*) cnamip, cvalip
         call ipsetc (cnamip, cvalip)
       end if
       goto 1
    2 continue
*   ..read geometry
      call cfruch (ninp(1), 120, lblgm, 'label')
      call cfruin (ninp(1), 1, idum, 'isymm')
#ifdef WG_TODO
      call b2rugm (ninp(1), nx, ny, isymm)
#endif
*   ..read physics common
      call cfruch (ninp(2), 120, lblcp, 'label')
      call b2rucp (ninp(2), b2fparam_version, ns)
*   ..read state
      call cfruch (ninp(3), 120, lblmn, 'label')
      call b2ruzd (ninp(3), b2fstate_version,
     &  ns, zamin, zamax, zn, am, .true.)
      call b2rups (ninp(3), nx, ny, ns, ne, na, ua, uadia, te,           !xpb
     &  ti, tn, po, kt, zt,
     &  fna, fhe, fhi, fhn, fch, fch_32, fch_52, fch_p, kinrgy,
     &  fna_mdf, fhe_mdf, fhi_mdf, fna_fcor, fna_nodrift, fna_he,
     &  fnaPSch, fhePSch, fhiPSch, fna_eir, fne_eir, fhe_eir, fhi_eir,
     &  fna_32, fna_52, fni_32, fni_52, fne_32, fne_52,
     &  fchdia, fchin, fchvispar, fchvisper, fchvisq, fchinert,
     &  vaecrb, vadia, wadia, veecrb, vedia, floe_noc, floi_noc,
     1  b2fstate_version)
*   ..test plasma state and fluxes
#ifdef WG_TODO
      call b2xvps (nx, ny, ns,
     &  ne, na, ua, te, ti, po, fna, fhe, fhi, fch)
#endif
*   ..read atomic rate data
      call cfruch (ninp(4), 120, lblrc, 'label')
      call read_b2mod_ppout('rates', ninp(4), lblrc)
      call b2rurc (ninp(4), b2frates_version)
*   ..test rtns, rtzmin, rtzmax, rtzn
      call xertst (ns.eq.rtns, 'faulty input rtns--wrong rate table?')
      do is = 0, ns-1
       call xertst (ltst(zamin(is),rtzmin(is)),
     &   'faulty input rtzmin--wrong rate table?')
       call xertst (ltst(zamax(is),rtzmax(is)),
     &   'faulty input rtzmax--wrong rate table?')
       call xertst (ltst(zn(is),rtzn(is)),
     &   'faulty input rtzn--wrong rate table?')
      enddo
*    ..compute log-log electron rate coefficients
#ifdef WG_TODO
      call b2spel (nx, ny, ns, ev, te, ne, rlsa, rlra,
     &     rlqa, rlrd, rlbr, rlza, rlz2, rlpt, rlpi)
*   ..compute electron rate coefficients
      call ipgeti ('b2mndr_ismain', ismain)
      call xertst (0.le.ismain.and.ismain.lt.ns,
     . 'invalid main plasma species index ismain')
      call xertst (.not.is_neutral(ismain),
     . 'invalid main plasma species ismain; must not be neutral')
      call b2sqel (nx, ny, ns, ismain, ev, te,
     &    rlsa, rlra, rlqa, rlrd, rlbr, rlza, rlz2, rlpt, rlpi,
     &    rsa, rra, rqa, rrd, rbr, rza, rz2, rpt, rpi)
#endif
*    ..check for external species
      call ipgeti ('b2mndr_external_species', external_species)
      if (external_species.ne.0) then
        call read_b2mod_external(nx,ny,ns,ismain)
      else
        call alloc_b2mod_external_dummy(nx,ny)
      endif
*   ..write labels
      write (nout(0),'(/2x,a)') 'labels for this calculation:'
      write (nout(0),'(/4x,a/4x,a)') lblgm(1:60), lblgm(61:120)
      write (nout(0),'(/4x,a/4x,a)') lblcp(1:60), lblcp(61:120)
      write (nout(0),'(/4x,a/4x,a)') lblmn(1:60), lblmn(61:120)
*   ..write geometric information
      call b2wfgm (nout(0), idout, nx, ny)
*   ..test /b2cmpa/, /b2cmpb/, /b2cmpt/
      call b2xvcp (ns)
*   ..write physics parameters
      call b2wfcp (nout(0), 1, ns)
*   ..write state
      call b2wfps (nout(0), idout, nx, ny, ns,
     &  gs, qc, ne, na, ua, te, ti, po,
     &  fna, fhe, fhi, fch)
*   ..activate graphics on nout(1)
      call gacwk (nout(1))
*   ..mark contour style
      call lbfilx (iftp)
*   ..plot geometry
      call b2wggm (nout(0), idout, nx, ny, lblgm(61:120), crx,
     &  cry, fpsi, ffbz, bb)
*   ..plot labels and parameter values
*!!   (to follow: routines b2wglb, b2wgcp)
*   ..plot state
      call b2wgps (nout(0), idout, nx, ny, ns, crx, cry,
     &  ne, na, ua, te, ti, po, fna, fhe,
     &  fhi, fch)
*   ..deactivate graphics on nout(1)
      call gdawk (nout(1))
*   ..produce special output
      call b2wscp (nout(2), nx, ny, ns)
      call b2wsps (nout(2), nx, ny, ns, crx, cry, bb,
     &  vol, hx, hy, qz, qc, qs, gs, pbs, cell_width, cell_height,
     &  ne, na, ua, te, ti, po, fna, fhe, fhi, fch)

* ..return
      call dealloc_b2mod_b2cmrc
      call dealloc_b2mod_external
      call subend ()
      return

*-----------------------------------------------------------------------
*.error conditions

   91 call xerrab ('error trying to read heading *idout')
   92 call xerrab ('error trying to read output control')
   93 call xerrab ('error trying to read heading *nmbpcc')
   94 call xerrab ('error trying to read nmbpcc data')
   95 call xerrab ('error trying to read heading *nmbpdm')
   96 call xerrab ('error trying to read nmbpdm data')
   97 call xerrab ('error trying to read internal parameters')

*-----------------------------------------------------------------------
*.end b2ypdr

      end subroutine b2ypdr
