      subroutine b2tlv0 (nCv, nFc, nVx, ns, switch, geo, mpg,
     &  na, ua, te,  tn, rza, cvsa0, cvsa, cvsahz, flv)
      use b2mod_types
      use b2mod_constants
      use b2mod_b2cmpa
      use b2mod_switches
      use b2us_geo
      use b2us_map
! csc The following are not necessary for computation but are needed
!     for adjoint AD to avoid side-effect variables
      use b2mod_ad
     & , only : b2tlv0_cutlo
#ifndef NAGFOR
      use b2mod_ad
     & , only : my_out_folder
#endif
      use b2mod_subsys
      implicit none
*   ..input arguments (unchanged on exit)
      integer, intent (in) :: nCv, nFc, nVx, ns
      type (switches), intent (in) :: switch
      type (geometry), intent (in) :: geo
      type (mapping), intent (in) :: mpg
      real (kind=R8) ::
     *  na(nCv,0:ns-1), ua(nCv,0:ns-1), te(nCv), tn(nCv), 
     *  rza(nCv,0:ns-1), cvsa0(nFc,0:ns-1)
*   ..input and output arguments
      real (kind=R8) ::
     *  cvsa(nFc,0:1,0:ns-1), cvsahz(nFc,0:1,0:ns-1)
*   ..output arguments (unspecified on entry)
      real (kind=R8) ::
     *  flv(nFc,0:1,0:ns-1)
*   ..common blocks
*     ------------------------------------------------------------------
*     B2TLV0 computes the neutral viscosity flux limit.
*     ------------------------------------------------------------------
*   ..local variables
      integer iFc, is
      character charns*3
      real (kind=R8) ::
     *  alpha, gamma, qcl, qfl, tfl, maxfluxlimit(0:1),
     *  dubf(nFc,0:1), ubv(nVx)
*   ..initialization
*   ..procedures
      intrinsic max, abs, sqrt
      external xertst
*     ------------------------------------------------------------------
*   ..subprogram start-up calls
      call subini ('b2tlv0')
*   ..test nCv, nFc, ns
      call xertst (0.lt.nCv.and.0.lt.nFc, 'faulty argument nCv, nFc')
      call xertst (1.le.ns, 'faulty argument ns')

      call sfill(nFc*2*ns, 1.0_R8, flv, 1)
      call sfill(2, 1.0_R8, maxfluxlimit, 1)

      alpha = switch%b2tlv0_alpha
      gamma = switch%b2tlv0_gamma

*   ..nothing done if alpha.eq.0
      if (alpha.ne.0.0_R8) then
       if (switch%b2tlv0_style.eq.0) then
        do is = 0, ns-1
         if (is_neutral(is)) then
*    ..compute differences of parallel velocity
          call diff (nCv, nFc, nVx, 0, geo, mpg, ua(1,is), ubv, dubf)
          do iFc = 1, nFc
*    ..poloidal
            qcl = abs(cvsa(iFc,0,is)*dubf(iFc,0))
            qfl = alpha*geo%fcS(iFc)*abs(geo%fcQalf(iFc,0))*
     &           (na(mpg%fcCv(iFc,1),is)*tn(mpg%fcCv(iFc,1))+
     &            na(mpg%fcCv(iFc,2),is)*tn(mpg%fcCv(iFc,2)))/2.0_R8
            tfl = 1.0_R8/(1.0_R8 + abs(qcl/(qfl+b2tlv0_cutlo))**gamma)
     &                                                 **(1.0_R8/gamma)
            cvsa(iFc,0,is)   = cvsa(iFc,0,is)*tfl
            cvsahz(iFc,0,is) = cvsahz(iFc,0,is)*tfl
            flv(iFc,0,is) = tfl
            maxfluxlimit(0)=max(maxfluxlimit(0),tfl)
*    ..perpendicular
            qcl = abs(cvsa(iFc,1,is)*dubf(iFc,1))
            qfl = alpha*geo%fcS(iFc)*abs(geo%fcQalf(iFc,1))*
     &           (na(mpg%fcCv(iFc,1),is)*tn(mpg%fcCv(iFc,1))+
     &            na(mpg%fcCv(iFc,2),is)*tn(mpg%fcCv(iFc,2)))/2.0_R8
            tfl = 1.0_R8/(1.0_R8 + abs(qcl/(qfl+b2tlv0_cutlo))**gamma)
     &                                                 **(1.0_R8/gamma)
            cvsa(iFc,1,is)   = cvsa(iFc,1,is)*tfl
            cvsahz(iFc,1,is) = cvsahz(iFc,1,is)*tfl
            flv(iFc,1,is) = tfl
            maxfluxlimit(1)=max(maxfluxlimit(1),tfl)
           enddo
         endif
        enddo
       else
cwdk    flux limit total gradient-driven flow, not individual poloidal
cwdk    or radial contributions, since neutral transport is isotropic
        do is = 0, ns-1
         if (is_neutral(is)) then
*    ..compute differences of parallel velocity
          call diff (nCv, nFc, nVx, 0, geo, mpg, ua(1,is), ubv, dubf)
          do iFc = 1, nFc
*    ..limit total gradient
            qcl = cvsa0(iFc,is)*sqrt(dubf(iFc,0)**2 + dubf(iFc,1)**2)
            qfl = alpha*geo%fcS(iFc)*
     &           (na(mpg%fcCv(iFc,1),is)*tn(mpg%fcCv(iFc,1))+
     &            na(mpg%fcCv(iFc,2),is)*tn(mpg%fcCv(iFc,2)))/2.0_R8
            tfl = 1.0_R8/(1.0_R8 + abs(qcl/(qfl+b2tlv0_cutlo))**gamma)
     &                                                 **(1.0_R8/gamma)
*    ..poloidal
            cvsa(iFc,0,is)   = cvsa(iFc,0,is)*tfl
            cvsahz(iFc,0,is) = cvsahz(iFc,0,is)*tfl
            flv(iFc,0,is) = tfl
            maxfluxlimit(0) = max(maxfluxlimit(0),tfl)
*    ..radial
            cvsa(iFc,1,is)   = cvsa(iFc,1,is)*tfl
            cvsahz(iFc,1,is) = cvsahz(iFc,1,is)*tfl
            flv(iFc,1,is) = tfl
            maxfluxlimit(1) = max(maxfluxlimit(1),tfl)
          enddo
         endif
        enddo
       endif
      endif

!      write(*,'(1x,a,1p,2e10.2)') 'b2tlv0: maxfluxlimit = ',maxfluxlimit

      if (switch%b2tlv0_iout.ne.0) then
        do is = 0, ns-1
          if (is_neutral(is)) then
            write (charns,'(i3.3)') is
            call my_out_us(70,nFc,1, flv(1,0,is),
     &              'fl_visc_th'//charns)
            call my_out_us(70,nFc,1, flv(1,1,is),
     &              'fl_visc_r'//charns)
          endif
        enddo
      endif

*   ..return
      call subend ()
      return
*     ------------------------------------------------------------------
      end subroutine b2tlv0
